Constant Contact for WordPress: Ctct\Services\ListService Class Reference
Ctct\Services\ListService Class Reference
Public Member Functions
getLists ($accessToken, array $params=array())
Get lists within an account.
addList ($accessToken, ContactList $list)
Create a new Contact List.
updateList ($accessToken, ContactList $list)
Update a Contact List.
getList ($accessToken, $list_id)
Get an individual contact list.
getContactsFromList ($accessToken, $list_id, $params=null)
Get all contacts from an individual list.
Public Member Functions inherited from Ctct\Services\BaseService
__construct ($apiKey, $restClient=null)
Constructor with the option to to supply an alternative rest client to be used.
buildUrl ($url, array $queryParams=null)
Build a URL from a base url and optional array of query parameters to append to the url.
getRestClient ()
Get the rest client being used by the service.
setRestClient (RestClientInterface $restClient)
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Services\BaseService
static getHeaders ($accessToken)
Helper function to return required headers for making an http request with constant contact.
Protected Attributes inherited from Ctct\Services\BaseService
$restClient
$apiKey
Detailed Description
Definition at line 16 of file ListService.php.
Member Function Documentation
Ctct\Services\ListService::addList ($accessToken, ContactList $list)
Create a new Contact List.
Parameters
string $accessToken - Constant Contact OAuth2 access token
ContactList $list
Returns
ContactList
Definition at line 43 of file ListService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Contacts\ContactList\create(), Ctct\Util\Config\get(), and Ctct\Components\Contacts\ContactList\toJson().
     {
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.lists');
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->post($url, parent::getHeaders($accessToken), $list->toJson());
         return ContactList::create(json_decode($response->body, true));
     }
Ctct\Services\ListService::getContactsFromList ($accessToken, $list_id, $params = null)
Get all contacts from an individual list.
Parameters
string $accessToken - Constant Contact OAuth2 access token
string $list_id - list id to retrieve contacts for
array $params - query params to attach to request
Returns
ResultSet
Definition at line 86 of file ListService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Contacts\Contact\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . sprintf(Config::get('endpoints.list_contacts'), $list_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $contacts = array();
         foreach ($body['results'] as $contact) {
             $contacts[] = Contact::create($contact);
         }
         return new ResultSet($contacts, $body['meta']);
     }
Ctct\Services\ListService::getList ($accessToken, $list_id)
Get an individual contact list.
Parameters
$accessToken - Constant Contact OAuth2 access token
$list_id - list id
Returns
ContactList
Definition at line 71 of file ListService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Contacts\ContactList\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . sprintf(Config::get('endpoints.list'), $list_id);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         return ContactList::create(json_decode($response->body, true));
     }
Ctct\Services\ListService::getLists ($accessToken, array $params = array())
Get lists within an account.
Parameters
$accessToken - Constant Contact OAuth2 access token
array $params - array of query parameters to be appened to the request
Returns
Array - ContactLists
Definition at line 24 of file ListService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Contacts\ContactList\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.lists');
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $lists = array();
         foreach (json_decode($response->body, true) as $contact) {
             $lists[] = ContactList::create($contact);
         }
         return $lists;
     }
Ctct\Services\ListService::updateList ($accessToken, ContactList $list)
Update a Contact List.
Parameters
string $accessToken - Constant Contact OAuth2 access token
ContactList $list - ContactList to be updated
Returns
ContactList
Definition at line 57 of file ListService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Contacts\ContactList\create(), Ctct\Util\Config\get(), and Ctct\Components\Contacts\ContactList\toJson().
     {
         $baseUrl = Config::get('endpoints.base_url') . sprintf(Config::get('endpoints.list'), $list->id);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->put($url, parent::getHeaders($accessToken), $list->toJson());
         return ContactList::create(json_decode($response->body, true));
     }
The documentation for this class was generated from the following file:
ListService.php