Constant Contact for WordPress: ExceptionalTest Class Reference
ExceptionalTest Class Reference
Public Member Functions
testGetParameters ()
testPostParameters ()
testBlacklist ()
testControllerAndAction ()
testSessionFilter ()
createExceptionData ()
Protected Member Functions
setUp ()
Detailed Description
Definition at line 15 of file exceptional_test.php.
Member Function Documentation
ExceptionalTest::createExceptionData ()
Definition at line 76 of file exceptional_test.php.
Referenced by testBlacklist(), testControllerAndAction(), testGetParameters(), testPostParameters(), and testSessionFilter().
{
         $notice = new PhpNotice("Test", 0, "", 0);
         $this->data = new ExceptionalData($notice);
         $this->request = $this->data->data["request"];
     }
ExceptionalTest::setUp () protected
Definition at line 18 of file exceptional_test.php.
     {
         $_SERVER["HTTP_HOST"] = "localhost";
     }
ExceptionalTest::testBlacklist ()
Definition at line 40 of file exceptional_test.php.
References Exceptional\blacklist(), and createExceptionData().
{
         $_POST["password"] = "test123";
         $_POST["user"]["creditcardnumber"] = 1234;
         $_POST["zipcode"] = 55555;
         Exceptional::blacklist(array('password', 'creditcardnumber'));
         $this->createExceptionData();
         $this->assertEquals($this->request["parameters"]["password"], "[FILTERED]");
         $this->assertEquals($this->request["parameters"]["user"]["creditcardnumber"], "[FILTERED]");
         $this->assertEquals($this->request["parameters"]["zipcode"], 55555);
     }
ExceptionalTest::testControllerAndAction ()
Definition at line 53 of file exceptional_test.php.
References Exceptional\$action, Exceptional\$controller, and createExceptionData().
     {
         Exceptional::$controller = "home";
         Exceptional::$action = "index";
         $this->createExceptionData();
         $this->assertEquals($this->request["controller"], "home");
         $this->assertEquals($this->request["action"], "index");
     }
ExceptionalTest::testGetParameters ()
Definition at line 23 of file exceptional_test.php.
References createExceptionData().
     {
         $_GET["a"] = "GET works";
         $this->createExceptionData();
         $this->assertEquals($this->request["parameters"]["a"], "GET works");
     }
ExceptionalTest::testPostParameters ()
Definition at line 32 of file exceptional_test.php.
References createExceptionData().
{
         $_POST["b"] = "POST works";
         $this->createExceptionData();
         $this->assertEquals($this->request["parameters"]["b"], "POST works");
     }
ExceptionalTest::testSessionFilter ()
Definition at line 64 of file exceptional_test.php.
References createExceptionData().
{
         $session_name = md5(rand());
         $session_id = md5(rand());
         ini_set("session.name", $session_name);
         $_SERVER["HTTP_Cookie"] = "$session_name=$session_id";
         $this->createExceptionData();
         $this->assertEquals($this->request["headers"]["Cookie"], "$session_name=[FILTERED]");
     }
The documentation for this class was generated from the following file:
exceptional_test.php