Constant Contact for WordPress: CTCT_Admin_Contacts Class Reference
CTCT_Admin_Contacts Class Reference
Data Fields
$errors
$id
$can_edit = true
$can_add = true
$component = 'Contact'
Data Fields inherited from CTCT_Admin_Page
$key
$title
$permission = 'manage_options'
$cc
$oauth
$errors
$can_edit = false
$can_add = false
$component = ''
$pointers = array()
Protected Member Functions
getKey ()
getTitle ($value= '')
getNavTitle ()
add ()
processForms ()
edit ()
single ()
view ()
Protected Member Functions inherited from CTCT_Admin_Page
addIncludes ()
addScripts ()
isAdd ()
isEdit ()
isSingle ()
isView ()
getKey ()
getTitle ()
getNavTitle ()
add ()
edit ()
view ()
single ()
processForms ()
addActions ()
content ()
print_errors ()
Additional Inherited Members
Public Member Functions inherited from CTCT_Admin_Page
__construct ()
print_styles ()
print_scripts ()
help_tabs ($tabs)
pointer_content ()
getPointers ($hook_suffix= '')
getPermission ()
add_menu ()
page ()
Detailed Description
Definition at line 12 of file contacts.php.
Member Function Documentation
CTCT_Admin_Contacts::add () protected
Definition at line 39 of file contacts.php.
{
         $Contact = new KWSContact();
         include(CTCT_DIR_PATH.'views/admin/view.contact-addedit.php');
     }
CTCT_Admin_Contacts::edit () protected
Definition at line 140 of file contacts.php.
References $id.
{
         $id = intval(@$_GET['edit']);
         /**
          * @todo Specify no contact ID error
          */
         if(!isset($id) || empty($id)) {
             echo 'no contact is specified.';
             return;
         }
         $Contact = $this->cc->getContact(CTCT_ACCESS_TOKEN, $id);
         $Contact = new KWSContact($Contact);
         include(CTCT_DIR_PATH.'views/admin/view.contact-addedit.php');
     }
CTCT_Admin_Contacts::getKey () protected
Definition at line 20 of file contacts.php.
Referenced by processForms().
{
         return "constant-contact-contacts";
     }
CTCT_Admin_Contacts::getNavTitle () protected
Definition at line 35 of file contacts.php.
{
         return 'Contacts';
     }
CTCT_Admin_Contacts::getTitle ($value = '') protected
Definition at line 24 of file contacts.php.
References CTCT_Admin_Page\isAdd(), CTCT_Admin_Page\isEdit(), and CTCT_Admin_Page\isSingle().
{
         if(empty($value) && $this->isEdit() || $value == 'edit')
             return __("Edit Contact", 'constant-contact-api');
         if(empty($value) && $this->isSingle() || $value == 'single')
             return __('Contact', 'constant-contact-api');
         if(empty($value) && $this->isAdd() || $value == 'add')
             return __('Add a Contact', 'constant-contact-api');
         return 'Contacts';
     }
CTCT_Admin_Contacts::processForms () protected
Definition at line 46 of file contacts.php.
References getKey().
{
         // check if the form was submitted
         if (isset($_POST['email_addresses']) && !empty($_POST['email_addresses'])) {
             $email = esc_attr($_REQUEST['email_addresses']);
             /////RANDASDSADSADASD
             $email = rand(0,10000).$email;
             $action = "Getting Contact By Email Address";
             try {
                 // check to see if a contact with the email addess already exists in the account
                 $response = $this->cc->getContactByEmail($email);
                 $data = $_POST;
                 $data['email_addresses'] = $email;
                 // Placeholder until we get $_POST
                 /*$data = array(
                     'first_name' => 'Example',
                     'last_name' => 'Jones',
                     'job_title' => 'President',
                     'email_addresses' => array(rand(0, 0200000).$email),
                     // 'address' => array(
                     //             'line1' => '584 Elm Street',
                     //             'city' => 'Cortez',
                     //             'address_type' => 'personal',
                     //             'country_code' => 'us',
                     //         ),
                     'addresses' => array(
                             array(
                                 'line1' => '14870 Road 29',
                                 'address_type' => 'personal',
                                 'country_code' => 'us',
                             ),
                             array(
                                 'line1' => '216 A',
                                 'line2' => 'W. Montezuma Ave.',
                                 'city' => 'Cortez',
                                 'postal_code' => '81321',
                                 'address_type' => 'business',
                                 'country_code' => 'us',
                             ),
                     ),
                     'custom_fields' => array(
                          array(
                          'name' => 'CustomField1',
                          'value' => 'custom value now doesnt match'
                         ),
                         array(
                           'name' => 'CustomField2',
                           'value' => 'Does not match'
                          )
                     ),
                     'notes' => array(
                         array(
                          'note' => 'Note 1'
                         ),
                         array(
                          'note' => 'Note 2'
                         ),
                     ),
                     'lists' => array('3', '27', '34')
                 );*/
                 // create a new contact if one does not exist
                 if (empty($response->results)) {
                     $action = "Creating Contact";
                     $kwscontact = new KWSContact($data);
                     $returnContact = $this->cc->addContact(CTCT_ACCESS_TOKEN, $kwscontact);
                     wp_redirect(add_query_arg(array('page' => $this->getKey(), 'view' => $returnContact->id), admin_url('admin.php')));
                 // update the existing contact if address already existed
                 } else {
                     $action = "Updating Contact";
                     $contact = new KWSContact($response->results[0]);
                     $contact = $contact->update($data);
                     $returnContact = $this->cc->updateContact(CTCT_ACCESS_TOKEN, $contact);
                 }
             // catch any exceptions thrown during the process and print the errors to screen
             } catch (CtctException $ex) {
                 r($ex, true, $action.' Exception');
                 $this->errors = $ex;
             }
         }
     }
CTCT_Admin_Contacts::single () protected
Definition at line 159 of file contacts.php.
References $id.
{
         $id = intval(@$_GET['view']);
         /**
          * @todo Specify no contact ID error
          */
         if(!isset($id) || empty($id)) {
             echo 'no contact is specified.';
             return;
         }
         if($refresh = get_site_option( 'ctct_refresh_contact_'.$id)) {
             delete_site_option( 'ctct_refresh_contact_'.$id);
             add_filter('ctct_cache', '__return_false');
         }
         $CC_Contact = $this->cc->getContact(CTCT_ACCESS_TOKEN, $id);
         $Contact = new KWSContact($CC_Contact);
         include(CTCT_DIR_PATH.'views/admin/view.contact-view.php');
     }
CTCT_Admin_Contacts::view () protected
Definition at line 182 of file contacts.php.
{
         add_filter('ctct_cachekey', function() {
             return isset($_GET['status']) ? false : 'ctct_all_contacts';
         });
         $Contacts = $this->cc->getAllContacts();
         kws_print_subsub('status', array(
             array('val' => '', 'text' => 'All'),
             array('val' => 'ACTIVE', 'text' => 'Active'),
             array('val' => 'UNCONFIRMED', 'text' => 'Unconfirmed'),
             array('val' => 'OPTOUT', 'text' => 'Opt-Out'),
             array('val' => 'REMOVED', 'text' => 'Removed'),
             array('val' => 'NON_SUBSCRIBER', 'text' => 'Non-Subscriber'),
         ));
         if(empty($Contacts)) {
             echo 'Your account has no contacts.';
         } else {
             include(CTCT_DIR_PATH.'views/admin/view.contacts-view.php');
         }
     }
Field Documentation
CTCT_Admin_Contacts::$can_add = true
Definition at line 17 of file contacts.php.
CTCT_Admin_Contacts::$can_edit = true
Definition at line 16 of file contacts.php.
CTCT_Admin_Contacts::$component = 'Contact'
Definition at line 18 of file contacts.php.
CTCT_Admin_Contacts::$errors
Definition at line 14 of file contacts.php.
CTCT_Admin_Contacts::$id
Definition at line 15 of file contacts.php.
Referenced by edit(), and single().
The documentation for this class was generated from the following file:
contacts.php