Constant Contact for WordPress: Event Class Reference
Event Class Reference
Public Member Functions
__construct ($params=array())
Constructor.
Static Public Member Functions
static createStruct ($parsedResponse)
Create an associative array of object properties from XML.
Data Fields
$title
$link
$updated
$id
$name
$description
$registered
$createdDate
$status
$eventType
$eventLocation
$registrationUrl
$startDate
$endDate
$publishDate
$attendedCount
$cancelledCount
$eventFeeRequired
$currencyType
$paymentOptions
$registrationTypes
Additional Inherited Members
Protected Member Functions inherited from CCObject
validate (Array $params)
Validate an object to check that all required fields have been supplied array $params - object property names to reference for validation before HTTP requests.
Detailed Description
Definition at line 1095 of file Components.php.
Constructor & Destructor Documentation
Event::__construct ($params = array())
Constructor.
Parameters
array $params - associative array of properties/values
Definition at line 1122 of file Components.php.
{
         $this->title = (isset($params['title'])) ? $params['title'] : '';
         $this->link = (isset($params['link'])) ? $params['link'] : '';
         $this->name = (isset($params['name'])) ? $params['name'] : '';
         $this->updated = (isset($params['updated'])) ? $params['updated'] : '';
         $this->id = (isset($params['id'])) ? $params['id'] : '';
         $this->description = (isset($params['description'])) ? $params['description'] : '';
         $this->registered = (isset($params['registered'])) ? $params['registered'] : '';
         $this->createdDate = (isset($params['createdDate'])) ? $params['createdDate'] : '';
         $this->status = (isset($params['status'])) ? $params['status'] : '';
         $this->eventType = (isset($params['eventType'])) ? $params['eventType'] : '';
         $this->eventLocation = (isset($params['eventLocation'])) ? $params['eventLocation'] : new EventLocation();
         $this->registrationUrl = (isset($params['registrationUrl'])) ? $params['registrationUrl'] : '';
         $this->startDate = (isset($params['startDate'])) ? $params['startDate'] : '';
         $this->endDate = (isset($params['endDate'])) ? $params['endDate'] : '';
         $this->publishDate = (isset($params['publishDate'])) ? $params['publishDate'] : '';
         $this->attendedCount = (isset($params['attendedCount'])) ? $params['attendedCount'] : '';
         $this->cancelledCount = (isset($params['cancelledCount'])) ? $params['cancelledCount'] : '';
         $this->eventFeeRequired = (isset($params['eventFeeRequired'])) ? $params['eventFeeRequired'] : '';
         $this->currencyType = (isset($params['currencyType'])) ? $params['currencyType'] : '';
         $this->paymentOptions = (isset($params['paymentOptions'])) ? $params['paymentOptions'] : array();
         $this->registrationTypes = (isset($params['registrationTypes'])) ? $params['registrationTypes'] : array(new RegistrationType());
     }
Member Function Documentation
static Event::createStruct ($parsedResponse) static
Create an associative array of object properties from XML.
Parameters
SimpleXMLElement $parsedResponse - XML of an event
Returns
array
Definition at line 1152 of file Components.php.
References CheckPayment\createStruct(), and RegistrationType\createStruct().
Referenced by EventsCollection\getEventDetails(), and EventsCollection\getEvents().
{
         $event['link'] = (string) $parsedResponse->link->Attributes()->href;
         $event['updated'] = (string) $parsedResponse->updated;
         $event['id'] = (string) $parsedResponse->id;
         $eventNode = $parsedResponse->content->children();
         $event['name'] = (string) $eventNode->Event->Name;
         $event['description'] = (string) $eventNode->Event->Description;
         $event['title'] = (string) $eventNode->Event->Title;
         $event['registered'] = (string) $eventNode->Event->Registered;
         $event['createdDate'] = (string) $eventNode->Event->CreatedDate;
         $event['status'] = (string) $eventNode->Event->Status;
         $event['eventType'] = (string) $eventNode->Event->EventType;
         $location['location'] =  (string) $eventNode->Event->EventLocation->Location;
         $location['addr1'] =  (string) $eventNode->Event->EventLocation->Address1;
         $location['addr2'] = (string) $eventNode->Event->EventLocation->Address2;
         $location['addr3'] = (string) $eventNode->Event->EventLocation->Address3;
         $location['city'] = (string) $eventNode->Event->EventLocation->City;
         $location['state'] = (string) $eventNode->Event->EventLocation->State;
         $location['country'] = (string) $eventNode->Event->EventLocation->Country;
         $location['postalCode'] = (string) $eventNode->Event->EventLocation->PostalCode;
         $event['eventLocation'] = new EventLocation($location);
         $event['registrationUrl'] = (string) $eventNode->Event->RegistrationURL;
         $event['startDate'] = (string) $eventNode->Event->StartDate;
         $event['endDate'] = (string) $eventNode->Event->EndDate;
         $event['publishDate'] = (string) $eventNode->Event->PublishDate;
         $event['attendedCount'] = (string) $eventNode->Event->AttendedCount;
         $event['cancelledCount'] = (string) $eventNode->Event->CancelledCount;
         $event['eventFeeRequired'] = (string) $eventNode->Event->EventFeeRequired;
         $event['currencyType'] = (string) $eventNode->Event->CurrencyType;
         $event['paymentOptions'] = array();
         if(isset($eventNode->Event->PaymentOptions->PaymentOption)){
             foreach($eventNode->Event->PaymentOptions->PaymentOption as $options){
                 $payOption = '';
                 $type = (string) $options->Type;
                 try{
                     if($type == "PAYPAL"){
                         $paypalAddr = (string) $options->PayPalAccountEmail;
                         $payOption = new PayPalPayment($paypalAddr);
                     } elseif ($type == "CHECK"){
                         $payOption = new CheckPayment(CheckPayment::createStruct($options));
                     } elseif ($type == "DOOR"){
                         $payOption = new DoorPayment();
                     }
                     if (empty($payOption)){throw new Exception('Payment Type '.$type.' is not a valid option');}
                 } catch (Exception $e) {
                     die($e->getMessage());
                 }
                     $event['paymentOptions'][] = $payOption;
             }
             foreach($eventNode->Event->RegistrationTypes->RegistrationType as $regType){
                 $registration = new RegistrationType(RegistrationType::createStruct($regType));
             }
             $event['registrationTypes'][] = $registration;
         }
         return $event;
     }
Field Documentation
Event::$attendedCount
Definition at line 1111 of file Components.php.
Event::$cancelledCount
Definition at line 1112 of file Components.php.
Event::$createdDate
Definition at line 1103 of file Components.php.
Event::$currencyType
Definition at line 1114 of file Components.php.
Event::$description
Definition at line 1101 of file Components.php.
Event::$endDate
Definition at line 1109 of file Components.php.
Event::$eventFeeRequired
Definition at line 1113 of file Components.php.
Event::$eventLocation
Definition at line 1106 of file Components.php.
Event::$eventType
Definition at line 1105 of file Components.php.
Event::$id
Definition at line 1099 of file Components.php.
Event::$link
Definition at line 1097 of file Components.php.
Event::$name
Definition at line 1100 of file Components.php.
Event::$paymentOptions
Definition at line 1115 of file Components.php.
Event::$publishDate
Definition at line 1110 of file Components.php.
Event::$registered
Definition at line 1102 of file Components.php.
Event::$registrationTypes
Definition at line 1116 of file Components.php.
Event::$registrationUrl
Definition at line 1107 of file Components.php.
Event::$startDate
Definition at line 1108 of file Components.php.
Event::$status
Definition at line 1104 of file Components.php.
Event::$title
Definition at line 1096 of file Components.php.
Event::$updated
Definition at line 1098 of file Components.php.
The documentation for this class was generated from the following file:
Components.php