Constant Contact for WordPress: Contact Class Reference
Contact Class Reference
Public Member Functions
__construct ($params=array())
Constructor.
createXml ()
Create XML Representation of the object.
Static Public Member Functions
static createStruct ($parsedReturn)
Create associate array of object from XML.
Data Fields
$link
$id
$updated
$status
$emailAddress
$emailType
$firstName
$middleName
$lastName
$fullName
$jobTitle
$companyName
$homePhone
$workPhone
$addr1
$addr2
$addr3
$city
$stateCode
$stateName
$countryCode
$countryName
$postalCode
$subPostalCode
$notes
$customField1
$customField2
$customField3
$customField4
$customField5
$customField6
$customField7
$customField8
$customField9
$customField10
$customField11
$customField12
$customField13
$customField14
$customField15
$contactLists
$confirmed
$optInSource
$lists = array()
Additional Inherited Members
Protected Member Functions inherited from CCObject
validate (Array $params)
Validate an object to check that all required fields have been supplied array $params - object property names to reference for validation before HTTP requests.
Detailed Description
Definition at line 97 of file Components.php.
Constructor & Destructor Documentation
Contact::__construct ($params = array())
Constructor.
Parameters
array $params - associative array of properties/values
Definition at line 147 of file Components.php.
{
         $this->link = (isset($params['link'])) ? $params['link'] : '';
         $this->id = (isset($params['id'])) ? $params['id'] : 'data:,';
         $this->updated = (isset($params['updated'])) ? $params['updated'] : '';
         $this->status = (isset($params['status'])) ? $params['status'] : '';
         $this->emailAddress = (isset($params['emailAddress'])) ? $params['emailAddress'] : '';
         $this->emailType = (isset($params['emailType'])) ? $params['emailType'] : '';
         $this->firstName = (isset($params['firstName'])) ? $params['firstName'] : '';
         $this->middleName = (isset($params['middleName'])) ? $params['middleName'] : '';
         $this->lastName = (isset($params['lastName'])) ? $params['lastName'] : '';
         $this->fullName = (isset($params['fullName'])) ? $params['fullName']: '';
         $this->jobTitle = (isset($params['jobTitle'])) ? $params['jobTitle']: '';
         $this->companyName = (isset($params['companyName'])) ? $params['companyName']: '';
         $this->homePhone = (isset($params['homePhone'])) ? $params['homePhone']: '';
         $this->workPhone = (isset($params['workPhone'])) ? $params['workPhone']: '';
         $this->addr1 = (isset($params['addr1'])) ? $params['addr1']: '';
         $this->addr2 = (isset($params['addr2'])) ? $params['addr2']: '';
         $this->addr3 = (isset($params['addr3'])) ? $params['addr3']: '';
         $this->city = (isset($params['city'])) ? $params['city']: '';
         $this->stateCode = (isset($params['stateCode'])) ? $params['stateCode']: '';
         $this->stateName = (isset($params['stateName'])) ? $params['stateName']: '';
         $this->countryCode = (isset($params['countryCode'])) ? $params['countryCode']: '';
         $this->countryName = (isset($params['countryName'])) ? $params['countryName']: '';
         $this->postalCode = (isset($params['postalCode'])) ? $params['postalCode']: '';
         $this->subPostalCode = (isset($params['subPostalCode'])) ? $params['subPostalCode']: '';
         $this->notes = (isset($params['notes'])) ? $params['notes']: '';
         $this->customField1 = (isset($params['customField1'])) ? $params['customField1']: '';
         $this->customField2 = (isset($params['customField2'])) ? $params['customField2']: '';
         $this->customField3 = (isset($params['customField3'])) ? $params['customField3']: '';
         $this->customField4 = (isset($params['customField4'])) ? $params['customField4']: '';
         $this->customField5 = (isset($params['customField5'])) ? $params['customField5']: '';
         $this->customField6 = (isset($params['customField6'])) ? $params['customField6']: '';
         $this->customField7 = (isset($params['customField7'])) ? $params['customField7']: '';
         $this->customField8 = (isset($params['customField8'])) ? $params['customField8']: '';
         $this->customField9 = (isset($params['customField9'])) ? $params['customField9']: '';
         $this->customField10 = (isset($params['customField10'])) ? $params['customField10']: '';
         $this->customField11 = (isset($params['customField11'])) ? $params['customField11']: '';
         $this->customField12 = (isset($params['customField12'])) ? $params['customField12']: '';
         $this->customField13 = (isset($params['customField13'])) ? $params['customField13']: '';
         $this->customField14 = (isset($params['customField14'])) ? $params['customField14']: '';
         $this->customField15 = (isset($params['customField15'])) ? $params['customField15']: '';
         $this->contactLists = (isset($params['contactLists'])) ? $params['contactLists']: '';
         $this->confirmed = (isset($params['confirmed'])) ? $params['confirmed']: '';
         $this->optInSource = (isset($params['optInSource'])) ? $params['optInSource']: 'ACTION_BY_CUSTOMER';
        if(!empty($params['lists'])){
             if(is_string($params['lists'])){$this->lists[] = $params['lists'];}
             else{
                 foreach($params['lists'] as $list){
                     $this->lists[] = $list;
                 }
             }
         } else {$this->lists = array(); }
     }
Member Function Documentation
static Contact::createStruct ($parsedReturn) static
Create associate array of object from XML.
Parameters
SimpleXMLElement $parsedReturn - parsed XML
Returns
Definition at line 207 of file Components.php.
Referenced by ContactsCollection\addContact(), ContactsCollection\getContactDetails(), ContactsCollection\getContacts(), and ContactsCollection\searchContactsByEmail().
{
         $contact['link'] = (string) $parsedReturn->link->Attributes()->href;
         $contact['id'] = (string) $parsedReturn->id;
         $contact['updated'] = (string) $parsedReturn->updated;
         $contact['emailAddress'] = (string) $parsedReturn->content->Contact->EmailAddress;
         $contact['firstName'] = (string) $parsedReturn->content->Contact->FirstName;
         $contact['lastName'] = (string) $parsedReturn->content->Contact->LastName;
         $contact['middleName'] = (string) $parsedReturn->content->Contact->MiddleName;
         $contact['companyName'] = (string) $parsedReturn->content->Contact->CompanyName;
         $contact['optInSource'] = (string) $parsedReturn->content->Contact->OptInSource;
         $contact['jobTitle'] = (string) $parsedReturn->content->Contact->JobTitle;
         $contact['homePhone'] = (string) $parsedReturn->content->Contact->HomePhone;
         $contact['workPhone'] = (string) $parsedReturn->content->Contact->WorkPhone;
         $contact['addr1'] = (string) $parsedReturn->content->Contact->Addr1;
         $contact['addr2'] = (string) $parsedReturn->content->Contact->Addr2;
         $contact['addr3'] = (string) $parsedReturn->content->Contact->Addr3;
         $contact['city'] = (string) $parsedReturn->content->Contact->City;
         $contact['stateCode'] = (string) $parsedReturn->content->Contact->StateCode;
         $contact['stateName'] = (string) $parsedReturn->content->Contact->StateName;
         $contact['countryCode'] = (string) $parsedReturn->content->Contact->CountryCode;
         $contact['postalCode'] = (string) $parsedReturn->content->Contact->PostalCode;
         $contact['subPostalCode'] = (string) $parsedReturn->content->Contact->SubPostalCode;
         $contact['customField1'] = (string) $parsedReturn->content->Contact->CustomField1;
         $contact['customField2'] = (string) $parsedReturn->content->Contact->CustomField2;
         $contact['customField3'] = (string) $parsedReturn->content->Contact->CustomField3;
         $contact['customField4'] = (string) $parsedReturn->content->Contact->CustomField4;
         $contact['customField5'] = (string) $parsedReturn->content->Contact->CustomField5;
         $contact['customField6'] = (string) $parsedReturn->content->Contact->CustomField6;
         $contact['customField7'] = (string) $parsedReturn->content->Contact->CustomField7;
         $contact['customField8'] = (string) $parsedReturn->content->Contact->CustomField8;
         $contact['customField9'] = (string) $parsedReturn->content->Contact->CustomField9;
         $contact['customField10'] = (string) $parsedReturn->content->Contact->CustomField10;
         $contact['customField11'] = (string) $parsedReturn->content->Contact->CustomField11;
         $contact['customField12'] = (string) $parsedReturn->content->Contact->CustomField12;
         $contact['customField13'] = (string) $parsedReturn->content->Contact->CustomField13;
         $contact['customField14'] = (string) $parsedReturn->content->Contact->CustomField14;
         $contact['customField15'] = (string) $parsedReturn->content->Contact->CustomField15;
         $contact['notes'] = (string) $parsedReturn->content->Contact->Note;
         $contact['emailType'] = (string) $parsedReturn->content->Contact->EmailType;
         $contact['status'] = (string) $parsedReturn->content->Contact->Status;
         if($parsedReturn->content->Contact->ContactLists){
             foreach($parsedReturn->content->Contact->ContactLists->ContactList as $list){
                 $myVar = $list;
                 $contact['lists'][] = (string) $list->Attributes()->id;
             }
         }
         return $contact;
     }
Contact::createXml ()
Create XML Representation of the object.
Returns
SimpleXMLElement
Definition at line 261 of file Components.php.
References CCObject\validate().
Referenced by ContactsCollection\addContact(), and ContactsCollection\updateContact().
{
         $this->validate(array('emailAddress', 'lists'));
         $update_date = '2008-07-23T14:21:06.407Z';
         $xml_string = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><entry xmlns='http://www.w3.org/2005/Atom'></entry>";
         $xml_object = simplexml_load_string($xml_string);
         $xml_object->addChild("title");
         $xml_object->addChild("updated",$update_date);
         $author_node = $xml_object->addChild("author");
         $author_node->addChild("name", ("CTCT Samples"));
         $xml_object->addChild("id", $this->id);
         $summary_node = $xml_object->addChild("summary");
         $summary_node->addAttribute("type", "text");
         $content_node = $xml_object->addChild("content");
         $content_node->addAttribute("type", "application/vnd.ctct+xml");
         $contact_node = $content_node->addChild("Contact");
         $contact_node->addAttribute("xmlns", "http://ws.constantcontact.com/ns/1.0/");
         $contact_node->addChild("EmailAddress", $this->emailAddress);
         $contact_node->addChild("FirstName", $this->firstName);
         $contact_node->addChild("LastName", $this->lastName);
         $contact_node->addChild("MiddleName", $this->middleName);
         $contact_node->addChild("CompanyName", $this->companyName);
         $contact_node->addChild("JobTitle", $this->jobTitle);
         $contact_node->addChild("OptInSource", $this->optInSource);
         $contact_node->addChild("HomePhone",$this->homePhone);
         $contact_node->addChild("WorkPhone", $this->workPhone);
         $contact_node->addChild("Addr1", $this->addr1);
         $contact_node->addChild("Addr2", $this->addr2);
         $contact_node->addChild("Addr3", $this->addr3);
         $contact_node->addChild("City", $this->city);
         $contact_node->addChild("StateCode", $this->stateCode);
         $contact_node->addChild("StateName", $this->stateName);
         $contact_node->addChild("CountryCode", $this->countryCode);
         $contact_node->addChild("PostalCode", $this->postalCode);
         $contact_node->addChild("SubPostalCode", $this->subPostalCode);
         $contact_node->addChild("Note", $this->notes);
         $contact_node->addChild("EmailType", $this->emailType);
         $contact_node->addChild("CustomField1", $this->customField1);
         $contact_node->addChild("CustomField2", $this->customField2);
         $contact_node->addChild("CustomField3", $this->customField3);
         $contact_node->addChild("CustomField4", $this->customField4);
         $contact_node->addChild("CustomField5", $this->customField5);
         $contact_node->addChild("CustomField6", $this->customField6);
         $contact_node->addChild("CustomField7", $this->customField7);
         $contact_node->addChild("CustomField8", $this->customField8);
         $contact_node->addChild("CustomField9", $this->customField9);
         $contact_node->addChild("CustomField10", $this->customField10);
         $contact_node->addChild("CustomField11", $this->customField11);
         $contact_node->addChild("CustomField12", $this->customField12);
         $contact_node->addChild("CustomField13", $this->customField13);
         $contact_node->addChild("CustomField14", $this->customField14);
         $contact_node->addChild("CustomField15", $this->customField15);
         $contactlists_node = $contact_node->addChild("ContactLists");
         foreach($this->lists as $list){
             $listNode = $contactlists_node->addChild("ContactList");
             $listNode->addAttribute("id", $list);
         }
         $entry = $xml_object->asXML();
         return $entry;
     }
Field Documentation
Contact::$addr1
Definition at line 112 of file Components.php.
Contact::$addr2
Definition at line 113 of file Components.php.
Contact::$addr3
Definition at line 114 of file Components.php.
Contact::$city
Definition at line 115 of file Components.php.
Contact::$companyName
Definition at line 109 of file Components.php.
Contact::$confirmed
Definition at line 139 of file Components.php.
Contact::$contactLists
Definition at line 138 of file Components.php.
Contact::$countryCode
Definition at line 118 of file Components.php.
Contact::$countryName
Definition at line 119 of file Components.php.
Contact::$customField1
Definition at line 123 of file Components.php.
Contact::$customField10
Definition at line 132 of file Components.php.
Contact::$customField11
Definition at line 133 of file Components.php.
Contact::$customField12
Definition at line 134 of file Components.php.
Contact::$customField13
Definition at line 135 of file Components.php.
Contact::$customField14
Definition at line 136 of file Components.php.
Contact::$customField15
Definition at line 137 of file Components.php.
Contact::$customField2
Definition at line 124 of file Components.php.
Contact::$customField3
Definition at line 125 of file Components.php.
Contact::$customField4
Definition at line 126 of file Components.php.
Contact::$customField5
Definition at line 127 of file Components.php.
Contact::$customField6
Definition at line 128 of file Components.php.
Contact::$customField7
Definition at line 129 of file Components.php.
Contact::$customField8
Definition at line 130 of file Components.php.
Contact::$customField9
Definition at line 131 of file Components.php.
Contact::$emailAddress
Definition at line 102 of file Components.php.
Contact::$emailType
Definition at line 103 of file Components.php.
Contact::$firstName
Definition at line 104 of file Components.php.
Contact::$fullName
Definition at line 107 of file Components.php.
Contact::$homePhone
Definition at line 110 of file Components.php.
Contact::$id
Definition at line 99 of file Components.php.
Contact::$jobTitle
Definition at line 108 of file Components.php.
Contact::$lastName
Definition at line 106 of file Components.php.
Contact::$link
Definition at line 98 of file Components.php.
Contact::$lists = array()
Definition at line 141 of file Components.php.
Contact::$middleName
Definition at line 105 of file Components.php.
Contact::$notes
Definition at line 122 of file Components.php.
Contact::$optInSource
Definition at line 140 of file Components.php.
Contact::$postalCode
Definition at line 120 of file Components.php.
Contact::$stateCode
Definition at line 116 of file Components.php.
Contact::$stateName
Definition at line 117 of file Components.php.
Contact::$status
Definition at line 101 of file Components.php.
Contact::$subPostalCode
Definition at line 121 of file Components.php.
Contact::$updated
Definition at line 100 of file Components.php.
Contact::$workPhone
Definition at line 111 of file Components.php.
The documentation for this class was generated from the following file:
Components.php