Constant Contact for WordPress: Ctct\Components\Activities\Activity Class Reference
Ctct\Components\Activities\Activity Class Reference
Public Member Functions
toJson ()
Create json used for a POST/PUT request, also handles removing attributes that will cause errors if sent.
Static Public Member Functions
static create (array $props)
Factory method to create an Activity object from an array.
Data Fields
$id
$type
$status
$start_date
$finish_date
$file_name
$created_date
$error_count
$errors = array()
$warnings = array()
$contact_count
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Components\Component
static getValue (array $array, $item, $default=null)
Get the requested value from an array, or return the default.
Detailed Description
Definition at line 14 of file Activity.php.
Member Function Documentation
static Ctct\Components\Activities\Activity::create (array $props) static
Factory method to create an Activity object from an array.
Parameters
array $props - associative array of initial properties to set
Returns
Campaign
Definition at line 33 of file Activity.php.
References Ctct\Components\Activities\ActivityError\create().
Referenced by Ctct\Services\ActivityService\addClearListsActivity(), Ctct\Services\ActivityService\addExportContactsActivity(), Ctct\Services\ActivityService\addRemoveContactsFromListsActivity(), Ctct\Services\ActivityService\createAddContactsActivity(), Ctct\Services\ActivityService\getActivities(), and Ctct\Services\ActivityService\getActivity().
     {
         $activity = new Activity();
         $activity->id = parent::getValue($props, "id");
         $activity->type = parent::getValue($props, "type");
         $activity->status = parent::getValue($props, "status");
         $activity->start_date = parent::getValue($props, "start_date");
         $activity->finish_date = parent::getValue($props, "finish_date");
         $activity->created_date = parent::getValue($props, "created_date");
         $activity->error_count = parent::getValue($props, "error_count");
         $activity->contact_count = parent::getValue($props, "contact_count");
         // set any errors that exist, otherewise destroy the property
         if (array_key_exists('errors', $props)) {
             foreach ($props['errors'] as $error) {
                 $activity->errors[] = ActivityError::create($error);
             }
         } else {
             unset($activity->errors);
         }
         // set any warnings that exist, otherewise destroy the property
         if (array_key_exists('warnings', $props)) {
             foreach ($props['warnings'] as $error) {
                 $activity->warnings[] = ActivityError::create($error);
             }
         } else {
             unset($activity->warnings);
         }
         // set the file name if exists
         if (array_key_exists('file_name', $props)) {
             $activity->file_name = $props['file_name'];
         } else {
             unset($activity->file_name);
         }
         return $activity;
     }
Ctct\Components\Activities\Activity::toJson ()
Create json used for a POST/PUT request, also handles removing attributes that will cause errors if sent.
Returns
string
Definition at line 77 of file Activity.php.
     {
         return json_encode($this);
     }
Field Documentation
Ctct\Components\Activities\Activity::$contact_count
Definition at line 26 of file Activity.php.
Ctct\Components\Activities\Activity::$created_date
Definition at line 22 of file Activity.php.
Ctct\Components\Activities\Activity::$error_count
Definition at line 23 of file Activity.php.
Ctct\Components\Activities\Activity::$errors = array()
Definition at line 24 of file Activity.php.
Ctct\Components\Activities\Activity::$file_name
Definition at line 21 of file Activity.php.
Ctct\Components\Activities\Activity::$finish_date
Definition at line 20 of file Activity.php.
Ctct\Components\Activities\Activity::$id
Definition at line 16 of file Activity.php.
Ctct\Components\Activities\Activity::$start_date
Definition at line 19 of file Activity.php.
Ctct\Components\Activities\Activity::$status
Definition at line 18 of file Activity.php.
Ctct\Components\Activities\Activity::$type
Definition at line 17 of file Activity.php.
Ctct\Components\Activities\Activity::$warnings = array()
Definition at line 25 of file Activity.php.
The documentation for this class was generated from the following file:
Activity.php