Constant Contact for WordPress: CTCT_Admin_User_Profile Class Reference
CTCT_Admin_User_Profile Class Reference
Public Member Functions
add_menu ()
add ()
edit ()
view ()
single ()
processForms ()
addActions ()
update ($user)
Hook into profile_update action to update our user subscription info if necessary.
display ($user)
Hook into show_user_profile action to display our user subscription settings if necessary.
Public Member Functions inherited from CTCT_Admin_Page
__construct ()
print_styles ()
print_scripts ()
help_tabs ($tabs)
pointer_content ()
getPointers ($hook_suffix= '')
getPermission ()
add_menu ()
page ()
Data Fields
$subscribe_method
Data Fields inherited from CTCT_Admin_Page
$key
$title
$permission = 'manage_options'
$cc
$oauth
$errors
$can_edit = false
$can_add = false
$component = ''
$pointers = array()
Additional Inherited Members
Protected Member Functions inherited from CTCT_Admin_Page
addIncludes ()
addScripts ()
isAdd ()
isEdit ()
isSingle ()
isView ()
getKey ()
getTitle ()
getNavTitle ()
add ()
edit ()
view ()
single ()
processForms ()
addActions ()
content ()
print_errors ()
Detailed Description
Definition at line 3 of file profile.php.
Member Function Documentation
CTCT_Admin_User_Profile::add ()
Definition at line 8 of file profile.php.
 {}
CTCT_Admin_User_Profile::add_menu ()
Definition at line 7 of file profile.php.
 { return; }
CTCT_Admin_User_Profile::addActions ()
Definition at line 14 of file profile.php.
References CTCT_Settings\get().
{
         // Get our "User Subscription Method" option value.
         $this->subscribe_method = CTCT_Settings::get('profile_page_form');
         // If it is disabled exit this function
         if($this->subscribe_method) {
             // register user update action
             add_action('profile_update', array(&$this, 'update'));
         }
         // register show user update form action
         add_action('show_user_profile', array(&$this, 'display'), 1);
         add_action('edit_user_profile', array(&$this, 'display'), 1);
     }
CTCT_Admin_User_Profile::display ($user)
Hook into show_user_profile action to display our user subscription settings if necessary.
$cc
Parameters
<type> $user
Returns
<type>
Definition at line 99 of file profile.php.
References CTCT_Settings\get(), and KWSContactList\outputHTML().
{
         $Contact = new KWSContact($this->cc->getContactByEmail($user->data->user_email));
         if($Contact && current_user_can('edit_users') && !isset($_GET['debug-user-display'])) {
             echo sprintf(__('
                 <p><img src="%s" width="225" height="33" alt="Constant Contact" class="block" /><a href="%s">Admin-Only: Edit this User\'s Details</a> %s</p>
             ', 'constant-contact-api'),
                 plugins_url('images/admin/logo-horizontal.png', CTCT_FILE),
                 admin_url('admin.php?page=constant-contact-contacts&edit='.$Contact->id),
                 constant_contact_tip(__('Users will not see this link or the Constant Contact logo.'), false)
             );
         }
         if(!$this->subscribe_method) { return; }
         $register_page_method = CTCT_Settings::get('profile_page_form');
         // Prepare the description from the settings screen
         $signup_description =  CTCT_Settings::get('signup_description');
         if ($signup_description)    :
             $signup_description = wpautop ($signup_description);
             $signup_description = "<div class='description'>$signup_description</div>";
         endif;
     ?>
         <h3><?php echo CTCT_Settings::get('signup_title');?></h3>
         <?php echo $signup_description;?>
         <p><?php
             $lists = (array)$Contact->get('lists', true);
             echo KWSContactList::outputHTML('all', array('checked' => $lists));
         ?></p>
         <br />
     <?php
     }
CTCT_Admin_User_Profile::edit ()
Definition at line 9 of file profile.php.
 {}
CTCT_Admin_User_Profile::processForms ()
Definition at line 12 of file profile.php.
 {}
CTCT_Admin_User_Profile::single ()
Definition at line 11 of file profile.php.
 {}
CTCT_Admin_User_Profile::update ($user)
Hook into profile_update action to update our user subscription info if necessary.
Parameters
<type> $user
Returns
<type>
Definition at line 37 of file profile.php.
References CTCT_Admin_Page\$cc, CTCT_Admin_Page\$key, and $subscribe_method.
{
         r($_POST, true, 'profile.php line 39');
         $email = get_user_option( 'user_email', $user );
         $selected_lists = array();
         if(isset($_POST['cc_newsletter'])) {
             $lists = (is_array($_POST['cc_newsletter'])) ? $_POST['cc_newsletter'] : array();
             $fields = get_option('cc_extra_fields');
             $field_mappings = constant_contact_build_field_mappings();
             // get contact and selected lists
             $contact = $cc->query_contacts($email);
             if($subscribe_method == 'checkbox' && isset($_POST['cc_newsletter']) && !is_array($_POST['cc_newsletter'])) {
                 $lists = get_option('cc_lists');
             }
             // parse custom fields
             $extra_fields = array();
             if(is_array($fields)) {
                 foreach($fields as $field) {
                     $fieldname = str_replace(' ','', $field);
                     if(isset($field_mappings[$fieldname]) && isset($_POST[$field_mappings[$fieldname]])) {
                         $extra_fields[$fieldname] = $_POST[$field_mappings[$fieldname]];
                     }
                 }
             }
             // Kind of sanitize the input
             foreach($lists as $key => $list) { if(!is_numeric($list)) { unset($lists["{$key}"]); } }
             $cc->set_action_type('contact');
             if($contact) {
                 $status = $cc->update_contact($contact['id'], $email, $lists, $extra_fields);
             } else {
                 $status = $cc->create_contact($email, $lists, $extra_fields);
             }
             if(!$status):
                 //echo constant_contact_last_error($cc->http_response_code);
                 return;
             endif;
         } else {
             $contact = $cc->query_contacts($email);
             $cc->set_action_type('contact');
             if($contact) {
                 $status = $cc->update_contact($contact['id'], $email, array());
             }
         }
     }
CTCT_Admin_User_Profile::view ()
Definition at line 10 of file profile.php.
 {}
Field Documentation
CTCT_Admin_User_Profile::$subscribe_method
Definition at line 5 of file profile.php.
Referenced by update().
The documentation for this class was generated from the following file:
profile.php