Constant Contact for WordPress: CTCT_Widget_Simple Class Reference
CTCT_Widget_Simple Class Reference
Public Member Functions
register ()
__construct ()
constructor
widget ($args, $instance)
update ($new_instance, $old_instance)
form ($instance)
Data Fields
$widget_cssclass
Variables to setup the widget.
$widget_description
$widget_idbase
$widget_name
Detailed Description
Definition at line 12 of file simple-widget.php.
Constructor & Destructor Documentation
CTCT_Widget_Simple::__construct ()
constructor
Definition at line 25 of file simple-widget.php.
{
         $this->cc = new KWSConstantContact();
         /* Widget variable settings. */
         $this->widget_cssclass = 'ctct-widget-simple';
         $this->widget_description = __( 'Allow users to subscribe to your Constant Contact .', 'constant-contact-api' );
         $this->widget_idbase = 'ctct_widget_simple';
         $this->widget_name = __('Subscribe to Newsletter', 'constant-contact-api' );
         /* Widget settings. */
         $widget_ops = array( 'classname' => $this->widget_cssclass, 'description' => $this->widget_description );
         /* Create the widget. */
         $this->WP_Widget('subscribe_to_newsletter', $this->widget_name, $widget_ops);
     }
Member Function Documentation
CTCT_Widget_Simple::form ($instance)
See Also
WP_Widget->form
Definition at line 90 of file simple-widget.php.
References KWSContactList\outputHTML().
Referenced by widget().
{
         extract($instance);
  ?>
             <h2><label for="<?php echo $this->get_field_id('title'); ?>"><?php _e('Widget Title:', 'constant-contact-api') ?></label></h2>
             <p>
             <input type="text" class="widefat" id="<?php echo esc_attr( $this->get_field_id('title') ); ?>" name="<?php echo esc_attr( $this->get_field_name('title') ); ?>" value="<?php if ( !empty($title)) { echo esc_attr( $title ); } else { echo __('Newsletter', 'constant-contact-api');} ?>" /></p>
             <h2><label for="<?php echo $this->get_field_id('list'); ?>"><?php _e('Newsletter List:', 'constant-contact-api') ?></label></h2>
             <span class="description" style="font-style:normal;"><?php _e('Users will be subscribed to the following lists when submitted.', 'constant-contact-api'); ?></span>
             <p>
 <?php
                         $lists = array( '' => __('Select a list...', 'constant-contact-api') );
                         $lists = $this->cc->getAllLists();
                         #IDX_Plus::r($lists);
                         if (!$lists) {
                             echo '<div class="error"><p>'.__('Unable to load lists() from Constant Contact.', 'constant-contact-api').'</p></div>';
                         } else {
                             $listHTML = KWSContactList::outputHTML($lists, array(
                                 'type' => 'checkboxes',
                                 'format' => '%%name%%',
                                 'name_attr' => $this->get_field_name('lists'),
                                 'id_attr' => $this->get_field_id('ctct-%%id%%'),
                                 'checked' => $instance['lists'],
                             ));
                             echo $listHTML;
                         }
     }
CTCT_Widget_Simple::register ()
Definition at line 14 of file simple-widget.php.
{
         register_widget( 'CTCT_Widget_Simple' );
     }
CTCT_Widget_Simple::update ($new_instance, $old_instance)
See Also
WP_Widget->update
Definition at line 83 of file simple-widget.php.
{
         $instance['title'] = strip_tags(stripslashes($new_instance['title']));
         $instance['lists']  = $new_instance['lists'];
         return $instance;
     }
CTCT_Widget_Simple::widget ($args, $instance)
See Also
WP_Widget
Definition at line 41 of file simple-widget.php.
References form().
{
         extract($args);
         $title   = $instance['title'];
         $lists  = $instance['lists'];
         $title   = apply_filters('widget_title', $title, $instance, $this->id_base);
         echo $before_widget;
         if ($title) echo $before_title . $title . $after_title;
         ?>
         <form method="post" id="<?php echo $this->get_field_id(''); ?>" action="#<?php echo $this->get_field_id(''); ?>">
             <?php
                 $email = '';
                 if (isset($_POST['ctct']) && isset($_POST['ctct']['email'])) {
                     $email = sanitize_text_field( $_POST['ctct']['email'] );
                     if (!is_email($email)) {
                         echo '<div class="woocommerce_error">'.__('Please enter a valid email address.', 'constant-contact-api').'</div>';
                     } else {
                         $Contact = $this->cc->addUpdateContact(array('email' => $email, 'lists' => $lists));
                         echo '<div class="woocommerce_message">'.__('Thanks for subscribing.', 'constant-contact-api').'</div>';
                     }
                 }
             ?>
             <div>
                 <label class="screen-reader-text hidden" for="s"><?php _e('Email Address:', 'constant-contact-api'); ?></label>
                 <input type="text" name="ctct[email]" id="ctct-newsletter-email" placeholder="<?php _e('Your email address', 'constant-contact-api'); ?>" value="" />
                 <input type="submit" id="newsletter_subscribe" value="<?php _e('Subscribe', 'constant-contact-api'); ?>" />
             </div>
         </form>
         <?php
         echo $after_widget;
     }
Field Documentation
CTCT_Widget_Simple::$widget_cssclass
Variables to setup the widget.
Definition at line 19 of file simple-widget.php.
CTCT_Widget_Simple::$widget_description
Definition at line 20 of file simple-widget.php.
CTCT_Widget_Simple::$widget_idbase
Definition at line 21 of file simple-widget.php.
CTCT_Widget_Simple::$widget_name
Definition at line 22 of file simple-widget.php.
The documentation for this class was generated from the following file:
simple-widget.php