Constant Contact for WordPress: OAuthToken Class Reference
OAuthToken Class Reference
Public Member Functions
__construct ($key, $secret)
key = the token secret = the token secret
to_string ()
generates the basic string serialization of a token that a server would respond to request_token and access_token calls with
__toString ()
Data Fields
$key
$secret
Detailed Description
Definition at line 29 of file Authentication.php.
Constructor & Destructor Documentation
OAuthToken::__construct ($key, $secret)
key = the token secret = the token secret
Definition at line 38 of file Authentication.php.
References $key, and $secret.
{
     $this->key = $key;
     $this->secret = $secret;
   }
Member Function Documentation
OAuthToken::__toString ()
Definition at line 54 of file Authentication.php.
References to_string().
{
     return $this->to_string();
   }
OAuthToken::to_string ()
generates the basic string serialization of a token that a server would respond to request_token and access_token calls with
Definition at line 47 of file Authentication.php.
References OAuthUtil\urlencode_rfc3986().
Referenced by __toString().
{
     return "oauth_token=" .
            OAuthUtil::urlencode_rfc3986($this->key) .
            "&oauth_token_secret=" .
            OAuthUtil::urlencode_rfc3986($this->secret);
   }
Field Documentation
OAuthToken::$key
Definition at line 31 of file Authentication.php.
Referenced by __construct().
OAuthToken::$secret
Definition at line 32 of file Authentication.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
Authentication.php