Constant Contact for WordPress: JsonLoader Class Reference
JsonLoader Class Reference
Static Public Member Functions
static getContactsTextContents ()
static getRemoveContactsTextContents ()
static getTokenInfoJson ()
static getAccessTokenJson ()
static getVerifiedAddressesJson ()
static getContactJson ()
static getContactsJson ()
static getContactsModifiedSinceJson ()
static getContactsNoNextJson ()
static getListsJson ()
static getListJson ()
static getCampaignJson ()
static getCampaignModifiedSinceJson ($page=1)
static getCampaignsJson ()
static getCampaignScheduleJson ()
static getCampaignSchedulesJson ()
static getTestSendJson ()
static getClicks ()
static getBounces ()
static getForwards ()
static getOptOuts ()
static getSends ()
static getOpens ()
static getSummary ()
static getActivities ()
static getActivity ()
static getClearListsActivity ()
static getExportContactsActivity ()
static getRemoveContactsFromListsActivity ()
static getAddContactsActivity ()
Data Fields
const CONTACTS_FOLDER = "/Contacts"
const LISTS_FOLDER = "/Lists"
const CAMPAIGNS_FOLDER = "/Campaigns"
const CAMPAIGN_TRACKING_FOLDER = "/Tracking"
const ACTIVITES_FOLDER = "/Activities"
const ACCCOUNT_FOLDER = "/Account"
const AUTH_FOLDER = "/Auth"
Detailed Description
Definition at line 3 of file JsonLoader.php.
Member Function Documentation
static JsonLoader::getAccessTokenJson () static
Definition at line 29 of file JsonLoader.php.
Referenced by CtctOAuth2UnitTest\testGetAccessToken().
     {
         return file_get_contents(__DIR__ . self::AUTH_FOLDER . "/get_access_token.json");
     }
static JsonLoader::getActivities () static
Definition at line 134 of file JsonLoader.php.
Referenced by ActivityServiceUnitTest\testGetActivities(), and ActivityServiceUnitTest\testGetActivitiesWithType().
     {
         return file_get_contents(__DIR__ . self::ACTIVITES_FOLDER . "/get_activities.json");
     }
static JsonLoader::getActivity () static
Definition at line 139 of file JsonLoader.php.
Referenced by ActivityServiceUnitTest\testGetActivity().
     {
         return file_get_contents(__DIR__ . self::ACTIVITES_FOLDER . "/get_activity.json");
     }
static JsonLoader::getAddContactsActivity () static
Definition at line 159 of file JsonLoader.php.
Referenced by ActivityServiceUnitTest\testAddCreateContactsActivity(), and ActivityServiceUnitTest\testAddCreateContactsActivityFromFile().
     {
         return file_get_contents(__DIR__ . self::ACTIVITES_FOLDER . "/post_add_contacts.json");
     }
static JsonLoader::getBounces () static
Definition at line 104 of file JsonLoader.php.
Referenced by CampaignTrackingServiceUnitTest\testGetBounces(), and ContactTrackingServiceUnitTest\testGetBounces().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGN_TRACKING_FOLDER . "/get_bounces.json");
     }
static JsonLoader::getCampaignJson () static
Definition at line 69 of file JsonLoader.php.
Referenced by EmailMarketingServiceUnitTest\testAddCampaign(), EmailMarketingServiceUnitTest\testGetCampaign(), and EmailMarketingServiceUnitTest\testUpdateCampaign().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGNS_FOLDER . "/get_campaign.json");
     }
static JsonLoader::getCampaignModifiedSinceJson ($page = 1) static
Definition at line 74 of file JsonLoader.php.
Referenced by EmailMarketingServiceUnitTest\testGetCampaignsModifiedSince().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGNS_FOLDER . "/get_campaigns_modified_since{$page}.json");
     }
static JsonLoader::getCampaignScheduleJson () static
Definition at line 84 of file JsonLoader.php.
Referenced by CampaignScheduleServiceUnitTest\testAddSchedule(), CampaignScheduleServiceUnitTest\testGetSchedule(), and CampaignScheduleServiceUnitTest\testUpdateSchedule().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGNS_FOLDER . "/get_schedule.json");
     }
static JsonLoader::getCampaignSchedulesJson () static
Definition at line 89 of file JsonLoader.php.
Referenced by CampaignScheduleServiceUnitTest\testGetSchedules().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGNS_FOLDER . "/get_schedules.json");
     }
static JsonLoader::getCampaignsJson () static
Definition at line 79 of file JsonLoader.php.
Referenced by EmailMarketingServiceUnitTest\testGetCampaigns().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGNS_FOLDER . "/get_campaigns.json");
     }
static JsonLoader::getClearListsActivity () static
Definition at line 144 of file JsonLoader.php.
Referenced by ActivityServiceUnitTest\testAddClearListsActivity().
     {
         return file_get_contents(__DIR__ . self::ACTIVITES_FOLDER . "/post_clear_lists.json");
     }
static JsonLoader::getClicks () static
Definition at line 99 of file JsonLoader.php.
Referenced by CampaignTrackingServiceUnitTest\testGetClicks(), and ContactTrackingServiceUnitTest\testGetClicks().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGN_TRACKING_FOLDER . "/get_clicks.json");
     }
static JsonLoader::getContactJson () static
Definition at line 39 of file JsonLoader.php.
Referenced by ContactServiceUnitTest\testAddContact(), ContactServiceUnitTest\testGetContact(), and ContactServiceUnitTest\testUpdateContact().
     {
         return file_get_contents(__DIR__ . self::CONTACTS_FOLDER . "/get_contact.json");
     }
static JsonLoader::getContactsJson () static
Definition at line 44 of file JsonLoader.php.
Referenced by ContactServiceUnitTest\testGetContactByEmail(), ContactServiceUnitTest\testGetContacts(), and ListServiceUnitTest\testGetContactsFromList().
     {
         return file_get_contents(__DIR__ . self::CONTACTS_FOLDER . "/get_contacts.json");
     }
static JsonLoader::getContactsModifiedSinceJson () static
Definition at line 49 of file JsonLoader.php.
Referenced by ContactServiceUnitTest\testGetContactsModifiedSince().
     {
         return file_get_contents(__DIR__ . self::CONTACTS_FOLDER . "/get_contacts_modified_since.json");
     }
static JsonLoader::getContactsNoNextJson () static
Definition at line 54 of file JsonLoader.php.
Referenced by ContactServiceUnitTest\testGetContactsNoNextLink().
     {
         return file_get_contents(__DIR__ . self::CONTACTS_FOLDER . "/get_contacts_no_next.json");
     }
static JsonLoader::getContactsTextContents () static
Definition at line 14 of file JsonLoader.php.
Referenced by ActivityServiceUnitTest\testAddCreateContactsActivityFromFile().
     {
         return file_get_contents(__DIR__. self::ACTIVITES_FOLDER . "/add_contacts.txt");
     }
static JsonLoader::getExportContactsActivity () static
Definition at line 149 of file JsonLoader.php.
Referenced by ActivityServiceUnitTest\testAddExportContactsActivity().
     {
         return file_get_contents(__DIR__ . self::ACTIVITES_FOLDER . "/post_export_contacts.json");
     }
static JsonLoader::getForwards () static
Definition at line 109 of file JsonLoader.php.
Referenced by CampaignTrackingServiceUnitTest\testGetForwards(), and ContactTrackingServiceUnitTest\testGetForwards().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGN_TRACKING_FOLDER . "/get_forwards.json");
     }
static JsonLoader::getListJson () static
Definition at line 64 of file JsonLoader.php.
Referenced by ListServiceUnitTest\testAddList(), ListServiceUnitTest\testGetList(), and ListServiceUnitTest\testUpdateList().
     {
         return file_get_contents(__DIR__ . self::LISTS_FOLDER . "/get_list.json");
     }
static JsonLoader::getListsJson () static
Definition at line 59 of file JsonLoader.php.
Referenced by ListServiceUnitTest\testGetLists(), and ListServiceUnitTest\testGetListsModifiedSince().
     {
         return file_get_contents(__DIR__ . self::LISTS_FOLDER . "/get_lists.json");
     }
static JsonLoader::getOpens () static
Definition at line 124 of file JsonLoader.php.
Referenced by ContactTrackingServiceUnitTest\testGetOpens(), and CampaignTrackingServiceUnitTest\testGetOpens().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGN_TRACKING_FOLDER . "/get_opens.json");
     }
static JsonLoader::getOptOuts () static
Definition at line 114 of file JsonLoader.php.
Referenced by CampaignTrackingServiceUnitTest\testGetUnsubscribes(), and ContactTrackingServiceUnitTest\testGetUnsubscribes().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGN_TRACKING_FOLDER . "/get_opt_outs.json");
     }
static JsonLoader::getRemoveContactsFromListsActivity () static
Definition at line 154 of file JsonLoader.php.
Referenced by ActivityServiceUnitTest\testAddRemoveContactsFromListsActivity(), and ActivityServiceUnitTest\testAddRemoveContactsFromListsActivityFromFile().
     {
         return file_get_contents(__DIR__ . self::ACTIVITES_FOLDER . "/post_remove_contacts_from_lists.json");
     }
static JsonLoader::getRemoveContactsTextContents () static
Definition at line 19 of file JsonLoader.php.
Referenced by ActivityServiceUnitTest\testAddRemoveContactsFromListsActivityFromFile().
     {
         return file_get_contents(__DIR__. self::ACTIVITES_FOLDER . "/remove_contacts.txt");
     }
static JsonLoader::getSends () static
Definition at line 119 of file JsonLoader.php.
Referenced by ContactTrackingServiceUnitTest\testGetSends(), and CampaignTrackingServiceUnitTest\testGetSends().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGN_TRACKING_FOLDER . "/get_sends.json");
     }
static JsonLoader::getSummary () static
Definition at line 129 of file JsonLoader.php.
Referenced by ContactTrackingServiceUnitTest\testGetSummary(), and CampaignTrackingServiceUnitTest\testGetSummary().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGN_TRACKING_FOLDER . "/get_summary.json");
     }
static JsonLoader::getTestSendJson () static
Definition at line 94 of file JsonLoader.php.
Referenced by CampaignScheduleServiceUnitTest\testSendTest().
     {
         return file_get_contents(__DIR__ . self::CAMPAIGNS_FOLDER . "/post_test_send.json");
     }
static JsonLoader::getTokenInfoJson () static
Definition at line 24 of file JsonLoader.php.
Referenced by CtctOAuth2UnitTest\testGetTokenInfo().
     {
         return file_get_contents(__DIR__ . self::AUTH_FOLDER . "/token_info.json");
     }
static JsonLoader::getVerifiedAddressesJson () static
Definition at line 34 of file JsonLoader.php.
Referenced by AccountServiceUnitTest\testGetVerifiedAddresses().
     {
         return file_get_contents(__DIR__ . self::ACCCOUNT_FOLDER . "/get_verified_email_addresses.json");
     }
Field Documentation
const JsonLoader::ACCCOUNT_FOLDER = "/Account"
Definition at line 11 of file JsonLoader.php.
const JsonLoader::ACTIVITES_FOLDER = "/Activities"
Definition at line 10 of file JsonLoader.php.
const JsonLoader::AUTH_FOLDER = "/Auth"
Definition at line 12 of file JsonLoader.php.
const JsonLoader::CAMPAIGN_TRACKING_FOLDER = "/Tracking"
Definition at line 9 of file JsonLoader.php.
const JsonLoader::CAMPAIGNS_FOLDER = "/Campaigns"
Definition at line 8 of file JsonLoader.php.
const JsonLoader::CONTACTS_FOLDER = "/Contacts"
Definition at line 6 of file JsonLoader.php.
const JsonLoader::LISTS_FOLDER = "/Lists"
Definition at line 7 of file JsonLoader.php.
The documentation for this class was generated from the following file:
JsonLoader.php