Constant Contact for WordPress: OAuthRequest Class Reference
OAuthRequest Class Reference
Public Member Functions
__construct ($http_method, $http_url, $parameters=NULL)
set_parameter ($name, $value, $allow_duplicates=true)
get_parameter ($name)
get_parameters ()
unset_parameter ($name)
get_signable_parameters ()
The request parameters, sorted and concatenated into a normalized string.
get_signature_base_string ()
Returns the base string of this request.
get_normalized_http_method ()
just uppercases the http method
get_normalized_http_url ()
parses the url and rebuilds it to be scheme://host/path
to_url ()
builds a url usable for a GET request
to_postdata ()
builds the data one would send in a POST request
to_header ($realm=null)
builds the Authorization: header
__toString ()
sign_request ($signature_method, $consumer, $token)
build_signature ($signature_method, $consumer, $token)
Static Public Member Functions
static from_request ($http_method=NULL, $http_url=NULL, $parameters=NULL)
attempt to build up a request from what was passed to the server
static from_consumer_and_token ($consumer, $token, $http_method, $http_url, $parameters=NULL)
pretty much a helper function to set up the request
Data Fields
$base_string
Static Public Attributes
static $version = '1.0'
static $POST_INPUT = 'php://input'
Static Private Member Functions
static generate_timestamp ()
util function: current timestamp
static generate_nonce ()
util function: current nonce
Private Attributes
$parameters
$http_method
$http_url
Detailed Description
Definition at line 224 of file Authentication.php.
Constructor & Destructor Documentation
OAuthRequest::__construct ($http_method, $http_url, $parameters = NULL)
Definition at line 233 of file Authentication.php.
References $http_method, $http_url, $parameters, and OAuthUtil\parse_parameters().
{
     @$parameters or $parameters = array();
     $parameters = array_merge( OAuthUtil::parse_parameters(parse_url($http_url, PHP_URL_QUERY)), $parameters);
     $this->parameters = $parameters;
     $this->http_method = $http_method;
     $this->http_url = $http_url;
   }
Member Function Documentation
OAuthRequest::__toString ()
Definition at line 444 of file Authentication.php.
References to_url().
{
     return $this->to_url();
   }
OAuthRequest::build_signature ($signature_method, $consumer, $token)
Definition at line 459 of file Authentication.php.
Referenced by sign_request().
{
     $signature = $signature_method->build_signature($this, $consumer, $token);
     return $signature;
   }
static OAuthRequest::from_consumer_and_token ($consumer, $token, $http_method, $http_url, $parameters = NULL) static
pretty much a helper function to set up the request
Definition at line 296 of file Authentication.php.
References $http_method, $http_url, $parameters, $version, generate_nonce(), and generate_timestamp().
Referenced by CTCTOAuth\getAccessToken(), CTCTOAuth\getRequestToken(), and CTCTRequest\makeRequest().
{
     @$parameters or $parameters = array();
     $defaults = array("oauth_version" => OAuthRequest::$version,
                       "oauth_nonce" => OAuthRequest::generate_nonce(),
                       "oauth_timestamp" => OAuthRequest::generate_timestamp(),
                       "oauth_consumer_key" => $consumer->key);
     if ($token)
       $defaults['oauth_token'] = $token->key;
     $parameters = array_merge($defaults, $parameters);
     return new OAuthRequest($http_method, $http_url, $parameters);
   }
static OAuthRequest::from_request ($http_method = NULL, $http_url = NULL, $parameters = NULL) static
attempt to build up a request from what was passed to the server
Definition at line 245 of file Authentication.php.
References $http_method, $http_url, $parameters, OAuthUtil\get_headers(), OAuthUtil\parse_parameters(), and OAuthUtil\split_header().
{
     $scheme = (!isset($_SERVER['HTTPS']) || $_SERVER['HTTPS'] != "on")
               ? 'http'
               : 'https';
     @$http_url or $http_url = $scheme .
                               '://' . $_SERVER['HTTP_HOST'] .
                               ':' .
                               $_SERVER['SERVER_PORT'] .
                               $_SERVER['REQUEST_URI'];
     @$http_method or $http_method = $_SERVER['REQUEST_METHOD'];
     // We weren't handed any parameters, so let's find the ones relevant to
     // this request.
     // If you run XML-RPC or similar you should use this to provide your own
     // parsed parameter-list
     if (!$parameters) {
       // Find request headers
       $request_headers = OAuthUtil::get_headers();
       // Parse the query-string to find GET parameters
       $parameters = OAuthUtil::parse_parameters($_SERVER['QUERY_STRING']);
       // It's a POST request of the proper content-type, so parse POST
       // parameters and add those overriding any duplicates from GET
       if ($http_method == "POST"
           && @strstr($request_headers["Content-Type"],
                      "application/x-www-form-urlencoded")
           ) {
         $post_data = OAuthUtil::parse_parameters(
           file_get_contents(self::$POST_INPUT)
         );
         $parameters = array_merge($parameters, $post_data);
       }
       // We have a Authorization-header with OAuth data. Parse the header
       // and add those overriding any duplicates from GET or POST
       if (@substr($request_headers['Authorization'], 0, 6) == "OAuth ") {
         $header_parameters = OAuthUtil::split_header(
           $request_headers['Authorization']
         );
         $parameters = array_merge($parameters, $header_parameters);
       }
     }
     return new OAuthRequest($http_method, $http_url, $parameters);
   }
static OAuthRequest::generate_nonce () static private
util function: current nonce
Definition at line 474 of file Authentication.php.
Referenced by from_consumer_and_token().
{
     $mt = microtime();
     $rand = mt_rand();
     return md5($mt . $rand); // md5s look nicer than numbers
   }
static OAuthRequest::generate_timestamp () static private
util function: current timestamp
Definition at line 467 of file Authentication.php.
Referenced by from_consumer_and_token().
{
     return time();
   }
OAuthRequest::get_normalized_http_method ()
just uppercases the http method
Definition at line 376 of file Authentication.php.
Referenced by get_signature_base_string().
{
     return strtoupper($this->http_method);
   }
OAuthRequest::get_normalized_http_url ()
parses the url and rebuilds it to be scheme://host/path
Definition at line 384 of file Authentication.php.
Referenced by get_signature_base_string(), and to_url().
{
     $parts = parse_url($this->http_url);
     $port = @$parts['port'];
     $scheme = $parts['scheme'];
     $host = $parts['host'];
     $path = @$parts['path'];
     $port or $port = ($scheme == 'https') ? '443' : '80';
     if (($scheme == 'https' && $port != '443')
         || ($scheme == 'http' && $port != '80')) {
       $host = "$host:$port";
     }
     return "$scheme://$host$path";
   }
OAuthRequest::get_parameter ($name)
Definition at line 325 of file Authentication.php.
{
     return isset($this->parameters[$name]) ? $this->parameters[$name] : null;
   }
OAuthRequest::get_parameters ()
Definition at line 329 of file Authentication.php.
References $parameters.
{
     return $this->parameters;
   }
OAuthRequest::get_signable_parameters ()
The request parameters, sorted and concatenated into a normalized string.
Returns
string
Definition at line 341 of file Authentication.php.
References $parameters, and OAuthUtil\build_http_query().
Referenced by get_signature_base_string().
{
     // Grab all parameters
     $params = $this->parameters;
     // Remove oauth_signature if present
     // Ref: Spec: 9.1.1 ("The oauth_signature parameter MUST be excluded.")
     if (isset($params['oauth_signature'])) {
       unset($params['oauth_signature']);
     }
     return OAuthUtil::build_http_query($params);
   }
OAuthRequest::get_signature_base_string ()
Returns the base string of this request.
The base string defined as the method, the url and the parameters (normalized), each urlencoded and the concated with &.
Definition at line 361 of file Authentication.php.
References get_normalized_http_method(), get_normalized_http_url(), get_signable_parameters(), and OAuthUtil\urlencode_rfc3986().
{
     $parts = array(
       $this->get_normalized_http_method(),
       $this->get_normalized_http_url(),
       $this->get_signable_parameters()
     );
     $parts = OAuthUtil::urlencode_rfc3986($parts);
     return implode('&', $parts);
   }
OAuthRequest::set_parameter ($name, $value, $allow_duplicates = true)
Definition at line 310 of file Authentication.php.
Referenced by sign_request().
{
     if ($allow_duplicates && isset($this->parameters[$name])) {
       // We have already added parameter(s) with this name, so add to the list
       if (is_scalar($this->parameters[$name])) {
         // This is the first duplicate, so transform scalar (string)
         // into an array so we can add the duplicates
         $this->parameters[$name] = array($this->parameters[$name]);
       }
       $this->parameters[$name][] = $value;
     } else {
       $this->parameters[$name] = $value;
     }
   }
OAuthRequest::sign_request ($signature_method, $consumer, $token)
Definition at line 449 of file Authentication.php.
References build_signature(), and set_parameter().
{
     $this->set_parameter(
       "oauth_signature_method",
       $signature_method->get_name(),
       false
     );
     $signature = $this->build_signature($signature_method, $consumer, $token);
     $this->set_parameter("oauth_signature", $signature, false);
   }
OAuthRequest::to_header ($realm = null)
builds the Authorization: header
Definition at line 423 of file Authentication.php.
References OAuthUtil\urlencode_rfc3986().
{
     if($realm)
       $out = 'Authorization: OAuth realm="' . OAuthUtil::urlencode_rfc3986($realm) . '"';
     else
       $out = 'Authorization: OAuth';
     $total = array();
     foreach ($this->parameters as $k => $v) {
       if (substr($k, 0, 5) != "oauth") continue;
       if (is_array($v)) {
         throw new OAuthException('Arrays not supported in headers');
       }
       $out .= ',' .
               OAuthUtil::urlencode_rfc3986($k) .
               '="' .
               OAuthUtil::urlencode_rfc3986($v) .
               '"';
     }
     return $out;
   }
OAuthRequest::to_postdata ()
builds the data one would send in a POST request
Definition at line 416 of file Authentication.php.
References OAuthUtil\build_http_query().
Referenced by to_url().
{
     return OAuthUtil::build_http_query($this->parameters);
   }
OAuthRequest::to_url ()
builds a url usable for a GET request
Definition at line 404 of file Authentication.php.
References get_normalized_http_url(), and to_postdata().
Referenced by __toString().
{
     $post_data = $this->to_postdata();
     $out = $this->get_normalized_http_url();
     if ($post_data) {
       $out .= '?'.$post_data;
     }
     return $out;
   }
OAuthRequest::unset_parameter ($name)
Definition at line 333 of file Authentication.php.
{
     unset($this->parameters[$name]);
   }
Field Documentation
OAuthRequest::$base_string
Definition at line 229 of file Authentication.php.
OAuthRequest::$http_method private
Definition at line 226 of file Authentication.php.
Referenced by __construct(), from_consumer_and_token(), and from_request().
OAuthRequest::$http_url private
Definition at line 227 of file Authentication.php.
Referenced by __construct(), from_consumer_and_token(), and from_request().
OAuthRequest::$parameters private
Definition at line 225 of file Authentication.php.
Referenced by __construct(), from_consumer_and_token(), from_request(), get_parameters(), and get_signable_parameters().
OAuthRequest::$POST_INPUT = 'php://input' static
Definition at line 231 of file Authentication.php.
OAuthRequest::$version = '1.0' static
Definition at line 230 of file Authentication.php.
Referenced by from_consumer_and_token().
The documentation for this class was generated from the following file:
Authentication.php