Constant Contact for WordPress: KWS_V1API Class Reference
KWS_V1API Class Reference
Public Member Functions
__construct ($authType, $apiKey, $username, $param)
refreshCache ($type= '')
getEventDetails (Event $Event)
Get all details for an event.
getRegistrantDetails (Registrant $Registrant)
Get detailed information on a Registrant.
Static Public Attributes
static $registrant_cache_age
static $event_cache_age
Detailed Description
Definition at line 3 of file class.kwsv1api.php.
Constructor & Destructor Documentation
KWS_V1API::__construct ($authType, $apiKey, $username, $param)
Definition at line 8 of file class.kwsv1api.php.
{
         parent::__construct($authType, $apiKey, $username, $param);
         self::$event_cache_age = apply_filters('constant_contact_event_cache_age', apply_filters('constant_contact_cache_age', 60 * 60 * 6));
         self::$registrant_cache_age = apply_filters('constant_contact_registrant_cache_age', apply_filters('constant_contact_cache_age', 60 * 60 * 24 * 7));
     }
Member Function Documentation
KWS_V1API::getEventDetails (Event $Event)
Get all details for an event.
Parameters
Event Event - Event object to get details for
Returns
Event
Definition at line 24 of file class.kwsv1api.php.
References refreshCache().
{
         $EventsCollection = new EventsCollection($this->CTCTRequest);
         $key = constant_contact_cache_key('Event', $Event);
         $details = get_transient($key);
         if(!$details || $this->refreshCache('event')) {
             $details = $EventsCollection->getEventDetails($this->CTCTRequest->baseUri.$Event->link);
             set_transient( $key, $details, self::$event_cache_age);
         }
         return $details;
     }
KWS_V1API::getRegistrantDetails (Registrant $Registrant)
Get detailed information on a Registrant.
Parameters
Registrant $Registrant - Registrant Object
Returns
Registrant
Definition at line 42 of file class.kwsv1api.php.
References refreshCache().
{
         $EventsCollection = new EventsCollection($this->CTCTRequest);
         $key = constant_contact_cache_key('Registrant', $Registrant);
         $details = get_transient( $key );
         if(!$details || $this->refreshCache('registrant')) {
             $details = $EventsCollection->getRegistrantDetails($this->CTCTRequest->baseUri.$Registrant->link);
             set_transient( $key, $details, self::$registrant_cache_age);
         }
         return $details;
     }
KWS_V1API::refreshCache ($type = '')
Definition at line 15 of file class.kwsv1api.php.
Referenced by getEventDetails(), and getRegistrantDetails().
{
         return constant_contact_refresh_cache($type);
     }
Field Documentation
KWS_V1API::$event_cache_age static
Definition at line 6 of file class.kwsv1api.php.
KWS_V1API::$registrant_cache_age static
Definition at line 5 of file class.kwsv1api.php.
The documentation for this class was generated from the following file:
class.kwsv1api.php