Constant Contact for WordPress: KWSOAuth2 Class Reference
KWSOAuth2 Class Reference
Public Member Functions
__construct ($processResponse=true)
saveToken ($token, $configured=false)
getToken ($key= 'access_token')
Get the token response from the WP database and return the token, if exists.
deleteToken ()
Public Member Functions inherited from Ctct\Auth\CtctOAuth2
__construct ($clientId, $clientSecret, $redirectUri, $restClient=null)
getAuthorizationUrl ($server=true, $state=null)
Get the URL at which the user can authenticate and authorize the requesting application.
getAccessToken ($code)
Obtain an access token.
getTokenInfo ($accessToken)
Get an information about an access token.
Static Public Member Functions
static getInstance ()
static processResponse ($force=false)
Private Member Functions
getRedirectUri ($urlencode=true)
Static Private Attributes
static $token
static $error
static $instance
Additional Inherited Members
Data Fields inherited from Ctct\Auth\CtctOAuth2
$clientId
$clientSecret
$redirectUri
$props
Detailed Description
Definition at line 16 of file class.kwsoauth2.php.
Constructor & Destructor Documentation
KWSOAuth2::__construct ($processResponse = true)
Definition at line 22 of file class.kwsoauth2.php.
References getRedirectUri(), and processResponse().
{
         $this->redirect_uri = $this->getRedirectUri(false);
         parent::__construct(CTCT_APIKEY, CTCT_APISECRET, $this->redirect_uri, new KWSRestClient(CTCT_APIKEY));
         if($processResponse) {
             $this->processResponse();
         }
     }
Member Function Documentation
KWSOAuth2::deleteToken ()
Definition at line 126 of file class.kwsoauth2.php.
{
         if(current_user_can('manage_options')) {
             delete_site_option( 'ctct_configured' );
             delete_site_option( 'ctct_token_response' );
         }
     }
static KWSOAuth2::getInstance () static
Definition at line 33 of file class.kwsoauth2.php.
{
         if(empty(self::$instance)) {
             self::$instance = new KWSOAuth2(false);
         }
         return self::$instance;
     }
KWSOAuth2::getRedirectUri ($urlencode = true) private
Definition at line 75 of file class.kwsoauth2.php.
Referenced by __construct().
{
         $url = add_query_arg(array(
                 '_wpnonce'  => wp_create_nonce('ctct_oauth'),
                 'prefix'    => is_ssl() ? 'https' : 'http',
                 'domain'    => str_replace(array('http://', 'https://'), '', trailingslashit( get_bloginfo('url') )),
                 'action'    => 'ctct_oauth'
             ), 'http://ctct.katz.co/');
         return $urlencode ? urlencode($url) : $url;
     }
KWSOAuth2::getToken ($key = 'access_token')
Get the token response from the WP database and return the token, if exists.
The token response is saved in the DB as an array (access_token, expires_in, and token_type)
Returns
string|boolean If token, returns token string. Otherwise, returns false.
Definition at line 105 of file class.kwsoauth2.php.
References $token.
{
         $token = maybe_unserialize(get_site_option( 'ctct_token_response', 'error_No_Token_In_Database'));
         if(!empty($token) && is_array($token) && !empty($token[$key])) {
             if($key === 'access_token') {
                 self::$token = $token[$key];
             }
             $value = $token[$key];
         } else {
             if($key === 'access_token') {
                 self::$error = $token;
                 self::$token = false;
             }
             $value = false;
         }
         return $value;
     }
static KWSOAuth2::processResponse ($force = false) static
Definition at line 41 of file class.kwsoauth2.php.
References $token.
Referenced by __construct().
{
         // Response
         if(isset($_REQUEST['_wpnonce']) && wp_verify_nonce($_REQUEST['_wpnonce'], 'ctct_oauth')) {
             # http://ctct.katz.co/?_wpnonce=13d09269c5&prefix=http&domain=localhost.local/wordpress/&action=ctct_oauth&error=access_denied&error_description=User+denied+authentication./
             if(isset($_REQUEST['error'])) {
                 $url = add_query_arg(array('error' => esc_html($_REQUEST['error']), 'error_description' => urlencode(untrailingslashit( $_REQUEST['error_description']))), admin_url('admin.php?page=constant-contact-api'));
                     wp_redirect($url);
                 die();
             }
             if(isset($_REQUEST['code'])) {
                 try {
                     $token = self::getInstance()->getAccessToken($_REQUEST['code']);
                     $token['_wpnonce'] = $_REQUEST['_wpnonce'];
                     $token['time'] = time();
                     $token['username'] = $_REQUEST['username'];
                     self::getInstance()->saveToken($token, true);
                     do_action('ctct_token_saved', $token);
                 } catch(Exception $e) {
                     $token = false;
                     self::getInstance()->saveToken($e->getMessage(), false);
                 }
                 do_action('ctct_token_updated', $token);
                 wp_redirect( admin_url('admin.php?page=constant-contact-api&oauth=new') );
                 die();
             }
         }
     }
KWSOAuth2::saveToken ($token, $configured = false)
Definition at line 87 of file class.kwsoauth2.php.
References $token.
{
         if(!$configured) {
             delete_site_option( 'ctct_configured' );
         } else {
             update_site_option( 'ctct_configured', 1);
         }
         update_site_option( 'ctct_token_response', $token );
     }
Field Documentation
KWSOAuth2::$error static private
Definition at line 19 of file class.kwsoauth2.php.
KWSOAuth2::$instance static private
Definition at line 20 of file class.kwsoauth2.php.
KWSOAuth2::$token static private
Definition at line 18 of file class.kwsoauth2.php.
Referenced by getToken(), processResponse(), and saveToken().
The documentation for this class was generated from the following file:
class.kwsoauth2.php