Constant Contact for WordPress: Ctct\Services\BaseService Class Reference
Ctct\Services\BaseService Class Reference
Public Member Functions
__construct ($apiKey, $restClient=null)
Constructor with the option to to supply an alternative rest client to be used.
buildUrl ($url, $queryParams=null)
Build a url from the base url and query parameters array.
getRestClient ()
Get the rest client being used by the service.
setRestClient (RestClientInterface $restClient)
Static Protected Member Functions
static getHeaders ($accessToken)
Helper function to return required headers for making an http request with constant contact.
Protected Attributes
$restClient
$apiKey
Detailed Description
Definition at line 13 of file BaseService.php.
Constructor & Destructor Documentation
Ctct\Services\BaseService::__construct ($apiKey, $restClient = null)
Constructor with the option to to supply an alternative rest client to be used.
Parameters
RestClientInterface - RestClientInterface implementation to be used in the service
Definition at line 31 of file BaseService.php.
References Ctct\Services\BaseService\$apiKey, and Ctct\Services\BaseService\$restClient.
     {
         $this->apiKey = $apiKey;
         if (is_null($restClient)) {
             $this->restClient = new RestClient();
         } else {
             $this->restClient = $restClient;
         }
     }
Member Function Documentation
Ctct\Services\BaseService::buildUrl ($url, $queryParams = null)
Build a url from the base url and query parameters array.
Returns
string
Definition at line 46 of file BaseService.php.
Referenced by Ctct\Services\EmailMarketingService\addCampaign(), Ctct\Services\ActivityService\addClearListsActivity(), Ctct\Services\ContactService\addContact(), Ctct\Services\ActivityService\addExportContactsActivity(), Ctct\Services\ListService\addList(), Ctct\Services\ActivityService\addRemoveContactsFromListsActivity(), Ctct\Services\CampaignScheduleService\addSchedule(), Ctct\Services\ActivityService\createAddContactsActivity(), Ctct\Services\EmailMarketingService\deleteCampaign(), Ctct\Services\ContactService\deleteContact(), Ctct\Services\ContactService\deleteContactFromList(), Ctct\Services\ContactService\deleteContactFromLists(), Ctct\Services\CampaignScheduleService\deleteSchedule(), Ctct\Services\ActivityService\getActivities(), Ctct\Services\ActivityService\getActivity(), Ctct\Services\CampaignTrackingService\getBounces(), Ctct\Services\ContactTrackingService\getBounces(), Ctct\Services\EmailMarketingService\getCampaign(), Ctct\Services\EmailMarketingService\getCampaigns(), Ctct\Services\CampaignTrackingService\getClicks(), Ctct\Services\ContactTrackingService\getClicks(), Ctct\Services\ContactService\getContact(), Ctct\Services\ContactService\getContacts(), Ctct\Services\ListService\getContactsFromList(), Ctct\Services\CampaignTrackingService\getForwards(), Ctct\Services\ContactTrackingService\getForwards(), Ctct\Services\ListService\getList(), Ctct\Services\ListService\getLists(), Ctct\Services\CampaignTrackingService\getOpens(), Ctct\Services\ContactTrackingService\getOpens(), Ctct\Services\CampaignScheduleService\getSchedule(), Ctct\Services\CampaignScheduleService\getSchedules(), Ctct\Services\CampaignTrackingService\getSends(), Ctct\Services\ContactTrackingService\getSends(), Ctct\Services\CampaignTrackingService\getSummary(), Ctct\Services\ContactTrackingService\getSummary(), Ctct\Services\CampaignTrackingService\getUnsubscribes(), Ctct\Services\ContactTrackingService\getUnsubscribes(), Ctct\Services\AccountService\getVerifiedEmailAddresses(), Ctct\Services\CampaignScheduleService\sendTest(), Ctct\Services\EmailMarketingService\updateCampaign(), Ctct\Services\ContactService\updateContact(), Ctct\Services\ListService\updateList(), and Ctct\Services\CampaignScheduleService\updateSchedule().
     {
         $keyArr = array('api_key' => $this->apiKey);
         if ($queryParams) {
             $params = array_merge($keyArr, $queryParams);
         } else {
             $params = $keyArr;
         }
         return $url . '?' . http_build_query($params);
     }
static Ctct\Services\BaseService::getHeaders ($accessToken) static protected
Helper function to return required headers for making an http request with constant contact.
Parameters
$accessToken - OAuth2 access token to be placed into the Authorization header
Returns
array - authorization headers
Definition at line 78 of file BaseService.php.
     {
         return array(
             'Content-Type: application/json',
             'Accept: application/json',
             'Authorization: Bearer ' . $accessToken
         );
     }
Ctct\Services\BaseService::getRestClient ()
Get the rest client being used by the service.
Returns
RestClientInterface - RestClientInterface implementation being used
Definition at line 62 of file BaseService.php.
References Ctct\Services\BaseService\$restClient.
     {
         return $this->restClient;
     }
Ctct\Services\BaseService::setRestClient (RestClientInterface $restClient)
Definition at line 67 of file BaseService.php.
References Ctct\Services\BaseService\$restClient.
     {
         $this->restClient = $restClient;
     }
Field Documentation
Ctct\Services\BaseService::$apiKey protected
Definition at line 25 of file BaseService.php.
Referenced by Ctct\Services\BaseService\__construct().
Ctct\Services\BaseService::$restClient protected
Definition at line 19 of file BaseService.php.
Referenced by Ctct\Services\BaseService\__construct(), Ctct\Services\BaseService\getRestClient(), and Ctct\Services\BaseService\setRestClient().
The documentation for this class was generated from the following file:
BaseService.php