Constant Contact for WordPress: Net_DNS_RR_AAAA Class Reference
Net_DNS_RR_AAAA Class Reference
Public Member Functions
Net_DNS_RR_AAAA (&$rro, $data, $offset= '')
rdatastr ()
rr_rdata ($packet, $offset)
ipv6_compress ($addr)
ipv6_decompress ($pack)
Public Member Functions inherited from Net_DNS_RR
Net_DNS_RR ($rrdata)
& factory ($rrdata, $update_type= '')
& new_from_data ($name, $rrtype, $rrclass, $ttl, $rdlength, $data, $offset)
& new_from_string ($rrstring, $update_type= '')
& new_from_array ($rrarray)
display ()
string ()
rdatastr ()
rdata (&$packetORrdata, $offset= '')
rr_rdata (&$packet, $offset)
data (&$packet, $offset)
Data Fields
$name
$type
$class
$ttl
$rdlength
$rdata
$address
Data Fields inherited from Net_DNS_RR
$name
$type
$class
$ttl
$rdlength
$rdata
Detailed Description
Definition at line 30 of file AAAA.php.
Member Function Documentation
Net_DNS_RR_AAAA::ipv6_compress ($addr)
Definition at line 83 of file AAAA.php.
Referenced by rr_rdata().
     {
         $numparts = count(explode(':', $addr));
         if ($numparts < 3 || $numparts > 8 ||
             !preg_match('/^([0-9A-F]{0,4}:){0,7}(:[0-9A-F]{0,4}){0,7}$/i', $addr)) {
             /* Non-sensical IPv6 address */
             return pack('n8', 0, 0, 0, 0, 0, 0, 0, 0);
         }
         if (strpos($addr, '::') !== false) {
             /* First we have to normalize the address, turn :: into :0:0:0:0: */
             $filler = str_repeat(':0', 9 - $numparts) . ':';
             if (substr($addr, 0, 2) == '::') {
                 $filler = "0$filler";
             }
             if (substr($addr, -2, 2) == '::') {
                 $filler .= '0';
             }
             $addr = str_replace('::', $filler, $addr);
         }
         $aparts = explode(':', $addr);
         return pack('n8', hexdec($aparts[0]), hexdec($aparts[1]), hexdec($aparts[2]), hexdec($aparts[3]),
                           hexdec($aparts[4]), hexdec($aparts[5]), hexdec($aparts[6]), hexdec($aparts[7]));
     }
Net_DNS_RR_AAAA::ipv6_decompress ($pack)
Definition at line 109 of file AAAA.php.
Referenced by Net_DNS_RR_AAAA().
     {
         if (strlen($pack) != 16) {
             /* Must be 8 shorts long */
             return '::';
         }
         $a = unpack('n8', $pack);
         $addr = vsprintf("%x:%x:%x:%x:%x:%x:%x:%x", $a);
         /* Shorthand the first :0:0: set into a :: */
         /* TODO: Make this is a single replacement pattern */
         if (substr($addr, -4) == ':0:0') {
             return preg_replace('/((:0){2,})$/', '::', $addr);
         } elseif (substr($addr, 0, 4) == '0:0:') {
             return '0:0:'. substr($addr, 4);
         } else {
             return preg_replace('/(:(0:){2,})/', '::', $addr);
         }
     }
Net_DNS_RR_AAAA::Net_DNS_RR_AAAA (& $rro, $data, $offset = '')
Definition at line 43 of file AAAA.php.
References ipv6_decompress(), and Net_DNS_RR\rdata().
     {
         $this->name = $rro->name;
         $this->type = $rro->type;
         $this->class = $rro->class;
         $this->ttl = $rro->ttl;
         $this->rdlength = $rro->rdlength;
         $this->rdata = $rro->rdata;
         if ($offset) {
             $this->address = Net_DNS_RR_AAAA::ipv6_decompress(substr($this->rdata, 0, $this->rdlength));
         } else {
             if (strlen($data)) {
                 if (count($adata = explode(':', $data, 8)) >= 3) {
                     foreach($adata as $addr)
                         if (!preg_match('/^[0-9A-F]{0,4}$/i', $addr)) return;
                     $this->address = trim($data);
                 }
             }
         }
     }
Net_DNS_RR_AAAA::rdatastr ()
Definition at line 67 of file AAAA.php.
References $address.
     {
         if (strlen($this->address)) {
             return $this->address;
         }
         return '; no data';
     }
Net_DNS_RR_AAAA::rr_rdata ($packet, $offset)
Definition at line 76 of file AAAA.php.
References ipv6_compress().
     {
         return Net_DNS_RR_AAAA::ipv6_compress($this->address);
     }
Field Documentation
Net_DNS_RR_AAAA::$address
Definition at line 39 of file AAAA.php.
Referenced by rdatastr().
Net_DNS_RR_AAAA::$class
Definition at line 35 of file AAAA.php.
Net_DNS_RR_AAAA::$name
Definition at line 33 of file AAAA.php.
Net_DNS_RR_AAAA::$rdata
Definition at line 38 of file AAAA.php.
Net_DNS_RR_AAAA::$rdlength
Definition at line 37 of file AAAA.php.
Net_DNS_RR_AAAA::$ttl
Definition at line 36 of file AAAA.php.
Net_DNS_RR_AAAA::$type
Definition at line 34 of file AAAA.php.
The documentation for this class was generated from the following file:
AAAA.php