Constant Contact for WordPress: Net_DNS_RR_NAPTR Class Reference
Net_DNS_RR_NAPTR Class Reference
Public Member Functions
Net_DNS_RR_NAPTR (&$rro, $data, $offset= '')
rdatastr ()
rr_rdata ($packet, $offset)
Public Member Functions inherited from Net_DNS_RR
Net_DNS_RR ($rrdata)
& factory ($rrdata, $update_type= '')
& new_from_data ($name, $rrtype, $rrclass, $ttl, $rdlength, $data, $offset)
& new_from_string ($rrstring, $update_type= '')
& new_from_array ($rrarray)
display ()
string ()
rdatastr ()
rdata (&$packetORrdata, $offset= '')
rr_rdata (&$packet, $offset)
data (&$packet, $offset)
Data Fields
$name
$type
$class
$ttl
$rdlength
$rdata
$order
$preference
$flags
$services
$regex
$replacement
Data Fields inherited from Net_DNS_RR
$name
$type
$class
$ttl
$rdlength
$rdata
Detailed Description
Definition at line 29 of file NAPTR.php.
Member Function Documentation
Net_DNS_RR_NAPTR::Net_DNS_RR_NAPTR (& $rro, $data, $offset = '')
Definition at line 47 of file NAPTR.php.
References $flags, $regex, $replacement, $services, Net_DNS_Packet\dn_expand(), Net_DNS_Packet\label_extract(), and Net_DNS_RR\rdata().
     {
         $this->name = $rro->name;
         $this->type = $rro->type;
         $this->class = $rro->class;
         $this->ttl = $rro->ttl;
         $this->rdlength = $rro->rdlength;
         $this->rdata = $rro->rdata;
         if ($offset) {
             if ($this->rdlength > 0) {
                 $a = unpack("@$offset/norder/npreference", $data);
                 $offset += 4;
                 list($flags, $offset) = Net_DNS_Packet::label_extract($data, $offset);
                 list($services, $offset) = Net_DNS_Packet::label_extract($data, $offset);
                 list($regex, $offset) = Net_DNS_Packet::label_extract($data, $offset);
                 list($replacement, $offset) = Net_DNS_Packet::dn_expand($data, $offset);
                 $this->order = $a['order'];
                 $this->preference = $a['preference'];
                 $this->flags = $flags;
                 $this->services = $services;
                 $this->regex = $regex;
                 $this->replacement = $replacement;
             }
         } else {
             $data = str_replace('\\\\', chr(1) . chr(1), $data); /* disguise escaped backslash */
             $data = str_replace('\\"', chr(2) . chr(2), $data); /* disguise \" */
             ereg('([0-9]+)[ \t]+([0-9]+)[ \t]+("[^"]*"|[^ \t]*)[ \t]+("[^"]*"|[^ \t]*)[ \t]+("[^"]*"|[^ \t]*)[ \t]+(.*?)[ \t]*$', $data, $regs);
             $this->preference = $regs[1];
             $this->weight = $regs[2];
             foreach($regs as $idx => $value) {
                 $value = str_replace(chr(2) . chr(2), '\\"', $value);
                 $value = str_replace(chr(1) . chr(1), '\\\\', $value);
                 $regs[$idx] = stripslashes($value);
             }
             $this->flags = $regs[3];
             $this->services = $regs[4];
             $this->regex = $regs[5];
             $this->replacement = $regs[6];
         }
     }
Net_DNS_RR_NAPTR::rdatastr ()
Definition at line 92 of file NAPTR.php.
References Net_DNS_RR\rdata().
     {
         if ($this->rdata) {
             return intval($this->order) . ' ' . intval($this->preference) . ' "' . addslashes($this->flags) . '" "' .
                    addslashes($this->services) . '" "' . addslashes($this->regex) . '" "' . addslashes($this->replacement) . '"';
         } else return '; no data';
     }
Net_DNS_RR_NAPTR::rr_rdata ($packet, $offset)
Definition at line 102 of file NAPTR.php.
References $flags, $rdata, $regex, and $services.
     {
         if ($this->preference) {
             $rdata  = pack('nn', $this->order, $this->preference);
             $rdata .= pack('C', strlen($this->flags))    . $this->flags;
             $rdata .= pack('C', strlen($this->services)) . $this->services;
             $rdata .= pack('C', strlen($this->regex))    . $this->regex;
             $rdata .= $packet->dn_comp($this->replacement, $offset + strlen($rdata));
             return $rdata;
         }
         return null;
     }
Field Documentation
Net_DNS_RR_NAPTR::$class
Definition at line 34 of file NAPTR.php.
Net_DNS_RR_NAPTR::$flags
Definition at line 40 of file NAPTR.php.
Referenced by Net_DNS_RR_NAPTR(), and rr_rdata().
Net_DNS_RR_NAPTR::$name
Definition at line 32 of file NAPTR.php.
Net_DNS_RR_NAPTR::$order
Definition at line 38 of file NAPTR.php.
Net_DNS_RR_NAPTR::$preference
Definition at line 39 of file NAPTR.php.
Net_DNS_RR_NAPTR::$rdata
Definition at line 37 of file NAPTR.php.
Referenced by rr_rdata().
Net_DNS_RR_NAPTR::$rdlength
Definition at line 36 of file NAPTR.php.
Net_DNS_RR_NAPTR::$regex
Definition at line 42 of file NAPTR.php.
Referenced by Net_DNS_RR_NAPTR(), and rr_rdata().
Net_DNS_RR_NAPTR::$replacement
Definition at line 43 of file NAPTR.php.
Referenced by Net_DNS_RR_NAPTR().
Net_DNS_RR_NAPTR::$services
Definition at line 41 of file NAPTR.php.
Referenced by Net_DNS_RR_NAPTR(), and rr_rdata().
Net_DNS_RR_NAPTR::$ttl
Definition at line 35 of file NAPTR.php.
Net_DNS_RR_NAPTR::$type
Definition at line 33 of file NAPTR.php.
The documentation for this class was generated from the following file:
NAPTR.php