Constant Contact for WordPress: CTCT_Admin_Campaigns Class Reference
CTCT_Admin_Campaigns Class Reference
Data Fields
$errors
$id
$can_edit = false
$can_add = false
Data Fields inherited from CTCT_Admin_Page
$key
$title
$permission = 'manage_options'
$cc
$oauth
$errors
$can_edit = false
$can_add = false
$component = ''
$pointers = array()
Protected Member Functions
getKey ()
getNavTitle ()
getTitle ($value= '')
add ()
processForms ()
edit ()
single ()
view ()
Protected Member Functions inherited from CTCT_Admin_Page
addIncludes ()
addScripts ()
isAdd ()
isEdit ()
isSingle ()
isView ()
getKey ()
getTitle ()
getNavTitle ()
add ()
edit ()
view ()
single ()
processForms ()
addActions ()
content ()
print_errors ()
Additional Inherited Members
Public Member Functions inherited from CTCT_Admin_Page
__construct ()
print_styles ()
print_scripts ()
help_tabs ($tabs)
pointer_content ()
getPointers ($hook_suffix= '')
getPermission ()
add_menu ()
page ()
Detailed Description
Definition at line 12 of file campaigns.php.
Member Function Documentation
CTCT_Admin_Campaigns::add () protected
Definition at line 38 of file campaigns.php.
 {}
CTCT_Admin_Campaigns::edit () protected
Definition at line 42 of file campaigns.php.
References $id, and CTCT_Admin_Page\$key.
{
         $id = intval(@$_GET['edit']);
         /**
          * @todo Specify no contact ID error
          */
         if(!isset($id) || empty($id)) {
             echo 'no contact is specified.';
             return;
         }
         $CC_Campaign = $this->cc->getEmailCampaign(CTCT_ACCESS_TOKEN, $id);
         $Campaign = new KWSCampaign($CC_Campaign);
         if($Campaign->status === 'DRAFT') {
             foreach(array('last_run_date', 'next_run_date', 'tracking_summary', 'sent_to_contact_lists', 'click_through_details') as $key) {
                 unset($Campaign->{$key});
             }
         }
         include(CTCT_DIR_PATH.'views/admin/view.campaign-edit.php');
     }
CTCT_Admin_Campaigns::getKey () protected
Definition at line 19 of file campaigns.php.
{
         return "constant-contact-campaigns";
     }
CTCT_Admin_Campaigns::getNavTitle () protected
Definition at line 23 of file campaigns.php.
References CTCT_Admin_Page\getTitle().
{
         return $this->getTitle('views');
     }
CTCT_Admin_Campaigns::getTitle ($value = '') protected
Definition at line 26 of file campaigns.php.
References CTCT_Admin_Page\isEdit(), and CTCT_Admin_Page\isSingle().
{
         if(empty($value) && $this->isEdit() || $value == 'edit')
             return "Edit Campaign";
         if(empty($value) && $this->isSingle() || $value == 'single')
             return sprintf('Campaign #%s', $_GET['view']);
         return 'Campaigns';
     }
CTCT_Admin_Campaigns::processForms () protected
Definition at line 40 of file campaigns.php.
 {}
CTCT_Admin_Campaigns::single () protected
Definition at line 67 of file campaigns.php.
{
         $id = intval(@$_GET['view']);
         /**
          * @todo Specify no contact ID error
          */
         if(!isset($id) || empty($id)) {
             echo 'no list is specified.';
             return;
         }
         $CC_Campaign = $this->cc->getEmailCampaign(CTCT_ACCESS_TOKEN, $id);
         $Campaign = new KWSCampaign($CC_Campaign);
         include(CTCT_DIR_PATH.'views/admin/view.campaign-view.php');
     }
CTCT_Admin_Campaigns::view () protected
Definition at line 86 of file campaigns.php.
{
         $status = isset($_GET['status']) ? $_GET['status'] : null;
         add_filter('ctct_cachekey', function() {
             return isset($_GET['status']) ? false : 'ctct_all_campaigns';
         });
         $Campaigns = $this->cc->getAllEmailCampaigns($status);
         kws_print_subsub('status', array(
             array('val' => '', 'text' => 'All'),
             array('val' => 'DRAFT', 'text' => 'Draft'),
             array('val' => 'RUNNING', 'text' => 'Running'),
             array('val' => 'SCHEDULED', 'text' => 'Scheduled'),
             array('val' => 'SENT', 'text' => 'Sent'),
         ));
         include(CTCT_DIR_PATH.'views/admin/view.campaigns-view.php');
     }
Field Documentation
CTCT_Admin_Campaigns::$can_add = false
Definition at line 17 of file campaigns.php.
CTCT_Admin_Campaigns::$can_edit = false
Definition at line 16 of file campaigns.php.
CTCT_Admin_Campaigns::$errors
Definition at line 14 of file campaigns.php.
CTCT_Admin_Campaigns::$id
Definition at line 15 of file campaigns.php.
Referenced by edit().
The documentation for this class was generated from the following file:
campaigns.php