Constant Contact for WordPress: CTCT_Admin_Page Class Reference
CTCT_Admin_Page Class Reference
Public Member Functions
__construct ()
print_styles ()
print_scripts ()
help_tabs ($tabs)
pointer_content ()
getPointers ($hook_suffix= '')
getPermission ()
add_menu ()
page ()
Data Fields
$key
$title
$permission = 'manage_options'
$cc
$oauth
$errors
$can_edit = false
$can_add = false
$component = ''
$pointers = array()
Protected Member Functions
addIncludes ()
addScripts ()
isAdd ()
isEdit ()
isSingle ()
isView ()
getKey ()
getTitle ()
getNavTitle ()
add ()
edit ()
view ()
single ()
processForms ()
addActions ()
content ()
print_errors ()
Detailed Description
Definition at line 4 of file class.ctct_admin_page.php.
Constructor & Destructor Documentation
CTCT_Admin_Page::__construct ()
Definition at line 17 of file class.ctct_admin_page.php.
References addActions(), addIncludes(), WP_CTCT\getInstance(), getKey(), getTitle(), and processForms().
{
         $this->addIncludes();
         $WP_CTCT = WP_CTCT::getInstance();
         $this->cc = $WP_CTCT->cc;
         $this->oauth = $WP_CTCT->oauth;
         $this->title = $this->getTitle();
         $this->key = $this->getKey();
         $this->processForms();
         add_action('admin_menu', array(&$this, 'add_menu'));
         if(is_admin()) {
             add_action('admin_print_scripts', array(&$this, 'print_scripts'));
             add_action('admin_print_styles', array(&$this, 'print_styles'));
         }
         add_filter( 'ctct_admin_pointers-'.$this->getKey(), array(&$this, 'pointer_content'));
         add_filter( 'constant_contact_help_tabs', array(&$this, 'help_tabs'));
         $this->addActions();
     }
Member Function Documentation
CTCT_Admin_Page::add () abstract protected
Referenced by content().
CTCT_Admin_Page::add_menu ()
Definition at line 178 of file class.ctct_admin_page.php.
References getKey(), and getNavTitle().
{
         // Only add the menu if connected to Constant Contact
         if(!$this->cc->isConfigured()) { return; }
         add_submenu_page( 'constant-contact-api', 'CTCT - '.htmlentities($this->title), '<span id="menu-'.esc_attr($this->getKey()).'">'.htmlentities($this->getNavTitle()).'</span>', $this->permission, $this->key, array(&$this, 'page'));
     }
CTCT_Admin_Page::addActions () protected
Definition at line 100 of file class.ctct_admin_page.php.
Referenced by __construct().
 {}
CTCT_Admin_Page::addIncludes () protected
Definition at line 43 of file class.ctct_admin_page.php.
Referenced by __construct().
 {}
CTCT_Admin_Page::addScripts () protected
Definition at line 79 of file class.ctct_admin_page.php.
Referenced by print_scripts().
 {}
CTCT_Admin_Page::content () protected
Definition at line 102 of file class.ctct_admin_page.php.
References $title, add(), edit(), isAdd(), isEdit(), isSingle(), single(), and view().
Referenced by page().
{
         Exceptional::$controller = $this->title;
         if($this->isAdd()) {
             Exceptional::$action = 'add';
             $this->add();
         } else if($this->isEdit()) {
             Exceptional::$action = 'edit';
             $this->edit();
         } else if($this->isSingle()) {
             Exceptional::$action = 'single';
             $this->single();
         } else {
             Exceptional::$action = 'view';
             $this->view();
         }
     }
CTCT_Admin_Page::edit () abstract protected
Referenced by content().
CTCT_Admin_Page::getKey () protected
Definition at line 85 of file class.ctct_admin_page.php.
References $key.
Referenced by __construct(), add_menu(), CTCT_Form_Designer\addIncludes(), CTCT_Form_Designer\addScripts(), getPointers(), and CTCT_Admin\pluginStatus().
{
         return $this->key;
     }
CTCT_Admin_Page::getNavTitle () protected
Definition at line 91 of file class.ctct_admin_page.php.
References $title.
Referenced by add_menu(), and page().
{
         return $this->title;
     }
CTCT_Admin_Page::getPermission ()
Definition at line 175 of file class.ctct_admin_page.php.
 {}
CTCT_Admin_Page::getPointers ($hook_suffix = '')
Definition at line 144 of file class.ctct_admin_page.php.
References $pointers, and getKey().
Referenced by print_scripts().
{
         global $plugin_page;
         if($plugin_page !== $this->getKey()) { return; }
        // Get pointers for this screen
         $pointers = apply_filters( 'ctct_admin_pointers-' . $this->getKey(), $this->pointers );
         if ( ! $pointers || ! is_array( $pointers ) )
             return;
         // Get dismissed pointers
         $dismissed = explode( ',', (string)get_user_meta( get_current_user_id(), 'dismissed_wp_pointers', true ) );
         $valid_pointers =array();
         // Check pointers and remove dismissed ones.
         foreach ( $pointers as $pointer_id => $pointer ) {
             // Sanity check
             if ( in_array( $pointer_id, $dismissed ) || empty( $pointer )  || empty( $pointer_id ) || empty( $pointer['target'] ) || empty( $pointer['options'] ) )
                 continue;
             $pointer['pointer_id'] = $pointer_id;
             // Add the pointer to $valid_pointers array
             $valid_pointers['pointers'][] =  $pointer;
         }
         #r($valid_pointers, true);
         return (array)$valid_pointers;
     }
CTCT_Admin_Page::getTitle () protected
Definition at line 88 of file class.ctct_admin_page.php.
References $title.
Referenced by __construct(), CTCT_Admin_Campaigns\getNavTitle(), and page().
{
         return $this->title;
     }
CTCT_Admin_Page::help_tabs ($tabs)
Definition at line 119 of file class.ctct_admin_page.php.
{
         foreach($tabs as &$tab) {
             $tab['title'] = str_replace('Constant Contact: ', '', $tab['title']);
         }
         return $tabs;
     }
CTCT_Admin_Page::isAdd () protected
Definition at line 80 of file class.ctct_admin_page.php.
Referenced by content(), and CTCT_Admin_Contacts\getTitle().
 { return isset($_GET['add']); }
CTCT_Admin_Page::isEdit () protected
Definition at line 81 of file class.ctct_admin_page.php.
Referenced by content(), CTCT_Admin_Contacts\getTitle(), CTCT_Admin_Campaigns\getTitle(), CTCT_Admin_Lists\getTitle(), CTCT_EventSpot\getTitle(), and page().
 { return isset($_GET['edit']); }
CTCT_Admin_Page::isSingle () protected
Definition at line 82 of file class.ctct_admin_page.php.
Referenced by content(), CTCT_Admin_Contacts\getTitle(), CTCT_Admin_Campaigns\getTitle(), CTCT_Admin_Lists\getTitle(), CTCT_EventSpot\getTitle(), and page().
 { return isset($_GET['view']); }
CTCT_Admin_Page::isView () protected
Definition at line 83 of file class.ctct_admin_page.php.
Referenced by page().
 { return !isset($_GET['view']) && !isset($_GET['edit']) && !isset($_GET['add']); }
CTCT_Admin_Page::page ()
Definition at line 208 of file class.ctct_admin_page.php.
References content(), getNavTitle(), getTitle(), isEdit(), isSingle(), isView(), and print_errors().
Referenced by CTCT_Constant_Analytics\addActions(), CTCT_Constant_Analytics\admin_head(), and CTCT_Constant_Analytics\enqueue_scripts().
                            { ?>
         <div class="wrap">
             <h2 class="cc_logo"><a class="cc_logo" href="<?php echo admin_url('admin.php?page=constant-contact-api'); ?>"><?php _e('Constant Contact', 'constant-contact-api'); ?></a></h2>
     <?php
         include(CTCT_DIR_PATH.'views/admin/view.page-menu.php');
         if(!$this->isView()) {
             $breadcrumb[] = '<a href="'.remove_query_arg(array('view', 'edit', 'add')).'">'.$this->getNavTitle().'</a>';
         }
         if($this->isEdit()) {
             $breadcrumb[] = '<a href="'.add_query_arg(array('view' => $_GET['edit']), remove_query_arg(array('edit'))).'">'.$this->getTitle('single').'</a>';
         }
         $breadcrumb[] = $this->getTitle();
         $button = '';
         if($this->isSingle() && $this->can_edit) {
             $button = ' <a href="'.add_query_arg(array('edit' => $_GET['view']), remove_query_arg('view')).'" class="button clear edit-new-h2" title="edit">'.__('Edit', 'constant-contact-api').'</a>';
         }
         if($this->isView() && $this->can_add) {
             $button = ' <a href="'.add_query_arg(array('add' => 1), remove_query_arg('status')).'" class="button clear edit-new-h2" title="Add" id="ctct-add-new-item">'.sprintf(__('Add %s', 'constant-contact-api'), $this->getTitle('single')).'</a>';
         }
         echo '<h2>'.implode(' &raquo; ', $breadcrumb).$button.'</h2>';
             $this->print_errors();
         // Show the content that's ready.
         flush();
         $this->content();
     ?>
         </div>
     <?php
     }
CTCT_Admin_Page::pointer_content ()
Definition at line 126 of file class.ctct_admin_page.php.
References $pointers.
{
         global $plugin_page;
         include_once(CTCT_DIR_PATH.'/inc/pointers.php');
         $pointers = ctct_get_pointers();
         if(isset($_GET['pointers']) && $_GET['pointers'] === 'debug' && current_user_can('manage_options')){
             // TODO: REmove this; it's only for debug
             foreach((array)$pointers as $k => $v) {
                 $pointers[rand(0,1000).$k] = $v;
                 unset($pointers[$k]);
             }
         }
         return apply_filters('constant_contact_pointers', $pointers);
     }
CTCT_Admin_Page::print_errors () protected
Definition at line 186 of file class.ctct_admin_page.php.
References $key.
Referenced by page().
{
         if(empty($this->errors)) { return; }
         echo '
             <div id="message" class="container alert-error errors error">
                 <h3>';
                 _e(sprintf('%s occurred:', _n( 'An error', 'Errors', sizeof($this->errors), 'constant-contact-api' )), 'constant-contact-api');
         echo ' </h3>
                 <ul class="ul-square">
         ';
             foreach($this->errors as $key => $error) {
                 echo '<li>'.esc_html($error->get_error_message()).' (<code>error code: '.esc_html($error->get_error_code()).'</code>)</li>';
             }
         echo '
                 </ul>
             </div>';
     }
CTCT_Admin_Page::print_scripts ()
Definition at line 54 of file class.ctct_admin_page.php.
References addScripts(), and getPointers().
{
         global $plugin_page;
         wp_enqueue_script('alertify', CTCT_FILE_URL.'js/alertify.js/lib/alertify.min.js', array('jquery'));
         wp_enqueue_script('jquery-cookie', CTCT_FILE_URL.'js/admin/jquery.cookie.js', array('jquery'));
         wp_enqueue_script('select2', CTCT_FILE_URL.'js/select2/select2.min.js', array('jquery'));
         wp_enqueue_script('ctct-admin-page', CTCT_FILE_URL.'js/admin/cc-page.js', array('jquery', 'jquery-effects-highlight', 'jquery-ui-tooltip', 'jquery-ui-tabs', 'select2', 'thickbox', 'wp-pointer'));
         wp_enqueue_script('ctct-admin-fittext', CTCT_FILE_URL.'js/admin/jquery.fittext.js', array('ctct-admin-page'));
         wp_enqueue_script('ctct-admin-equalize', CTCT_FILE_URL.'js/admin/jquery.equalize.min.js', array('ctct-admin-page'));
         wp_enqueue_script('ctct-admin-inlineedit', CTCT_FILE_URL.'js/admin/jquery.inlineedit.js', array('ctct-admin-page'));
         if($plugin_page === $this->key) {
             wp_localize_script( 'ctct-admin-page', 'CTCT', array(
                 'component' => $this->component,
                 'id' => @$_GET['view'],
                 '_wpnonce' => wp_create_nonce('ctct'),
                 'pointers' => $this->getPointers(),
             ));
         }
         $this->addScripts();
     }
CTCT_Admin_Page::print_styles ()
Definition at line 46 of file class.ctct_admin_page.php.
{
         wp_enqueue_style('constant-contact-api-admin', CTCT_FILE_URL.'css/admin/constant-contact-admin-css.css', array('thickbox'));
         wp_enqueue_style('alertify-core', CTCT_FILE_URL.'js/alertify.js/themes/alertify.core.css');
         wp_enqueue_style('alertify-default', CTCT_FILE_URL.'js/alertify.js/themes/alertify.default.css');
         wp_enqueue_style('select2', CTCT_FILE_URL.'css/select2/select2.css');
         wp_enqueue_style( 'wp-pointer' );
     }
CTCT_Admin_Page::processForms () abstract protected
Referenced by __construct().
CTCT_Admin_Page::single () abstract protected
Referenced by content().
CTCT_Admin_Page::view () abstract protected
Referenced by content().
Field Documentation
CTCT_Admin_Page::$can_add = false
Definition at line 13 of file class.ctct_admin_page.php.
CTCT_Admin_Page::$can_edit = false
Definition at line 12 of file class.ctct_admin_page.php.
CTCT_Admin_Page::$cc
Definition at line 9 of file class.ctct_admin_page.php.
Referenced by CTCT_Admin_User_Profile\update().
CTCT_Admin_Page::$component = ''
Definition at line 14 of file class.ctct_admin_page.php.
CTCT_Admin_Page::$errors
Definition at line 11 of file class.ctct_admin_page.php.
Referenced by CTCT_Constant_Analytics\show_ga_auth_error(), and CTCT_Constant_Analytics\warning_box().
CTCT_Admin_Page::$key
Definition at line 6 of file class.ctct_admin_page.php.
Referenced by CTCT_Admin_Campaigns\edit(), CTCT_Settings\get(), CTCT_Settings\get_setting(), getKey(), CTCT_EventSpot\latest_registrant(), print_errors(), CTCT_Settings\setting_input_generator(), and CTCT_Admin_User_Profile\update().
CTCT_Admin_Page::$oauth
Definition at line 10 of file class.ctct_admin_page.php.
CTCT_Admin_Page::$permission = 'manage_options'
Definition at line 8 of file class.ctct_admin_page.php.
CTCT_Admin_Page::$pointers = array()
Definition at line 15 of file class.ctct_admin_page.php.
Referenced by getPointers(), and pointer_content().
CTCT_Admin_Page::$title
Definition at line 7 of file class.ctct_admin_page.php.
Referenced by content(), getNavTitle(), and getTitle().
The documentation for this class was generated from the following file:
class.ctct_admin_page.php