Constant Contact for WordPress: Ctct\Services\EmailMarketingService Class Reference
Ctct\Services\EmailMarketingService Class Reference
Public Member Functions
addCampaign ($accessToken, Campaign $campaign)
Create a new campaign.
getCampaigns ($accessToken, Array $params=null)
Get a set of campaigns.
getCampaign ($accessToken, $campaign_id)
Get campaign details for a specific campaign.
deleteCampaign ($accessToken, $campaign_id)
Delete an email campaign.
updateCampaign ($accessToken, Campaign $campaign)
Update a specific email campaign.
Public Member Functions inherited from Ctct\Services\BaseService
__construct ($apiKey, $restClient=null)
Constructor with the option to to supply an alternative rest client to be used.
buildUrl ($url, $queryParams=null)
Build a url from the base url and query parameters array.
getRestClient ()
Get the rest client being used by the service.
setRestClient (RestClientInterface $restClient)
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Services\BaseService
static getHeaders ($accessToken)
Helper function to return required headers for making an http request with constant contact.
Protected Attributes inherited from Ctct\Services\BaseService
$restClient
$apiKey
Detailed Description
Definition at line 15 of file EmailMarketingService.php.
Member Function Documentation
Ctct\Services\EmailMarketingService::addCampaign ($accessToken, Campaign $campaign)
Create a new campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
Campaign $campaign - Campign to be created
Returns
Campaign
Definition at line 23 of file EmailMarketingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\EmailMarketing\Campaign\create(), Ctct\Util\Config\get(), and Ctct\Components\EmailMarketing\Campaign\toJson().
     {
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.campaigns');
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->post($url, parent::getHeaders($accessToken), $campaign->toJson());
         return Campaign::create(json_decode($response->body, true));
     }
Ctct\Services\EmailMarketingService::deleteCampaign ($accessToken, $campaign_id)
Delete an email campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $campaign_id - Valid campaign id
Returns
boolean
Definition at line 70 of file EmailMarketingService.php.
References Ctct\Services\BaseService\buildUrl(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . sprintf(Config::get('endpoints.campaign'), $campaign_id);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->delete($url, parent::getHeaders($accessToken));
         return ($response->info['http_code'] == 204) ? true : false;
     }
Ctct\Services\EmailMarketingService::getCampaign ($accessToken, $campaign_id)
Get campaign details for a specific campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $campaign_id - Valid campaign id
Returns
Campaign
Definition at line 56 of file EmailMarketingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\EmailMarketing\Campaign\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . sprintf(Config::get('endpoints.campaign'), $campaign_id);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         return Campaign::create(json_decode($response->body, true));
     }
Ctct\Services\EmailMarketingService::getCampaigns ($accessToken, Array $params = null)
Get a set of campaigns.
Parameters
string $accessToken - Constant Contact OAuth2 access token
array $params - query params to be appended to the request
Returns
ResultSet
Definition at line 37 of file EmailMarketingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\EmailMarketing\Campaign\createSummary(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.campaigns');
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $campaigns = array();
         foreach ($body['results'] as $contact) {
             $campaigns[] = Campaign::createSummary($contact);
         }
         return new ResultSet($campaigns, $body['meta']);
     }
Ctct\Services\EmailMarketingService::updateCampaign ($accessToken, Campaign $campaign)
Update a specific email campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
Campaign $campaign - Campaign to be updated
Returns
Campaign
Definition at line 84 of file EmailMarketingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\EmailMarketing\Campaign\create(), Ctct\Util\Config\get(), and Ctct\Components\EmailMarketing\Campaign\toJson().
     {
         $baseUrl = Config::get('endpoints.base_url') . sprintf(Config::get('endpoints.campaign'), $campaign->id);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->put($url, parent::getHeaders($accessToken), $campaign->toJson());
         return Campaign::create(json_decode($response->body, true));
     }
The documentation for this class was generated from the following file:
EmailMarketingService.php