Constant Contact for WordPress: SMTP_validateEmail Class Reference
SMTP_validateEmail Class Reference
Validate Email Addresses Via SMTP This queries the SMTP server to see if the email address is accepted.
Public Member Functions
SMTP_validateEmail ($emails=false, $sender=false)
Initializes the Class.
_parseEmail ($email)
setEmails ($emails)
Set the Emails to validate.
setSenderEmail ($email)
Set the Email of the sender/validator.
validate ($emails=false, $sender=false)
Validate Email Addresses.
send ($msg)
queryMX ($domain)
Query DNS server for MX entries.
microtime_float ()
Simple function to replicate PHP 5 behaviour.
debug ($str)
Data Fields
$sock
PHP Socket resource to remote MTA.
$user
Current User being validated.
$domain
Current domain where user is being validated.
$domains
List of domains to validate users on.
$port = 25
SMTP Port.
$max_conn_time = 30
Maximum Connection Time to wait for connection establishment per MTA.
$max_read_time = 5
Maximum time to read from socket before giving up.
$from_user = 'user'
username of sender
$from_domain = 'localhost'
Host Name of sender.
$nameservers
Nameservers to use when make DNS query for MX entries.
$debug = false
Detailed Description
Validate Email Addresses Via SMTP This queries the SMTP server to see if the email address is accepted.
Copyright
http://creativecommons.org/licenses/by/2.0/ - Please keep this comment intact
Author
gabe@.nosp@m.fiji.nosp@m.webde.nosp@m.sign.nosp@m..com adnan.nosp@m.@bar.nosp@m.akatd.nosp@m.esig.nosp@m.ns.ne.nosp@m.t
Version
0.1a
Definition at line 11 of file smtp_validateEmail.class.php.
Member Function Documentation
SMTP_validateEmail::_parseEmail ($email)
Definition at line 78 of file smtp_validateEmail.class.php.
References $domain, and $user.
Referenced by setEmails(), and setSenderEmail().
{
     $parts = explode('@', $email);
     $domain = array_pop($parts);
     $user= implode('@', $parts);
     return array($user, $domain);
  }
SMTP_validateEmail::debug ($str)
Definition at line 265 of file smtp_validateEmail.class.php.
Referenced by send(), and validate().
                       {
   if ($this->debug) {
    echo '<pre>'.htmlentities($str).'</pre>';
   }
  }
SMTP_validateEmail::microtime_float ()
Simple function to replicate PHP 5 behaviour.
http://php.net/microtime
Definition at line 260 of file smtp_validateEmail.class.php.
{
   list($usec, $sec) = explode(" ", microtime());
   return ((float)$usec + (float)$sec);
  }
SMTP_validateEmail::queryMX ($domain)
Query DNS server for MX entries.
Returns
Definition at line 232 of file smtp_validateEmail.class.php.
References $debug, $domain, and $nameservers.
Referenced by validate().
{
     $hosts = array();
     $mxweights = array();
     if (function_exists('getmxrr')) {
         getmxrr($domain, $hosts, $mxweights);
     } else {
         // windows, we need Net_DNS
         require_once 'Net/DNS.php';
         $resolver = new Net_DNS_Resolver();
         $resolver->debug = $this->debug;
         // nameservers to query
         $resolver->nameservers = $this->nameservers;
         $resp = $resolver->query($domain, 'MX');
         if ($resp) {
             foreach($resp->answer as $answer) {
                 $hosts[] = $answer->exchange;
                 $mxweights[] = $answer->preference;
             }
         }
     }
     return array($hosts, $mxweights);
  }
SMTP_validateEmail::send ($msg)
Definition at line 217 of file smtp_validateEmail.class.php.
References debug().
Referenced by validate().
                      {
   fwrite($this->sock, $msg."\r\n");
   $reply = fread($this->sock, 2082);
   $this->debug(">>>\n$msg\n");
   $this->debug("<<<\n$reply");
   return $reply;
  }
SMTP_validateEmail::setEmails ($emails)
Set the Emails to validate.
Parameters
$emails Array List of Emails
Definition at line 89 of file smtp_validateEmail.class.php.
References $domain, $user, and _parseEmail().
Referenced by SMTP_validateEmail(), and validate().
{
     foreach($emails as $email) {
         list($user, $domain) = $this->_parseEmail($email);
         if (!isset($this->domains[$domain])) {
              $this->domains[$domain] = array();
         }
         $this->domains[$domain][] = $user;
     }
  }
SMTP_validateEmail::setSenderEmail ($email)
Set the Email of the sender/validator.
Parameters
$email String
Definition at line 103 of file smtp_validateEmail.class.php.
References _parseEmail().
Referenced by SMTP_validateEmail(), and validate().
{
     $parts = $this->_parseEmail($email);
     $this->from_user = $parts[0];
     $this->from_domain = $parts[1];
  }
SMTP_validateEmail::SMTP_validateEmail ($emails = false, $sender = false)
Initializes the Class.
Returns
SMTP_validateEmail Instance
Parameters
$email Array[optional] List of Emails to Validate
$sender String[optional] Email of validator
Definition at line 69 of file smtp_validateEmail.class.php.
References setEmails(), and setSenderEmail().
{
   if ($emails) {
    $this->setEmails($emails);
   }
   if ($sender) {
    $this->setSenderEmail($sender);
   }
  }
SMTP_validateEmail::validate ($emails = false, $sender = false)
Validate Email Addresses.
Parameters
String $emails Emails to validate (recipient emails)
String $sender Sender's Email
Returns
Array Associative List of Emails and their validation results
Definition at line 115 of file smtp_validateEmail.class.php.
References $domain, $max_conn_time, $user, debug(), queryMX(), send(), setEmails(), and setSenderEmail().
{
   $results = array();
   if ($emails) {
    $this->setEmails($emails);
   }
   if ($sender) {
    $this->setSenderEmail($sender);
   }
   // query the MTAs on each Domain
   foreach($this->domains as $domain=>$users) {
      $mxs = array();
      // current domain being queried
      $this->domain = $domain;
       // retrieve SMTP Server via MX query on domain
       list($hosts, $mxweights) = $this->queryMX($domain);
       // retrieve MX priorities
       for($n=0; $n < count($hosts); $n++){
        $mxs[$hosts[$n]] = $mxweights[$n];
       }
       asort($mxs);
       // last fallback is the original domain
       $mxs[$this->domain] = 0;
       $this->debug(print_r($mxs, 1));
       $timeout = $this->max_conn_time;
       // try each host
       while(list($host) = each($mxs)) {
        // connect to SMTP server
        $this->debug("try $host:$this->port\n");
        if ($this->sock = fsockopen($host, $this->port, $errno, $errstr, (float) $timeout)) {
         stream_set_timeout($this->sock, $this->max_read_time);
         break;
        }
       }
       // did we get a TCP socket
       if ($this->sock) {
        $reply = fread($this->sock, 2082);
        $this->debug("<<<\n$reply");
        preg_match('/^([0-9]{3}) /ims', $reply, $matches);
        $code = isset($matches[1]) ? $matches[1] : '';
        if($code != '220') {
         // MTA gave an error...
         foreach($users as $user) {
             $results[$user.'@'.$domain] = false;
         }
         continue;
        }
        // say helo
        $this->send("HELO ".$this->from_domain);
        // tell of sender
        $this->send("MAIL FROM: <".$this->from_user.'@'.$this->from_domain.">");
        // ask for each recepient on this domain
        foreach($users as $user) {
            // ask of recepient
            $reply = $this->send("RCPT TO: <".$user.'@'.$domain.">");
             // get code and msg from response
            preg_match('/^([0-9]{3}) /ims', $reply, $matches);
            $code = isset($matches[1]) ? $matches[1] : '';
            if ($code == '250') {
             // you received 250 so the email address was accepted
             $results[$user.'@'.$domain] = true;
            } elseif ($code == '451' || $code == '452') {
             // you received 451 so the email address was greylisted (or some temporary error occured on the MTA) - so assume is ok
             $results[$user.'@'.$domain] = true;
            } else {
             $results[$user.'@'.$domain] = false;
            }
        }
        // reset before quit
        $this->send("RSET");
        // quit
        $this->send("quit");
        // close socket
        fclose($this->sock);
       }
     }
     return $results;
  }
Field Documentation
SMTP_validateEmail::$debug = false
Definition at line 61 of file smtp_validateEmail.class.php.
Referenced by queryMX().
SMTP_validateEmail::$domain
Current domain where user is being validated.
Definition at line 26 of file smtp_validateEmail.class.php.
Referenced by _parseEmail(), queryMX(), setEmails(), and validate().
SMTP_validateEmail::$domains
List of domains to validate users on.
Definition at line 30 of file smtp_validateEmail.class.php.
SMTP_validateEmail::$from_domain = 'localhost'
Host Name of sender.
Definition at line 51 of file smtp_validateEmail.class.php.
SMTP_validateEmail::$from_user = 'user'
username of sender
Definition at line 47 of file smtp_validateEmail.class.php.
SMTP_validateEmail::$max_conn_time = 30
Maximum Connection Time to wait for connection establishment per MTA.
Definition at line 38 of file smtp_validateEmail.class.php.
Referenced by validate().
SMTP_validateEmail::$max_read_time = 5
Maximum time to read from socket before giving up.
Definition at line 42 of file smtp_validateEmail.class.php.
Array SMTP_validateEmail::$nameservers
Initial value:
= array(
    '192.168.0.1'
)
Nameservers to use when make DNS query for MX entries.
Definition at line 57 of file smtp_validateEmail.class.php.
Referenced by queryMX().
SMTP_validateEmail::$port = 25
SMTP Port.
Definition at line 34 of file smtp_validateEmail.class.php.
resource SMTP_validateEmail::$sock
PHP Socket resource to remote MTA.
Definition at line 17 of file smtp_validateEmail.class.php.
SMTP_validateEmail::$user
Current User being validated.
Definition at line 22 of file smtp_validateEmail.class.php.
Referenced by _parseEmail(), setEmails(), and validate().
The documentation for this class was generated from the following file:
smtp_validateEmail.class.php