Constant Contact for WordPress: Image Class Reference
Image Class Reference
Public Member Functions
__construct ($params=array())
Constructor.
createXml ()
Create XML Representation of the object.
Static Public Member Functions
static createStruct ($parsedReturn)
Create associate array of object from XML.
Data Fields
$name
$id
$link
$updated
$imageUrl
$height
$width
$description
$folder
$md5hash
$fileSize
$fileType
Additional Inherited Members
Protected Member Functions inherited from CCObject
validate (Array $params)
Validate an object to check that all required fields have been supplied array $params - object property names to reference for validation before HTTP requests.
Detailed Description
Definition at line 660 of file Components.php.
Constructor & Destructor Documentation
Image::__construct ($params = array())
Constructor.
Parameters
array $params - associative array of properties/values
Definition at line 678 of file Components.php.
{
         $this->name = (isset($params['name'])) ? $params['name'] : '';
         $this->link = (isset($params['link'])) ? $params['link'] : '';
         $this->id = (isset($params['id'])) ? $params['id'] : '';
         $this->updated = (isset($params['updated'])) ? $params['updated'] : '';
         $this->imageUrl = (isset($params['imageUrl'])) ? $params['imageUrl'] : '';
         $this->height = (isset($params['height'])) ? $params['height'] : '';
         $this->width = (isset($params['width'])) ? $params['width'] : '';
         $this->description = (isset($params['description'])) ? $params['description'] : '';
         $this->folder = (isset($params['folder'])) ? $params['folder'] : '';
         $this->md5hash = (isset($params['md5hash'])) ? $params['md5hash'] : '';
         $this->fileSize = (isset($params['fileSize'])) ? $params['fileSize'] : '';
         $this->fileType = (isset($params['fileType'])) ? $params['fileType'] : '';
     }
Member Function Documentation
static Image::createStruct ($parsedReturn) static
Create associate array of object from XML.
Parameters
SimpleXMLElement $parsedReturn - parsed XML
Returns
Definition at line 699 of file Components.php.
Referenced by LibraryCollection\getImageDetails(), LibraryCollection\getImagesFromFolder(), and LibraryCollection\uploadImage().
{
         $image['link'] = (string) $parsedReturn->link->Attributes()->href;
         $image['id'] = (string) $parsedReturn->id;
         $image['name'] = (string) $parsedReturn->title;
         $image['updated'] = (string) $parsedReturn->updated;
         $content = $parsedReturn->content->children();
         $image['imageUrl'] = (string) $content->Image->ImageURL;
         $image['height'] = (string) $content->Image->Height;
         $image['width'] = (string) $content->Image->Width;
         $image['description'] = (string) $content->Image->Description;
         $image['folder'] = (string) $content->Image->Folder->Name;
         $image['md5hash'] = (string) $content->Image->MD5Hash;
         $image['fileSize'] = (string) $content->Image->FileSize;
         $image['fileType'] = (string) $content->Image->FileType;
         return $image;
     }
Image::createXml ()
Create XML Representation of the object.
Returns
SimpleXMLElement
Definition at line 720 of file Components.php.
References CCObject\validate().
{
         $this->validate(array('name', 'id'));
         $xml = simplexml_load_string("<?xml version='1.0' encoding='UTF-8' standalone='yes'?><atom:entry xmlns:atom='http://www.w3.org/2005/Atom'/>");
         $entry = $xml->asXML();
         return $entry;
     }
Field Documentation
Image::$description
Definition at line 668 of file Components.php.
Image::$fileSize
Definition at line 671 of file Components.php.
Image::$fileType
Definition at line 672 of file Components.php.
Image::$folder
Definition at line 669 of file Components.php.
Image::$height
Definition at line 666 of file Components.php.
Image::$id
Definition at line 662 of file Components.php.
Image::$imageUrl
Definition at line 665 of file Components.php.
Image::$link
Definition at line 663 of file Components.php.
Image::$md5hash
Definition at line 670 of file Components.php.
Image::$name
Definition at line 661 of file Components.php.
Image::$updated
Definition at line 664 of file Components.php.
Image::$width
Definition at line 667 of file Components.php.
The documentation for this class was generated from the following file:
Components.php