Constant Contact for WordPress: OAuthUtil Class Reference
OAuthUtil Class Reference
Static Public Member Functions
static urlencode_rfc3986 ($input)
static urldecode_rfc3986 ($string)
static split_header ($header, $only_allow_oauth_parameters=true)
static get_headers ()
static parse_parameters ($input)
static build_http_query ($params)
Detailed Description
Definition at line 694 of file Authentication.php.
Member Function Documentation
static OAuthUtil::build_http_query ($params) static
Definition at line 814 of file Authentication.php.
References urlencode_rfc3986().
Referenced by OAuthRequest\get_signable_parameters(), and OAuthRequest\to_postdata().
{
     if (!$params) return '';
     // Urlencode both keys and values
     $keys = OAuthUtil::urlencode_rfc3986(array_keys($params));
     $values = OAuthUtil::urlencode_rfc3986(array_values($params));
     $params = array_combine($keys, $values);
     // Parameters are sorted by name, using lexicographical byte value ordering.
     // Ref: Spec: 9.1.1 (1)
     uksort($params, 'strcmp');
     $pairs = array();
     foreach ($params as $parameter => $value) {
       if (is_array($value)) {
         // If two or more parameters share the same name, they are sorted by their value
         // Ref: Spec: 9.1.1 (1)
         natsort($value);
         foreach ($value as $duplicate_value) {
           $pairs[] = $parameter . '=' . $duplicate_value;
         }
       } else {
         $pairs[] = $parameter . '=' . $value;
       }
     }
     // For each parameter, the name is separated from the corresponding value by an '=' character (ASCII code 61)
     // Each name-value pair is separated by an '&' character (ASCII code 38)
     return implode('&', $pairs);
   }
static OAuthUtil::get_headers () static
Definition at line 742 of file Authentication.php.
Referenced by OAuthRequest\from_request().
{
     if (function_exists('apache_request_headers')) {
       // we need this to get the actual Authorization: header
       // because apache tends to tell us it doesn't exist
       $headers = apache_request_headers();
       // sanitize the output of apache_request_headers because
       // we always want the keys to be Cased-Like-This and arh()
       // returns the headers in the same case as they are in the
       // request
       $out = array();
       foreach( $headers AS $key => $value ) {
         $key = str_replace(
             " ",
             "-",
             ucwords(strtolower(str_replace("-", " ", $key)))
           );
         $out[$key] = $value;
       }
     } else {
       // otherwise we don't have apache and are just going to have to hope
       // that $_SERVER actually contains what we need
       $out = array();
       foreach ($_SERVER as $key => $value) {
         if (substr($key, 0, 5) == "HTTP_") {
           // this is chaos, basically it is just there to capitalize the first
           // letter of every word that is not an initial HTTP and strip HTTP
           // code from przemek
           $key = str_replace(
             " ",
             "-",
             ucwords(strtolower(str_replace("_", " ", substr($key, 5))))
           );
           $out[$key] = $value;
         }
       }
     }
     return $out;
   }
static OAuthUtil::parse_parameters ($input) static
Definition at line 785 of file Authentication.php.
References urldecode_rfc3986().
Referenced by OAuthRequest\__construct(), and OAuthRequest\from_request().
{
     if (!isset($input) || !$input) return array();
     $pairs = explode('&', $input);
     $parsed_parameters = array();
     foreach ($pairs as $pair) {
       $split = explode('=', $pair, 2);
       $parameter = OAuthUtil::urldecode_rfc3986($split[0]);
       $value = isset($split[1]) ? OAuthUtil::urldecode_rfc3986($split[1]) : '';
       if (isset($parsed_parameters[$parameter])) {
         // We have already recieved parameter(s) with this name, so add to the list
         // of parameters with this name
         if (is_scalar($parsed_parameters[$parameter])) {
           // This is the first duplicate, so transform scalar (string) into an array
           // so we can add the duplicates
           $parsed_parameters[$parameter] = array($parsed_parameters[$parameter]);
         }
         $parsed_parameters[$parameter][] = $value;
       } else {
         $parsed_parameters[$parameter] = $value;
       }
     }
     return $parsed_parameters;
   }
static OAuthUtil::split_header ($header, $only_allow_oauth_parameters = true) static
Definition at line 720 of file Authentication.php.
References urldecode_rfc3986().
Referenced by OAuthRequest\from_request().
{
     $pattern = '/(([-_a-z]*)=("([^"]*)"|([^,]*)),?)/';
     $offset = 0;
     $params = array();
     while (preg_match($pattern, $header, $matches, PREG_OFFSET_CAPTURE, $offset) > 0) {
       $match = $matches[0];
       $header_name = $matches[2][0];
       $header_content = (isset($matches[5])) ? $matches[5][0] : $matches[4][0];
       if (preg_match('/^oauth_/', $header_name) || !$only_allow_oauth_parameters) {
         $params[$header_name] = OAuthUtil::urldecode_rfc3986($header_content);
       }
       $offset = $match[1] + strlen($match[0]);
     }
     if (isset($params['realm'])) {
       unset($params['realm']);
     }
     return $params;
   }
static OAuthUtil::urldecode_rfc3986 ($string) static
Definition at line 713 of file Authentication.php.
Referenced by parse_parameters(), and split_header().
{
     return urldecode($string);
   }
static OAuthUtil::urlencode_rfc3986 ($input) static
Definition at line 695 of file Authentication.php.
Referenced by build_http_query(), OAuthSignatureMethod_HMAC_SHA1\build_signature(), OAuthSignatureMethod_PLAINTEXT\build_signature(), OAuthRequest\get_signature_base_string(), OAuthRequest\to_header(), and OAuthToken\to_string().
{
   if (is_array($input)) {
     return array_map(array('OAuthUtil', 'urlencode_rfc3986'), $input);
   } else if (is_scalar($input)) {
     return str_replace(
       '+',
       ' ',
       str_replace('%7E', '~', rawurlencode($input))
     );
   } else {
     return '';
   }
 }
The documentation for this class was generated from the following file:
Authentication.php