Constant Contact for WordPress: CTCT_Form_Designer Class Reference
CTCT_Form_Designer Class Reference
Public Member Functions
addScripts ($value='')
Public Member Functions inherited from CTCT_Admin_Page
__construct ()
print_styles ()
print_scripts ()
help_tabs ($tabs)
pointer_content ()
getPointers ($hook_suffix= '')
getPermission ()
add_menu ()
page ()
Data Fields
$key = 'constant-contact-forms'
$title = 'Form Designer'
$messages = array()
$form_id = -1
Data Fields inherited from CTCT_Admin_Page
$key
$title
$permission = 'manage_options'
$cc
$oauth
$errors
$can_edit = false
$can_add = false
$component = ''
$pointers = array()
Protected Member Functions
addIncludes ()
add ()
edit ()
view ()
single ()
processForms ()
Protected Member Functions inherited from CTCT_Admin_Page
addIncludes ()
addScripts ()
isAdd ()
isEdit ()
isSingle ()
isView ()
getKey ()
getTitle ()
getNavTitle ()
add ()
edit ()
view ()
single ()
processForms ()
addActions ()
content ()
print_errors ()
Detailed Description
Definition at line 10 of file form-designer.php.
Member Function Documentation
CTCT_Form_Designer::add () protected
Definition at line 57 of file form-designer.php.
 {}
CTCT_Form_Designer::addIncludes () protected
Definition at line 17 of file form-designer.php.
References CTCT_Admin_Page\getKey().
{
         global $pagenow, $plugin_page;
         if(is_admin() && !empty($plugin_page) && ($plugin_page !== $this->getKey() || empty($plugin_page) && @$_GET['page'] !== $this->getKey())) {
             return;
         }
         define('CC_FORM_GEN_URL', plugin_dir_url(__FILE__));
         define('CC_FORM_GEN_PATH', plugin_dir_path(__FILE__)); // @ Added 2.0 The full URL to this file
         require_once( CC_FORM_GEN_PATH . 'form-designer-functions.php' );
         require_once( CC_FORM_GEN_PATH . 'widget-form-designer.php');
         add_action('init', 'check_ccfg_compatibility');
         add_shortcode('constantcontactapi', 'constant_contact_signup_form_shortcode');
         add_action('widgets_init', 'constant_contact_form_load_widget');
         if(!($pagenow === 'admin.php' && $plugin_page === 'constant-contact-forms')) { return; }
         add_action('admin_print_scripts', 'constant_contact_admin_widget_scripts');
         add_filter( 'teeny_mce_before_init', 'ccfg_tiny_mce_before_init', 10, 2);
         add_filter( 'tiny_mce_before_init', 'ccfg_tiny_mce_before_init', 10, 2);
     }
CTCT_Form_Designer::addScripts ($value = '')
Definition at line 43 of file form-designer.php.
References CTCT_Admin_Page\getKey().
{
         global $plugin_page;
         if(!is_admin() || $plugin_page !== $this->getKey()) { return; }
         wp_enqueue_style('admin');
         wp_enqueue_style('wp-color-picker');
         wp_enqueue_style( 'cc-style', plugin_dir_url(__FILE__).'css/style.css');
         // Otto is the man.
         wp_enqueue_script( 'cc-code', plugin_dir_url(__FILE__).'js/cc-code-dev.js', array('wp-color-picker', 'jquery', 'jquery-ui-core', 'jquery-ui-tabs', 'jquery-ui-sortable'));
         $params = array('path' => plugin_dir_url(__FILE__), 'rand' => mt_rand(0, 100000000), 'text' => cc_form_text());
         wp_localize_script('cc-code', 'ScriptParams', $params);
     }
CTCT_Form_Designer::edit () protected
Definition at line 58 of file form-designer.php.
 {}
CTCT_Form_Designer::processForms () protected
Definition at line 98 of file form-designer.php.
References $messages.
{
             if(!isset($_REQUEST['cc-form-id'])) { return; }
             global $cc_form_selected_id;
             // Allowed actions: add, update, delete
             $action = isset( $_REQUEST['action'] ) ? $_REQUEST['action'] : 'edit';
             $cc_form_selected_id = cc_form_get_selected_id();
             if($action === 'edit') { return; }
             $messages = array();
             switch ( $action ) {
                 case 'delete_all':
                     delete_option('cc_form_design');
                     break;
                 case 'delete':
                     $cc_form_selected_id = isset($_REQUEST['form']) ? (int)$_REQUEST['form'] : $cc_form_selected_id;
                     if ( $deleted_form = wp_get_cc_form( $cc_form_selected_id ) ) {
                         $delete_cc_form = wp_delete_cc_form( $cc_form_selected_id );
                         if ( is_wp_error($delete_cc_form) ) {
                             $messages[] = '<div id="message" class="error"><p>' . $delete_cc_form->get_error_message() . '</p></div>';
                         } else {
                             $messages[] = '<div id="message" class="updated"><p>' . __('The form '.$deleted_form['form-name'].' has been successfully deleted.','constant-contact-api') . '</p></div>';
                             // Select the next available menu
                             $cc_form_selected_id = -1;
                             $_cc_forms = wp_get_cc_forms( array('orderby' => 'name') );
                             foreach( $_cc_forms as $index => $_cc_form ) {
                                 if ( $index == count( $_cc_forms ) - 1 ) {
                                     $cc_form_selected_id = $_cc_form['cc-form-id'];
                                     break;
                                 }
                             }
                         }
                         $_REQUEST['deleted'] = 1;
                     } else {
                         $_REQUEST['deleted'] = 0;
                         // Reset the selected menu
                         $cc_form_selected_id = -1;
                         unset( $_REQUEST['form'] );
                         $messages[] = '<div id="message" class="error"><p>'.__('The form could not be deleted. The form may have already been deleted.', 'constant-contact-api').'</p></div>';
                     }
                     break;
                 case 'update':
         #           check_admin_referer( 'update-nav_menu', 'update-nav-menu-nonce' );
                     // Add Form
                     if ( -1 == $cc_form_selected_id ) {
                         $new_form_title = trim( esc_html( $_REQUEST['form-name'] ) );
                         if($new_form_title == 'Enter form name here') { $new_form_title = ''; }
                             $cc_form_selected_id = wp_create_cc_form();
                             if ( is_wp_error( $cc_form_selected_id ) ) {
                                 $messages[] = '<div id="message" class="error"><p>' . $cc_form_selected_id->get_error_message() . '</p></div>';
                             } else {
                                 $messages[] = '<div id="message" class="updated"><p>' . sprintf( __('The <strong>%s</strong> form has been successfully created.','constant-contact-api'), $new_form_title ) . '</p></div>';
                             }
                     // update existing form
                     } else {
                         if(wp_get_cc_form($cc_form_selected_id)) {
                             $request = wp_update_cc_form_object($cc_form_selected_id, $_REQUEST);
                             if(!is_wp_error($request)) {
                                 $messages[] = '<div id="message" class="updated after-h2 fade"><p>' . sprintf( __('The <strong>%s</strong> form has been updated.','constant-contact-api'), $request['form-name'] ) . '</p></div>';
                             } else {
                                 $messages[] = '<div id="message" class="error"><p>' . $cc_form_selected_id->get_error_message() . '</p></div>';
                             }
                         } else {
                         }
                     }
                     break;
             }
             $this->messages = $messages;
     }
CTCT_Form_Designer::single () protected
Definition at line 96 of file form-designer.php.
 {}
CTCT_Form_Designer::view () protected
Definition at line 60 of file form-designer.php.
References $messages.
{
             $compat = check_ccfg_compatibility();
             if(empty($compat)) { return false; }
             global $cc_form_selected_id;
             $cc_forms = array();
             // Container for any messages displayed to the user
             $messages = array();
             $_form = wp_get_cc_form( $cc_form_selected_id );
             // Container that stores the name of the active menu
             $cc_form_selected_title = constant_contact_get_form_title($_form);
             // Work with the actions and echo a message if there is one.
             $messages = $this->messages;
             // Get all forms
             $cc_forms = wp_get_cc_forms();
             // The menu id of the current menu being edited
             $cc_form_selected_id = cc_form_get_selected_id($cc_forms);
         ?>
         <?php
         wp_cc_form_setup($_form);
         include(CC_FORM_GEN_PATH.'views/form-designer.php');
     }
Field Documentation
CTCT_Form_Designer::$form_id = -1
Definition at line 15 of file form-designer.php.
CTCT_Form_Designer::$key = 'constant-contact-forms'
Definition at line 12 of file form-designer.php.
CTCT_Form_Designer::$messages = array()
Definition at line 14 of file form-designer.php.
Referenced by processForms(), and view().
CTCT_Form_Designer::$title = 'Form Designer'
Definition at line 13 of file form-designer.php.
The documentation for this class was generated from the following file:
form-designer.php