Constant Contact for WordPress: Utility Class Reference
Utility Class Reference
Static Public Member Functions
static findUrl ($item)
Find the URL of the provided object.
static findNextLink ($item)
Find the next link from collection XML.
Detailed Description
Definition at line 1403 of file Components.php.
Member Function Documentation
static Utility::findNextLink ($item) static
Find the next link from collection XML.
Parameters
SimpleXMLElement $item
Returns
string - valid nextlink to be used, else false if none could be found
Definition at line 1428 of file Components.php.
Referenced by SettingsCollection\getAddresses(), CampaignsCollection\getCampaignEvents(), CampaignsCollection\getCampaigns(), CampaignsCollection\getCampaignsByStatus(), ContactsCollection\getContactEvents(), ContactsCollection\getContacts(), EventsCollection\getEvents(), LibraryCollection\getFolders(), ListsCollection\getListMembers(), ListsCollection\getLists(), and EventsCollection\getRegistrants().
{
         $nextLink = $item->xpath("//*[@rel='next']");
         return ($nextLink) ? (string) $nextLink[0]->Attributes()->href : false;
     }
static Utility::findUrl ($item) static
Find the URL of the provided object.
Parameters
mixed $item
Returns
string
Definition at line 1410 of file Components.php.
References CTCTException\generateError().
{
         $return = null;
          try{
             if (is_string($item)){$return = $item;}
             elseif (is_object($item)){$return = 'https://api.constantcontact.com'.$item->link;}
             if($return == null){ throw new CTCTException('Constant Contact Error: Unable to determine which url to access');}
          } catch (CTCTException $e){
             $e->generateError();
          }
           return $return;
     }
The documentation for this class was generated from the following file:
Components.php