Constant Contact for WordPress: DataValidation Class Reference
DataValidation Class Reference
Public Member Functions
__construct ($apikey, $email=false)
validate ($email)
getRequestArgs ($body)
get ($location)
post ($email)
getStatusIntent ($status_code)
getStatusMessage ($status_code)
Get the message associated with the status code.
Data Fields
$host = 'dvapi.com'
$post_endpoint = 'http://dvapi.com/email/validate'
$get_endpoint = 'http://dvapi.com'
$apikey
$message
Detailed Description
Definition at line 6 of file class.datavalidation.php.
Constructor & Destructor Documentation
DataValidation::__construct ($apikey, $email = false)
Definition at line 14 of file class.datavalidation.php.
References $apikey, and validate().
{
         $this->apikey = $apikey;
         if($email) {
             return $this->validate($email);
         }
     }
Member Function Documentation
DataValidation::get ($location)
Definition at line 57 of file class.datavalidation.php.
References getRequestArgs().
{
         $url = $this->get_endpoint.$location.'.json';
         $request = wp_remote_get($url, $this->getRequestArgs(''));
         return wp_remote_retrieve_body($request);
     }
DataValidation::getRequestArgs ($body)
Definition at line 39 of file class.datavalidation.php.
Referenced by get(), and post().
{
         $args = array(
             'headers' => array(
                 'Host' => $this->host,
                 'apikey' => $this->apikey,
                 'Content-Type' => 'application/json',
                 'Content-Length' => strlen($body),
             ),
             'timeout' => 5,
             'redirection' => 0,
             'httpversion' => '1.1',
         );
         if(!empty($body)) {
             $args['body'] = $body;
         }
         return $args;
     }
DataValidation::getStatusIntent ($status_code)
Definition at line 80 of file class.datavalidation.php.
Referenced by validate().
{
         switch($status_code) {
             case 1:
             case 2:
             case 3:
             case 4:
             case 5:
             case 6:
                 return false;
                 break;
             case 7:
             case 9:
             case 10:
                 return null;
                 break;
             case 8:
                 return true;
                 break;
         }
     }
DataValidation::getStatusMessage ($status_code)
Get the message associated with the status code.
Modify the output using datavalidation_status_message filter
datavalidation_status_message
Parameters
integer $status_code Status code returned from DataValidation.com
Returns
string Status message
Definition at line 110 of file class.datavalidation.php.
References $message.
Referenced by validate().
{
         switch($status_code) {
             case 1: $message = __('Invalid email address', 'datavalidation'); break;
             case 2: $message = __('Invalid email address host name', 'datavalidation'); break;
             case 3: $message = __('Invalid email server for this domain', 'datavalidation'); break;
             case 4: $message = __('Invalid email address local part', 'datavalidation'); break;
             case 5: $message = __('Email address length exceeded', 'datavalidation'); break;
             case 6: $message = __('Email address not found', 'datavalidation'); break;
             case 7: $message = __('Email address could not be verified', 'datavalidation'); break;
             case 8: $message = __('Email address found', 'datavalidation'); break;
             case 9: $message = __('Domain accepts all recipients &ndash; Accepts All', 'datavalidation'); break;
             case 10: $message = __('Domain has an email server but there is no connection to it &ndash; Ambiguous', 'datavalidation'); break;
         }
         return apply_filters('datavalidation_status_message', $message, $status_code);
     }
DataValidation::post ($email)
Definition at line 63 of file class.datavalidation.php.
References getRequestArgs().
Referenced by validate().
{
         $body = json_encode(array(
                 'settings' => array(),
                 #'apikey' => $this->apikey,
                 'emails' => array(
                     array('email' => $email)
                 )
             ));
         $request = wp_remote_post($this->post_endpoint, $this->getRequestArgs($body));
         $headers = wp_remote_retrieve_headers($request);
         return isset($headers['location']) ? $headers['location'] : false;
     }
DataValidation::validate ($email)
Definition at line 22 of file class.datavalidation.php.
References getStatusIntent(), getStatusMessage(), and post().
Referenced by __construct().
{
         $location = $this->post($email);
         // The post failed.
         if(!$location) { return false; }
         $response = $this->get($location);
         $response = @json_decode($response);
         if(empty($response)) { return false; }
         $this->message = $this->getStatusMessage($response->code);
         return $this->getStatusIntent($response->code);
     }
Field Documentation
DataValidation::$apikey
Definition at line 11 of file class.datavalidation.php.
Referenced by __construct().
DataValidation::$get_endpoint = 'http://dvapi.com'
Definition at line 10 of file class.datavalidation.php.
DataValidation::$host = 'dvapi.com'
Definition at line 8 of file class.datavalidation.php.
DataValidation::$message
Definition at line 12 of file class.datavalidation.php.
Referenced by getStatusMessage().
DataValidation::$post_endpoint = 'http://dvapi.com/email/validate'
Definition at line 9 of file class.datavalidation.php.
The documentation for this class was generated from the following file:
class.datavalidation.php