Constant Contact for WordPress: Registrant Class Reference
Registrant Class Reference
Public Member Functions
__construct ($params=array())
Constructor.
Static Public Member Functions
static createStruct ($parsedResponse)
Create an associative array of object properties from XML.
Data Fields
$title
$link
$id
$updated
$lastName
$firstName
$email
$personalInformation
$businessInformation
$customInformation1
$customInformation2
$registrationStatus
$registrationDate
$guestCount
$paymentStatus
$orderAmount
$currencyType
$paymentType
$costs
Additional Inherited Members
Protected Member Functions inherited from CCObject
validate (Array $params)
Validate an object to check that all required fields have been supplied array $params - object property names to reference for validation before HTTP requests.
Detailed Description
Definition at line 801 of file Components.php.
Constructor & Destructor Documentation
Registrant::__construct ($params = array())
Constructor.
Parameters
array $params - associative array of properties/values
Definition at line 826 of file Components.php.
{
         $this->title = (isset($params['title'])) ? $params['title'] : '';
         $this->link = (isset($params['link'])) ? $params['link'] : '';
         $this->id = (isset($params['id'])) ? $params['id'] : '';
         $this->updated = (isset($params['updated'])) ? $params['updated'] : '';
         $this->lastName = (isset($params['lastName'])) ? $params['lastName'] : '';
         $this->firstName = (isset($params['firstName'])) ? $params['firstName'] : '';
         $this->email = (isset($params['email'])) ? $params['email'] : '';
         $this->personalInformation = (isset($params['personalInformation'])) ? $params['personalInformation'] : new PersonalInformation();
         $this->businessInformation = (isset($params['businessInformation'])) ? $params['businessInformation'] : new BusinessInformation();
         $this->customInformation1 = (isset($params['customInformation1'])) ? $params['customInformation1'] : array();
         $this->customInformation2 = (isset($params['customInformation2'])) ? $params['customInformation2'] : array();
         $this->registrationStatus = (isset($params['registrationStatus'])) ? $params['registrationStatus'] : '';
         $this->registrationDate = (isset($params['registrationDate'])) ? $params['registrationDate'] : '';
         $this->guestCount = (isset($params['guestCount'])) ? $params['guestCount'] : '';
         $this->paymentStatus = (isset($params['paymentStatus'])) ? $params['paymentStatus'] : '';
         $this->ticketId = (isset($params['ticketId'])) ? $params['ticketId'] : '';
         $this->orderAmount = (isset($params['orderAmount'])) ? $params['orderAmount'] : '';
         $this->currencyType = (isset($params['currencyType'])) ? $params['currencyType'] : '';
         $this->paymentType = (isset($params['paymentType'])) ? $params['paymentType'] : '';
         $this->costs = (isset($params['costs'])) ? $params['costs'] : array();
     }
Member Function Documentation
static Registrant::createStruct ($parsedResponse) static
Create an associative array of object properties from XML.
Parameters
SimpleXMLElement $parsedResponse - XML of registrant
Returns
Definition at line 855 of file Components.php.
References CustomField\createFromXml(), Cost\createStruct(), PersonalInformation\createStruct(), and BusinessInformation\createStruct().
Referenced by EventsCollection\getRegistrantDetails(), and EventsCollection\getRegistrants().
{
         $reg['title'] = (string) $parsedResponse->title;
         $reg['updated'] = (string) $parsedResponse->updated;
         $reg['link'] = (string) $parsedResponse->link->Attributes()->href;
         $reg['id'] = (string) $parsedResponse->id;
         $content = $parsedResponse->content->children();
         $reg['lastName'] = (string) $content->Registrant->LastName;
         $reg['firstName'] = (string) $content->Registrant->FirstName;
         $reg['email'] = (string) $content->Registrant->EmailAddress;
         $reg['registrationStatus'] = (string) $content->Registrant->RegistrationStatus;
         $reg['registrationDate'] = (string) $content->Registrant->RegistrationDate;
         $reg['guestCount'] = (string) $content->Registrant->GuestCount;
         $reg['paymentStatus'] = (string) $content->Registrant->PaymentStatus;
         $reg['ticketId'] = (string) $content->Registrant->TicketId;
         $reg['personalInformation'] = new PersonalInformation(PersonalInformation::createStruct($content->Registrant->PersonalInformation));
         $reg['businessInformation'] = new BusinessInformation(BusinessInformation::createStruct($content->Registrant->BusinessInformation));
         $reg['customInformation1'] = array();
         $reg['customInformation2'] = array();
         $reg['costs'] = array();
         if(isset($content->Registrant->CustomInformation1->CustomField)){
             foreach($content->Registrant->CustomInformation1->CustomField as $customInfo){
                 $reg['customInformation1'][] = CustomField::createFromXml($customInfo);
             }
         }
         if(isset($content->Registrant->CustomInformation2->CustomField)){
             foreach($content->Registrant->CustomInformation2->CustomField as $customInfo){
                 $reg['customInformation2'][] = CustomField::createFromXml($customInfo);
             }
         }
         if(isset($content->Registrant->Costs->Cost)){
             foreach($content->Registrant->Costs->Cost as $cost){
                 $reg['costs'] = new Cost(Cost::createStruct($cost));
             }
         }
         return $reg;
     }
Field Documentation
Registrant::$businessInformation
Definition at line 810 of file Components.php.
Registrant::$costs
Definition at line 820 of file Components.php.
Registrant::$currencyType
Definition at line 818 of file Components.php.
Registrant::$customInformation1
Definition at line 811 of file Components.php.
Registrant::$customInformation2
Definition at line 812 of file Components.php.
Registrant::$email
Definition at line 808 of file Components.php.
Registrant::$firstName
Definition at line 807 of file Components.php.
Registrant::$guestCount
Definition at line 815 of file Components.php.
Registrant::$id
Definition at line 804 of file Components.php.
Registrant::$lastName
Definition at line 806 of file Components.php.
Registrant::$link
Definition at line 803 of file Components.php.
Registrant::$orderAmount
Definition at line 817 of file Components.php.
Registrant::$paymentStatus
Definition at line 816 of file Components.php.
Registrant::$paymentType
Definition at line 819 of file Components.php.
Registrant::$personalInformation
Definition at line 809 of file Components.php.
Registrant::$registrationDate
Definition at line 814 of file Components.php.
Registrant::$registrationStatus
Definition at line 813 of file Components.php.
Registrant::$title
Definition at line 802 of file Components.php.
Registrant::$updated
Definition at line 805 of file Components.php.
The documentation for this class was generated from the following file:
Components.php