Constant Contact for WordPress: Folder Class Reference
Folder Class Reference
Public Member Functions
__construct ($params=array())
Constructor.
createXml ()
Create XML Representation of the object.
Static Public Member Functions
static createStruct ($parsedReturn)
Create associate array of object from XML.
Data Fields
$name
$id
$link
Additional Inherited Members
Protected Member Functions inherited from CCObject
validate (Array $params)
Validate an object to check that all required fields have been supplied array $params - object property names to reference for validation before HTTP requests.
Detailed Description
Definition at line 617 of file Components.php.
Constructor & Destructor Documentation
Folder::__construct ($params = array())
Constructor.
Parameters
array $params - associative array of properties/values
Definition at line 626 of file Components.php.
{
         $this->name = (isset($params['name'])) ? $params['name'] : '';
         $this->link = (isset($params['link'])) ? $params['link'] : '';
         $this->id = (isset($params['id'])) ? $params['id'] : '';
     }
Member Function Documentation
static Folder::createStruct ($parsedReturn) static
Create associate array of object from XML.
Parameters
SimpleXMLElement $parsedReturn - parsed XML
Returns
Definition at line 638 of file Components.php.
Referenced by LibraryCollection\addFolder(), and LibraryCollection\getFolders().
{
         $folder['link'] = (string) $parsedReturn->link->Attributes()->href;
         $folder['id'] = (string) $parsedReturn->id;
         $folder['name'] = (string) $parsedReturn->title;
         return $folder;
     }
Folder::createXml ()
Create XML Representation of the object.
Returns
SimpleXMLElement
Definition at line 649 of file Components.php.
References CCObject\validate().
Referenced by LibraryCollection\addFolder().
{
         $this->validate(array('name'));
         $xml = simplexml_load_string("<?xml version='1.0' encoding='UTF-8' standalone='yes'?><atom:entry xmlns:atom='http://www.w3.org/2005/Atom'/>");
         $content = $xml->addChild("content");
         $folder = $content->addChild("Folder", "", "");
         $folder->addChild("Name", $this->name, "");
         $entry = $xml->asXML();
         return $entry;
     }
Field Documentation
Folder::$id
Definition at line 619 of file Components.php.
Folder::$link
Definition at line 620 of file Components.php.
Folder::$name
Definition at line 618 of file Components.php.
The documentation for this class was generated from the following file:
Components.php