Constant Contact for WordPress: Ctct\Components\Contacts\Contact Class Reference
Ctct\Components\Contacts\Contact Class Reference
Public Member Functions
addList ($contactList)
Add a ContactList.
addEmail ($emailAddress)
Add an EmailAddress.
addCustomField (CustomField $customField)
Add a custom field to the contact object.
addAddress (Address $address)
Add an address.
toJson ()
Static Public Member Functions
static create (array $props)
Factory method to create a Contact object from an array.
Data Fields
$id
$status
$first_name
$middle_name
$last_name
$confirmed
$source
$email_addresses = array()
$prefix_name
$job_title
$addresses = array()
$notes = array()
$company_name
$home_phone
$work_phone
$cell_phone
$fax
$custom_fields = array()
$lists = array()
$source_details
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Components\Component
static getValue (array $array, $item, $default=null)
Get the requested value from an array, or return the default.
Detailed Description
Definition at line 14 of file Contact.php.
Member Function Documentation
Ctct\Components\Contacts\Contact::addAddress (Address $address)
Add an address.
Parameters
Address $address - Address to add
Definition at line 226 of file Contact.php.
     {
         $this->addresses[] = $address;
     }
Ctct\Components\Contacts\Contact::addCustomField (CustomField $customField)
Add a custom field to the contact object.
Parameters
CustomField $customField - custom field to add to the contact
Definition at line 217 of file Contact.php.
     {
         $this->custom_fields[] = $customField;
     }
Ctct\Components\Contacts\Contact::addEmail ($emailAddress)
Add an EmailAddress.
Parameters
mixed $emailAddress - EmailAddress object or email address
Definition at line 204 of file Contact.php.
     {
         if (! $emailAddress instanceof EmailAddress) {
             $emailAddress = new EmailAddress($emailAddress);
         }
         $this->email_addresses[] = $emailAddress;
     }
Ctct\Components\Contacts\Contact::addList ($contactList)
Add a ContactList.
Parameters
mixed $contactList - ContactList object or contact list id
Definition at line 191 of file Contact.php.
     {
         if (!$contactList instanceof ContactList) {
             $contactList = new ContactList($contactList);
         }
         $this->lists[] = $contactList;
     }
static Ctct\Components\Contacts\Contact::create (array $props) static
Factory method to create a Contact object from an array.
Parameters
array $props - Associative array of initial properties to set
Returns
Contact
Definition at line 142 of file Contact.php.
References Ctct\Components\Contacts\CustomField\create(), Ctct\Components\Contacts\Note\create(), Ctct\Components\Contacts\ContactList\create(), Ctct\Components\Contacts\EmailAddress\create(), and Ctct\Components\Contacts\Address\create().
Referenced by Ctct\Services\ContactService\addContact(), Ctct\Services\ContactService\getContact(), Ctct\Services\ContactService\getContacts(), Ctct\Services\ListService\getContactsFromList(), and Ctct\Services\ContactService\updateContact().
     {
         $contact = new Contact();
         $contact->id = parent::getValue($props, "id");
         $contact->status = parent::getValue($props, "status");
         $contact->first_name = parent::getValue($props, "first_name");
         $contact->middle_name = parent::getValue($props, "middle_name");
         $contact->last_name = parent::getValue($props, "last_name");
         $contact->confirmed = parent::getValue($props, "confirmed");
         $contact->source = parent::getValue($props, "source");
         foreach ($props['email_addresses'] as $email_address) {
             $contact->email_addresses[] = EmailAddress::create($email_address);
         }
         $contact->prefix_name = parent::getValue($props, "prefix_name");
         $contact->job_title = parent::getValue($props, "job_title");
         foreach ($props['addresses'] as $address) {
             $contact->addresses[] = Address::create($address);
         }
         foreach ($props['notes'] as $note) {
             $contact->notes[] = Note::create($note);
         }
         $contact->company_name = parent::getValue($props, "company_name");
         $contact->home_phone = parent::getValue($props, "home_phone");
         $contact->work_phone = parent::getValue($props, "work_phone");
         $contact->cell_phone = parent::getValue($props, "cell_phone");
         $contact->fax = parent::getValue($props, "fax");
         foreach ($props['custom_fields'] as $custom_field) {
             $contact->custom_fields[] = CustomField::create($custom_field);
         }
         foreach ($props['lists'] as $contact_list) {
             $contact->lists[] = ContactList::create($contact_list);
         }
         $contact->source_details = parent::getValue($props, "source_details");
         return $contact;
     }
Ctct\Components\Contacts\Contact::toJson ()
Definition at line 231 of file Contact.php.
Referenced by Ctct\Services\ContactService\addContact(), and Ctct\Services\ContactService\updateContact().
     {
         unset($this->last_update_date);
         return json_encode($this);
     }
Field Documentation
Ctct\Components\Contacts\Contact::$addresses = array()
Definition at line 81 of file Contact.php.
Ctct\Components\Contacts\Contact::$cell_phone
Definition at line 111 of file Contact.php.
Ctct\Components\Contacts\Contact::$company_name
Definition at line 93 of file Contact.php.
Ctct\Components\Contacts\Contact::$confirmed
Definition at line 51 of file Contact.php.
Ctct\Components\Contacts\Contact::$custom_fields = array()
Definition at line 123 of file Contact.php.
Ctct\Components\Contacts\Contact::$email_addresses = array()
Definition at line 63 of file Contact.php.
Ctct\Components\Contacts\Contact::$fax
Definition at line 117 of file Contact.php.
Ctct\Components\Contacts\Contact::$first_name
Definition at line 33 of file Contact.php.
Ctct\Components\Contacts\Contact::$home_phone
Definition at line 99 of file Contact.php.
Ctct\Components\Contacts\Contact::$id
Definition at line 21 of file Contact.php.
Ctct\Components\Contacts\Contact::$job_title
Definition at line 75 of file Contact.php.
Ctct\Components\Contacts\Contact::$last_name
Definition at line 45 of file Contact.php.
Ctct\Components\Contacts\Contact::$lists = array()
Definition at line 129 of file Contact.php.
Ctct\Components\Contacts\Contact::$middle_name
Definition at line 39 of file Contact.php.
Ctct\Components\Contacts\Contact::$notes = array()
Definition at line 87 of file Contact.php.
Ctct\Components\Contacts\Contact::$prefix_name
Definition at line 69 of file Contact.php.
Ctct\Components\Contacts\Contact::$source
Definition at line 57 of file Contact.php.
Ctct\Components\Contacts\Contact::$source_details
Definition at line 135 of file Contact.php.
Ctct\Components\Contacts\Contact::$status
Definition at line 27 of file Contact.php.
Ctct\Components\Contacts\Contact::$work_phone
Definition at line 105 of file Contact.php.
The documentation for this class was generated from the following file:
Contact.php