Constant Contact for WordPress: Ctct\Components\Activities\AddContacts Class Reference
Ctct\Components\Activities\AddContacts Class Reference
Public Member Functions
__construct (Array $contacts, Array $lists, Array $columnNames=array())
toJson ()
Turn the object into json, removing any extra fields.
Data Fields
$import_data = array()
$lists = array()
$column_names = array()
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Components\Component
static getValue (array $array, $item, $default=null)
Get the requested value from an array, or return the default.
Detailed Description
Definition at line 17 of file AddContacts.php.
Constructor & Destructor Documentation
Ctct\Components\Activities\AddContacts::__construct (Array $contacts, Array $lists, Array $columnNames = array())
Definition at line 23 of file AddContacts.php.
References Ctct\Components\Activities\AddContacts\$lists, and Ctct\Util\Config\get().
     {
         if (!empty($contacts)) {
             if ($contacts[0] instanceof AddContactsImportData) {
                 $this->import_data = $contacts;
             } else {
                 $msg = sprintf(Config::get('errors.id_or_object'), "AddContactsImportData");
                 throw new IllegalArgumentException($msg);
             }
         }
         $this->lists = $lists;
         if (empty($columnNames)) {
             $usedColumns[] = Config::get('activities_columns.email');
             $contact = $contacts[0];
             if (isset($contact->first_name)) {
                 $usedColumns[] = Config::get('activities_columns.first_name');
             }
             if (isset($contact->middle_name)) {
                 $usedColumns[] = Config::get('activities_columns.middle_name');
             }
             if (isset($contact->last_name)) {
                 $usedColumns[] = Config::get('activities_columns.last_name');
             }
             if (isset($contact->job_title)) {
                 $usedColumns[] = Config::get('activities_columns.job_title');
             }
             if (isset($contact->company_name)) {
                 $usedColumns[] = Config::get('activities_columns.company_name');
             }
             if (isset($contact->work_phone)) {
                 $usedColumns[] = Config::get('activities_columns.work_phone');
             }
             if (isset($contact->home_phone)) {
                 $usedColumns[] = Config::get('activities_columns.home_phone');
             }
             // Addresses
             if (!empty($contact->addresses)) {
                 $address = $contact->addresses[0];
                 if (isset($address->line1)) {
                     $usedColumns[] = Config::get('activities_columns.address1');
                 }
                 if (isset($address->line2)) {
                     $usedColumns[] = Config::get('activities_columns.address2');
                 }
                 if (isset($address->line3)) {
                     $usedColumns[] = Config::get('activities_columns.address3');
                 }
                 if (isset($address->city)) {
                     $usedColumns[] = Config::get('activities_columns.city');
                 }
                 if (isset($address->state_code)) {
                     $usedColumns[] = Config::get('activities_columns.state');
                 }
                 if (isset($address->state_province)) {
                     $usedColumns[] = Config::get('activities_columns.state_province');
                 }
                 if (isset($address->country)) {
                     $usedColumns[] = Config::get('activities_columns.country');
                 }
                 if (isset($address->postal_code)) {
                     $usedColumns[] = Config::get('activities_columns.postal_code');
                 }
                 if (isset($address->sub_postal_code)) {
                     $usedColumns[] = Config::get('activities_columns.sub_postal_code');
                 }
             }
             // Custom Fields
             if (!empty($contact->custom_fields)) {
                 foreach ($contact->custom_fields as $customField) {
                     if (strpos($customField->name, 'custom_field_') !== false) {
                         $customFieldNumber = substr($customField->name, 13);
                         $usedColumns[] = Config::get('activities_columns.custom_field_' . $customFieldNumber);
                     }
                 }
             }
             $this->column_names = $usedColumns;
         }
     }
Member Function Documentation
Ctct\Components\Activities\AddContacts::toJson ()
Turn the object into json, removing any extra fields.
Returns
string
Definition at line 111 of file AddContacts.php.
Referenced by Ctct\Services\ActivityService\createAddContactsActivity().
     {
         foreach ($this->import_data as $contact) {
             foreach ($contact as $key => $value) {
                 if ($value == null) {
                     unset($contact->$key);
                 }
             }
         }
         return json_encode($this);
     }
Field Documentation
Ctct\Components\Activities\AddContacts::$column_names = array()
Definition at line 21 of file AddContacts.php.
Ctct\Components\Activities\AddContacts::$import_data = array()
Definition at line 19 of file AddContacts.php.
Ctct\Components\Activities\AddContacts::$lists = array()
Definition at line 20 of file AddContacts.php.
Referenced by Ctct\Components\Activities\AddContacts\__construct().
The documentation for this class was generated from the following file:
AddContacts.php