Constant Contact for WordPress: SettingsCollection Class Reference
SettingsCollection Class Reference
Public Member Functions
__construct ($CTCTRequest)
SettingsCollection constructor.
getAddresses ($page=null)
Get a list of verified email addresses for an account.
Public Member Functions inherited from Collection
__construct (CTCTRequest $CTCTRequest, $collectionUri)
Collection constructor.
Data Fields
$CTCTRequest
$uri
Data Fields inherited from Collection
$CTCTRequest
$uri
Detailed Description
Definition at line 570 of file Collections.php.
Constructor & Destructor Documentation
SettingsCollection::__construct ($CTCTRequest)
SettingsCollection constructor.
Parameters
$CTCTRequest
Definition at line 578 of file Collections.php.
References $CTCTRequest.
{
         parent::__construct($CTCTRequest, '/ws/customers/'.$CTCTRequest->username.'/settings');
     }
Member Function Documentation
SettingsCollection::getAddresses ($page = null)
Get a list of verified email addresses for an account.
Parameters
string $page - page of verified emails, default is first page
Returns
array - page of verified addresses and a link to the next page if one exists
Definition at line 587 of file Collections.php.
References VerifiedAddress\createStruct(), Utility\findNextLink(), and CTCTRequest\makeRequest().
{
         $url = ($page) ? $this->CTCTRequest->baseUri.$page : $this->uri.'/emailaddresses';
         $addressCollection = array('addresses' => array(), 'nextLink' => '');
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $parsedResponse = simplexml_load_string($response['xml']);
         foreach($parsedResponse->entry as $entry){
             $addressCollection['addresses'][] = new VerifiedAddress(VerifiedAddress::createStruct($entry));
         }
         $addressCollection['nextLink'] = Utility::findNextLink($parsedResponse);
         return $addressCollection;
     }
Field Documentation
SettingsCollection::$CTCTRequest
Definition at line 571 of file Collections.php.
Referenced by __construct().
SettingsCollection::$uri
Definition at line 572 of file Collections.php.
The documentation for this class was generated from the following file:
Collections.php