Constant Contact for WordPress: Net_DNS_RR Class Reference
Net_DNS_RR Class Reference
Public Member Functions
Net_DNS_RR ($rrdata)
& factory ($rrdata, $update_type= '')
& new_from_data ($name, $rrtype, $rrclass, $ttl, $rdlength, $data, $offset)
& new_from_string ($rrstring, $update_type= '')
& new_from_array ($rrarray)
display ()
string ()
rdatastr ()
rdata (&$packetORrdata, $offset= '')
rr_rdata (&$packet, $offset)
data (&$packet, $offset)
Data Fields
$name
$type
$class
$ttl
$rdlength
$rdata
Detailed Description
Definition at line 46 of file RR.php.
Member Function Documentation
Net_DNS_RR::data (& $packet, $offset)
Definition at line 284 of file RR.php.
References Net_DNS\classesbyname(), and Net_DNS\typesbyname().
     {
         $data = $packet->dn_comp($this->name, $offset);
         $data .= pack('n', Net_DNS::typesbyname(strtoupper($this->type)));
         $data .= pack('n', Net_DNS::classesbyname(strtoupper($this->class)));
         $data .= pack('N', $this->ttl);
         $offset += strlen($data) + 2;  // The 2 extra bytes are for rdlength
         $rdata = $this->rdata($packet, $offset);
         $data .= pack('n', strlen($rdata));
         $data .= $rdata;
         return $data;
     }
Net_DNS_RR::display ()
Definition at line 236 of file RR.php.
     {
         echo $this->string() . "\n";
     }
& Net_DNS_RR::factory ($rrdata, $update_type = '')
Definition at line 78 of file RR.php.
References $name, $rdlength, $ttl, new_from_array(), new_from_data(), and new_from_string().
Referenced by Net_DNS_Packet\parse_rr().
     {
         if (is_string($rrdata)) {
             $rr = &Net_DNS_RR::new_from_string($rrdata, $update_type);
         } elseif (count($rrdata) == 7) {
             list($name, $rrtype, $rrclass, $ttl, $rdlength, $data, $offset) = $rrdata;
             $rr = &Net_DNS_RR::new_from_data($name, $rrtype, $rrclass, $ttl, $rdlength, $data, $offset);
         } else {
             $rr = &Net_DNS_RR::new_from_array($rrdata);
         }
         return $rr;
     }
Net_DNS_RR::Net_DNS_RR ($rrdata)
Definition at line 63 of file RR.php.
Referenced by new_from_array(), new_from_data(), and new_from_string().
     {
         if ($rrdata != 'getRR') { //BC check/warning remove later
             trigger_error("Please use Net_DNS_RR::factory() instead");
         }
     }
& Net_DNS_RR::new_from_array ($rrarray)
Definition at line 204 of file RR.php.
References Net_DNS_RR().
Referenced by factory().
     {
         $rr = &new Net_DNS_RR('getRR');
         foreach ($rrarray as $k => $v) {
             $rr->{strtolower($k)} = $v;
         }
         if (! strlen($rr->name)) {
             return null;
         }
         if (! strlen($rr->type)){
             return null;
         }
         if (! $rr->ttl) {
             $rr->ttl = 0;
         }
         if (! strlen($rr->class)) {
             $rr->class = 'IN';
         }
         if (strlen($rr->rdata)) {
             $rr->rdlength = strlen($rr->rdata);
         }
         if (class_exists('Net_DNS_RR_' . $rr->rrtype)) {
             $scn = 'Net_DNS_RR_' . $rr->rrtype;
             return new $scn($rr, $rr->rdata);
         } else {
             return $rr;
         }
     }
& Net_DNS_RR::new_from_data ($name, $rrtype, $rrclass, $ttl, $rdlength, $data, $offset)
Definition at line 93 of file RR.php.
References $name, $rdlength, $ttl, and Net_DNS_RR().
Referenced by factory().
     {
         $rr = &new Net_DNS_RR('getRR');
         $rr->name = $name;
         $rr->type = $rrtype;
         $rr->class = $rrclass;
         $rr->ttl = $ttl;
         $rr->rdlength = $rdlength;
         $rr->rdata = substr($data, $offset, $rdlength);
         if (class_exists('Net_DNS_RR_' . $rrtype)) {
             $scn = 'Net_DNS_RR_' . $rrtype;
             $rr = new $scn($rr, $data, $offset);
         }
         return $rr;
     }
& Net_DNS_RR::new_from_string ($rrstring, $update_type = '')
Definition at line 111 of file RR.php.
References $name, $rdata, $ttl, Net_DNS\classesbyname(), Net_DNS_RR(), and Net_DNS\typesbyname().
Referenced by factory().
     {
         $rr = &new Net_DNS_RR('getRR');
         $ttl = 0;
         $parts = preg_split('/[\s]+/', $rrstring);
         while (count($parts) > 0) {
             $s = array_shift($parts);
             if (!isset($name)) {
                 $name = ereg_replace('\.+$', '', $s);
             } else if (preg_match('/^\d+$/', $s)) {
                 $ttl = $s;
             } else if (!isset($rrclass) && ! is_null(Net_DNS::classesbyname(strtoupper($s)))) {
                 $rrclass = strtoupper($s);
                 $rdata = join(' ', $parts);
             } else if (! is_null(Net_DNS::typesbyname(strtoupper($s)))) {
                 $rrtype = strtoupper($s);
                 $rdata = join(' ', $parts);
                 break;
             } else {
                 break;
             }
         }
         /*
          *  Do we need to do this?
          */
         $rdata = trim(chop($rdata));
         if (! strlen($rrtype) && strlen($rrclass) && $rrclass == 'ANY') {
             $rrtype = $rrclass;
             $rrclass = 'IN';
         } else if (! isset($rrclass)) {
             $rrclass = 'IN';
         }
         if (! strlen($rrtype)) {
             $rrtype = 'ANY';
         }
         if (strlen($update_type)) {
             $update_type = strtolower($update_type);
             if ($update_type == 'yxrrset') {
                 $ttl = 0;
                 if (! strlen($rdata)) {
                     $rrclass = 'ANY';
                 }
             } else if ($update_type == 'nxrrset') {
                 $ttl = 0;
                 $rrclass = 'NONE';
                 $rdata = '';
             } else if ($update_type == 'yxdomain') {
                 $ttl = 0;
                 $rrclass = 'ANY';
                 $rrtype = 'ANY';
                 $rdata = '';
             } else if ($update_type == 'nxdomain') {
                 $ttl = 0;
                 $rrclass = 'NONE';
                 $rrtype = 'ANY';
                 $rdata = '';
             } else if (preg_match('/^(rr_)?add$/', $update_type)) {
                 $update_type = 'add';
                 if (! $ttl) {
                     $ttl = 86400;
                 }
             } else if (preg_match('/^(rr_)?del(ete)?$/', $update_type)) {
                 $update_type = 'del';
                 $ttl = 0;
                 $rrclass = $rdata ? 'NONE' : 'ANY';
             }
         }
         if (strlen($rrtype)) {
             $rr->name = $name;
             $rr->type = $rrtype;
             $rr->class = $rrclass;
             $rr->ttl = $ttl;
             $rr->rdlength = 0;
             $rr->rdata = '';
             if (class_exists('Net_DNS_RR_' . $rrtype)) {
                 $scn = 'Net_DNS_RR_' . $rrtype;
                 return new $scn($rr, $rdata);
             } else {
                 return $rr;
             }
         } else {
             return null;
         }
     }
Net_DNS_RR::rdata (& $packetORrdata, $offset = '')
Definition at line 265 of file RR.php.
Referenced by Net_DNS_RR_A\Net_DNS_RR_A(), Net_DNS_RR_AAAA\Net_DNS_RR_AAAA(), Net_DNS_RR_CNAME\Net_DNS_RR_CNAME(), Net_DNS_RR_HINFO\Net_DNS_RR_HINFO(), Net_DNS_RR_MX\Net_DNS_RR_MX(), Net_DNS_RR_NAPTR\Net_DNS_RR_NAPTR(), Net_DNS_RR_NS\Net_DNS_RR_NS(), Net_DNS_RR_PTR\Net_DNS_RR_PTR(), Net_DNS_RR_SOA\Net_DNS_RR_SOA(), Net_DNS_RR_SRV\Net_DNS_RR_SRV(), Net_DNS_RR_TSIG\Net_DNS_RR_TSIG(), Net_DNS_RR_TXT\Net_DNS_RR_TXT(), and Net_DNS_RR_NAPTR\rdatastr().
     {
         if ($offset) {
             return $this->rr_rdata($packetORrdata, $offset);
         } else if (strlen($this->rdata)) {
             return $this->rdata;
         } else {
             return null;
         }
     }
Net_DNS_RR::rdatastr ()
Definition at line 255 of file RR.php.
     {
         if ($this->rdlength) {
             return '; rdlength = ' . $this->rdlength;
         }
         return '; no data';
     }
Net_DNS_RR::rr_rdata (& $packet, $offset)
Definition at line 278 of file RR.php.
     {
         return (strlen($this->rdata) ? $this->rdata : '');
     }
Net_DNS_RR::string ()
Definition at line 243 of file RR.php.
     {
         return $this->name . ".\t" . (strlen($this->name) < 16 ? "\t" : '') .
                 $this->ttl  . "\t"  .
                 $this->class. "\t"  .
                 $this->type . "\t"  .
                 $this->rdatastr();
     }
Field Documentation
Net_DNS_RR::$class
Definition at line 51 of file RR.php.
Net_DNS_RR::$name
Definition at line 49 of file RR.php.
Referenced by factory(), new_from_data(), and new_from_string().
Net_DNS_RR::$rdata
Definition at line 54 of file RR.php.
Referenced by new_from_string().
Net_DNS_RR::$rdlength
Definition at line 53 of file RR.php.
Referenced by factory(), and new_from_data().
Net_DNS_RR::$ttl
Definition at line 52 of file RR.php.
Referenced by factory(), new_from_data(), and new_from_string().
Net_DNS_RR::$type
Definition at line 50 of file RR.php.
The documentation for this class was generated from the following file:
RR.php