Constant Contact for WordPress: Ctct\Services\ContactService Class Reference
Ctct\Services\ContactService Class Reference
Public Member Functions
getContacts ($accessToken, array $params=array())
Get a ResultSet of contacts.
getContact ($accessToken, $contactId)
Get contact details for a specific contact.
addContact ($accessToken, Contact $contact, array $params=array())
Add a new contact to the Constant Contact account.
deleteContact ($accessToken, $contactId)
Delete contact details for a specific contact.
deleteContactFromLists ($accessToken, $contactId)
Delete a contact from all contact lists.
deleteContactFromList ($accessToken, $contactId, $listId)
Delete a contact from a specific contact list.
updateContact ($accessToken, Contact $contact, array $params=array())
Update contact details for a specific contact.
Public Member Functions inherited from Ctct\Services\BaseService
__construct ($apiKey, $restClient=null)
Constructor with the option to to supply an alternative rest client to be used.
buildUrl ($url, array $queryParams=null)
Build a URL from a base url and optional array of query parameters to append to the url.
getRestClient ()
Get the rest client being used by the service.
setRestClient (RestClientInterface $restClient)
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Services\BaseService
static getHeaders ($accessToken)
Helper function to return required headers for making an http request with constant contact.
Protected Attributes inherited from Ctct\Services\BaseService
$restClient
$apiKey
Detailed Description
Definition at line 15 of file ContactService.php.
Member Function Documentation
Ctct\Services\ContactService::addContact ($accessToken, Contact $contact, array $params = array())
Add a new contact to the Constant Contact account.
Parameters
string $accessToken - Constant Contact OAuth2 access token
Contact $contact - Contact to add
array $params - query params to be appended to the request
Returns
Contact
Definition at line 59 of file ContactService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Contacts\Contact\create(), Ctct\Util\Config\get(), and Ctct\Components\Contacts\Contact\toJson().
     {
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.contacts');
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->post($url, parent::getHeaders($accessToken), $contact->toJson());
         return Contact::create(json_decode($response->body, true));
     }
Ctct\Services\ContactService::deleteContact ($accessToken, $contactId)
Delete contact details for a specific contact.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $contactId - Unique contact id
Returns
boolean
Definition at line 73 of file ContactService.php.
References Ctct\Services\BaseService\buildUrl(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . sprintf(Config::get('endpoints.contact'), $contactId);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->delete($url, parent::getHeaders($accessToken));
         return ($response->info['http_code'] == 204) ? true : false;
     }
Ctct\Services\ContactService::deleteContactFromList ($accessToken, $contactId, $listId)
Delete a contact from a specific contact list.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $contactId - Contact id to be removed
int $listId - ContactList to remove the contact from
Returns
boolean
Definition at line 102 of file ContactService.php.
References Ctct\Services\BaseService\buildUrl(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.contact_list'), $contactId, $listId);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->delete($url, parent::getHeaders($accessToken));
         return ($response->info['http_code'] == 204) ? true : false;
     }
Ctct\Services\ContactService::deleteContactFromLists ($accessToken, $contactId)
Delete a contact from all contact lists.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $contactId - Contact id to be removed from lists
Returns
boolean
Definition at line 87 of file ContactService.php.
References Ctct\Services\BaseService\buildUrl(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . sprintf(Config::get('endpoints.contact_lists'), $contactId);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->delete($url, parent::getHeaders($accessToken));
         return ($response->info['http_code'] == 204) ? true : false;
     }
Ctct\Services\ContactService::getContact ($accessToken, $contactId)
Get contact details for a specific contact.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $contactId - Unique contact id
Returns
Contact
Definition at line 44 of file ContactService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Contacts\Contact\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . sprintf(Config::get('endpoints.contact'), $contactId);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         return Contact::create(json_decode($response->body, true));
     }
Ctct\Services\ContactService::getContacts ($accessToken, array $params = array())
Get a ResultSet of contacts.
Parameters
string $accessToken - Constant Contact OAuth2 access token
array $params - array of query parameters to be appended to the url
Returns
ResultSet
Definition at line 24 of file ContactService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Contacts\Contact\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.contacts');
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $contacts = array();
         foreach ($body['results'] as $contact) {
             $contacts[] = Contact::create($contact);
         }
         return new ResultSet($contacts, $body['meta']);
     }
Ctct\Services\ContactService::updateContact ($accessToken, Contact $contact, array $params = array())
Update contact details for a specific contact.
Parameters
string $accessToken - Constant Contact OAuth2 access token
Contact $contact - Contact to be updated
array $params - query params to be appended to the request
Returns
Contact
Definition at line 118 of file ContactService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Contacts\Contact\create(), Ctct\Util\Config\get(), and Ctct\Components\Contacts\Contact\toJson().
     {
         $baseUrl = Config::get('endpoints.base_url') . sprintf(Config::get('endpoints.contact'), $contact->id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->put($url, parent::getHeaders($accessToken), $contact->toJson());
         return Contact::create(json_decode($response->body, true));
     }
The documentation for this class was generated from the following file:
ContactService.php