Constant Contact for WordPress: Composer\Autoload\ClassLoader Class Reference
Composer\Autoload\ClassLoader Class Reference
ClassLoader implements a PSR-0 class loader.
Public Member Functions
getPrefixes ()
getFallbackDirs ()
getClassMap ()
addClassMap (array $classMap)
add ($prefix, $paths, $prepend=false)
Registers a set of classes, merging with any others previously set.
set ($prefix, $paths)
Registers a set of classes, replacing any others previously set.
setUseIncludePath ($useIncludePath)
Turns on searching the include path for class files.
getUseIncludePath ()
Can be used to check if the autoloader uses the include path to check for classes.
register ($prepend=false)
Registers this instance as an autoloader.
unregister ()
Unregisters this instance as an autoloader.
loadClass ($class)
Loads the given class or interface.
findFile ($class)
Finds the path to the file where the class is defined.
Private Attributes
$prefixes = array()
$fallbackDirs = array()
$useIncludePath = false
$classMap = array()
Detailed Description
ClassLoader implements a PSR-0 class loader.
See https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md
$loader = new \Composer\Autoload\ClassLoader();
// register classes with namespaces
$loader->add('Symfony\Component', __DIR__.'/component');
$loader->add('Symfony',           __DIR__.'/framework');
// activate the autoloader
$loader->register();
// to enable searching the include path (eg. for PEAR packages)
$loader->setUseIncludePath(true);
In this example, if you try to use a class in the Symfony namespace or one of its children (Symfony for instance), the autoloader will first look for the class under the component/ directory, and it will then fallback to the framework/ directory if not found before giving up.
This class is loosely based on the Symfony UniversalClassLoader.
Author
Fabien Potencier fabie.nosp@m.n@sy.nosp@m.mfony.nosp@m..com
Jordi Boggiano j.bog.nosp@m.gian.nosp@m.o@sel.nosp@m.d.be
Definition at line 43 of file ClassLoader.php.
Member Function Documentation
Composer\Autoload\ClassLoader::add ($prefix, $paths, $prepend = false)
Registers a set of classes, merging with any others previously set.
Parameters
string $prefix The classes prefix
array | string $paths The location(s) of the classes
bool $prepend Prepend the location(s)
Definition at line 84 of file ClassLoader.php.
     {
         if (!$prefix) {
             if ($prepend) {
                 $this->fallbackDirs = array_merge(
                     (array) $paths,
                     $this->fallbackDirs
                 );
             } else {
                 $this->fallbackDirs = array_merge(
                     $this->fallbackDirs,
                     (array) $paths
                 );
             }
             return;
         }
         $first = $prefix[0];
         if (!isset($this->prefixes[$first][$prefix])) {
             $this->prefixes[$first][$prefix] = (array) $paths;
             return;
         }
         if ($prepend) {
             $this->prefixes[$first][$prefix] = array_merge(
                 (array) $paths,
                 $this->prefixes[$first][$prefix]
             );
         } else {
             $this->prefixes[$first][$prefix] = array_merge(
                 $this->prefixes[$first][$prefix],
                 (array) $paths
             );
         }
     }
Composer\Autoload\ClassLoader::addClassMap (array $classMap)
Parameters
array $classMap Class to filename map
Definition at line 68 of file ClassLoader.php.
References Composer\Autoload\ClassLoader\$classMap.
     {
         if ($this->classMap) {
             $this->classMap = array_merge($this->classMap, $classMap);
         } else {
             $this->classMap = $classMap;
         }
     }
Composer\Autoload\ClassLoader::findFile ($class)
Finds the path to the file where the class is defined.
Parameters
string $class The name of the class
Returns
string|false The path if found, false otherwise
Definition at line 198 of file ClassLoader.php.
Referenced by Composer\Autoload\ClassLoader\loadClass().
     {
         // work around for PHP 5.3.0 - 5.3.2 https://bugs.php.net/50731
         if ('\\' == $class[0]) {
             $class = substr($class, 1);
         }
         if (isset($this->classMap[$class])) {
             return $this->classMap[$class];
         }
         if (false !== $pos = strrpos($class, '\\')) {
             // namespaced class name
             $classPath = strtr(substr($class, 0, $pos), '\\', DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;
             $className = substr($class, $pos + 1);
         } else {
             // PEAR-like class name
             $classPath = null;
             $className = $class;
         }
         $classPath .= strtr($className, '_', DIRECTORY_SEPARATOR) . '.php';
         $first = $class[0];
         if (isset($this->prefixes[$first])) {
             foreach ($this->prefixes[$first] as $prefix => $dirs) {
                 if (0 === strpos($class, $prefix)) {
                     foreach ($dirs as $dir) {
                         if (file_exists($dir . DIRECTORY_SEPARATOR . $classPath)) {
                             return $dir . DIRECTORY_SEPARATOR . $classPath;
                         }
                     }
                 }
             }
         }
         foreach ($this->fallbackDirs as $dir) {
             if (file_exists($dir . DIRECTORY_SEPARATOR . $classPath)) {
                 return $dir . DIRECTORY_SEPARATOR . $classPath;
             }
         }
         if ($this->useIncludePath && $file = stream_resolve_include_path($classPath)) {
             return $file;
         }
         return $this->classMap[$class] = false;
     }
Composer\Autoload\ClassLoader::getClassMap ()
Definition at line 60 of file ClassLoader.php.
References Composer\Autoload\ClassLoader\$classMap.
     {
         return $this->classMap;
     }
Composer\Autoload\ClassLoader::getFallbackDirs ()
Definition at line 55 of file ClassLoader.php.
References Composer\Autoload\ClassLoader\$fallbackDirs.
     {
         return $this->fallbackDirs;
     }
Composer\Autoload\ClassLoader::getPrefixes ()
Definition at line 50 of file ClassLoader.php.
     {
         return call_user_func_array('array_merge', $this->prefixes);
     }
Composer\Autoload\ClassLoader::getUseIncludePath ()
Can be used to check if the autoloader uses the include path to check for classes.
Returns
bool
Definition at line 153 of file ClassLoader.php.
References Composer\Autoload\ClassLoader\$useIncludePath.
     {
         return $this->useIncludePath;
     }
Composer\Autoload\ClassLoader::loadClass ($class)
Loads the given class or interface.
Parameters
string $class The name of the class
Returns
bool|null True if loaded, null otherwise
Definition at line 182 of file ClassLoader.php.
References Composer\Autoload\ClassLoader\findFile().
     {
         if ($file = $this->findFile($class)) {
             include $file;
             return true;
         }
     }
Composer\Autoload\ClassLoader::register ($prepend = false)
Registers this instance as an autoloader.
Parameters
bool $prepend Whether to prepend the autoloader or not
Definition at line 163 of file ClassLoader.php.
     {
         spl_autoload_register(array($this, 'loadClass'), true, $prepend);
     }
Composer\Autoload\ClassLoader::set ($prefix, $paths)
Registers a set of classes, replacing any others previously set.
Parameters
string $prefix The classes prefix
array | string $paths The location(s) of the classes
Definition at line 127 of file ClassLoader.php.
     {
         if (!$prefix) {
             $this->fallbackDirs = (array) $paths;
             return;
         }
         $this->prefixes[substr($prefix, 0, 1)][$prefix] = (array) $paths;
     }
Composer\Autoload\ClassLoader::setUseIncludePath ($useIncludePath)
Turns on searching the include path for class files.
Parameters
bool $useIncludePath
Definition at line 142 of file ClassLoader.php.
References Composer\Autoload\ClassLoader\$useIncludePath.
     {
         $this->useIncludePath = $useIncludePath;
     }
Composer\Autoload\ClassLoader::unregister ()
Unregisters this instance as an autoloader.
Definition at line 171 of file ClassLoader.php.
     {
         spl_autoload_unregister(array($this, 'loadClass'));
     }
Field Documentation
Composer\Autoload\ClassLoader::$classMap = array() private
Definition at line 48 of file ClassLoader.php.
Referenced by Composer\Autoload\ClassLoader\addClassMap(), and Composer\Autoload\ClassLoader\getClassMap().
Composer\Autoload\ClassLoader::$fallbackDirs = array() private
Definition at line 46 of file ClassLoader.php.
Referenced by Composer\Autoload\ClassLoader\getFallbackDirs().
Composer\Autoload\ClassLoader::$prefixes = array() private
Definition at line 45 of file ClassLoader.php.
Composer\Autoload\ClassLoader::$useIncludePath = false private
Definition at line 47 of file ClassLoader.php.
Referenced by Composer\Autoload\ClassLoader\getUseIncludePath(), and Composer\Autoload\ClassLoader\setUseIncludePath().
The documentation for this class was generated from the following file:
ClassLoader.php