Constant Contact for WordPress: Ctct\Auth\CtctOAuth2 Class Reference
Ctct\Auth\CtctOAuth2 Class Reference
Public Member Functions
__construct ($clientId, $clientSecret, $redirectUri, $restClient=null)
getAuthorizationUrl ($server=true)
Get the URL at which the user can authenticate and authorize the requesting application.
getAccessToken ($code)
Obtain an access token.
getTokenInfo ($accessToken)
Get an information about an access token.
Data Fields
$clientId
$clientSecret
$redirectUri
$props
Detailed Description
Definition at line 14 of file CtctOAuth2.php.
Constructor & Destructor Documentation
Ctct\Auth\CtctOAuth2::__construct ($clientId, $clientSecret, $redirectUri, $restClient = null)
Definition at line 21 of file CtctOAuth2.php.
References Ctct\Auth\CtctOAuth2\$clientId, Ctct\Auth\CtctOAuth2\$clientSecret, and Ctct\Auth\CtctOAuth2\$redirectUri.
     {
         $this->clientId = $clientId;
         $this->clientSecret = $clientSecret;
         $this->redirectUri = $redirectUri;
         $this->restClient = ($restClient) ? $restClient : new RestClient();
     }
Member Function Documentation
Ctct\Auth\CtctOAuth2::getAccessToken ($code)
Obtain an access token.
Parameters
string $code - code returned from Constant Contact after a user has granted access to their account
Returns
array
Exceptions
\Ctct\Exception\OAuth2Exception
Definition at line 53 of file CtctOAuth2.php.
References Ctct\Util\Config\get().
     {
         $params = array(
             'grant_type'       => Config::get('auth.authorization_code_grant_type'),
             'client_id'         => $this->clientId,
             'client_secret'     => $this->clientSecret,
             'code'             => $code,
             'redirect_uri'      => $this->redirectUri
         );
         $url = Config::get('auth.base_url') . Config::get('auth.token_endpoint') . '?' . http_build_query($params);
         $response = $this->restClient->post($url);
         $resposeBody = json_decode($response->body, true);
         if (array_key_exists('error', $resposeBody)) {
             throw new OAuth2Exception($resposeBody['error'] . ': ' . $resposeBody['error_description']);
         }
         return $resposeBody;
     }
Ctct\Auth\CtctOAuth2::getAuthorizationUrl ($server = true)
Get the URL at which the user can authenticate and authorize the requesting application.
Parameters
boolean $server - Whether or not to use OAuth2 server flow, alternative is client flow
Returns
string - url to send a user to, to grant access to their account
Definition at line 34 of file CtctOAuth2.php.
References Ctct\Util\Config\get().
     {
         $responseType = ($server) ? Config::get('auth.response_type_code') : Config::get("auth.response_type_token");
         $params = array(
             'response_type' => $responseType,
             'client_id'     => $this->clientId,
             'redirect_uri'  => $this->redirectUri
         );
         $url = Config::get('auth.base_url') . Config::get('auth.authorization_endpoint');
         return $url . '?' . http_build_query($params);
     }
Ctct\Auth\CtctOAuth2::getTokenInfo ($accessToken)
Get an information about an access token.
Parameters
string $accessToken - Constant Contact OAuth2 access token
Returns
array
Exceptions
\Ctct\Exception\CtctException
Definition at line 81 of file CtctOAuth2.php.
References Ctct\Util\Config\get().
     {
         $restClient = new RestClient();
         $url = Config::get('auth.base_url') . Config::get('auth.token_info');
         $response = $this->restClient->post($url, array(), "access_token=".$accessToken);
         return json_decode($response->body, true);
     }
Field Documentation
Ctct\Auth\CtctOAuth2::$clientId
Definition at line 16 of file CtctOAuth2.php.
Referenced by Ctct\Auth\CtctOAuth2\__construct().
Ctct\Auth\CtctOAuth2::$clientSecret
Definition at line 17 of file CtctOAuth2.php.
Referenced by Ctct\Auth\CtctOAuth2\__construct().
Ctct\Auth\CtctOAuth2::$props
Definition at line 19 of file CtctOAuth2.php.
Ctct\Auth\CtctOAuth2::$redirectUri
Definition at line 18 of file CtctOAuth2.php.
Referenced by Ctct\Auth\CtctOAuth2\__construct().
The documentation for this class was generated from the following file:
CtctOAuth2.php