Constant Contact for WordPress: CTCT_EventSpot Class Reference
CTCT_EventSpot Class Reference
Public Member Functions
add ()
edit ()
addActions ()
view ()
View all events.
single ()
View a single event or registrant.
singleEvent ()
singleRegistrant ()
Show the details of a single registrant.
processForms ()
events_output ($args=array(), $content=null, $echo=false)
latest_registrant ($event)
Get the date of the latest registration activity for an event.
dashboard_setup ()
dashboard_make_table ($title= 'Events', $events=array())
events_dashboard ()
make_table ($events=array(), $title= '')
Public Member Functions inherited from CTCT_Admin_Page
__construct ()
print_styles ()
print_scripts ()
help_tabs ($tabs)
pointer_content ()
getPointers ($hook_suffix= '')
getPermission ()
add_menu ()
page ()
Static Public Member Functions
static getInstance ()
static setup ()
Data Fields
$old_api
Data Fields inherited from CTCT_Admin_Page
$key
$title
$permission = 'manage_options'
$cc
$oauth
$errors
$can_edit = false
$can_add = false
$component = ''
$pointers = array()
Static Public Attributes
static $instance
Protected Member Functions
getNavTitle ()
Set the submenu anchor text.
getKey ()
getTitle ($value= '')
Protected Member Functions inherited from CTCT_Admin_Page
addIncludes ()
addScripts ()
isAdd ()
isEdit ()
isSingle ()
isView ()
getKey ()
getTitle ()
getNavTitle ()
add ()
edit ()
view ()
single ()
processForms ()
addActions ()
content ()
print_errors ()
Detailed Description
Definition at line 17 of file eventspot.php.
Member Function Documentation
CTCT_EventSpot::add ()
Definition at line 30 of file eventspot.php.
 {}
CTCT_EventSpot::addActions ()
Definition at line 42 of file eventspot.php.
{
         require_once(EVENTSPOT_FILE_PATH.'functions.php');
         require_once(EVENTSPOT_FILE_PATH.'ctct_php_library/ConstantContact.php');
         require_once(EVENTSPOT_FILE_PATH.'class.kwsv1api.php');
         include_once(EVENTSPOT_FILE_PATH.'embed.php');
         $this->old_api = new KWS_V1API('oauth2', CTCT_APIKEY, CTCT_USERNAME, CTCT_ACCESS_TOKEN);
         if(!class_exists('constant_contact_events_widget')) {
             require_once EVENTSPOT_FILE_PATH . 'widget-events.php';
         }
         add_action('wp_dashboard_setup', array(&$this, 'dashboard_setup'));
         // Create events shortcode
         add_shortcode('ccevents', array(&$this, 'events_output'));
         add_shortcode('constantcontactevents', array(&$this, 'events_output'));
         add_shortcode('eventspot', array(&$this, 'events_output'));
         add_action('eventspot_output',  array(&$this, 'events_output'), 10, 3);
         add_filter('cc_event_registrationdate', 'constant_contact_event_date');
         add_filter('cc_event_startdate', 'constant_contact_event_date');
         add_filter('cc_event_enddate', 'constant_contact_event_date');
     }
CTCT_EventSpot::dashboard_make_table ($title = 'Events', $events = array())
Definition at line 189 of file eventspot.php.
Referenced by events_dashboard().
{
         include(EVENTSPOT_FILE_PATH.'views/dashboard-table.php');
     }
CTCT_EventSpot::dashboard_setup ()
Definition at line 185 of file eventspot.php.
{
         wp_add_dashboard_widget( 'constant_contact_events_dashboard', __( 'EventSpot','constant-contact-api'), array(&$this, 'events_dashboard') );
     }
CTCT_EventSpot::edit ()
Definition at line 31 of file eventspot.php.
 {}
CTCT_EventSpot::events_dashboard ()
Definition at line 193 of file eventspot.php.
References dashboard_make_table().
{
         $_events = constant_contact_old_api_get_all('Events', $this->old_api);
         if(!empty($_events) && is_array($_events)) {
             $draft = $active = array();
             foreach($_events as $k => $v) {
                 if($v->status === 'ACTIVE') {
                     $active[$v->id] = $v;
                 } elseif($v->status === 'DRAFT') {
                     $draft[$v->id] = $v;
                 }
             }
             if(!empty($active)) { $this->dashboard_make_table(__('Active Events','constant-contact-api'), $active); }
             if(!empty($draft)) { $this->dashboard_make_table(__('Draft Events','constant-contact-api'), $draft); }
         ?>
             <p class="textright">
                 <a class="button" href="<?php echo admin_url('admin.php?page=constant-contact-events'); ?>"><?php _e('View All Events', 'constant-contact-api'); ?></a>
             </p>
     <?php
         } else {
     ?>
         <p style='font-size:12px;'><?php _e(sprintf("You don't have any events. Did you know that Constant Contact offers %sEvent Marketing%s?", '<a href="http://conta.cc/hB5lnC" title="Learn more about Constant Contact Event Marketing">', '</a>'), 'constant_contact_api'); ?></p>
     <?php
         }
         return true;
     }
CTCT_EventSpot::events_output ($args = array(), $content = null, $echo = false)
Definition at line 155 of file eventspot.php.
{
         require(EVENTSPOT_FILE_PATH.'shortcode.php');
     }
static CTCT_EventSpot::getInstance () static
Definition at line 33 of file eventspot.php.
{
         if(empty(self::$instance)) {
             self::$instance = new CTCT_EventSpot;
         }
         return self::$instance;
     }
CTCT_EventSpot::getKey () protected
Definition at line 137 of file eventspot.php.
{
         return "constant-contact-events";
     }
CTCT_EventSpot::getNavTitle () protected
Set the submenu anchor text.
Returns
string "Events"
Definition at line 26 of file eventspot.php.
{
         return __('Events', 'constant-contact-api');
     }
CTCT_EventSpot::getTitle ($value = '') protected
Definition at line 141 of file eventspot.php.
References CTCT_Admin_Page\isEdit(), and CTCT_Admin_Page\isSingle().
{
         if(empty($value) && $this->isEdit() || $value == 'edit')
             return "Edit Event";
         if(empty($value) && $this->isSingle() || $value == 'single')
             return 'Event';
         return 'Events';
     }
CTCT_EventSpot::latest_registrant ($event)
Get the date of the latest registration activity for an event.
Parameters
Event $event The event object
Returns
string The date of the last registration activity
Definition at line 164 of file eventspot.php.
References CTCT_Admin_Page\$key.
{
         $_registrants = $this->old_api->getRegistrants($event);
         foreach($_registrants['registrants'] as $key => &$reg) {
             $latest = 0;
             if(isset($reg->registrationStatus) && strtolower($reg->registrationStatus) !== 'cancelled') {
                 $timestamp = strtotime($reg->registrationDate);
                 $reg->registrationTimestamp = $timestamp;
                 if($timestamp > $latest) { $latest = $timestamp; }
             } else {
                 unset($_registrants['registrants'][$key]);
             }
         }
         if(empty($timestamp)) {
             return __('N/A','constant-contact-api');
         } else {
             return apply_filters('cc_event_registrationdate', $timestamp);
         }
     }
CTCT_EventSpot::make_table ($events = array(), $title = '')
Definition at line 221 of file eventspot.php.
Referenced by view().
{
         include(EVENTSPOT_FILE_PATH.'views/events.php');
     }
CTCT_EventSpot::processForms ()
Definition at line 135 of file eventspot.php.
 { }
static CTCT_EventSpot::setup () static
Definition at line 150 of file eventspot.php.
{
         $CTCT_EventSpot = new CTCT_EventSpot;
     }
CTCT_EventSpot::single ()
View a single event or registrant.
Definition at line 108 of file eventspot.php.
References singleEvent(), and singleRegistrant().
                       {
         if(isset($_GET['registrant'])) {
             $this->singleRegistrant();
         } else {
             $this->singleEvent();
         }
     }
CTCT_EventSpot::singleEvent ()
Definition at line 117 of file eventspot.php.
Referenced by single().
{
         $v = $this->old_api->getEventDetails(new Event(array('link' => sprintf('/ws/customers/%s/events/%s', CTCT_USERNAME, $_GET['view']))));
         $completed = strtotime($v->endDate) <= time();
         include(EVENTSPOT_FILE_PATH.'views/event.php');
     }
CTCT_EventSpot::singleRegistrant ()
Show the details of a single registrant.
Definition at line 127 of file eventspot.php.
Referenced by single().
{
         $v = $this->old_api->getRegistrantDetails(new Registrant(array('link' => sprintf('/ws/customers/%s/events/%s/registrants/%s', CTCT_USERNAME, $_GET['view'], $_GET['registrant']))));
         $event = $this->old_api->getEventDetails(new Event(array('link' => sprintf('/ws/customers/%s/events/%s', CTCT_USERNAME, $_GET['view']))));
         include(EVENTSPOT_FILE_PATH.'views/registrant.php');
     }
CTCT_EventSpot::view ()
View all events.
Populate the $events var with only events matching the filtered status
Definition at line 72 of file eventspot.php.
References make_table().
                     {
         $events = constant_contact_old_api_get_all('Events', $this->old_api);
         if(empty($events) || !is_array($events)) {
             constant_contact_get_signup_message('events');
             constant_contact_admin_refresh();
         } else {
             kws_print_subsub('status', array(
                 array('val' => '', 'text' => 'All'),
                 array('val' => 'ACTIVE', 'text' => 'Active'),
                 array('val' => 'DRAFT', 'text' => 'Draft'),
                 array('val' => 'COMPLETE', 'text' => 'Complete'),
                 array('val' => 'CANCELLED', 'text' => 'Cancelled'),
             ));
             /** Populate the $events var with only events matching the filtered status */
             if(isset($_GET['status']) && in_array($_GET['status'], array('ACTIVE', 'COMPLETE', 'DRAFT', 'CANCELLED'))) {
                 $ACTIVE = $COMPLETE = $DRAFT = $CANCELLED = array();
                 foreach($events as $id => $v) { ${$v->status}[] = $v; }
                 $events = ${$_GET['status']};
             }
             $this->make_table($events, __('Events','constant-contact-api'));
             ?>
             <p class="submit"><a href="<?php echo add_query_arg('refresh', 'events'); ?>" class="button-secondary alignright" title="<?php echo sprintf('Event registrants data is stored for %s hours. Refresh data now.', round(KWS_V1API::$event_cache_age / 3600)); ?>">Refresh Events</a></p>
             <?php
         }
     }
Field Documentation
CTCT_EventSpot::$instance static
Definition at line 20 of file eventspot.php.
CTCT_EventSpot::$old_api
Definition at line 19 of file eventspot.php.
The documentation for this class was generated from the following file:
eventspot.php