Constant Contact for WordPress: Net_DNS Class Reference
Net_DNS Class Reference
Public Member Functions
Net_DNS ($defaults=array())
Initializes a resolver object.
opcodesbyname ($opcode)
Translates opcode names to integers.
opcodesbyval ($opcodeval)
Translates opcode integers into names.
rcodesbyname ($rcode)
Translates rcode names to integers.
rcodesbyval ($rcodeval)
Translates rcode integers into names.
typesbyname ($rrtype)
Translates RR type names into integers.
typesbyval ($rrtypeval)
Translates RR type integers into names.
classesbyname ($class)
translates a DNS class from it's name to it's integer value.
classesbyval ($classval)
Translates RR class integers into names.
Data Fields
$resolver
$VERSION = '1.00b2'
$PACKETSZ = 512
$HFIXEDSZ = 12
$QFIXEDSZ = 4
$RRFIXEDSZ = 10
$INT32SZ = 4
$INT16SZ = 2
Detailed Description
Definition at line 71 of file DNS.php.
Member Function Documentation
Net_DNS::classesbyname ($class)
translates a DNS class from it's name to it's integer value.
Valid class names are:
IN
CH
HS
NONE
ANY
Parameters
string $class A DNS packet class type
Returns
integer The integer value of an class type
See Also
Net_DNS::classesbyval()
Definition at line 437 of file DNS.php.
Referenced by Net_DNS_Question\data(), Net_DNS_RR\data(), Net_DNS_Question\Net_DNS_Question(), Net_DNS_RR\new_from_string(), and Net_DNS_RR_TSIG\rr_rdata().
     {
         $rc = array(
                 'IN'   => 1,   // RFC 1035
                 'CH'   => 3,   // RFC 1035
                 'HS'   => 4,   // RFC 1035
                 'NONE' => 254, // RFC 2136
                 'ANY'  => 255  // RFC 1035
                 );
         if (!isset($rc[$class])) {
             $rc[$class] = null;
         }
         return $rc[$class];
     }
Net_DNS::classesbyval ($classval)
Translates RR class integers into names.
Translates the integer value of an RR class into it's name
Parameters
integer $classval A DNS packet RR class integer
Returns
string The name of the RR class
See Also
Net_DNS::classesbyname()
Definition at line 463 of file DNS.php.
Referenced by Net_DNS_Packet\parse_question(), and Net_DNS_Packet\parse_rr().
     {
         $rc = array(
                 1 => 'IN',
                 3 => 'CH',
                 4 => 'HS',
                 254 => 'NONE',
                 255 => 'ANY'
                 );
         $classval = preg_replace(array('/\s*/',' /^0*/'), '', $classval);
         if (empty($rc[$classval])) {
             $rc[$classval] = null;
         }
         return $rc[$classval];
     }
Net_DNS::Net_DNS ($defaults = array())
Initializes a resolver object.
See Also
Net_DNS_Resolver
Parameters
array $defaults
Returns
Net_DNS
Definition at line 97 of file DNS.php.
     {
         $this->resolver = new Net_DNS_Resolver($defaults);
     }
Net_DNS::opcodesbyname ($opcode)
Translates opcode names to integers.
Translates the name of a DNS OPCODE into it's assigned number listed in RFC1035, RFC1996, or RFC2136. Valid OPCODES are:
QUERY
IQUERY
STATUS
NS_NOTIFY_OP
UPDATE
string $opcode A DNS Packet OPCODE name
Returns
integer The integer value of an OPCODE
See Also
Net_DNS::opcodesbyval()
Definition at line 120 of file DNS.php.
Referenced by Net_DNS_Header\data().
     {
         $op = array(
                 'QUERY'        => 0,   // RFC 1035
                 'IQUERY'       => 1,   // RFC 1035
                 'STATUS'       => 2,   // RFC 1035
                 'NS_NOTIFY_OP' => 4,   // RFC 1996
                 'UPDATE'       => 5,   // RFC 2136
                 );
         if (! strlen($op[$opcode])) {
             $op[$opcode] = null;
         }
         return $op[$opcode];
     }
Net_DNS::opcodesbyval ($opcodeval)
Translates opcode integers into names.
Translates the integer value of an opcode into it's name
Parameters
integer $opcodeval A DNS packet opcode integer
Returns
string The name of the OPCODE
See Also
Net_DNS::opcodesbyname()
Definition at line 146 of file DNS.php.
Referenced by Net_DNS_Header\Net_DNS_Header().
     {
         $opval = array(
                 0 => 'QUERY',
                 1 => 'IQUERY',
                 2 => 'STATUS',
                 4 => 'NS_NOTIFY_OP',
                 5 => 'UPDATE',
                 );
         if (! strlen($opval[$opcodeval])) {
             $opval[$opcodeval] = null;
         }
         return $opval[$opcodeval];
     }
Net_DNS::rcodesbyname ($rcode)
Translates rcode names to integers.
Translates the name of a DNS RCODE (result code) into it's assigned number.
NOERROR
FORMERR
SERVFAIL
NXDOMAIN
NOTIMP
REFUSED
YXDOMAIN
YXRRSET
NXRRSET
NOTAUTH
NOTZONE
string $rcode A DNS Packet RCODE name
Returns
integer The integer value of an RCODE
See Also
Net_DNS::rcodesbyval()
Definition at line 185 of file DNS.php.
Referenced by Net_DNS_Header\data().
     {
         $rc = array(
                 'NOERROR'   => 0,   // RFC 1035
                 'FORMERR'   => 1,   // RFC 1035
                 'SERVFAIL'  => 2,   // RFC 1035
                 'NXDOMAIN'  => 3,   // RFC 1035
                 'NOTIMP'    => 4,   // RFC 1035
                 'REFUSED'   => 5,   // RFC 1035
                 'YXDOMAIN'  => 6,   // RFC 2136
                 'YXRRSET'   => 7,   // RFC 2136
                 'NXRRSET'   => 8,   // RFC 2136
                 'NOTAUTH'   => 9,   // RFC 2136
                 'NOTZONE'   => 10,    // RFC 2136
                 );
         if (! strlen($rc[$rcode])) {
             $rc[$rcode] = null;
         }
         return $rc[$rcode];
     }
Net_DNS::rcodesbyval ($rcodeval)
Translates rcode integers into names.
Translates the integer value of an rcode into it's name
Parameters
integer $rcodeval A DNS packet rcode integer
Returns
string The name of the RCODE
See Also
Net_DNS::rcodesbyname()
Definition at line 217 of file DNS.php.
Referenced by Net_DNS_RR_TSIG\error(), and Net_DNS_Header\Net_DNS_Header().
     {
         $rc = array(
                 0 => 'NOERROR',
                 1 => 'FORMERR',
                 2 => 'SERVFAIL',
                 3 => 'NXDOMAIN',
                 4 => 'NOTIMP',
                 5 => 'REFUSED',
                 6 => 'YXDOMAIN',
                 7 => 'YXRRSET',
                 8 => 'NXRRSET',
                 9 => 'NOTAUTH',
                 10 => 'NOTZONE',
                 );
         if (! strlen($rc[$rcodeval])) {
             $rc[$rcodeval] = null;
         }
         return $rc[$rcodeval];
     }
Net_DNS::typesbyname ($rrtype)
Translates RR type names into integers.
Translates a Resource Record from it's name to it's integer value. Valid resource record types are:
A
NS
MD
MF
CNAME
SOA
MB
MG
MR
NULL
WKS
PTR
HINFO
MINFO
MX
TXT
RP
AFSDB
X25
ISDN
RT
NSAP
NSAP_PTR
SIG
KEY
PX
GPOS
AAAA
LOC
NXT
EID
NIMLOC
SRV
ATMA
NAPTR
TSIG
UINFO
UID
GID
UNSPEC
IXFR
AXFR
MAILB
MAILA
ANY
string $rrtype A DNS packet RR type name
Returns
integer The integer value of an RR type
See Also
Net_DNS::typesbyval()
Definition at line 298 of file DNS.php.
Referenced by Net_DNS_Question\data(), Net_DNS_RR\data(), Net_DNS_Question\Net_DNS_Question(), and Net_DNS_RR\new_from_string().
     {
         $rc = array(
                 'A'             => 1,
                 'NS'            => 2,
                 'MD'            => 3,
                 'MF'            => 4,
                 'CNAME'         => 5,
                 'SOA'           => 6,
                 'MB'            => 7,
                 'MG'            => 8,
                 'MR'            => 9,
                 'NULL'          => 10,
                 'WKS'           => 11,
                 'PTR'           => 12,
                 'HINFO'         => 13,
                 'MINFO'         => 14,
                 'MX'            => 15,
                 'TXT'           => 16,
                 'RP'            => 17,
                 'AFSDB'         => 18,
                 'X25'           => 19,
                 'ISDN'          => 20,
                 'RT'            => 21,
                 'NSAP'          => 22,
                 'NSAP_PTR'      => 23,
                 'SIG'           => 24,
                 'KEY'           => 25,
                 'PX'            => 26,
                 'GPOS'          => 27,
                 'AAAA'          => 28,
                 'LOC'           => 29,
                 'NXT'           => 30,
                 'EID'           => 31,
                 'NIMLOC'        => 32,
                 'SRV'           => 33,
                 'ATMA'          => 34,
                 'NAPTR'         => 35,
                 'UINFO'         => 100,
                 'UID'           => 101,
                 'GID'           => 102,
                 'UNSPEC'        => 103,
                 'TSIG'          => 250,
                 'IXFR'          => 251,
                 'AXFR'          => 252,
                 'MAILB'         => 253,
                 'MAILA'         => 254,
                 'ANY'           => 255,
                 );
         if (empty($rc[$rrtype])) {
             $rc[$rrtype] = null;
         }
         return $rc[$rrtype];
     }
Net_DNS::typesbyval ($rrtypeval)
Translates RR type integers into names.
Translates the integer value of an RR type into it's name
Parameters
integer $rrtypeval A DNS packet RR type integer
Returns
string The name of the RR type
See Also
Net_DNS::typesbyname()
Definition at line 364 of file DNS.php.
Referenced by Net_DNS_Packet\parse_question(), and Net_DNS_Packet\parse_rr().
     {
         $rc = array(
                 1 => 'A',
                 2 => 'NS',
                 3 => 'MD',
                 4 => 'MF',
                 5 => 'CNAME',
                 6 => 'SOA',
                 7 => 'MB',
                 8 => 'MG',
                 9 => 'MR',
                 10 => 'NULL',
                 11 => 'WKS',
                 12 => 'PTR',
                 13 => 'HINFO',
                 14 => 'MINFO',
                 15 => 'MX',
                 16 => 'TXT',
                 17 => 'RP',
                 18 => 'AFSDB',
                 19 => 'X25',
                 20 => 'ISDN',
                 21 => 'RT',
                 22 => 'NSAP',
                 23 => 'NSAP_PTR',
                 24 => 'SIG',
                 25 => 'KEY',
                 26 => 'PX',
                 27 => 'GPOS',
                 28 => 'AAAA',
                 29 => 'LOC',
                 30 => 'NXT',
                 31 => 'EID',
                 32 => 'NIMLOC',
                 33 => 'SRV',
                 34 => 'ATMA',
                 35 => 'NAPTR',
                 100 => 'UINFO',
                 101 => 'UID',
                 102 => 'GID',
                 103 => 'UNSPEC',
                 250 => 'TSIG',
                 251 => 'IXFR',
                 252 => 'AXFR',
                 253 => 'MAILB',
                 254 => 'MAILA',
                 255 => 'ANY',
                 );
         $rrtypeval = preg_replace(array('/\s*/',' /^0*/'), '', $rrtypeval);
         if (empty($rc[$rrtypeval])) {
             $rc[$rrtypeval] = null;
         }
         return $rc[$rrtypeval];
     }
Field Documentation
Net_DNS::$HFIXEDSZ = 12
Definition at line 82 of file DNS.php.
Net_DNS::$INT16SZ = 2
Definition at line 86 of file DNS.php.
Net_DNS::$INT32SZ = 4
Definition at line 85 of file DNS.php.
Net_DNS::$PACKETSZ = 512
Definition at line 81 of file DNS.php.
Net_DNS::$QFIXEDSZ = 4
Definition at line 83 of file DNS.php.
Net_DNS::$resolver
Definition at line 79 of file DNS.php.
Net_DNS::$RRFIXEDSZ = 10
Definition at line 84 of file DNS.php.
Net_DNS::$VERSION = '1.00b2'
Definition at line 80 of file DNS.php.
The documentation for this class was generated from the following file:
DNS.php