Constant Contact for WordPress: KWSContactList Class Reference
KWSContactList Class Reference
Public Member Functions
__construct ($List= '')
update (array $new_contact_array)
getLabel ($key)
set ($key, $value)
get ($key, $format=false)
Public Member Functions inherited from Ctct\Components\Contacts\ContactList
__construct ($list_id=null)
toJson ()
Static Public Member Functions
static create (array $props)
Factory method to create a Contact object from an array.
static outputHTML ($passed_items=array(), $atts=array())
Convert an array of List objects into HTML output.
Static Public Member Functions inherited from Ctct\Components\Contacts\ContactList
static create (array $props)
Factory method to create a ContactList object from an array.
Private Member Functions
prepareAddress (array $address)
prepareMessageFooter ($message_footer_array)
prepare (array $list_array, $add=false)
is_editable ($key)
Static Private Attributes
static $read_only = array('contact_count', 'id')
Additional Inherited Members
Data Fields inherited from Ctct\Components\Contacts\ContactList
$id
$name
$status
$contact_count
Static Protected Member Functions inherited from Ctct\Components\Component
static getValue (array $array, $item, $default=null)
Get the requested value from an array, or return the default.
Detailed Description
Definition at line 5 of file class.kwscontactlist.php.
Constructor & Destructor Documentation
KWSContactList::__construct ($List = '')
Definition at line 9 of file class.kwscontactlist.php.
References prepare().
{
         if(is_array($List)) {
             $List = $this->prepare($List, true);
         }
         if(!empty($List) && (is_array($List) || $List instanceof ContactList)) {
             foreach($List as $k => &$v) {
                 $this->{$k} = $v;
             }
         }
     }
Member Function Documentation
static KWSContactList::create (array $props) static
Factory method to create a Contact object from an array.
Parameters
array $props - Associative array of initial properties to set
Returns
Contact
Definition at line 27 of file class.kwscontactlist.php.
     {
         $List = new KWSContactList($props);
         return $List;
     }
KWSContactList::get ($key, $format = false)
Definition at line 237 of file class.kwscontactlist.php.
{
         switch($key) {
             default:
                 if(isset($this->{$key})) {
                     return ($format && $this->is_editable($key)) ? '<span class="editable" data-name="'.$key.'" data-id="'.$this->get('id').'">'.esc_html($this->{$key}).'</span>' : $this->{$key};
                 } else {
                     return '';
                 }
                 break;
         }
     }
KWSContactList::getLabel ($key)
Definition at line 75 of file class.kwscontactlist.php.
{
         switch($key) {
             case 'id':
                 return 'ID';
                 break;
             case 'email_addresses':
                 return 'Email Address';
                 break;
         }
         $key = ucwords(preg_replace('/\_/ism', ' ', $key));
         $key = preg_replace('/Addr([0-9])/', __('Address $1', 'constant-contact-api'), $key);
         $key = preg_replace('/Field([0-9])/', __('Field $1', 'constant-contact-api'), $key);
         return $key;
     }
KWSContactList::is_editable ($key) private
Definition at line 233 of file class.kwscontactlist.php.
{
         return !in_array($key, $this::$read_only);
     }
static KWSContactList::outputHTML ($passed_items = array(), $atts = array()) static
Convert an array of List objects into HTML output.
Parameters
string $as Format of HTML; list|select
array $items List array
array $atts Settings; fill, selected, format; format should use replacement tags with the tag being the name of the var of the List object you want to replace. For example, %name%% (%contact_count%% Contacts) will return an item with the content "List Name (140 Contacts)"
showhidden If true, will exclude lists that have a status of "hidden" in http://dotcms.constantcontact.com/docs/contact-list-api/contactlist-collection.html
Returns
[type] [description]
Definition at line 121 of file class.kwscontactlist.php.
References WP_CTCT\getInstance().
Referenced by CTCT_Admin_User_Profile\display(), CTCT_Widget_Simple\form(), CTCT_Registration\form(), and CTCT_Settings\settings_init().
{
         $settings = wp_parse_args($atts, array(
             'type' => 'checkboxes',
             'fill' => true, // Fill data into lists
             'format' => '<span>%%name%%</span>', // Choose HTML format for each item
             'id_attr' => 'ctct-%%id%%', // Pass a widget instance
             'name_attr' => 'lists',
             'checked' => array(), // If as select, what's active?
             'include' => array(),
             'showhidden' => true,
         ));
         extract($settings);
         $items = array();
         // Tell the cache that if the current requests are forced to be
         // refreshed, the cache should also reset this key.
         // See Cache_WP_HTTP
         add_filter('flush_key', function() { return 'ctct_all_lists'; });
         if($passed_items === 'all') {
             $items = WP_CTCT::getInstance()->cc->getAllLists();
         } elseif(!empty($passed_items) && is_array($passed_items)) {
             foreach($passed_items as $item) {
                 global $list_id;
                 if($fill) {
                     $list_id = is_object($item) ? $item->id : $item;
                     // Tell Cache_WP_HTTP to use the following key
                     // as the transient name
                     add_filter('ctct_cachekey', function() {
                         global $list_id;
                         return 'ctct_list_'.$list_id;
                     });
                     $item = WP_CTCT::getInstance()->cc->getList(CTCT_ACCESS_TOKEN, $list_id);
                 }
                 $items[] = $item;
             }
         }
         switch($type) {
             case 'hidden':
                 $before = $before_item = $after_item = $after = '';
                 $format = '<input type="hidden" value="%%id%%" name="%%name_attr%%[]" />';
                 break;
             case 'ul':
                 $before = '<ul class="ul-square">';
                     $before_item = '<li>';
                     $after_item = '</li>';
                 $after = '</ul>';
                 break;
             case 'dropdown':
             case 'select':
             case 'multiselect':
                 $multiple = '';
                 // Even though the multiselect option is no longer available
                 // in the settings, keep this around for backward compatibility.
                 // And if crazy people want multi-selects
                 if($type === 'select' || $type === 'multiselect') {
                     $multiple = ' multiple="multiple"';
                 }
                 $before = '<select name="%%name_attr%%"'.$multiple.' class="select2 ctct-lists">';
                     $before_item = '<option value="%%id%%">';
                     $after_item = '</option>';
                 $after = '</select>';
                 break;
             case 'checkbox':
             case 'checkboxes':
                 $before = '<ul class="ctct-lists ctct-checkboxes">';
                     $before_item = '<li><label for="%%id_attr%%"><input type="checkbox" id="%%id_attr%%" value="%%id%%" name="%%name_attr%%[]" %%checked%% /> ';
                     $after_item = '</label></li>';
                 $after = '</ul>';
                 break;
         }
         $output = $before;
         $items_output = '';
         foreach($items as &$item) {
             // If include was specified, then we need to skip lists not included
             if(is_array($passed_items) && (!empty($include) && !in_array($item->id, $include)) || ($item->status === 'HIDDEN' && !$showhidden)) {
                 #continue;
             }
             $item = new KWSContactList($item);
             $item_content = (!empty($format) || is_null($format)) ? $format : $item->name;
             $item_output = $before_item.$item_content.$after_item."\n";
             $item_output = str_replace('%%name_attr%%', $name_attr, $item_output);
             $item_output = str_replace('%%id_attr%%', $id_attr, $item_output);
             $item_output = str_replace('%%id%%', sanitize_title( $item->get('id') ), $item_output);
             $item_output = str_replace('%%name%%',  $item->get('name', false), $item_output);
             $item_output = str_replace('%%status%%', $item->get('status', false), $item_output);
             $item_output = str_replace('%%contact_count%%', $item->get('contact_count', true), $item_output);
             $item_output = str_replace('%%checked%%', checked((in_array($item->get('id'), (array)$checked) || (is_null($checked) && $item->get('status') === 'ACTIVE')), true, false), $item_output);
             $items_output .= $item_output;
         }
         $output .= $items_output;
         $output .= $after;
         return $output;
     }
KWSContactList::prepare (array $list_array, $add = false) private
Definition at line 61 of file class.kwscontactlist.php.
Referenced by __construct().
{
         $defaults = array(
             'id' => NULL,
             'name' => NULL,
             'status' => NULL,
             'contact_count' => NULL,
         );
         $List = wp_parse_args( $list_array, $defaults );
         return $List;
     }
KWSContactList::prepareAddress (array $address) private
Definition at line 49 of file class.kwscontactlist.php.
{
         return wp_parse_args($address, array('line1' => '', 'line2' => '', 'line3' => '', 'city' => '', 'address_type' => 'PERSONAL', 'state_code' => '', 'country_code' => '', 'postal_code' => '', 'sub_postal_code' => ''));
     }
KWSContactList::prepareMessageFooter ($message_footer_array) private
Definition at line 54 of file class.kwscontactlist.php.
{
         $defaults = array("city" => '', "state" => '', "country" => '', "organization_name" => '', "address_line_1" => '', "address_line_2" => '', "address_line_3" => '', "international_state" => '', "postal_code" => '', "include_forward_email" => false, "forward_email_link_text" => '', "include_subscribe_link" => true, "subscribe_link_text" => '');
         $message_footer = wp_parse_args( $message_footer_array, $defaults );
         $message_footer['country'] = strtoupper($message_footer['country']);
         return $message_footer;
     }
KWSContactList::set ($key, $value)
Definition at line 93 of file class.kwscontactlist.php.
{
         switch($key) {
             case 'name':
                 $this->{$key} = $value;
                 break;
             case 'status':
                 // Only these two values are allowed.
                 if($value === 'ACTIVE' || $value === 'HIDDEN') {
                     $this->{$key} = $value;
                 }
                 break;
             default:
                 return false;
                 break;
         }
         return true;
     }
KWSContactList::update (array $new_contact_array)
Definition at line 34 of file class.kwscontactlist.php.
{
         $existing_contact = wp_clone($this);
         $new_contact = new KWSContactList($new_contact_array, true);
         unset($new_contact->id, $new_contact->status, $new_contact->source, $new_contact->source_details);
         foreach($new_contact as $k => $v) {
             $existing_contact->{$k} = $v;
         }
         return $existing_contact;
     }
Field Documentation
KWSContactList::$read_only = array('contact_count', 'id') static private
Definition at line 7 of file class.kwscontactlist.php.
The documentation for this class was generated from the following file:
class.kwscontactlist.php