Constant Contact for WordPress: Campaign Class Reference
Campaign Class Reference
Public Member Functions
__construct ($params=array())
Constructor.
createXml ()
Create XML Representation of the object.
Static Public Member Functions
static createOverviewStruct ($parsedReturn)
Create associate array of object from XML.
static createStruct ($parsedReturn)
Create associate array of object from XML.
Data Fields
$name
$id
$link
$status
$campaignDate
$lastEditDate
$lastRunDate
$campaignSent
$campaignOpens
$campaignClicks
$campaignBounces
$campaignForwards
$campaignOptOuts
$campaignSpamReports
$subject
$fromName
$campaignType
$vawp
$vawpLinkText
$vawpText
$permissionReminder
$permissionReminderText
$greetingSalutation
$greetingName
$greetingString
$orgName
$orgAddr1
$orgAddr2
$orgAddr3
$orgCity
$orgState
$orgInternationalState
$orgCountry
$orgPostalCode
$incForwardEmail
$forwardEmailLinkText
$incSubscribeLink
$subscribeLinkText
$emailContentFormat
$emailContent
$textVersionContent
$styleSheet
$lists = array()
$fromAddress
$replyAddress
$archiveStatus
$archiveUrl
$urls = array()
Additional Inherited Members
Protected Member Functions inherited from CCObject
validate (Array $params)
Validate an object to check that all required fields have been supplied array $params - object property names to reference for validation before HTTP requests.
Detailed Description
Definition at line 323 of file Components.php.
Constructor & Destructor Documentation
Campaign::__construct ($params = array())
Constructor.
Parameters
array $params - associative array of properties/values
Definition at line 377 of file Components.php.
{
         $this->name = (isset($params['name'])) ? $params['name'] : '';
         $this->id = (isset($params['id'])) ? $params['id'] : 'data:,';
         $this->link = (isset($params['link'])) ? $params['link'] : '';
         $this->status = (isset($params['status'])) ? $params['status'] : '';
         $this->campaignDate = (isset($params['campaignDate'])) ? $params['campaignDate'] : '2009-10-19T18:34:53.105Z';
         $this->lastEditDate = (isset($params['lastEditDate'])) ? $params['lastEditDate'] : '';
         $this->lastRunDate = (isset($params['lastRunDate'])) ? $params['lastRunDate'] : '';
         $this->campaignSent = (isset($params['campaignSent'])) ? $params['campaignSent'] : '';
         $this->campaignOpens = (isset($params['campaignOpens'])) ? $params['campaignOpens'] : '';
         $this->campaignClicks = (isset($params['campaignClicks'])) ? $params['campaignClicks'] : '';
         $this->campaignBounces = (isset($params['campaignBounces'])) ? $params['campaignBounces'] : '';
         $this->campaignForwards = (isset($params['campaignForwards'])) ? $params['campaignForwards'] : '';
         $this->campaignOptOuts = (isset($params['campaignOptOuts'])) ? $params['campaignOptOuts'] : '';
         $this->campaignSpamReports = (isset($params['campaignSpamReports'])) ? $params['campaignSpamReports'] : '';
         $this->subject = (isset($params['subject'])) ? $params['subject'] : '';
         $this->fromName = (isset($params['fromName'])) ? $params['fromName'] : 'Default From Name';
         $this->campaignType = (isset($params['campaignType'])) ? $params['campaignType'] : '';
         $this->vawp = (isset($params['vawp'])) ? $params['vawp'] : 'NO';
         $this->vawpLinkText = (isset($params['vawpLinkText'])) ? $params['vawpLinkText'] : '';
         $this->vawpText = (isset($params['vawpText'])) ? $params['vawpText'] : '';
         $this->permissionReminder = (isset($params['permissionReminder'])) ? $params['permissionReminder'] : 'NO';
         $this->permissionReminderText = (isset($params['permissionReminderText'])) ? $params['permissionReminderText'] : '';
         $this->greetingSalutation = (isset($params['greetingSalutation'])) ? $params['greetingSalutation'] : 'Dear';
         $this->greetingName = (isset($params['greetingName'])) ? $params['greetingName'] : 'FirstName';
         $this->greetingString = (isset($params['greetingString'])) ? $params['greetingString'] : '';
         $this->orgName = (isset($params['orgName'])) ? $params['orgName'] : '$ACCOUNT.ORGANIZATIONNAME';
         $this->orgAddr1 = (isset($params['orgAddr1'])) ? $params['orgAddr1'] : '$ACCOUNT.ADDRESS_LINE_1';
         $this->orgAddr2 = (isset($params['orgAddr2'])) ? $params['orgAddr2'] : '$ACCOUNT.ADDRESS_LINE_2';;
         $this->orgAddr3 = (isset($params['orgAddr3'])) ? $params['orgAddr3'] : '$ACCOUNT.ADDRESS_LINE_3';
         $this->orgCity = (isset($params['orgCity'])) ? $params['orgCity'] : '';
         $this->orgState = (isset($params['orgState'])) ? $params['orgState'] : '';
         $this->orgInternationalState = (isset($params['orgInternationalState'])) ? $params['orgInternationalState'] : '';
         $this->orgCountry = (isset($params['orgCountry'])) ? $params['orgCountry'] : '';
         $this->orgPostalCode = (isset($params['orgPostalCode'])) ? $params['orgPostalCode'] : '';
         $this->incForwardEmail = (isset($params['incForwardEmail'])) ? $params['incForwardEmail'] : 'NO';
         $this->forwardEmailLinkText = (isset($params['forwardEmailLinkText'])) ? $params['forwardEmailLinkText'] : '';
         $this->incSubscribeLink = (isset($params['incSubscribeLink'])) ? $params['incSubscribeLink'] : 'NO';
         $this->subscribeLinkText = (isset($params['subscribeLinkText'])) ? $params['subscribeLinkText'] : '';
         $this->emailContentFormat = (isset($params['emailContentFormat'])) ? $params['emailContentFormat'] : 'HTML';
         $this->emailContent = (isset($params['emailContent'])) ? $params['emailContent'] : '';
         $this->textVersionContent = (isset($params['textVersionContent'])) ? $params['textVersionContent'] : '';
         $this->styleSheet = (isset($params['styleSheet'])) ? $params['styleSheet'] : '';;
         $this->lists = (isset($params['lists'])) ? $params['lists'] : array();
         $this->archiveStatus = (isset($params['archiveStatus'])) ? $params['archiveStatus'] : '';
         $this->archiveUrl = (isset($params['archiveUrl'])) ? $params['archiveUrl'] : '';
         $this->urls = (isset($params['urls'])) ? $params['urls'] : array();
         $this->replyAddress = (isset($params['replyAddress'])) ? $params['replyAddress'] : '';
         $this->fromAddress = (isset($params['fromAddress'])) ? $params['fromAddress'] : '';
     }
Member Function Documentation
static Campaign::createOverviewStruct ($parsedReturn) static
Create associate array of object from XML.
Parameters
SimpleXMLElement $parsedReturn - parsed XML
Returns
Definition at line 529 of file Components.php.
Referenced by CampaignsCollection\getCampaigns(), and CampaignsCollection\getCampaignsByStatus().
{
         $campaign = array();
         $campaign['link'] = (string) $parsedReturn->link->Attributes()->href;
         $campaign['id'] = (string) $parsedReturn->id;
         $campaign['name'] = (string) $parsedReturn->content->Campaign->Name;
         $campaign['status'] = (string) $parsedReturn->content->Campaign->Status;
         $campaign['campaignDate'] = (string) $parsedReturn->content->Campaign->Date;
         return $campaign;
     }
static Campaign::createStruct ($parsedReturn) static
Create associate array of object from XML.
Parameters
SimpleXMLElement $parsedReturn - parsed XML
Returns
Definition at line 545 of file Components.php.
References $link.
Referenced by CampaignsCollection\addCampaign(), and CampaignsCollection\getCampaignDetails().
{
         $campaign = array();
         $campaign['link'] = (string) $parsedReturn->link->Attributes()->href;
         $campaign['id'] = (string) $parsedReturn->id;
         $campaign['name'] = (string) $parsedReturn->content->Campaign->Name;
         $campaign['status'] = (string) $parsedReturn->content->Campaign->Status;
         $campaign['campaignDate'] = (string) $parsedReturn->content->Campaign->Date;
         $campaign['lastEditDate'] = (string) $parsedReturn->content->Campaign->LastEditDate;
         $campaign['lastRunDate'] = (string) $parsedReturn->content->Campaign->LastRunDate;
         $campaign['campaignSent'] = (string) $parsedReturn->content->Campaign->Sent;
         $campaign['campaignOpens'] = (string) $parsedReturn->content->Campaign->Opens;
         $campaign['campaignClicks'] = (string) $parsedReturn->content->Campaign->Clicks;
         $campaign['campaignBounces'] = (string) $parsedReturn->content->Campaign->Bounces;
         $campaign['campaignForwards'] = (string) $parsedReturn->content->Campaign->Forwards;
         $campaign['campaignOptOuts'] = (string) $parsedReturn->content->Campaign->OptOuts;
         $campaign['campaignSpamReports'] = (string) $parsedReturn->content->Campaign->SpamReports;
         $campaign['subject'] = (string) $parsedReturn->content->Campaign->Subject;
         $campaign['fromName'] = (string) $parsedReturn->content->Campaign->FromName;
         $campaign['campaignType'] = (string) $parsedReturn->content->Campaign->CampaignType;
         $campaign['vawp'] = (string) $parsedReturn->content->Campaign->ViewAsWebpage;
         $campaign['vawpLinkText'] = (string) $parsedReturn->content->Campaign->ViewAsWebPageLinkText;
         $campaign['vawpText'] = (string) $parsedReturn->content->Campaign->ViewAsWebpageText;
         $campaign['permissionReminder'] = (string) $parsedReturn->content->Campaign->PermissionReminder;
         $campaign['permissionReminderTxt'] = (string) $parsedReturn->content->Campaign->PermissionReminderText;
         $campaign['greetingSalutation'] = (string) $parsedReturn->content->Campaign->GreetingSalutation;
         $campaign['greetingName'] = (string) $parsedReturn->content->Campaign->GreetingName;
         $campaign['greetingString'] = (string) $parsedReturn->content->Campaign->GreetingString;
         $campaign['orgName'] = (string) $parsedReturn->content->Campaign->OrganizationName;
         $campaign['orgAddr1'] = (string) $parsedReturn->content->Campaign->OrganizationAddress1;
         $campaign['orgAddr2'] = (string) $parsedReturn->content->Campaign->OrganizationAddress2;
         $campaign['orgAddr3'] = (string) $parsedReturn->content->Campaign->OrganizationAddress3;
         $campaign['orgCity'] =(string)  $parsedReturn->content->Campaign->OrganizationCity;
         $campaign['orgState'] = (string) $parsedReturn->content->Campaign->OrganizationState;
         $campaign['orgInternationalState'] = (string) $parsedReturn->content->Campaign->OrganizationInternationalState;
         $campaign['orgCountry'] = (string) $parsedReturn->content->Campaign->OrganizationCountry;
         $campaign['orgPostalCode'] = (string) $parsedReturn->content->Campaign->OrganizationPostalCode;
         $campaign['incForwardEmail'] = (string) $parsedReturn->content->Campaign->IncludeForwardEmail;
         $campaign['forwardEmailLinkText'] = (string) $parsedReturn->content->Campaign->ForwardEmailLinkText;
         $campaign['incSubscribeLink'] = (string) $parsedReturn->content->Campaign->IncludeSubscribeLink;
         $campaign['subscribeLinkText'] = (string) $parsedReturn->content->Campaign->SubscribeLinkText;
         $campaign['emailContentFormat'] = (string) $parsedReturn->content->Campaign->EmailContentFormat;
         $campaign['emailContent'] = (string) $parsedReturn->content->Campaign->EmailContent;
         $campaign['textVersionContent'] = (string) $parsedReturn->content->Campaign->EmailTextContent;
         $campaign['styleSheet'] = (string) $parsedReturn->content->Campaign->StyleSheet;
         $campaign['archiveStatus'] = (string) $parsedReturn->content->Campaign->ArchiveStatus;
         $campaign['archiveUrl'] = (string) $parsedReturn->content->Campaign->ArchiveURL;
         $fromAddr = new VerifiedAddress();
         $fromAddr->email = (string) $parsedReturn->content->Campaign->FromEmail->EmailAddress;
         $fromAddr->link = (string) $parsedReturn->content->Campaign->FromEmail->Email->link->Attributes()->href;
         $campaign['fromAddress'] = $fromAddr;
         $replyAddr = new VerifiedAddress();
         $replyAddr->email = (string) $parsedReturn->content->Campaign->ReplyToEmail->EmailAddress;
         $replyAddr->link = (string) $parsedReturn->content->Campaign->ReplyToEmail->Email->link->Attributes()->href;
         $campaign['replyAddress'] = $replyAddr;
         if ($parsedReturn->content->Campaign->ContactLists->ContactList){
             foreach ($parsedReturn->content->Campaign->ContactLists->ContactList as $item){
                 $campaign['lists'][] = (string) $item->link->Attributes()->href;
             }
         }
         if ($parsedReturn->content->Campaign->Urls){
             foreach($parsedReturn->content->Campaign->Urls->Url as $link){
                 $url['id'] = (string) $link->Attributes()->id;
                 $url['value'] = (string) $link->Value;
                 $url['clicks'] = (string) $link->Clicks;
                 $urlArray[] = $url;
             }
             $campaign['urls'] = $urlArray;
         }
         return $campaign;
     }
Campaign::createXml ()
Create XML Representation of the object.
Returns
SimpleXMLElement
Definition at line 432 of file Components.php.
References $link, $lists, and CCObject\validate().
Referenced by CampaignsCollection\addCampaign(), CampaignsCollection\scheduleCampaign(), and CampaignsCollection\updateCampaign().
{
         $this->validate(array('emailContentFormat', 'textVersionContent', 'name', 'subject', 'id'));
         $xml = simplexml_load_string("<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom' />");
         $link = $xml->addChild("link");
         $link->addAttribute('href', '/ws/customers/customer/campaigns');
         $link->addAttribute('rel', 'edit');
         $xml->addChild("id", $this->id);
         $title = $xml->addChild("title", $this->name);
         $title->addAttribute("type", "text");
         $xml->addChild("updated", '2009-10-19T18:34:53.105Z');
         $author = $xml->addChild("author");
         $author->addChild("name", "Constant Contact");
         $content = $xml->addChild("content");
         $content->addAttribute("type", "application/vnd.ctct+xml");
         $campaign_node = $content->addChild("Campaign");
         $campaign_node->addAttribute("xmlns", "http://ws.constantcontact.com/ns/1.0/");
         $campaign_node->addAttribute("id", $this->id);
         $campaign_node->addChild("Name", $this->name);
         $campaign_node->addChild("Status", "draft");
         $campaign_node->addChild("Date", $this->campaignDate);
         $campaign_node->addChild("Subject", $this->subject);
         $campaign_node->addChild("FromName", $this->fromName);
         $campaign_node->addChild("ViewAsWebpage", $this->vawp);
         $campaign_node->addChild("ViewAsWebpageLinkText", $this->vawpLinkText);
         $campaign_node->addChild("ViewAsWebpageText", $this->vawpText);
         $campaign_node->addChild("PermissionReminder", $this->permissionReminder);
         $campaign_node->addChild("PermissionReminderText", $this->permissionReminderText);
         $campaign_node->addChild("GreetingSalutation", $this->greetingSalutation);
         $campaign_node->addChild("GreetingName", $this->greetingName);
         $campaign_node->addChild("GreetingString", $this->greetingString);
         $campaign_node->addChild("OrganizationName", $this->orgName);
         $campaign_node->addChild("OrganizationAddress1", $this->orgAddr1);
         $campaign_node->addChild("OrganizationAddress2", $this->orgAddr2);
         $campaign_node->addChild("OrganizationAddress3", $this->orgAddr3);
         $campaign_node->addChild("OrganizationCity", $this->orgCity);
         $campaign_node->addChild("OrganizationState", $this->orgState);
         $campaign_node->addChild("OrganizationInternationalState", $this->orgInternationalState);
         $campaign_node->addChild("OrganizationCountry", $this->orgCountry);
         $campaign_node->addChild("OrganizationPostalCode", $this->orgPostalCode);
         $campaign_node->addChild("IncludeForwardEmail", $this->incForwardEmail);
         $campaign_node->addChild("ForwardEmailLinkText", $this->forwardEmailLinkText);
         $campaign_node->addChild("IncludeSubscribeLink", $this->incSubscribeLink);
         $campaign_node->addChild("SubscribeLinkText", $this->subscribeLinkText);
         $campaign_node->addChild("EmailContentFormat", $this->emailContentFormat);
         $campaign_node->addChild("EmailContent", $this->emailContent);
         $campaign_node->addChild("EmailTextContent", $this->textVersionContent);
         $campaign_node->addChild("StyleSheet", $this->styleSheet);
         $contactLists = $campaign_node->addChild("ContactLists");
         $campaignLists = $this->lists;
         if ($campaignLists){
             foreach ($campaignLists as $list) {
                 $contactList = $contactLists->addChild("ContactList");
                 $contactList->addAttribute("id", $list);
                 $contactLink = $contactList->addChild("link");
                 $contactLink->addAttribute("xmlns", "http://www.w3.org/2005/Atom");
                 $contactLink->addAttribute("href", str_replace("http://api.constantcontact.com", "", $list));
                 $contactLink->addAttribute("rel", "self");
             }
         }
         $fromEmail = $campaign_node->addChild("FromEmail");
         $email_node = $fromEmail->addChild("Email");
         $email_node->addAttribute("id", "http://api.constantcontact.com" . $this->fromAddress->link);
         $email_link = $email_node->addChild("link");
         $email_link->addAttribute("xmlns", "http://www.w3.org/2005/Atom");
         $email_link->addAttribute("href", $this->fromAddress->link);
         $email_link->addAttribute("rel", "self");
         $fromEmail->addChild("EmailAddress", $this->fromAddress->email);
         $replyEmail = $campaign_node->addChild("ReplyToEmail");
         $replyEmailNode = $replyEmail->addChild("Email");
         $replyEmailNode->addAttribute("id", "http://api.constantcontact.com" . $this->replyAddress->link);
         $replyEmailLink = $replyEmailNode->addChild("link");
         $replyEmailLink->addAttribute("xmlns", "http://www.w3.org/2005/Atom");
         $replyEmailLink->addAttribute("href", $this->replyAddress->link);
         $replyEmailLink->addAttribute("rel", "self");
         $replyEmail->addChild("EmailAddress", $this->replyAddress->email);
         $sourceNode = $xml->addChild("source");
         $sourceNode->addChild("id", $this->id);
         $sourceTitle = $sourceNode->addChild("title", "Campaigns for customer");
         $sourceTitle->addAttribute("type", "text");
         $sourceLink1 = $sourceNode->addChild("link");
         $sourceLink1->addAttribute("href", "campaigns");
         $sourceLink2 = $sourceNode->addChild("link");
         $sourceLink2->addAttribute("href", "campaigns");
         $sourceLink2->addAttribute("rel", "self");
         $sourceAuthor = $sourceNode->addChild("author");
         $sourceAuthor->addChild("name", 'customer');
         $sourceNode->addChild("updated", date("Y-m-d").'T'.date("H:i:s").'+01:00');
         $xml = $xml->asXML();
         return $xml;
     }
Field Documentation
Campaign::$archiveStatus
Definition at line 369 of file Components.php.
Campaign::$archiveUrl
Definition at line 370 of file Components.php.
Campaign::$campaignBounces
Definition at line 334 of file Components.php.
Campaign::$campaignClicks
Definition at line 333 of file Components.php.
Campaign::$campaignDate
Definition at line 328 of file Components.php.
Campaign::$campaignForwards
Definition at line 335 of file Components.php.
Campaign::$campaignOpens
Definition at line 332 of file Components.php.
Campaign::$campaignOptOuts
Definition at line 336 of file Components.php.
Campaign::$campaignSent
Definition at line 331 of file Components.php.
Campaign::$campaignSpamReports
Definition at line 337 of file Components.php.
Campaign::$campaignType
Definition at line 340 of file Components.php.
Campaign::$emailContent
Definition at line 363 of file Components.php.
Campaign::$emailContentFormat
Definition at line 362 of file Components.php.
Campaign::$forwardEmailLinkText
Definition at line 359 of file Components.php.
Campaign::$fromAddress
Definition at line 367 of file Components.php.
Campaign::$fromName
Definition at line 339 of file Components.php.
Campaign::$greetingName
Definition at line 347 of file Components.php.
Campaign::$greetingSalutation
Definition at line 346 of file Components.php.
Campaign::$greetingString
Definition at line 348 of file Components.php.
Campaign::$id
Definition at line 325 of file Components.php.
Campaign::$incForwardEmail
Definition at line 358 of file Components.php.
Campaign::$incSubscribeLink
Definition at line 360 of file Components.php.
Campaign::$lastEditDate
Definition at line 329 of file Components.php.
Campaign::$lastRunDate
Definition at line 330 of file Components.php.
Campaign::$link
Definition at line 326 of file Components.php.
Referenced by createStruct(), and createXml().
Campaign::$lists = array()
Definition at line 366 of file Components.php.
Referenced by createXml().
Campaign::$name
Definition at line 324 of file Components.php.
Campaign::$orgAddr1
Definition at line 350 of file Components.php.
Campaign::$orgAddr2
Definition at line 351 of file Components.php.
Campaign::$orgAddr3
Definition at line 352 of file Components.php.
Campaign::$orgCity
Definition at line 353 of file Components.php.
Campaign::$orgCountry
Definition at line 356 of file Components.php.
Campaign::$orgInternationalState
Definition at line 355 of file Components.php.
Campaign::$orgName
Definition at line 349 of file Components.php.
Campaign::$orgPostalCode
Definition at line 357 of file Components.php.
Campaign::$orgState
Definition at line 354 of file Components.php.
Campaign::$permissionReminder
Definition at line 344 of file Components.php.
Campaign::$permissionReminderText
Definition at line 345 of file Components.php.
Campaign::$replyAddress
Definition at line 368 of file Components.php.
Campaign::$status
Definition at line 327 of file Components.php.
Campaign::$styleSheet
Definition at line 365 of file Components.php.
Campaign::$subject
Definition at line 338 of file Components.php.
Campaign::$subscribeLinkText
Definition at line 361 of file Components.php.
Campaign::$textVersionContent
Definition at line 364 of file Components.php.
Campaign::$urls = array()
Definition at line 371 of file Components.php.
Campaign::$vawp
Definition at line 341 of file Components.php.
Campaign::$vawpLinkText
Definition at line 342 of file Components.php.
Campaign::$vawpText
Definition at line 343 of file Components.php.
The documentation for this class was generated from the following file:
Components.php