Constant Contact for WordPress: KWSContact Class Reference
KWSContact Class Reference
Public Member Functions
__construct ($Contact= '')
update ($new_contact_array)
addNote ($note)
Add a note Contact object.
getLabel ($key)
is_editable ($key, $check_status=true)
set ($key, $value)
get ($key, $format=false)
getAddress ($type= 'personal', $format=false)
Public Member Functions inherited from Ctct\Components\Contacts\Contact
addList ($contactList)
Add a ContactList.
addEmail ($emailAddress)
Add an EmailAddress.
addCustomField (CustomField $customField)
Add a custom field to the contact object.
addAddress (Address $address)
Add an address.
toJson ()
Static Public Member Functions
static create (array $props)
Factory method to create a Contact object from an array.
Static Public Member Functions inherited from Ctct\Components\Contacts\Contact
static create (array $props)
Factory method to create a Contact object from an array.
Private Member Functions
prepareAddress (array $address)
prepareName ($contact_array, $key= 'name')
Split a full name into pieces.
prepare (array $contact_array, $add=false)
Clean and parse an array of contact details to be in CTCT format.
getEmail ()
Static Private Attributes
static $read_only = array('created_date', 'status', 'modified_date', 'id', 'confirmed', 'source', 'source_details', 'opt_out_date', 'opt_in_date', 'confirm_status')
Additional Inherited Members
Data Fields inherited from Ctct\Components\Contacts\Contact
$id
$status
$first_name
$middle_name
$last_name
$confirmed
$source
$email_addresses = array()
$prefix_name
$job_title
$addresses = array()
$notes = array()
$company_name
$home_phone
$work_phone
$cell_phone
$fax
$custom_fields = array()
$lists = array()
$source_details
Static Protected Member Functions inherited from Ctct\Components\Component
static getValue (array $array, $item, $default=null)
Get the requested value from an array, or return the default.
Detailed Description
Definition at line 12 of file class.kwscontact.php.
Constructor & Destructor Documentation
KWSContact::__construct ($Contact = '')
Definition at line 16 of file class.kwscontact.php.
References prepare().
{
         if(is_array($Contact)) {
             $Contact = $this->prepare($Contact, true);
         }
         if(is_wp_error($Contact)) {
             return $Contact;
         }
         if(!empty($Contact) && (is_array($Contact) || $Contact instanceof Contact)) {
             foreach($Contact as $k => &$v) {
                 $this->{$k} = constant_contact_prepare_value($v);
             }
         }
     }
Member Function Documentation
KWSContact::addNote ($note)
Add a note Contact object.
Parameters
Note $note - note to add to the contact
Definition at line 299 of file class.kwscontact.php.
{
         if(is_string($note)) {
             $note = array('note' => $note);
         }
         if (! $note instanceof EmailAddress) {
             $note = Note::create($note);
         }
         $this->notes[0] = $note;
     }
static KWSContact::create (array $props) static
Factory method to create a Contact object from an array.
Parameters
array $props - Associative array of initial properties to set
Returns
Contact
Definition at line 38 of file class.kwscontact.php.
     {
         $contact = new KWSContact($props);
         return $contact;
     }
KWSContact::get ($key, $format = false)
If an item has a parent, the parent is added as a prefix using {parent}_ syntax.
The following cases match personal addresses and business addresses in the format of personal_line1, business_city, etc.
Definition at line 384 of file class.kwscontact.php.
Referenced by CTCT_Process_Form\validateEmail().
{
         if(!$this->is_editable($key)) { $format = false; }
         switch(strtolower($key)) {
             case 'status':
                 return $format ? ucfirst(strtolower($this->{$key})) : $this->{$key};
                 break;
             case 'opt_in_date':
             case 'opt_out_date':
             case 'created_date':
             case 'modified_date':
                 if(empty($this->{$key})) { return false; }
                 $date = date_i18n(get_option('date_format'), strtotime($this->email_addresses[0]->{$key}), true);
                 return $format ? $date : $this->{$key};
                 break;
             case 'email_addresses':
             case 'email_address':
             case 'email':
                 return $this->getEmail();
                 break;
             case 'full_name':
                 return $format ? '<span data-name="prefix_name" class="editable" data-id="'.$this->get('id').'">'.$this->get('prefix_name') .'</span> <span data-name="first_name" class="editable" data-id="'.$this->get('id').'">'.$this->get('first_name') .'</span> <span data-name="middle_name" class="editable" data-id="middle_name">'. $this->get('middle_name') .'</span> <span data-name="last_name" class="editable" data-id="'.$this->get('id').'">'.$this->get('last_name').'</span>' : $this->get('first_name') .' ' . $this->get('middle_name') .' '.$this->get('last_name');
                 break;
             case 'name':
                     return $format ? '<span data-name="first_name" class="editable" data-id="'.$this->get('id').'">'.$this->get('first_name') .'</span> <span data-name="last_name" class="editable" data-id="'.$this->get('id').'">'.$this->get('last_name').'</span>' : $this->get('first_name') .' ' .$this->get('last_name');
                 break;
             case 'notes':
                     if(empty($this->{$key})) { return ''; }
                     $notes = is_array($this->{$key}) ? $this->{$key}[0]->note : $this->{$key};
                     return $format ? '<span data-name="notes" class="editable" data-id="'.$this->get('id').'">'.$notes.'</span>' : $notes;
                 break;
             case 'address':
             case 'personal_address':
             case 'home_address':
                 return $this->getAddress('personal', $format);
                 break;
             case 'business_address':
                 return $this->getAddress('business', $format);
                 break;
             /**
              * If an item has a parent, the parent is added as a prefix using `{parent}_` syntax.
              *
              * The following cases match personal addresses and business addresses in the
              * format of `personal_line1`, `business_city`, etc.
              *
              */
             case (preg_match('/^personal_/ism', $key) ? true : false):
                 $key = strtolower(str_ireplace('personal_', '', $key));
                 return isset($this->addresses[0]) ? $this->addresses[0]->{$key} : '';
                 break;
             case (preg_match('/^business_/ism', $key) ? true : false):
                 $key = strtolower(str_ireplace('business_', '', $key));
                 return isset($this->addresses[1]) ? $this->addresses[1]->{$key} : '';
                 break;
             case (preg_match('/^customfield/ism', $key) ? true : false):
                 foreach((array)$this->custom_fields as $customfield) {
                     if(strtolower($customfield->name) === strtolower($key)) {
                         return $customfield->value;
                     }
                 }
                 break;
             case 'lists':
                 $lists = array();
                 if($format) {
                     foreach((array)$this->lists as $list) {
                         $lists[] = $list->id;
                     }
                 } else {
                     $lists = $this->lists;
                 }
                 return $lists;
                 break;
             default:
                 if(preg_match('/date/', $key) && $format) {
                     return date('jS F Y \- H:i', (int)$cc->convert_timestamp($v));
                 }
                 if(isset($this->{$key})) {
                     $this->{$key} = is_string($this->{$key}) ? stripslashes($this->{$key}) : $this->{$key};
                     return $this->{$key};
                 } else {
                     return '';
                 }
                 break;
         }
     }
KWSContact::getAddress ($type = 'personal', $format = false)
Definition at line 475 of file class.kwscontact.php.
{
         $output = '';
         foreach($this->addresses as $Address) {
             if(strtoupper($type) !== $Address->address_type) { continue; }
             $output = $format ? '<span data-parent="'.$Address->address_type.'" data-name="line1" class="editable">'.$Address->line1.'</span>' : $Address->line1;
             if(!empty($Address->line2) || $format) {
                 $output .= $format ? '<br /><span data-parent="'.$Address->address_type.'" data-name="line2" class="editable">'.$Address->line2.'</span>' : '<br />'.$Address->line2;
             }
             if(!empty($Address->line3) || $format) {
                 $output .= $format ? '<br /><span data-parent="'.$Address->address_type.'" data-name="line3" class="editable">'.$Address->line3.'</span>' : '<br />'.$Address->line3;
             }
             if(!empty($Address->city) || $format) {
                 $output .= $format ? '<br /><span data-parent="'.$Address->address_type.'" data-name="city" class="editable">'.$Address->city.'</span>' : '<br />'.$Address->city;
                 if(!empty($Address->state_code)) { $output .= ','; }
             }
             if(!empty($Address->state_code) || $format) {
                 $output .= $format ? ' <span data-parent="'.$Address->address_type.'" data-name="state_code" class="editable">'.$Address->state_code.'</span>' : ' '.$Address->state_code;
             }
             if(!empty($Address->postal_code) || $format) {
                 $output .= $format ? ' <span data-parent="'.$Address->address_type.'" data-name="postal_code" class="editable">'.$Address->postal_code.'</span>' : ' '.$Address->postal_code;
                 if(!empty($Address->sub_postal_code)) {
                     $output .= $format ? '-<span data-parent="'.$Address->address_type.'" data-name="sub_postal_code" title="Sub-Postal Code" class="editable">'.$Address->sub_postal_code.'</span>' : '-'.$Address->sub_postal_code;
                 }
             }
             if(!empty($Address->country_code) || $format) {
                 $output .= $format ? '<br /><span data-parent="'.$Address->address_type.'" data-name="country_code" class="editable">'.strtoupper($Address->country_code).'</span>' : '<br />'.strtoupper($Address->country_code);
             }
         }
         return $output;
     }
KWSContact::getEmail () private
Definition at line 508 of file class.kwscontact.php.
{
         return isset($this->email_addresses[0]) ? $this->email_addresses[0]->email_address : false;
     }
KWSContact::getLabel ($key)
Definition at line 312 of file class.kwscontact.php.
{
         switch($key) {
             case 'id':
                 return 'ID';
                 break;
             case 'email_addresses':
                 return 'Email Address';
                 break;
             case 'line1': return 'Address'; break;
             case 'line2': return 'Address Line 2'; break;
             case 'line3': return 'Address Line 3'; break;
         }
         $key = ucwords(preg_replace('/\_/ism', ' ', $key));
         $key = preg_replace('/Addr([0-9])/', __('Address $1', 'constant-contact-api'), $key);
         $key = preg_replace('/Field([0-9])/', __('Field $1', 'constant-contact-api'), $key);
         return $key;
     }
KWSContact::is_editable ($key, $check_status = true)
Definition at line 333 of file class.kwscontact.php.
{
         return !in_array($key, $this::$read_only) && (!$check_status || ($check_status && $this->status !== 'NON_SUBSCRIBER'));
     }
KWSContact::prepare (array $contact_array, $add = false) private
Clean and parse an array of contact details to be in CTCT format.
The method filters out any data not allowed by Constant Contact, so you don't need to worry about having just the right details.
It converts email, email_address and user_email into the proper email_addresses array so you don't have to.
Parameters
array $contact_array Contact information.
boolean $add [description]
Returns
[type] [description]
Only allow permitted data in the Contact array
Definition at line 102 of file class.kwscontact.php.
Referenced by __construct().
{
         $defaults = array(
             'id' => NULL,
             'status' => NULL,
             'name' => NULL,
             'first_name' => NULL,
             'middle_name' => NULL,
             'last_name' => NULL,
             'source' => NULL,
             'email_addresses' => array(),
                 'email' => NULL,
                 'email_address' => NULL,
                 'user_email' => NULL,
             'prefix_name' => NULL,
             'job_title' => NULL,
             'addresses' => array(),
                 'address' => NULL,
                 'address_line1' => NULL,
                 'address_line2' => NULL,
                 'address_line3' => NULL,
                 'address_city' => NULL,
                 'address_state_code' => NULL,
                 'address_state_name' => NULL,
                 'address_country_code' => NULL,
                 'address_postal_code' => NULL,
                 'address_sub_postal_code' => NULL,
             'notes' => array(),
             'company_name' => NULL,
             'home_phone' => NULL,
             'work_phone' => NULL,
             'cell_phone' => NULL,
             'fax' => NULL,
             'custom_fields' => array(),
             'lists' => array(),
             'source_details' => CTCT_APIKEY,
         );
         $Contact = wp_parse_args( $contact_array, $defaults );
        # r($contact_array);
        # r($Contact);
         foreach($Contact as $k => $v) {
             /** Only allow permitted data in the Contact array */
             if(!array_key_exists($k, $defaults)) {
                 // @todo: Add logging notice.
                 unset($Contact[$k]);
             }
             switch($k) {
                 case 'user_email':
                     if(!empty($v)) {
                         $Contact['email'] = $Contact['user_email'];
                     }
                     unset($Contact['user_email']);
                     break;
                 case 'name':
                     $Contact = $this->prepareName($Contact);
                     unset($Contact['name']);
                     break;
                 case 'CustomField1':
                 case 'CustomField2':
                 case 'CustomField3':
                 case 'CustomField4':
                 case 'CustomField5':
                 case 'CustomField6':
                 case 'CustomField7':
                 case 'CustomField8':
                 case 'CustomField9':
                 case 'CustomField10':
                 case 'CustomField11':
                 case 'CustomField12':
                 case 'CustomField13':
                 case 'CustomField14':
                 case 'CustomField15':
                     $Contact['custom_fields'][] = array('name' => $k, 'value' => $v);
                     unset($Contact[$k]);
                     break;
                 case 'address_line1':
                 case 'address_line2':
                 case 'address_line3':
                 case 'address_city':
                 case 'address_state_code':
                 case 'address_state_name':
                 case 'address_country_code':
                 case 'address_postal_code':
                 case 'address_sub_postal_code':
                     $Contact['address'][str_replace('address_', '', $k)] = $v;
                     unset($Contact[$k]);
                     break;
             }
         }
         if(!empty($Contact['email_address']) && empty($Contact['email_addresses'])) {
             $Contact['email_addresses'] = array($Contact['email_address']);
         }
         unset($Contact['email_address']);
         if(!empty($Contact['email']) && empty($Contact['email_addresses'])) {
             $Contact['email_addresses'] = array($Contact['email']);
         }
         unset($Contact['email']);
         $Contact['email_addresses'] = (array)$Contact['email_addresses'];
         if(empty($Contact['email_addresses'])) {
             return new WP_Error('no_email_address', 'There was no email defined.', $Contact);
         }
         foreach($Contact['email_addresses'] as &$email_address) {
             if(is_email( $email_address )) {
                 $email_address= array('email_address' => $email_address);
             }
             $email_address = EmailAddress::create($email_address);
         }
         if(!empty($Contact['address']) && empty($Contact['addresses'])) {
             $Contact['address'] = $this->prepareAddress($Contact['address']);
             $Contact['addresses'] = array($Contact['address']);
         }
         unset($Contact['address']);
         if(!empty($Contact['addresses'])) {
             $Contact['addresses'] = (array)$Contact['addresses'];
             foreach($Contact['addresses'] as $key => &$address) {
                 $check_address = $address;
                 foreach($check_address as $k => $v) {
                     if(empty($v)) {
                         unset($check_address[$k]);
                     }
                 }
                 if(empty($check_address)) {
                     unset($address, $Contact['addresses'][$key]);
                     continue;
                 }
                 $address['address_type'] = strtoupper($address['address_type']);
                 if(!in_array($address['address_type'], array('PERSONAL', 'BUSINESS', 'UNKNOWN'))) {
                     $address['address_type'] = 'PERSONAL';
                 }
                 $address = Address::create($this->prepareAddress((array)$address));
             }
             if(empty($Contact['addresses'])) {
                 unset($Contact['addresses']);
             }
         }
         if(isset($Contact['notes'])) {
             $Contact['notes'] = (array)$Contact['notes'];
             foreach ($Contact['notes'] as &$note) {
                 $note = is_array($note) ? $note : array('note' => $note);
                 $note = Note::create($note);
             }
         }
         if(isset($Contact['custom_fields'])) {
             $Contact['custom_fields'] = (array)$Contact['custom_fields'];
             foreach ($Contact['custom_fields'] as &$custom_field) {
                 $custom_field = CustomField::create($custom_field);
             }
         }
         if(isset($Contact['lists'])) {
             $Contact['lists'] = (array)$Contact['lists'];
             foreach ($Contact['lists'] as &$contact_list) {
                 if(is_numeric( $contact_list )) {
                     $contact_list = array('id' => (string)$contact_list);
                 }
                 $contact_list = ContactList::create($contact_list);
             }
         }
         if($add || !in_array($Contact['status'], array('ACTIVE', 'UNCONFIRMED', 'OPTOUT', 'REMOVED', 'NON_SUBSCRIBER', 'VISITOR'))) {
             unset($Contact['status']);
         }
         if($add) {
             unset($Contact['id'], $Contact['confirmed']);
         }
         return $Contact;
     }
KWSContact::prepareAddress (array $address) private
Definition at line 60 of file class.kwscontact.php.
{
         return wp_parse_args($address, array('line1' => '', 'line2' => '', 'line3' => '', 'city' => '', 'address_type' => '', 'state_code' => '', 'state_name' => '', 'country_code' => '', 'country_name' => '', 'postal_code' => '', 'sub_postal_code' => ''));
     }
KWSContact::prepareName ($contact_array, $key = 'name') private
Split a full name into pieces.
Used for comment form submissions.
Parameters
array $contact_array Array of contact data
Returns
array Array with a better name structure
Definition at line 69 of file class.kwscontact.php.
{
         if(!function_exists('ctct_parse_name')) {
             include_once(CTCT_DIR_PATH.'lib/nameparse.php');
         }
         if(!isset($contact_array[$key])) { return $contact_array; }
         $name = ctct_parse_name($contact_array[$key]);
         if(isset($name['first']) && empty($contact_array['first_name'])) {
             $contact_array['first_name'] = $name['first'];
         }
         if(isset($name['middle']) && empty($contact_array['middle_name'])) { $contact_array['middle_name'] = $name['middle']; }
         if(isset($name['last']) && empty($contact_array['last_name'])) { $contact_array['last_name'] = $name['last']; }
         return $contact_array;
     }
KWSContact::set ($key, $value)
Definition at line 337 of file class.kwscontact.php.
{
         if(!$this->is_editable(strtolower($key), false)) { return false; }
         switch(strtolower($key)) {
             case 'email_addresses':
                 $this->email_addresses[0]->email_address = $value;
                 break;
             case 'notes':
                 if(isset($this->notes[0]) && is_object($this->notes[0])) {
                     $this->notes[0]->note = $value;
                 } else {
                     $this->addNote($value);
                 }
                 break;
             case (preg_match('/^personal_/ism', $key) ? true : false):
                 $key = strtolower(str_ireplace('personal_', '', $key));
                 $this->addresses[0]->{$key} = $value;
                 break;
             case (preg_match('/^business_/ism', $key) ? true : false):
                 $key = strtolower(str_ireplace('business_', '', $key));
                 $this->addresses[1]->{$key} = $value;
                 break;
             case (preg_match('/^customfield([0-9]+)/ism', $key, $matches) ? true : false):
                 // First, check whether it already exists.
                 foreach((array)$this->custom_fields as $customfield) {
                     if(strtolower($customfield->name) === strtolower($key)) {
                         $customfield->value = $value;
                         return true;
                     }
                 }
                 $this->custom_fields = (array)$this->custom_fields;
                 // Otherwise, create it.
                 $this->custom_fields[] = CustomField::create(array(
                     'name' => 'CustomField'.$matches[1],
                     'value' => $value
                 ));
                 break;
             default:
                 $this->{$key} = $value;
                 break;
         }
         return true;
     }
KWSContact::update ($new_contact_array)
Definition at line 45 of file class.kwscontact.php.
{
         $existing_contact = wp_clone($this);
         $new_contact = new KWSContact($new_contact_array, true);
         unset($new_contact->id, $new_contact->status, $new_contact->source, $new_contact->source_details);
         foreach($new_contact as $k => $v) {
             $existing_contact->{$k} = $v;
         }
         return $existing_contact;
     }
Field Documentation
KWSContact::$read_only = array('created_date', 'status', 'modified_date', 'id', 'confirmed', 'source', 'source_details', 'opt_out_date', 'opt_in_date', 'confirm_status') static private
Definition at line 14 of file class.kwscontact.php.
The documentation for this class was generated from the following file:
class.kwscontact.php