Constant Contact for WordPress: Ctct\Services\CampaignTrackingService Class Reference
Ctct\Services\CampaignTrackingService Class Reference
Public Member Functions
getBounces ($accessToken, $campaign_id, Array $params=null)
Get a result set of bounces for a given campaign.
getClicks ($accessToken, $campaign_id, Array $params=null)
Get clicks for a given campaign.
getForwards ($accessToken, $campaign_id, Array $params=null)
Get forwards for a given campaign.
getOpens ($accessToken, $campaign_id, Array $params=null)
Get opens for a given campaign.
getSends ($accessToken, $campaign_id, Array $params=null)
Get sends for a given campaign.
getUnsubscribes ($accessToken, $campaign_id, Array $params=null)
Get unsubscribes for a given campaign.
getSummary ($accessToken, $campaign_id)
Get a summary of reporting data for a given campaign.
Public Member Functions inherited from Ctct\Services\BaseService
__construct ($apiKey, $restClient=null)
Constructor with the option to to supply an alternative rest client to be used.
buildUrl ($url, $queryParams=null)
Build a url from the base url and query parameters array.
getRestClient ()
Get the rest client being used by the service.
setRestClient (RestClientInterface $restClient)
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Services\BaseService
static getHeaders ($accessToken)
Helper function to return required headers for making an http request with constant contact.
Protected Attributes inherited from Ctct\Services\BaseService
$restClient
$apiKey
Detailed Description
Definition at line 22 of file CampaignTrackingService.php.
Member Function Documentation
Ctct\Services\CampaignTrackingService::getBounces ($accessToken, $campaign_id, Array $params = null)
Get a result set of bounces for a given campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
string $campaign_id - Campaign id
array $params - query parameters to be appended to the request
Returns
ResultSet - Containing a results array of BounceActivity
Definition at line 32 of file CampaignTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\BounceActivity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_tracking_bounces'), $campaign_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $bounces = array();
         foreach ($body['results'] as $bounceActivity) {
             $contacts[] = BounceActivity::create($bounceActivity);
         }
         return new ResultSet($contacts, $body['meta']);
     }
Ctct\Services\CampaignTrackingService::getClicks ($accessToken, $campaign_id, Array $params = null)
Get clicks for a given campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
string $campaign_id - Campaign id
array $param - query params to be appended to request
Returns
TrackingActivity - Containing a results array of ClickActivity
Definition at line 55 of file CampaignTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\ClickActivity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_tracking_clicks'), $campaign_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $clicks = array();
         foreach ($body['results'] as $click_activity) {
             $clicks[] = ClickActivity::create($click_activity);
         }
         return new ResultSet($clicks, $body['meta']);
     }
Ctct\Services\CampaignTrackingService::getForwards ($accessToken, $campaign_id, Array $params = null)
Get forwards for a given campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
string $campaign_id - Campaign id
array $param - query param to be appended to request
Returns
ResultSet - Containing a results array of ForwardActivity
Definition at line 80 of file CampaignTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\ForwardActivity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_tracking_forwards'), $campaign_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $forwards = array();
         foreach ($body['results'] as $forward_activity) {
             $forwards[] = ForwardActivity::create($forward_activity);
         }
         return new ResultSet($forwards, $body['meta']);
     }
Ctct\Services\CampaignTrackingService::getOpens ($accessToken, $campaign_id, Array $params = null)
Get opens for a given campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
string $campaign_id - Campaign id
array $params - query params to be appended to request
Returns
ResultSet - Containing a results array of OpenActivity
Definition at line 104 of file CampaignTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\OpenActivity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_tracking_opens'), $campaign_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $opens = array();
         foreach ($body['results'] as $open_activity) {
             $opens[] = OpenActivity::create($open_activity);
         }
         return new ResultSet($opens, $body['meta']);
     }
Ctct\Services\CampaignTrackingService::getSends ($accessToken, $campaign_id, Array $params = null)
Get sends for a given campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
string $campaign_id - Campaign id
Array $param - query params to be appended to request
Returns
TrackingActivity - Containing a results array of SendActivity
Definition at line 128 of file CampaignTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\SendActivity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_tracking_sends'), $campaign_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $sends = array();
         foreach ($body['results'] as $send_activity) {
             $sends[] = SendActivity::create($send_activity);
         }
         return new ResultSet($sends, $body['meta']);
     }
Ctct\Services\CampaignTrackingService::getSummary ($accessToken, $campaign_id)
Get a summary of reporting data for a given campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $campaign_id - Campaign id
Returns
TrackingSummary
Definition at line 175 of file CampaignTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\TrackingSummary\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_tracking_summary'), $campaign_id);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         return TrackingSummary::create(json_decode($response->body, true));
     }
Ctct\Services\CampaignTrackingService::getUnsubscribes ($accessToken, $campaign_id, Array $params = null)
Get unsubscribes for a given campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
string $campaign_id - Campaign id
array $param - query params to be appended to request
Returns
ResultSet - Containing a results array of UnsubscribeActivity
Definition at line 152 of file CampaignTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\UnsubscribeActivity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_tracking_unsubscribes'), $campaign_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $optOuts = array();
         foreach ($body['results'] as $opt_out_activity) {
             $optOuts[] = UnsubscribeActivity::create($opt_out_activity);
         }
         return new ResultSet($optOuts, $body['meta']);
     }
The documentation for this class was generated from the following file:
CampaignTrackingService.php