Constant Contact for WordPress: Ctct\Services\ActivityService Class Reference
Ctct\Services\ActivityService Class Reference
Public Member Functions
getActivities ($accessToken, array $params=array())
Get an array of activities.
getActivity ($accessToken, $activityId)
Get an array of activities.
createAddContactsActivity ($accessToken, AddContacts $addContacts)
Create an Add Contacts Activity.
createAddContactsActivityFromFile ($accessToken, $fileName, $contents, $lists)
Create an Add Contacts Activity from a file.
addClearListsActivity ($accessToken, array $lists)
Create a Clear Lists Activity.
addExportContactsActivity ($accessToken, ExportContacts $exportContacts)
Create an Export Contacts Activity.
addRemoveContactsFromListsActivity ($accessToken, array $emailAddresses, array $lists)
Create a Remove Contacts From Lists Activity.
addRemoveContactsFromListsActivityFromFile ($accessToken, $fileName, $contents, $lists)
Create an Remove Contacts Activity from a file.
Public Member Functions inherited from Ctct\Services\BaseService
__construct ($apiKey, $restClient=null)
Constructor with the option to to supply an alternative rest client to be used.
buildUrl ($url, array $queryParams=null)
Build a URL from a base url and optional array of query parameters to append to the url.
getRestClient ()
Get the rest client being used by the service.
setRestClient (RestClientInterface $restClient)
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Services\BaseService
static getHeaders ($accessToken)
Helper function to return required headers for making an http request with constant contact.
Protected Attributes inherited from Ctct\Services\BaseService
$restClient
$apiKey
Detailed Description
Definition at line 20 of file ActivityService.php.
Member Function Documentation
Ctct\Services\ActivityService::addClearListsActivity ($accessToken, array $lists)
Create a Clear Lists Activity.
Parameters
string $accessToken - Constant Contact OAuth2 access token
array $lists - Array of list id's to be cleared
Returns
array - Array of all Activity
Definition at line 117 of file ActivityService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Activities\Activity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.clear_lists_activity');
         $url = $this->buildUrl($baseUrl);
         $payload = array('lists' => $lists);
         $response = parent::getRestClient()->post($url, parent::getHeaders($accessToken), json_encode($payload));
         return Activity::create(json_decode($response->body, true));
     }
Ctct\Services\ActivityService::addExportContactsActivity ($accessToken, ExportContacts $exportContacts)
Create an Export Contacts Activity.
Parameters
string $accessToken - Constant Contact OAuth2 access token
ExportContacts $exportContacts
Returns
array - Array of all ActivitySummaryReports
Definition at line 132 of file ActivityService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Activities\Activity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.export_contacts_activity');
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->post($url, parent::getHeaders($accessToken), json_encode($exportContacts));
         return Activity::create(json_decode($response->body, true));
     }
Ctct\Services\ActivityService::addRemoveContactsFromListsActivity ($accessToken, array $emailAddresses, array $lists)
Create a Remove Contacts From Lists Activity.
Parameters
string $accessToken - Constant Contact OAuth2 access token
array $emailAddresses - array of email addresses to remove
array $lists - array of lists to remove the provided email addresses from
Returns
array - Array of all ActivitySummaryReports
Definition at line 147 of file ActivityService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Activities\Activity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.remove_from_lists_activity');
         $url = $this->buildUrl($baseUrl);
         $payload = array(
             'import_data' => array(),
             'lists' => $lists
         );
         foreach ($emailAddresses as $emailAddress) {
             $payload['import_data'][] = array('email_addresses' => array($emailAddress));
         }
         $response = parent::getRestClient()->post($url, parent::getHeaders($accessToken), json_encode($payload));
         return Activity::create(json_decode($response->body, true));
     }
Ctct\Services\ActivityService::addRemoveContactsFromListsActivityFromFile ($accessToken, $fileName, $contents, $lists)
Create an Remove Contacts Activity from a file.
Valid file types are txt, csv, xls, xlsx
Parameters
string $accessToken - Constant Contact OAuth2 access token
string $fileName - The name of the file (ie: contacts.csv)
string $contents - The contents of the file
string $lists - Comma separated list of ContactList id' to add the contacts too
Returns
Definition at line 172 of file ActivityService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Activities\Activity\create(), and Ctct\Util\Config\get().
     {
         $eol = "\r\n";
         $data = '';
         $boundary=md5(time());
         $data .= '--' . $boundary . $eol;
         $data .= 'Content-Disposition: form-data; name="file_name"' . $eol;
         $data .= 'Content-Type: text/plain' . $eol . $eol;
         $data .= $fileName . $eol;
         $data .= '--' . $boundary . $eol;
         $data .= 'Content-Disposition: form-data; name="lists"' . $eol;
         $data .= 'Content-Type: text/plain' . $eol . $eol;
         $data .= $lists . $eol;
         $data .= '--' . $boundary . $eol;
         $data .= 'Content-Disposition: form-data; name="data"' . $eol . $eol;
         $data .= $contents . $eol;
         $data .= "--" . $boundary . "--" . $eol;
         $headers = array(
             "Authorization: Bearer {$accessToken}",
             "Content-Type: multipart/form-data; boundary={$boundary}"
         );
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.remove_from_lists_activity');
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->post($url, $headers, $data);
         return Activity::create(json_decode($response->body, true));
     }
Ctct\Services\ActivityService::createAddContactsActivity ($accessToken, AddContacts $addContacts)
Create an Add Contacts Activity.
Parameters
string $accessToken - Constant Contact OAuth2 access token
AddContacts $addContacts
Returns
array - Array of all ActivitySummaryReports
Definition at line 62 of file ActivityService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Activities\Activity\create(), Ctct\Util\Config\get(), and Ctct\Components\Activities\AddContacts\toJson().
     {
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.add_contacts_activity');
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->post($url, parent::getHeaders($accessToken), $addContacts->toJson());
         return Activity::create(json_decode($response->body, true));
     }
Ctct\Services\ActivityService::createAddContactsActivityFromFile ($accessToken, $fileName, $contents, $lists)
Create an Add Contacts Activity from a file.
Valid file types are txt, csv, xls, xlsx
Parameters
string $accessToken - Constant Contact OAuth2 access token
string $fileName - The name of the file (ie: contacts.csv)
string $contents - The contents of the file
string $lists - Comma separated list of ContactList id's to add the contacts to
Returns
Definition at line 78 of file ActivityService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Activities\Activity\create(), and Ctct\Util\Config\get().
     {
         $eol = "\r\n";
         $data = '';
         $boundary=md5(time());
         $data .= '--' . $boundary . $eol;
         $data .= 'Content-Disposition: form-data; name="file_name"' . $eol;
         $data .= 'Content-Type: text/plain' . $eol . $eol;
         $data .= $fileName . $eol;
         $data .= '--' . $boundary . $eol;
         $data .= 'Content-Disposition: form-data; name="lists"' . $eol;
         $data .= 'Content-Type: text/plain' . $eol . $eol;
         $data .= $lists . $eol;
         $data .= '--' . $boundary . $eol;
         $data .= 'Content-Disposition: form-data; name="data"' . $eol . $eol;
         $data .= $contents . $eol;
         $data .= "--" . $boundary . "--" . $eol;
         $headers = array(
             "Authorization: Bearer {$accessToken}",
             "Content-Type: multipart/form-data; boundary={$boundary}"
         );
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.add_contacts_activity');
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->post($url, $headers, $data);
         return Activity::create(json_decode($response->body, true));
     }
Ctct\Services\ActivityService::getActivities ($accessToken, array $params = array())
Get an array of activities.
Parameters
string $accessToken - Constant Contact OAuth2 access token
array $params - array of query parameters to be appended to the url
Returns
array - Array of all ActivitySummaryReports
Definition at line 28 of file ActivityService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Activities\Activity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.activities');
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $jsonResponse = json_decode($response->body, true);
         $activities = array();
         foreach ($jsonResponse as $activity) {
             $activities[] = Activity::create($activity);
         }
         return $activities;
     }
Ctct\Services\ActivityService::getActivity ($accessToken, $activityId)
Get an array of activities.
Parameters
string $accessToken - Constant Contact OAuth2 access token
string $activityId - Activity id
Returns
array - Array of all ActivitySummaryReports
Definition at line 48 of file ActivityService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Activities\Activity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') . sprintf(Config::get('endpoints.activity'), $activityId);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         return Activity::create(json_decode($response->body, true));
     }
The documentation for this class was generated from the following file:
ActivityService.php