Constant Contact for WordPress: Net_DNS_RR_TSIG Class Reference
Net_DNS_RR_TSIG Class Reference
Public Member Functions
Net_DNS_RR_TSIG (&$rro, $data, $offset= '')
rdatastr ()
rr_rdata ($packet, $offset)
error ()
Public Member Functions inherited from Net_DNS_RR
Net_DNS_RR ($rrdata)
& factory ($rrdata, $update_type= '')
& new_from_data ($name, $rrtype, $rrclass, $ttl, $rdlength, $data, $offset)
& new_from_string ($rrstring, $update_type= '')
& new_from_array ($rrarray)
display ()
string ()
rdatastr ()
rdata (&$packetORrdata, $offset= '')
rr_rdata (&$packet, $offset)
data (&$packet, $offset)
Data Fields
$name
$type
$class
$ttl
$rdlength
$rdata
$time_signed
$fudge
$mac_size
$mac
$original_id
$error
$other_len
$other_data
$key
Data Fields inherited from Net_DNS_RR
$name
$type
$class
$ttl
$rdlength
$rdata
Detailed Description
Definition at line 32 of file TSIG.php.
Member Function Documentation
Net_DNS_RR_TSIG::error ()
Definition at line 214 of file TSIG.php.
References $error, and Net_DNS\rcodesbyval().
Referenced by Net_DNS_RR_TSIG(), and rr_rdata().
     {
         if ($this->error != 0) {
             $rcode = Net_DNS::rcodesbyval($error);
         }
         return $rcode;
     }
Net_DNS_RR_TSIG::Net_DNS_RR_TSIG (& $rro, $data, $offset = '')
Definition at line 53 of file TSIG.php.
References $mac_size, Net_DNS_Packet\dn_expand(), error(), and Net_DNS_RR\rdata().
     {
         $this->name = $rro->name;
         $this->type = $rro->type;
         $this->class = $rro->class;
         $this->ttl = $rro->ttl;
         $this->rdlength = $rro->rdlength;
         $this->rdata = $rro->rdata;
         if ($offset) {
             if ($this->rdlength > 0) {
                 list($alg, $offset) = Net_DNS_Packet::dn_expand($data, $offset);
                 $this->algorithm = $alg;
                 $d = unpack("\@$offset/nth/Ntl/nfudge/nmac_size", $data);
                 $time_high = $d['th'];
                 $time_low = $d['tl'];
                 $this->time_signed = $time_low;
                 $this->fudge = $d['fudge'];
                 $this->mac_size = $d['mac_size'];
                 $offset += 10;
                 $this->mac = substr($data, $offset, $this->mac_size);
                 $offset += $this->mac_size;
                 $d = unpack("@$offset/noid/nerror/nolen", $data);
                 $this->original_id = $d['oid'];
                 $this->error = $d['error'];
                 $this->other_len = $d['olen'];
                 $offset += 6;
                 $odata = substr($data, $offset, $this->other_len);
                 $d = unpack('nodata_high/Nodata_low', $odata);
                 $this->other_data = $d['odata_low'];
             }
         } else {
             if (strlen($data) && preg_match('/^(.*)$/', $data, $regs)) {
                 $this->key = $regs[1];
             }
             $this->algorithm   = NET_DNS_DEFAULT_ALGORITHM;
             $this->time_signed = time();
             $this->fudge       = NET_DNS_DEFAULT_FUDGE;
             $this->mac_size    = 0;
             $this->mac         = '';
             $this->original_id = 0;
             $this->error       = 0;
             $this->other_len   = 0;
             $this->other_data  = '';
             // RFC 2845 Section 2.3
             $this->class = 'ANY';
         }
     }
Net_DNS_RR_TSIG::rdatastr ()
Definition at line 111 of file TSIG.php.
References $error, and $other_data.
     {
         $error = $this->error;
         if (! $error) {
             $error = 'UNDEFINED';
         }
         if (strlen($this->algorithm)) {
             $rdatastr = $this->algorithm . '. ' . $this->time_signed . ' ' .
                 $this->fudge . ' ';
             if ($this->mac_size && strlen($this->mac)) {
                 $rdatastr .= ' ' . $this->mac_size . ' ' . base64_encode($this->mac);
             } else {
                 $rdatastr .= ' 0 ';
             }
             $rdatastr .= ' ' . $this->original_id . ' ' . $error;
             if ($this->other_len && strlen($this->other_data)) {
                 $rdatastr .= ' ' . $this->other_data;
             } else {
                 $rdatastr .= ' 0 ';
             }
         } else {
             $rdatastr = '; no data';
         }
         return $rdatastr;
     }
Net_DNS_RR_TSIG::rr_rdata ($packet, $offset)
Definition at line 141 of file TSIG.php.
References $key, $mac, $rdata, Net_DNS\classesbyname(), Net_DNS_Packet\dn_comp(), and error().
     {
         $rdata = '';
         $sigdata = '';
         if (strlen($this->key)) {
             $key = $this->key;
             $key = ereg_replace(' ', '', $key);
             $key = base64_decode($key);
             $newpacket = $packet;
             $newoffset = $offset;
             array_pop($newpacket->additional);
             $newpacket->header->arcount--;
             $newpacket->compnames = array();
             /*
              * Add the request MAC if present (used to validate responses).
              */
             if (isset($this->request_mac)) {
                 $sigdata .= pack('H*', $this->request_mac);
             }
             $sigdata .= $newpacket->data();
             /*
              * Don't compress the record (key) name.
              */
             $tmppacket = new Net_DNS_Packet;
             $sigdata .= $tmppacket->dn_comp(strtolower($this->name), 0);
             $sigdata .= pack('n', Net_DNS::classesbyname(strtoupper($this->class)));
             $sigdata .= pack('N', $this->ttl);
             /*
              * Don't compress the algorithm name.
              */
             $tmppacket->compnames = array();
             $sigdata .= $tmppacket->dn_comp(strtolower($this->algorithm), 0);
             $sigdata .= pack('nN', 0, $this->time_signed);
             $sigdata .= pack('n', $this->fudge);
             $sigdata .= pack('nn', $this->error, $this->other_len);
             if (strlen($this->other_data)) {
                 $sigdata .= pack('nN', 0, $this->other_data);
             }
             $this->mac = mhash(MHASH_MD5, $sigdata, $key);
             $this->mac_size = strlen($this->mac);
             /*
              * Don't compress the algorithm name.
              */
             unset($tmppacket);
             $tmppacket = new Net_DNS_Packet;
             $rdata .= $tmppacket->dn_comp(strtolower($this->algorithm), 0);
             $rdata .= pack('nN', 0, $this->time_signed);
             $rdata .= pack('nn', $this->fudge, $this->mac_size);
             $rdata .= $this->mac;
             $rdata .= pack('nnn',$packet->header->id,
                     $this->error,
                     $this->other_len);
             if ($this->other_data) {
                 $rdata .= pack('nN', 0, $this->other_data);
             }
         }
         return $rdata;
     }
Field Documentation
Net_DNS_RR_TSIG::$class
Definition at line 37 of file TSIG.php.
Net_DNS_RR_TSIG::$error
Definition at line 46 of file TSIG.php.
Referenced by error(), and rdatastr().
Net_DNS_RR_TSIG::$fudge
Definition at line 42 of file TSIG.php.
Net_DNS_RR_TSIG::$key
Definition at line 49 of file TSIG.php.
Referenced by rr_rdata().
Net_DNS_RR_TSIG::$mac
Definition at line 44 of file TSIG.php.
Referenced by rr_rdata().
Net_DNS_RR_TSIG::$mac_size
Definition at line 43 of file TSIG.php.
Referenced by Net_DNS_RR_TSIG().
Net_DNS_RR_TSIG::$name
Definition at line 35 of file TSIG.php.
Net_DNS_RR_TSIG::$original_id
Definition at line 45 of file TSIG.php.
Net_DNS_RR_TSIG::$other_data
Definition at line 48 of file TSIG.php.
Referenced by rdatastr().
Net_DNS_RR_TSIG::$other_len
Definition at line 47 of file TSIG.php.
Net_DNS_RR_TSIG::$rdata
Definition at line 40 of file TSIG.php.
Referenced by rr_rdata().
Net_DNS_RR_TSIG::$rdlength
Definition at line 39 of file TSIG.php.
Net_DNS_RR_TSIG::$time_signed
Definition at line 41 of file TSIG.php.
Net_DNS_RR_TSIG::$ttl
Definition at line 38 of file TSIG.php.
Net_DNS_RR_TSIG::$type
Definition at line 36 of file TSIG.php.
The documentation for this class was generated from the following file:
TSIG.php