Constant Contact for WordPress: ContactsCollection Class Reference
ContactsCollection Class Reference
Public Member Functions
__construct ($CTCTRequest)
ContactsCollection constructor.
getContacts ($page=null)
getContactDetails ($url)
Get detailed Contact object for a given contact.
getContactEvents ($url, $eventType)
Get events for a given Contact.
addContact (Contact $Contact)
Add a contact to account.
updateContact (Contact $Contact)
Update a Contact.
deleteContact ($url)
Delete a Contact.
searchContactsByEmail ($extension)
Search for Contacts by email addresses.
searchContactsByLastUpdate ($List, $date)
Search for contacts that have been updated since a specific date.
Public Member Functions inherited from Collection
__construct (CTCTRequest $CTCTRequest, $collectionUri)
Collection constructor.
Data Fields
$CTCTRequest
$uri
Data Fields inherited from Collection
$CTCTRequest
$uri
Detailed Description
Definition at line 137 of file Collections.php.
Constructor & Destructor Documentation
ContactsCollection::__construct ($CTCTRequest)
ContactsCollection constructor.
Parameters
CTCTRequest $CTCTRequest
Definition at line 145 of file Collections.php.
References $CTCTRequest.
{
         parent::__construct($CTCTRequest, '/ws/customers/'.$CTCTRequest->username.'/contacts');
     }
Member Function Documentation
ContactsCollection::addContact (Contact $Contact)
Add a contact to account.
Parameters
Contact $Contact - Contact object to add
Returns
Contact
Definition at line 200 of file Collections.php.
References Contact\createStruct(), Contact\createXml(), and CTCTRequest\makeRequest().
{
         $contactXml = $Contact->createXml();
         $response = $this->CTCTRequest->makeRequest($this->uri, 'POST', $contactXml);
         $parsedResponse = simplexml_load_string($response['xml']);
         return new Contact(Contact::createStruct($parsedResponse));
     }
ContactsCollection::deleteContact ($url)
Delete a Contact.
Parameters
string $url - url to a contact
Returns
bool - true is successful, else false
Definition at line 223 of file Collections.php.
References CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'DELETE');
         return ($response['info']['http_code'] == 204) ? true : false;
     }
ContactsCollection::getContactDetails ($url)
Get detailed Contact object for a given contact.
Parameters
string $url - url of contact to get details for
Returns
Contact
Definition at line 170 of file Collections.php.
References Contact\createStruct(), and CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $parsedResponse = simplexml_load_string($response['xml']);
         return new Contact(Contact::createStruct($parsedResponse));
     }
ContactsCollection::getContactEvents ($url, $eventType)
Get events for a given Contact.
Parameters
string url - url to access events from
string $eventType - event type to pull
Returns
array
Definition at line 182 of file Collections.php.
References CampaignEvent\createStruct(), Utility\findNextLink(), and CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $parsedResponse = simplexml_load_string($response['xml']);
         $contactEvents = array('events' => array(), 'nextLink' => '');
         if($parsedResponse->entry){
             foreach($parsedResponse->entry as $entry){
                 $contactEvents['events'][] = new CampaignEvent(CampaignEvent::createStruct($entry, $eventType));
             }
         }
         $contactEvents['nextLink'] = Utility::findNextLink($parsedResponse);
         return $contactEvents;
     }
ContactsCollection::getContacts ($page = null)
Parameters
string $page - optional link to a contacts page, default is first page
Returns
array
Definition at line 153 of file Collections.php.
References Contact\createStruct(), Utility\findNextLink(), and CTCTRequest\makeRequest().
Referenced by searchContactsByLastUpdate().
{
         $page = ($page) ? $this->CTCTRequest->baseUri.$page : $this->uri;
         $contactsCollection = array('contacts' => array(), 'nextLink' => '');
         $response = $this->CTCTRequest->makeRequest($page, 'GET');
         $parsedResponse = simplexml_load_string($response['xml']);
         foreach ( $parsedResponse->entry as $entry){
             $contactsCollection['contacts'][] = new Contact(Contact::createStruct($entry));
         }
         $contactsCollection['nextLink'] = Utility::findNextLink($parsedResponse);
         return $contactsCollection;
     }
ContactsCollection::searchContactsByEmail ($extension)
Search for Contacts by email addresses.
Parameters
mixed extension - string to be appended to url
Returns
- array of found contacts, otherwise returns false
Definition at line 233 of file Collections.php.
References Contact\createStruct(), and CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($this->uri.$extension, 'GET');
         $parsedResponse = simplexml_load_string($response['xml']);
         $returnArray = array();
         if ($parsedResponse->entry){
             foreach ($parsedResponse->entry as $contact){
                 $returnArray[] = new Contact(Contact::createStruct($contact));
             }
         } else { $returnArray = false; }
         return $returnArray;
     }
ContactsCollection::searchContactsByLastUpdate ($List, $date)
Search for contacts that have been updated since a specific date.
Parameters
string $date
ContactList $List
Returns
array
Definition at line 251 of file Collections.php.
References CTCTException\generateError(), and getContacts().
{
         $listTypes = array('Active', 'Removed', 'Do Not Mail');
         $ext = '';
         try{
             $ext .= str_replace('https://api.constantcontact.com', '',$this->uri).'?updatedsince='.$date;
             if(in_array($List->name, $listTypes)){$ext .= '&listtype='.strtolower(str_replace(' ', '-', $List->name));}
             else{$ext .= '&listid='.substr(strrchr($List->id, "/"), 1);}
         } catch (CTCTException $e){
             $e->generateError();
         }
         return $this->getContacts($ext);
     }
ContactsCollection::updateContact (Contact $Contact)
Update a Contact.
Parameters
Contact $Contact
Returns
bool - true is successful, else false
Definition at line 212 of file Collections.php.
References Contact\createXml(), and CTCTRequest\makeRequest().
{
         $contactXml = $Contact->createXml();
         $response = $this->CTCTRequest->makeRequest($this->CTCTRequest->baseUri.$Contact->link, 'PUT', $contactXml);
         return ($response['info']['http_code'] == 204) ? true : false;
     }
Field Documentation
ContactsCollection::$CTCTRequest
Definition at line 138 of file Collections.php.
Referenced by __construct().
ContactsCollection::$uri
Definition at line 139 of file Collections.php.
The documentation for this class was generated from the following file:
Collections.php