Constant Contact for WordPress: Ctct\Components\Contacts\ContactList Class Reference
Ctct\Components\Contacts\ContactList Class Reference
Public Member Functions
__construct ($list_id=null)
toJson ()
Static Public Member Functions
static create (array $props)
Factory method to create a ContactList object from an array.
Data Fields
$id
$name
$status
$contact_count
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Components\Component
static getValue (array $array, $item, $default=null)
Get the requested value from an array, or return the default.
Detailed Description
Definition at line 13 of file ContactList.php.
Constructor & Destructor Documentation
Ctct\Components\Contacts\ContactList::__construct ($list_id = null)
Definition at line 39 of file ContactList.php.
     {
         if (!is_null($list_id)) {
             $this->id = $list_id;
         }
         return $this;
     }
Member Function Documentation
static Ctct\Components\Contacts\ContactList::create (array $props) static
Factory method to create a ContactList object from an array.
Parameters
array $props - Associative array of initial properties to set
Returns
ContactList
Definition at line 53 of file ContactList.php.
Referenced by Ctct\Services\ListService\addList(), Ctct\Components\Contacts\Contact\create(), Ctct\Components\EmailMarketing\Campaign\create(), Ctct\Services\ListService\getList(), Ctct\Services\ListService\getLists(), and Ctct\Services\ListService\updateList().
     {
         $contact_list = new ContactList();
         $contact_list->id = parent::getValue($props, "id");
         $contact_list->name = parent::getValue($props, "name");
         $contact_list->status = parent::getValue($props, "status");
         $contact_list->contact_count = parent::getValue($props, "contact_count");
         return $contact_list;
     }
Ctct\Components\Contacts\ContactList::toJson ()
Definition at line 63 of file ContactList.php.
Referenced by Ctct\Services\ListService\addList(), and Ctct\Services\ListService\updateList().
     {
         return json_encode($this);
     }
Field Documentation
Ctct\Components\Contacts\ContactList::$contact_count
Definition at line 37 of file ContactList.php.
Ctct\Components\Contacts\ContactList::$id
Definition at line 19 of file ContactList.php.
Ctct\Components\Contacts\ContactList::$name
Definition at line 25 of file ContactList.php.
Ctct\Components\Contacts\ContactList::$status
Definition at line 31 of file ContactList.php.
The documentation for this class was generated from the following file:
ContactList.php