Constant Contact for WordPress: Net_DNS_Packet Class Reference
Net_DNS_Packet Class Reference
Public Member Functions
Net_DNS_Packet ($debug=false)
Initalizes a Net_DNS_Packet object.
buildQuestion ($name, $type= 'A', $class= 'IN')
Adds a DNS question to the DNS packet.
parse ($data)
Parses a DNS packet returned by a DNS server.
data ()
Build a packet from a Packet object hierarchy.
dn_comp ($name, $offset)
DNS packet compression method.
dn_expand ($packet, $offset)
DNS packet decompression method.
label_extract ($packet, $offset)
DNS packet decompression method.
parse_question ($data, $offset)
Parses the question section of a packet.
parse_rr ($data, $offset)
Parses a resource record section of a packet.
display ()
Prints out the packet in a human readable formatted string.
string ()
Builds a human readable formatted string representing a packet.
Data Fields
$debug
debugging flag
$header
A packet Header object.
$compnames
A hash of compressed labels.
$answerfrom
The origin of the packet, if the packet is a server response.
$answersize
The size of the answer packet, if the packet is a server response.
$question
An array of Net_DNS_Question objects.
$answer
An array of Net_DNS_RR ANSWER objects.
$authority
An array of Net_DNS_RR AUTHORITY objects.
$additional
An array of Net_DNS_RR ADDITIONAL objects.
Detailed Description
Definition at line 34 of file Packet.php.
Member Function Documentation
Net_DNS_Packet::buildQuestion ($name, $type = 'A', $class = 'IN')
Adds a DNS question to the DNS packet.
Parameters
string $name The name of the record to query
string $type The type of record to query
string $class The class of record to query
See Also
Net_DNS::typesbyname(), Net_DNS::classesbyname()
Definition at line 159 of file Packet.php.
     {
         $this->header = new Net_DNS_Header();
         $this->header->qdcount = 1;
         $this->question[0] = new Net_DNS_Question($name, $type, $class);
         $this->answer = null;
         $this->authority = null;
         $this->additional = null;
         /* Do not print question packet
         if ($this->debug) {
             $this->display();
         }
         */
     }
Net_DNS_Packet::data ()
Build a packet from a Packet object hierarchy.
Builds a valid DNS packet suitable for sending to a DNS server or resolver client containing all of the data in the packet hierarchy.
Returns
string A binary string containing a DNS Packet
Definition at line 317 of file Packet.php.
     {
         $data = $this->header->data();
         for ($ctr = 0; $ctr < $this->header->qdcount; $ctr++) {
             $data .= $this->question[$ctr]->data($this, strlen($data));
         }
         for ($ctr = 0; $ctr < $this->header->ancount; $ctr++) {
             $data .= $this->answer[$ctr]->data($this, strlen($data));
         }
         for ($ctr = 0; $ctr < $this->header->nscount; $ctr++) {
             $data .= $this->authority[$ctr]->data($this, strlen($data));
         }
         for ($ctr = 0; $ctr < $this->header->arcount; $ctr++) {
             $data .= $this->additional[$ctr]->data($this, strlen($data));
         }
         return $data;
     }
Net_DNS_Packet::display ()
Prints out the packet in a human readable formatted string.
Definition at line 587 of file Packet.php.
References string().
     {
         echo $this->string();
     }
Net_DNS_Packet::dn_comp ($name, $offset)
DNS packet compression method.
Returns a domain name compressed for a particular packet object, to be stored beginning at the given offset within the packet data. The name will be added to a running list of compressed domain names for future use.
Parameters
string $name The name of the label to compress
integer $offset The location offset in the packet to where the label will be stored.
Returns
string $compname A binary string containing the compressed label.
See Also
Net_DNS_Packet::dn_expand()
Definition at line 357 of file Packet.php.
Referenced by Net_DNS_RR_TSIG\rr_rdata().
     {
         $names = explode('.', $name);
         $compname = '';
         while (count($names)) {
             $dname = join('.', $names);
             if (isset($this->compnames[$dname])) {
                 $compname .= pack('n', 0xc000 | $this->compnames[$dname]);
                 break;
             }
             $this->compnames[$dname] = $offset;
             $first = array_shift($names);
             $length = strlen($first);
             $compname .= pack('Ca*', $length, $first);
             $offset += $length + 1;
         }
         if (! count($names)) {
             $compname .= pack('C', 0);
         }
         return $compname;
     }
Net_DNS_Packet::dn_expand ($packet, $offset)
DNS packet decompression method.
Expands the domain name stored at a particular location in a DNS packet. The first argument is a variable containing the packet data. The second argument is the offset within the packet where the (possibly) compressed domain name is stored.
Parameters
string $packet The packet data
integer $offset The location offset in the packet of the label to decompress.
Returns
array Returns a list of type array($name, $offset) where $name is the name of the label which was decompressed and $offset is the offset of the next field in the packet. Returns array(null, null) on error
Definition at line 398 of file Packet.php.
Referenced by Net_DNS_RR_CNAME\Net_DNS_RR_CNAME(), Net_DNS_RR_MX\Net_DNS_RR_MX(), Net_DNS_RR_NAPTR\Net_DNS_RR_NAPTR(), Net_DNS_RR_NS\Net_DNS_RR_NS(), Net_DNS_RR_PTR\Net_DNS_RR_PTR(), Net_DNS_RR_SOA\Net_DNS_RR_SOA(), Net_DNS_RR_SRV\Net_DNS_RR_SRV(), Net_DNS_RR_TSIG\Net_DNS_RR_TSIG(), parse_question(), and parse_rr().
     {
         $packetlen = strlen($packet);
         $int16sz = 2;
         $name = '';
         while (1) {
             if ($packetlen < ($offset + 1)) {
                 return array(null, null);
             }
             $a = unpack("@$offset/Cchar", $packet);
             $len = $a['char'];
             if ($len == 0) {
                 $offset++;
                 break;
             } else if (($len & 0xc0) == 0xc0) {
                 if ($packetlen < ($offset + $int16sz)) {
                     return array(null, null);
                 }
                 $ptr = unpack("@$offset/ni", $packet);
                 $ptr = $ptr['i'];
                 $ptr = $ptr & 0x3fff;
                 $name2 = Net_DNS_Packet::dn_expand($packet, $ptr);
                 if (is_null($name2[0])) {
                     return array(null, null);
                 }
                 $name .= $name2[0];
                 $offset += $int16sz;
                 break;
             } else {
                 $offset++;
                 if ($packetlen < ($offset + $len)) {
                     return array(null, null);
                 }
                 $elem = substr($packet, $offset, $len);
                 $name .= $elem . '.';
                 $offset += $len;
             }
         }
         $name = ereg_replace('\.$', '', $name);
         return array($name, $offset);
     }
Net_DNS_Packet::label_extract ($packet, $offset)
DNS packet decompression method.
Extracts the label stored at a particular location in a DNS packet. The first argument is a variable containing the packet data. The second argument is the offset within the packet where the (possibly) compressed domain name is stored.
Parameters
string $packet The packet data
integer $offset The location offset in the packet of the label to extract.
Returns
array Returns a list of type array($name, $offset) where $name is the name of the label which was decompressed and $offset is the offset of the next field in the packet. Returns array(null, null) on error
Definition at line 463 of file Packet.php.
Referenced by Net_DNS_RR_HINFO\Net_DNS_RR_HINFO(), Net_DNS_RR_NAPTR\Net_DNS_RR_NAPTR(), and Net_DNS_RR_TXT\Net_DNS_RR_TXT().
     {
         $packetlen = strlen($packet);
         $name = '';
         if ($packetlen < ($offset + 1)) {
             return array(null, null);
         }
         $a = unpack("@$offset/Cchar", $packet);
         $len = $a['char'];
         $offset++;
         if ($len + $offset > $packetlen) {
             $name = substr($packet, $offset);
             $offset = $packetlen;
         } else {
             $name = substr($packet, $offset, $len);
             $offset += $len;
         }
         return array($name, $offset);
     }
Net_DNS_Packet::Net_DNS_Packet ($debug = false)
Initalizes a Net_DNS_Packet object.
Parameters
boolean $debug Turns debugging on or off
Definition at line 143 of file Packet.php.
References $debug.
     {
         $this->debug = $debug;
         $this->compnames = array();
     }
Net_DNS_Packet::parse ($data)
Parses a DNS packet returned by a DNS server.
Parses a complete DNS packet and builds an object hierarchy containing all of the parts of the packet:
HEADER
QUESTION
ANSWER || PREREQUISITE
ADDITIONAL || UPDATE
AUTHORITY
Parameters
string $data A binary string containing a DNS packet
Returns
boolean true on success, null on parser error
Definition at line 192 of file Packet.php.
References parse_question(), and parse_rr().
     {
         if ($this->debug) {
             echo ';; HEADER SECTION' . "\n";
         }
         $this->header = new Net_DNS_Header($data);
         if ($this->debug) {
             $this->header->display();
         }
         /*
          *  Print and parse the QUESTION section of the packet
          */
         if ($this->debug) {
             echo "\n";
             $section = ($this->header->opcode  == 'UPDATE') ? 'ZONE' : 'QUESTION';
             echo ";; $section SECTION (" . $this->header->qdcount . ' record' .
                 ($this->header->qdcount == 1 ? '' : 's') . ")\n";
         }
         $offset = 12;
         $this->question = array();
         for ($ctr = 0; $ctr < $this->header->qdcount; $ctr++) {
             list($qobj, $offset) = $this->parse_question($data, $offset);
             if (is_null($qobj)) {
                 return null;
             }
             $this->question[count($this->question)] = $qobj;
             if ($this->debug) {
                 echo ";;\n;";
                 $qobj->display();
             }
         }
         /*
          *  Print and parse the PREREQUISITE or ANSWER  section of the packet
          */
         if ($this->debug) {
             echo "\n";
             $section = ($this->header->opcode == 'UPDATE') ? 'PREREQUISITE' :'ANSWER';
             echo ";; $section SECTION (" .
                 $this->header->ancount . ' record' .
                 (($this->header->ancount == 1) ? '' : 's') .
                 ")\n";
         }
         $this->answer = array();
         for ($ctr = 0; $ctr < $this->header->ancount; $ctr++) {
             list($rrobj, $offset) = $this->parse_rr($data, $offset);
             if (is_null($rrobj)) {
                 return null;
             }
             array_push($this->answer, $rrobj);
             if ($this->debug) {
                 $rrobj->display();
             }
         }
         /*
          *  Print and parse the UPDATE or AUTHORITY section of the packet
          */
         if ($this->debug) {
             echo "\n";
             $section = ($this->header->opcode == 'UPDATE') ? 'UPDATE' : 'AUTHORITY';
             echo ";; $section SECTION (" .
                 $this->header->nscount . ' record' .
                 (($this->header->nscount == 1) ? '' : 's') .
                 ")\n";
         }
         $this->authority = array();
         for ($ctr = 0; $ctr < $this->header->nscount; $ctr++) {
             list($rrobj, $offset) = $this->parse_rr($data, $offset);
             if (is_null($rrobj)) {
                 return null;
             }
             array_push($this->authority, $rrobj);
             if ($this->debug) {
                 $rrobj->display();
             }
         }
         /*
          *  Print and parse the ADDITIONAL section of the packet
          */
         if ($this->debug) {
             echo "\n";
             echo ';; ADDITIONAL SECTION (' .
                 $this->header->arcount . ' record' .
                 (($this->header->arcount == 1) ? '' : 's') .
                 ")\n";
         }
         $this->additional = array();
         for ($ctr = 0; $ctr < $this->header->arcount; $ctr++) {
             list($rrobj, $offset) = $this->parse_rr($data, $offset);
             if (is_null($rrobj)) {
                 return null;
             }
             array_push($this->additional, $rrobj);
             if ($this->debug) {
                 $rrobj->display();
             }
         }
         return true;
     }
Net_DNS_Packet::parse_question ($data, $offset)
Parses the question section of a packet.
Examines a DNS packet at the specified offset and parses the data of the QUESTION section.
Parameters
string $data The packet data returned from the server
integer $offset The location offset of the start of the question section.
Returns
array An array of type array($q, $offset) where $q is a Net_DNS_Question object and $offset is the location of the next section of the packet which needs to be parsed.
Definition at line 501 of file Packet.php.
References Net_DNS\classesbyval(), dn_expand(), and Net_DNS\typesbyval().
Referenced by parse().
     {
         list($qname, $offset) = $this->dn_expand($data, $offset);
         if (is_null($qname)) {
             return array(null, null);
         }
         if (strlen($data) < ($offset + 2 * 2)) {
             return array(null, null);
         }
         $q = unpack("@$offset/n2int", $data);
         $qtype = $q['int1'];
         $qclass = $q['int2'];
         $offset += 2 * 2;
         $qtype = Net_DNS::typesbyval($qtype);
         $qclass = Net_DNS::classesbyval($qclass);
         $q = new Net_DNS_Question($qname, $qtype, $qclass);
         return array($q, $offset);
     }
Net_DNS_Packet::parse_rr ($data, $offset)
Parses a resource record section of a packet.
Examines a DNS packet at the specified offset and parses the data of a section which contains RRs (ANSWER, AUTHORITY, ADDITIONAL).
Parameters
string $data The packet data returned from the server
integer $offset The location offset of the start of the resource record section.
Returns
array An array of type array($rr, $offset) where $rr is a Net_DNS_RR object and $offset is the location of the next section of the packet which needs to be parsed.
Definition at line 540 of file Packet.php.
References Net_DNS\classesbyval(), dn_expand(), Net_DNS_RR\factory(), and Net_DNS\typesbyval().
Referenced by parse().
     {
         list($name, $offset) = $this->dn_expand($data, $offset);
         if ($name === null) {
             return array(null, null);
         }
         if (strlen($data) < ($offset + 10)) {
             return array(null, null);
         }
         $a = unpack("@$offset/n2tc/Nttl/nrdlength", $data);
         $type = $a['tc1'];
         $class = $a['tc2'];
         $ttl = $a['ttl'];
         $rdlength = $a['rdlength'];
         $type = Net_DNS::typesbyval($type);
         $class = Net_DNS::classesbyval($class);
         $offset += 10;
         if (strlen($data) < ($offset + $rdlength)) {
             return array(null, null);
         }
         $rrobj = &Net_DNS_RR::factory(array($name,
                     $type,
                     $class,
                     $ttl,
                     $rdlength,
                     $data,
                     $offset));
         if (is_null($rrobj)) {
             return array(null, null);
         }
         $offset += $rdlength;
         return array($rrobj, $offset);
     }
Net_DNS_Packet::string ()
Builds a human readable formatted string representing a packet.
Definition at line 597 of file Packet.php.
Referenced by display().
     {
         $retval = '';
         if ($this->answerfrom) {
             $retval .= ';; Answer received from ' . $this->answerfrom . '(' .
                 $this->answersize . " bytes)\n;;\n";
         }
         $retval .= ";; HEADER SECTION\n";
         $retval .= $this->header->string();
         $retval .= "\n";
         $section = ($this->header->opcode == 'UPDATE') ? 'ZONE' : 'QUESTION';
         $retval .= ";; $section SECTION (" . $this->header->qdcount     .
             ' record' . ($this->header->qdcount == 1 ? '' : 's') .
             ")\n";
         foreach ($this->question as $qr) {
             $retval .= ';; ' . $qr->string() . "\n";
         }
         $section = ($this->header->opcode == 'UPDATE') ? 'PREREQUISITE' : 'ANSWER';
         $retval .= "\n;; $section SECTION (" . $this->header->ancount     .
             ' record' . ($this->header->ancount == 1 ? '' : 's') .
             ")\n";
         if (is_array($this->answer)) {
             foreach ($this->answer as $ans) {
                 $retval .= ';; ' . $ans->string() . "\n";
             }
         }
         $section = ($this->header->opcode == 'UPDATE') ? 'UPDATE' : 'AUTHORITY';
         $retval .= "\n;; $section SECTION (" . $this->header->nscount     .
             ' record' . ($this->header->nscount == 1 ? '' : 's') .
             ")\n";
         if (is_array($this->authority)) {
             foreach ($this->authority as $auth) {
                 $retval .= ';; ' . $auth->string() . "\n";
             }
         }
         $retval .= "\n;; ADDITIONAL SECTION (" . $this->header->arcount     .
             ' record' . ($this->header->arcount == 1 ? '' : 's') .
             ")\n";
         if (is_array($this->additional)) {
             foreach ($this->additional as $addl) {
                 $retval .= ';; ' . $addl->string() . "\n";
             }
         }
         $retval .= "\n\n";
         return $retval;
     }
Field Documentation
array Net_DNS_Packet::$additional
An array of Net_DNS_RR ADDITIONAL objects.
Contains all of the additional RRs within the packet. Each additional is stored as an object of type Net_DNS_RR.
public
Definition at line 126 of file Packet.php.
array Net_DNS_Packet::$answer
An array of Net_DNS_RR ANSWER objects.
Contains all of the answer RRs within the packet. Each answer is stored as an object of type Net_DNS_RR.
public
Definition at line 106 of file Packet.php.
string Net_DNS_Packet::$answerfrom
The origin of the packet, if the packet is a server response.
This contains a string containing the IP address of the name server from which the answer was given.
public
Definition at line 75 of file Packet.php.
string Net_DNS_Packet::$answersize
The size of the answer packet, if the packet is a server response.
This contains a integer containing the size of the DNS packet the server responded with if this packet was received by a DNS server using the query() method.
public
Definition at line 86 of file Packet.php.
array Net_DNS_Packet::$authority
An array of Net_DNS_RR AUTHORITY objects.
Contains all of the authority RRs within the packet. Each authority is stored as an object of type Net_DNS_RR.
public
Definition at line 116 of file Packet.php.
array Net_DNS_Packet::$compnames
A hash of compressed labels.
A list of all labels which have been compressed in the DNS packet and the location offset of the label within the packet.
Definition at line 65 of file Packet.php.
boolean Net_DNS_Packet::$debug
debugging flag
If set to true (non-zero), debugging code will be displayed as the packet is parsed.
public
Definition at line 46 of file Packet.php.
Referenced by Net_DNS_Packet().
object Net_DNS_Header Net_DNS_Packet::$header
A packet Header object.
An object of type Net_DNS_Header which contains the header information of the packet.
public
Definition at line 56 of file Packet.php.
array Net_DNS_Packet::$question
An array of Net_DNS_Question objects.
Contains all of the questions within the packet. Each question is stored as an object of type Net_DNS_Question.
public
Definition at line 96 of file Packet.php.
The documentation for this class was generated from the following file:
Packet.php