Constant Contact for WordPress: KWSConstantContact Class Reference
KWSConstantContact Class Reference
Public Member Functions
__construct ($apiKey=null)
getInstance ()
Get access to instance or create one.
setHooks ()
Add actions to clear caches when appropriate.
_flushLists ()
Clear the lists cache.
_flushContacts ()
Clear the contacts cache.
_flushCampaigns ()
Clear the campaigns cache.
isConfigured ($force=false)
Check whether the plugin is configured with an active account.
setRestClient ($restClient)
Allow subclasses to set the REST Client used by the services.
addUpdateContact ($data)
Add a contact if it doesn't exist and update it if it does.
getAllContacts ()
Get all contacts KWSConstantContact::getAll()
getAllLists ()
Get all lists KWSConstantContact::getAll()
getAllContactSends ($id)
Get all contact sends KWSConstantContact::getAll()
getAllEmailCampaigns ($status=NULL)
Get all email campaigns KWSConstantContact::getAll()
getAll ($type= '', $id_or_status=NULL, $param=NULL, &$results=array())
Function to fetch multi-page results.
getContactByEmail ($email, $null=null)
Get contacts with a specified email eaddress.
Public Member Functions inherited from Ctct\ConstantContact
__construct ($apiKey)
Class constructor.
getContacts ($accessToken, $param=null)
Get a set of campaigns.
getContact ($accessToken, $contactId)
Get an individual contact.
getContactByEmail ($accessToken, $email)
Get contacts with a specified email eaddress.
addContact ($accessToken, Contact $contact, $actionByVisitor=false)
Add a new contact to an account.
deleteContact ($accessToken, $contact)
Sets an individual contact to 'REMOVED' status.
deleteContactFromLists ($accessToken, $contact)
Delete a contact from all contact lists.
deleteContactFromList ($accessToken, $contact, $list)
Delete a contact from all contact lists.
updateContact ($accessToken, Contact $contact, $actionByVisitor=false)
Update an individual contact.
getLists ($accessToken)
Get lists.
getList ($accessToken, $listId)
Get an individual list.
addList ($accessToken, ContactList $list)
Add a new contact list to an account.
updateList ($accessToken, ContactList $list)
Update a contact list.
getContactsFromList ($accessToken, $list, $param=null)
Get contact that belong to a specific list.
getEmailCampaigns ($accessToken, $status=null, $param=null)
Get a set of campaigns.
getEmailCampaign ($accessToken, $campaignId)
Get an individual campaign.
deleteEmailCampaign ($accessToken, $campaign)
Delete an individual campaign.
addEmailCampaign ($accessToken, Campaign $campaign)
Create a new campaign.
updateEmailCampaign ($accessToken, Campaign $campaign)
Update a specific campaign.
addEmailCampaignSchedule ($accessToken, $campaign, Schedule $schedule)
Schedule a campaign to be sent.
getEmailCampaignSchedules ($accessToken, $campaign)
Get an array of schedules associated with a given campaign.
getEmailCampaignSchedule ($accessToken, $campaign, $schedule)
Get a specific schedule associated with a given campaign.
updateEmailCampaignSchedule ($accessToken, $campaign, Schedule $schedule)
Update a specific schedule associated with a given campaign.
deleteEmailCampaignSchedule ($accessToken, $campaign, $schedule)
Delete a specific schedule associated with a given campaign.
sendEmailCampaignTest ($accessToken, $campaign, TestSend $test_send)
Send a test send of a campaign.
getEmailCampaignSends ($accessToken, $campaign, $param=null)
Get sends for a campaign.
getEmailCampaignBounces ($accessToken, $campaign, $param=null)
Get bounces for a campaign.
getEmailCampaignClicks ($accessToken, $campaign, $param=null)
Get clicks for a campaign.
getEmailCampaignOpens ($accessToken, $campaign, $param=null)
Get opens for a campaign.
getEmailCampaignForwards ($accessToken, $campaign, $param=null)
Get forwards for a campaign.
getEmailCampaignUnsubscribes ($accessToken, $campaign, $param=null)
Get unsubscribes for a campaign.
getEmailCampaignSummaryReport ($accessToken, $campaign)
Get a reporting summary for a campaign.
getContactSends ($accessToken, $contact, $param=null)
Get sends for a Contact.
getContactBounces ($accessToken, $contact, $param=null)
Get bounces for a Contact.
getContactClicks ($accessToken, $contact, $param=null)
Get clicks for a Contact.
getContactOpens ($accessToken, $contact, $param=null)
Get opens for a Contact.
getContactForwards ($accessToken, $contact, $param=null)
Get forwards for a Contact.
getContactUnsubscribes ($accessToken, $contact, $param=null)
Get opt outs for a Contact.
getVerifiedEmailAddresses ($accessToken, $status=null)
Get verified addresses for the account.
getContactSummaryReport ($accessToken, $contact)
Get a reporting summary for a Contact.
getActivities ($accessToken)
Get an array of activities.
getActivity ($accessToken, $activityId)
Get a single activity by id.
addCreateContactsActivity ($accessToken, AddContacts $addContactsActivity)
Add an AddContacts Activity to add contacts in bulk.
addClearListsActivity ($accessToken, Array $lists)
Add an ClearLists Activity to remove all contacts from the provided lists.
addRemoveContactsFromListsActivity ($accessToken, Array $emailAddresses, Array $lists)
Add a Remove Contacts From Lists Activity.
addExportContactsActivity ($accessToken, ExportContacts $exportContacts)
Create an Export Contacts Activity.
Data Fields
$configured = false
Static Public Attributes
static $instance
Private Member Functions
setUrls ()
Private Attributes
$cache_services = array('contacts' => 'contactService', 'campaigns' => 'emailMarketingService', 'activities' => 'activityService', 'lists' => 'listService')
Additional Inherited Members
Protected Attributes inherited from Ctct\ConstantContact
$contactService
$emailMarketingService
$listService
$activityService
$campaignTrackingService
$contactTrackingService
$campaignScheduleService
$accountService
Detailed Description
Definition at line 6 of file class.kwsconstantcontact.php.
Constructor & Destructor Documentation
KWSConstantContact::__construct ($apiKey = null)
Definition at line 13 of file class.kwsconstantcontact.php.
References Ctct\ConstantContact\$apiKey, setHooks(), setRestClient(), and setUrls().
{
         if(empty($apiKey)) { $apiKey = CTCT_APIKEY; }
         parent::__construct($apiKey);
         $Client = new KWSRestClient();
         $this->setRestClient($Client);
         $this->setUrls();
         $this->setHooks();
         self::$instance = $this;
     }
Member Function Documentation
KWSConstantContact::_flushCampaigns ()
Clear the campaigns cache.
Definition at line 67 of file class.kwsconstantcontact.php.
{
         delete_transient('ctct_all_campaigns');
     }
KWSConstantContact::_flushContacts ()
Clear the contacts cache.
Definition at line 61 of file class.kwsconstantcontact.php.
{
         delete_transient('ctct_all_contacts');
     }
KWSConstantContact::_flushLists ()
Clear the lists cache.
Definition at line 55 of file class.kwsconstantcontact.php.
{
         delete_transient('ctct_all_lists');
     }
KWSConstantContact::addUpdateContact ($data)
Add a contact if it doesn't exist and update it if it does.
Parameters
array | KWSContact $data Array of contact data or an existing KWSContact or Contact object.
Definition at line 126 of file class.kwsconstantcontact.php.
References Ctct\ConstantContact\addContact(), getContactByEmail(), and Ctct\ConstantContact\updateContact().
{
         $contact = new KWSContact($data);
         // check to see if a contact with the email addess already exists
         $existingContact = $this->getContactByEmail($contact->get('email'));
         // create a new contact if one does not exist
         if (empty($existingContact)) {
             $action = "Creating Contact";
             try {
                 $returnContact = $this->addContact(CTCT_ACCESS_TOKEN, $contact);
                 $action .= ' Succeeded';
             } catch(Exception $e) {
                 $returnContact = false;
                 $action .= ' Failed';
                 do_action('ctct_log_message', 'Creating Contact Exception', $e);
             }
         // update the existing contact if address already existed
         } else {
             $action = "Updating Contact";
             try {
                 // Update the contact details
                 $existingContact = $existingContact->update($data);
                 // Push the update to CTCT
                 $returnContact = $this->updateContact(CTCT_ACCESS_TOKEN, $existingContact);
                 $action .= ' Succeeded';
             } catch(Exception $e) {
                 $returnContact = false;
                 $action .= ' Failed';
                 do_action('ctct_log_message', 'Updating Contact Exception', $e);
             }
         }
         do_action('ctct_log_message', $action, $returnContact);
         do_action('ctct_debug', $action, $returnContact);
         return $returnContact;
     }
KWSConstantContact::getAll ($type = '', $id_or_status = NULL, $param = NULL, & $results = array())
Function to fetch multi-page results.
Works for all component types.
Parameters
string $type Component type name
int | string $id_or_status Either the ID of the component or the status filter. Depends on the component. Example: `$id_or_status = 'sent';forEmailCampaignscomponent. Example:$id_or_status = 13;forContactSends` component.
string $param Search filter. Sets the limit for requests.
array $results Pass the previous results for recursive calls to the method.
Returns
array Results array with id as key to each key/value pair.
Definition at line 213 of file class.kwsconstantcontact.php.
Referenced by getAllContacts(), getAllContactSends(), getAllEmailCampaigns(), and getAllLists().
{
         do_action('ctct_debug', $type);
         add_filter('ctct_cache', function() { return 60 * 60 * 48; });
         if($type === 'EmailCampaigns'){
             if(!is_null($param)) { $id_or_status = null; }
             $fetch = $this->{"get{$type}"}(CTCT_ACCESS_TOKEN, $id_or_status, $param);
         } else if(!is_null($id_or_status)) {
             if(is_null($param)) { $param = '?limit=500'; }
             $fetch = $this->{"get{$type}"}(CTCT_ACCESS_TOKEN, $id_or_status, $param);
         } else {
             if(is_null($param)) { $param = '?limit=500'; }
             $fetch = $this->{"get{$type}"}(CTCT_ACCESS_TOKEN, $param);
         }
         // If this returns the results directly, not as an object.
         if(is_array($fetch)) { return $fetch; }
         foreach($fetch->results as $r) { $results[$r->id] = $r;  }
         if(!empty($fetch->next) && $fetch->next != $param) {
             $this->getAll($type, $id_or_status, $fetch->next, $results);
         }
         return $results;
     }
KWSConstantContact::getAllContacts ()
Get all contacts KWSConstantContact::getAll()
Returns
array
Definition at line 174 of file class.kwsconstantcontact.php.
References getAll().
{
         return $this->getAll('Contacts');
     }
KWSConstantContact::getAllContactSends ($id)
Get all contact sends KWSConstantContact::getAll()
Returns
array
Definition at line 192 of file class.kwsconstantcontact.php.
References getAll().
{
         return $this->getAll('ContactSends', $id);
     }
KWSConstantContact::getAllEmailCampaigns ($status = NULL)
Get all email campaigns KWSConstantContact::getAll()
Returns
array
Definition at line 201 of file class.kwsconstantcontact.php.
References getAll().
{
         return $this->getAll('EmailCampaigns', $status);
     }
KWSConstantContact::getAllLists ()
Get all lists KWSConstantContact::getAll()
Returns
array
Definition at line 183 of file class.kwsconstantcontact.php.
References getAll().
{
         return $this->getAll('Lists');
     }
KWSConstantContact::getContactByEmail ($email, $null = null)
Get contacts with a specified email eaddress.
Parameters
string $email - contact email address to search for
string $null - placeholder for PHP 5.4 Strict standards
Returns
KWSContact|boolean If contact, KWSContact object; if none, false
Definition at line 247 of file class.kwsconstantcontact.php.
Referenced by addUpdateContact(), and isConfigured().
{
         $contact = $this->contactService->getContacts(CTCT_ACCESS_TOKEN, array('email' => $email));
         if(!empty($contact->results)) {
             return new KWSContact($contact->results[0]);
         }
         return false;
     }
KWSConstantContact::getInstance ()
Get access to instance or create one.
Returns
KWSConstantContact
Definition at line 32 of file class.kwsconstantcontact.php.
Referenced by CTCT_Process_Form\process().
{
         if(empty(self::$instance)) {
             self::$instance = new KWSConstantContact;
         }
         return self::$instance;
     }
KWSConstantContact::isConfigured ($force = false)
Check whether the plugin is configured with an active account.
KWSConstantContact::getContactByEmail()
Parameters
boolean $force Force re-checking configuration. Otherwise, it will use previous results as stored in the ctct_configured option.
Returns
boolean true: Configured; false: Not configured properly.
Definition at line 84 of file class.kwsconstantcontact.php.
References $configured, and getContactByEmail().
{
         if(!$force) {
             return get_site_option( 'ctct_configured' );
         }
         // Force caching feature to turn off.
         $_GET['cache'] = true;
         try {
             $contacts = $this->getContactByEmail('asdasdasdasd@asdasdasdasdasdasdasdasd.com');
             $this->configured = 1;
             update_site_option( 'ctct_configured', 1 );
         } catch(Exception $e) {
             $this->configured = 0;
             delete_site_option( 'ctct_configured' );
         }
         // Turn caching back on.
         unset($_GET['cache']);
         return $this->configured;
     }
KWSConstantContact::setHooks ()
Add actions to clear caches when appropriate.
Clear the lists cache by running `do_action('ctct_flush_lists'); Clear the contacts cache by runningdo_action('ctct_flush_contacts'); Clear the campaigns cache by runningdo_action('ctct_flush_campaigns');`
Definition at line 46 of file class.kwsconstantcontact.php.
Referenced by __construct().
{
         add_action('ctct_flush_lists', array(&$this, '_flushLists'));
         add_action('ctct_flush_contacts', array(&$this, '_flushContacts'));
         add_action('ctct_flush_campaigns', array(&$this, '_flushCampaigns'));
     }
KWSConstantContact::setRestClient ($restClient)
Allow subclasses to set the REST Client used by the services.
Parameters
RestClientInterface $restClient
See Also
BaseService::setRestClient()
Definition at line 111 of file class.kwsconstantcontact.php.
Referenced by __construct().
{
         $this->contactService->setRestClient($restClient);
         $this->emailMarketingService->setRestClient($restClient);
         $this->activityService->setRestClient($restClient);
         $this->campaignTrackingService->setRestClient($restClient);
         $this->contactTrackingService->setRestClient($restClient);
         $this->campaignScheduleService->setRestClient($restClient);
         $this->listService->setRestClient($restClient);
         $this->accountService->setRestClient($restClient);
     }
KWSConstantContact::setUrls () private
Definition at line 71 of file class.kwsconstantcontact.php.
Referenced by __construct().
{
         foreach($this->cache_services as $key => $service) {
             $this->{$service}->baseUrl = Config::get('endpoints.base_url') . Config::get('endpoints.'.$key);
         }
     }
Field Documentation
KWSConstantContact::$cache_services = array('contacts' => 'contactService', 'campaigns' => 'emailMarketingService', 'activities' => 'activityService', 'lists' => 'listService') private
Definition at line 11 of file class.kwsconstantcontact.php.
KWSConstantContact::$configured = false
Definition at line 8 of file class.kwsconstantcontact.php.
Referenced by isConfigured().
KWSConstantContact::$instance static
Definition at line 9 of file class.kwsconstantcontact.php.
The documentation for this class was generated from the following file:
class.kwsconstantcontact.php