Constant Contact for WordPress: EventsCollection Class Reference
EventsCollection Class Reference
Public Member Functions
__construct ($CTCTRequest)
EventsCollection constructor.
getEvents ($page=null)
Get a page of Events.
getEventDetails ($url)
Get full details for an Event object.
getRegistrants ($url)
Get a page of Registrants for an Event.
getRegistrantDetails ($url)
Get details for an Event Registrant.
Public Member Functions inherited from Collection
__construct (CTCTRequest $CTCTRequest, $collectionUri)
Collection constructor.
Data Fields
$CTCTRequest
$uri
Data Fields inherited from Collection
$CTCTRequest
$uri
Detailed Description
Definition at line 600 of file Collections.php.
Constructor & Destructor Documentation
EventsCollection::__construct ($CTCTRequest)
EventsCollection constructor.
Parameters
CTCTRequest $CTCTRequest
Definition at line 608 of file Collections.php.
References $CTCTRequest.
{
         parent::__construct($CTCTRequest, '/ws/customers/'.$CTCTRequest->username.'/events');
     }
Member Function Documentation
EventsCollection::getEventDetails ($url)
Get full details for an Event object.
Parameters
string $url - url to an Event
Returns
Event
Definition at line 634 of file Collections.php.
References Event\createStruct(), and CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $parsedResponse = simplexml_load_string($response['xml'], null, null, "http://www.w3.org/2005/Atom");
         return new Event(Event::createStruct($parsedResponse));
     }
EventsCollection::getEvents ($page = null)
Get a page of Events.
Parameters
string $page - url to a page of events, default is first page
Returns
array - Event objects and link to the next page if one exists
Definition at line 617 of file Collections.php.
References Event\createStruct(), Utility\findNextLink(), and CTCTRequest\makeRequest().
{
         $url = ($page) ? $this->CTCTRequest->baseUri.$page : $this->uri;
         $eventsCollection = array('events' => array(), 'nextLink' => '');
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $parsedResponse = simplexml_load_string($response['xml'], null, null, "http://www.w3.org/2005/Atom");
         foreach($parsedResponse->entry as $entry){
             $eventsCollection['events'][] = new Event(Event::createStruct($entry));
         }
         $eventsCollection['nextLink'] = Utility::findNextLink($parsedResponse);
         return $eventsCollection;
     }
EventsCollection::getRegistrantDetails ($url)
Get details for an Event Registrant.
Parameters
string $url - url to a Regitrant
Returns
Registrant
Definition at line 661 of file Collections.php.
References Registrant\createStruct(), and CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $parsedResponse = simplexml_load_string($response['xml'], null, null, "http://www.w3.org/2005/Atom");
         return new Registrant(Registrant::createStruct($parsedResponse));
     }
EventsCollection::getRegistrants ($url)
Get a page of Registrants for an Event.
Parameters
$url - url to an event
Returns
array - Registrants and a link to the next page if one exists
Definition at line 645 of file Collections.php.
References Registrant\createStruct(), Utility\findNextLink(), and CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $registrantsArr = array('registrants' => array(), 'nextLink' => '');
         $parsedResponse = simplexml_load_string($response['xml'], null, null, "http://www.w3.org/2005/Atom");
         foreach($parsedResponse->entry as $reg){
             $registrantsArr['registrants'][] = new Registrant(Registrant::createStruct($reg));
         }
         $registrantsArr['nextLink'] = Utility::findNextLink($parsedResponse);
         return $registrantsArr;
     }
Field Documentation
EventsCollection::$CTCTRequest
Definition at line 601 of file Collections.php.
Referenced by __construct().
EventsCollection::$uri
Definition at line 602 of file Collections.php.
The documentation for this class was generated from the following file:
Collections.php