Constant Contact for WordPress: Schedule Class Reference
Schedule Class Reference
Public Member Functions
__construct ($params=array())
createXml ()
Static Public Member Functions
static createStruct ($parsedResponse)
Data Fields
$link
$id
$updated
$time
$campaign
Additional Inherited Members
Protected Member Functions inherited from CCObject
validate (Array $params)
Validate an object to check that all required fields have been supplied array $params - object property names to reference for validation before HTTP requests.
Detailed Description
Definition at line 1360 of file Components.php.
Constructor & Destructor Documentation
Schedule::__construct ($params = array())
Definition at line 1367 of file Components.php.
{
         $this->link = (isset($params['link'])) ? $params['link'] : '';
         $this->id = (isset($params['id'])) ? $params['id'] : '';
         $this->updated = (isset($params['updated'])) ? $params['updated'] : '';
         $this->time = (isset($params['time'])) ? $params['time'] : '';
         $this->campaign = (isset($params['campaign'])) ? $params['campaign'] : '';
     }
Member Function Documentation
static Schedule::createStruct ($parsedResponse) static
Definition at line 1394 of file Components.php.
Referenced by CampaignsCollection\getSchedule(), and CampaignsCollection\scheduleCampaign().
{
         $schedule['link'] = (string) $parsedResponse->link->Attributes()->href;
         $schedule['id'] = (string) $parsedResponse->id;
         $schedule['updated'] = (string) $parsedResponse->updated;
         $schedule['time'] = (string) $parsedResponse->content->Schedule->ScheduledTime;
         return $schedule;
     }
Schedule::createXml ()
Definition at line 1375 of file Components.php.
References CCObject\validate().
{
         $this->validate(array('time'));
         $xml = simplexml_load_string("<?xml version='1.0' encoding='UTF-8' standalone='yes'?><entry xmlns='http://www.w3.org/2005/Atom'/>");
         $linkNode = $xml->addChild("link");
         $linkNode->addAttribute('href', $this->campaign->link.'/schedules/1');
         $linkNode->addAttribute('rel', 'edit');
         $xml->addChild("id", $this->campaign->id);
         $xml->addChild("title", $this->time);
         $xml->addChild("updated", $this->time);
         $author = $xml->addChild("author");
         $author->addChild("name", "ConstantContact");
         $content = $xml->addChild("content");
         $content->addAttribute("type", "application/vnd.ctct+xml");
         $schedule = $content->addChild("Schedule", "", 'http://ws.constantcontact.com/ns/1.0/');
         $schedule->addAttribute("id", $this->campaign->link.'/schedules/1');
         $schedule->addChild("ScheduledTime", $this->time);
         return $xml->asXML();
     }
Field Documentation
Schedule::$campaign
Definition at line 1365 of file Components.php.
Schedule::$id
Definition at line 1362 of file Components.php.
Schedule::$link
Definition at line 1361 of file Components.php.
Schedule::$time
Definition at line 1364 of file Components.php.
Schedule::$updated
Definition at line 1363 of file Components.php.
The documentation for this class was generated from the following file:
Components.php