Constant Contact for WordPress: Ctct\Services\ContactTrackingService Class Reference
Ctct\Services\ContactTrackingService Class Reference
Public Member Functions
getBounces ($accessToken, $contact_id, Array $params=null)
Get bounces for a given contact.
getClicks ($accessToken, $contact_id, Array $params=null)
Get clicks for a given contact.
getForwards ($accessToken, $contact_id, Array $params=null)
Get forwards for a given contact.
getOpens ($accessToken, $contact_id, Array $params=null)
Get opens for a given contact.
getSends ($accessToken, $contact_id, Array $params=null)
Get sends for a given contact.
getUnsubscribes ($accessToken, $contact_id, Array $params=null)
Get unsubscribes for a given contact.
getSummary ($accessToken, $contact_id)
Get a summary of reporting data for a given contact.
Public Member Functions inherited from Ctct\Services\BaseService
__construct ($apiKey, $restClient=null)
Constructor with the option to to supply an alternative rest client to be used.
buildUrl ($url, $queryParams=null)
Build a url from the base url and query parameters array.
getRestClient ()
Get the rest client being used by the service.
setRestClient (RestClientInterface $restClient)
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Services\BaseService
static getHeaders ($accessToken)
Helper function to return required headers for making an http request with constant contact.
Protected Attributes inherited from Ctct\Services\BaseService
$restClient
$apiKey
Detailed Description
Definition at line 22 of file ContactTrackingService.php.
Member Function Documentation
Ctct\Services\ContactTrackingService::getBounces ($accessToken, $contact_id, Array $params = null)
Get bounces for a given contact.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $contact_id - Contact id
array $param - query params to be appended to request
Returns
ResultSet - Containing a results array of BounceActivity
Definition at line 32 of file ContactTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\BounceActivity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.contact_tracking_bounces'), $contact_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $bounces = array();
         foreach ($body['results'] as $bounceActivity) {
             $bounces[] = BounceActivity::create($bounceActivity);
         }
         return new ResultSet($bounces, $body['meta']);
     }
Ctct\Services\ContactTrackingService::getClicks ($accessToken, $contact_id, Array $params = null)
Get clicks for a given contact.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $contact_id - Contact id
array $param - query params to be appended to request
Returns
ResultSet - Containing a results array of ClickActivity
Definition at line 57 of file ContactTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\ClickActivity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.contact_tracking_clicks'), $contact_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $clicks = array();
         foreach ($body['results'] as $click_activity) {
             $clicks[] = ClickActivity::create($click_activity);
         }
         return new ResultSet($clicks, $body['meta']);
     }
Ctct\Services\ContactTrackingService::getForwards ($accessToken, $contact_id, Array $params = null)
Get forwards for a given contact.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $contact_id - Contact id
array $param - query params to be appended to request
Returns
ResultSet - Containing a results array of ForwardActivity
Definition at line 82 of file ContactTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\ForwardActivity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.contact_tracking_forwards'), $contact_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $forwards = array();
         foreach ($body['results'] as $forward_activity) {
             $forwards[] = ForwardActivity::create($forward_activity);
         }
         return new ResultSet($forwards, $body['meta']);
     }
Ctct\Services\ContactTrackingService::getOpens ($accessToken, $contact_id, Array $params = null)
Get opens for a given contact.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $contact_id - Contact id
array $param - query params to be appended to request
Returns
ResultSet - Containing a results array of OpenActivity
Definition at line 106 of file ContactTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\OpenActivity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.contact_tracking_opens'), $contact_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $opens = array();
         foreach ($body['results'] as $open_activity) {
             $opens[] = OpenActivity::create($open_activity);
         }
         return new ResultSet($opens, $body['meta']);
     }
Ctct\Services\ContactTrackingService::getSends ($accessToken, $contact_id, Array $params = null)
Get sends for a given contact.
Parameters
string $accessToken - Constant Contact OAuth2 access token
string $accessToken - Constant Contact OAuth2 access token
int $contact_id - Contact id
array $param - query params to be appended to request
Returns
ResultSet - Containing a results array of SendActivity
Definition at line 131 of file ContactTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\SendActivity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.contact_tracking_sends'), $contact_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $sends = array();
         foreach ($body['results'] as $send_activity) {
             $sends[] = SendActivity::create($send_activity);
         }
         return new ResultSet($sends, $body['meta']);
     }
Ctct\Services\ContactTrackingService::getSummary ($accessToken, $contact_id)
Get a summary of reporting data for a given contact.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $contact_id - Contact id
Returns
TrackingSummary
Definition at line 178 of file ContactTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\TrackingSummary\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.contact_tracking_summary'), $contact_id);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         return TrackingSummary::create(json_decode($response->body, true));
     }
Ctct\Services\ContactTrackingService::getUnsubscribes ($accessToken, $contact_id, Array $params = null)
Get unsubscribes for a given contact.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $contact_id - Contact id
array $param - query params to be appended to request
Returns
ResultSet - Containing a results array of UnsubscribeActivity
Definition at line 155 of file ContactTrackingService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Tracking\UnsubscribeActivity\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.contact_tracking_unsubscribes'), $contact_id);
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $body = json_decode($response->body, true);
         $opt_outs = array();
         foreach ($body['results'] as $opt_out_activity) {
             $opt_outs[] = UnsubscribeActivity::create($opt_out_activity);
         }
         return new ResultSet($opt_outs, $body['meta']);
     }
The documentation for this class was generated from the following file:
ContactTrackingService.php