Constant Contact for WordPress: OAuthSignatureMethod_RSA_SHA1 Class Reference
OAuthSignatureMethod_RSA_SHA1 Class Reference
The RSA-SHA1 signature method uses the RSASSA-PKCS1-v1_5 signature algorithm as defined in [RFC3447] section 8.2 (more simply known as PKCS#1), using SHA-1 as the hash function for EMSA-PKCS1-v1_5.
Public Member Functions
get_name ()
build_signature ($request, $consumer, $token)
check_signature ($request, $consumer, $token, $signature)
Public Member Functions inherited from OAuthSignatureMethod
get_name ()
Needs to return the name of the Signature Method (ie HMAC-SHA1)
build_signature ($request, $consumer, $token)
Build up the signature NOTE: The output of this function MUST NOT be urlencoded.
check_signature ($request, $consumer, $token, $signature)
Verifies that a given signature is correct.
Protected Member Functions
fetch_public_cert (&$request)
fetch_private_cert (&$request)
Detailed Description
The RSA-SHA1 signature method uses the RSASSA-PKCS1-v1_5 signature algorithm as defined in [RFC3447] section 8.2 (more simply known as PKCS#1), using SHA-1 as the hash function for EMSA-PKCS1-v1_5.
It is assumed that the Consumer has provided its RSA public key in a verified way to the Service Provider, in a manner which is beyond the scope of this specification.
Chapter 9.3 ("RSA-SHA1")
Definition at line 165 of file Authentication.php.
Member Function Documentation
OAuthSignatureMethod_RSA_SHA1::build_signature ($request, $consumer, $token)
Definition at line 184 of file Authentication.php.
References fetch_private_cert().
{
     $base_string = $request->get_signature_base_string();
     $request->base_string = $base_string;
     // Fetch the private key cert based on the request
     $cert = $this->fetch_private_cert($request);
     // Pull the private key ID from the certificate
     $privatekeyid = openssl_get_privatekey($cert);
     // Sign using the key
     $ok = openssl_sign($base_string, $signature, $privatekeyid);
     // Release the key resource
     openssl_free_key($privatekeyid);
     return base64_encode($signature);
   }
OAuthSignatureMethod_RSA_SHA1::check_signature ($request, $consumer, $token, $signature)
Definition at line 203 of file Authentication.php.
References fetch_public_cert().
{
     $decoded_sig = base64_decode($signature);
     $base_string = $request->get_signature_base_string();
     // Fetch the public key cert based on the request
     $cert = $this->fetch_public_cert($request);
     // Pull the public key ID from the certificate
     $publickeyid = openssl_get_publickey($cert);
     // Check the computed signature against the one passed in the query
     $ok = openssl_verify($base_string, $decoded_sig, $publickeyid);
     // Release the key resource
     openssl_free_key($publickeyid);
     return $ok == 1;
   }
OAuthSignatureMethod_RSA_SHA1::fetch_private_cert (& $request) abstract protected
Referenced by build_signature().
OAuthSignatureMethod_RSA_SHA1::fetch_public_cert (& $request) abstract protected
Referenced by check_signature().
OAuthSignatureMethod_RSA_SHA1::get_name ()
Definition at line 166 of file Authentication.php.
{
     return "RSA-SHA1";
   }
The documentation for this class was generated from the following file:
Authentication.php