Constant Contact for WordPress: Ctct\Services\CampaignScheduleService Class Reference
Ctct\Services\CampaignScheduleService Class Reference
Public Member Functions
addSchedule ($accessToken, $campaignId, Schedule $schedule)
Create a new schedule for a campaign.
getSchedules ($accessToken, $campaignId)
Get a list of schedules for a campaign.
getSchedule ($accessToken, $campaignId, $scheduleId)
Get a specific schedule for a campaign.
updateSchedule ($accessToken, $campaignId, Schedule $schedule)
Update a specific schedule for a campaign.
deleteSchedule ($accessToken, $campaignId, $scheduleId)
Get a specific schedule for a campaign.
sendTest ($accessToken, $campaignId, TestSend $test_send)
Send a test send of a campaign.
Public Member Functions inherited from Ctct\Services\BaseService
__construct ($apiKey, $restClient=null)
Constructor with the option to to supply an alternative rest client to be used.
buildUrl ($url, $queryParams=null)
Build a url from the base url and query parameters array.
getRestClient ()
Get the rest client being used by the service.
setRestClient (RestClientInterface $restClient)
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Services\BaseService
static getHeaders ($accessToken)
Helper function to return required headers for making an http request with constant contact.
Protected Attributes inherited from Ctct\Services\BaseService
$restClient
$apiKey
Detailed Description
Definition at line 15 of file CampaignScheduleService.php.
Member Function Documentation
Ctct\Services\CampaignScheduleService::addSchedule ($accessToken, $campaignId, Schedule $schedule)
Create a new schedule for a campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $campaignId - Campaign id to be scheduled
Schedule $schedule - Schedule to be created
Returns
Campaign
Definition at line 24 of file CampaignScheduleService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\EmailMarketing\Schedule\create(), Ctct\Util\Config\get(), and Ctct\Components\EmailMarketing\Schedule\toJson().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_schedules'), $campaignId);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->post($url, parent::getHeaders($accessToken), $schedule->toJson());
         return Schedule::create(json_decode($response->body, true));
     }
Ctct\Services\CampaignScheduleService::deleteSchedule ($accessToken, $campaignId, $scheduleId)
Get a specific schedule for a campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $campaignId - Campaign id
int $scheduleId - Schedule id to delete
Returns
Schedule
Definition at line 94 of file CampaignScheduleService.php.
References Ctct\Services\BaseService\buildUrl(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_schedule'), $campaignId, $scheduleId);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->delete($url, parent::getHeaders($accessToken));
         return ($response->info['http_code'] == 204) ? true : false;
     }
Ctct\Services\CampaignScheduleService::getSchedule ($accessToken, $campaignId, $scheduleId)
Get a specific schedule for a campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $campaignId - Campaign id to be get a schedule for
int $scheudle_id - Schedule id to retrieve
Returns
Schedule
Definition at line 62 of file CampaignScheduleService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\EmailMarketing\Schedule\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_schedule'), $campaignId, $scheduleId);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         return Schedule::create(json_decode($response->body, true));
     }
Ctct\Services\CampaignScheduleService::getSchedules ($accessToken, $campaignId)
Get a list of schedules for a campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $campaignId - Campaign id to be scheduled
Returns
array
Definition at line 39 of file CampaignScheduleService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\EmailMarketing\Schedule\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_schedules'), $campaignId);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $schedules = array();
         foreach (json_decode($response->body, true) as $schedule) {
             $schedules[] = Schedule::create($schedule);
         }
         return $schedules;
     }
Ctct\Services\CampaignScheduleService::sendTest ($accessToken, $campaignId, TestSend $test_send)
Send a test send of a campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $campaignId - Id of campaign to send test of
TestSend $test_send - Test send details
Returns
TestSend
Definition at line 110 of file CampaignScheduleService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\EmailMarketing\TestSend\create(), Ctct\Util\Config\get(), and Ctct\Components\EmailMarketing\TestSend\toJson().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_test_sends'), $campaignId);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->post($url, parent::getHeaders($accessToken), $test_send->toJson());
         return TestSend::create(json_decode($response->body, true));
     }
Ctct\Services\CampaignScheduleService::updateSchedule ($accessToken, $campaignId, Schedule $schedule)
Update a specific schedule for a campaign.
Parameters
string $accessToken - Constant Contact OAuth2 access token
int $campaignId - Campaign id to be scheduled
Schedule $schedule - Schedule to retrieve
Returns
Schedule
Definition at line 78 of file CampaignScheduleService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\EmailMarketing\Schedule\create(), Ctct\Util\Config\get(), and Ctct\Components\EmailMarketing\Schedule\toJson().
     {
         $baseUrl = Config::get('endpoints.base_url') .
             sprintf(Config::get('endpoints.campaign_schedule'), $campaignId, $schedule->id);
         $url = $this->buildUrl($baseUrl);
         $response = parent::getRestClient()->put($url, parent::getHeaders($accessToken), $schedule->toJson());
         return Schedule::create(json_decode($response->body, true));
     }
The documentation for this class was generated from the following file:
CampaignScheduleService.php