Constant Contact for WordPress: Ctct\Components\EmailMarketing\Schedule Class Reference
Ctct\Components\EmailMarketing\Schedule Class Reference
Public Member Functions
toJson ()
Create json used for a POST/PUT request, also handles removing attributes that will cause errors if sent.
Static Public Member Functions
static create (array $props)
Factory method to create a Schedule object from an array.
Data Fields
$id
$scheduled_date
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Components\Component
static getValue (array $array, $item, $default=null)
Get the requested value from an array, or return the default.
Detailed Description
Definition at line 13 of file Schedule.php.
Member Function Documentation
static Ctct\Components\EmailMarketing\Schedule::create (array $props) static
Factory method to create a Schedule object from an array.
Parameters
array $props - associative array of initial properties to set
Returns
Schedule
Definition at line 33 of file Schedule.php.
Referenced by Ctct\Services\CampaignScheduleService\addSchedule(), Ctct\Services\CampaignScheduleService\getSchedule(), Ctct\Services\CampaignScheduleService\getSchedules(), and Ctct\Services\CampaignScheduleService\updateSchedule().
     {
         $schedule = new Schedule();
         $schedule->id = parent::getValue($props, "id");
         $schedule->scheduled_date = parent::getValue($props, "scheduled_date");
         return $schedule;
     }
Ctct\Components\EmailMarketing\Schedule::toJson ()
Create json used for a POST/PUT request, also handles removing attributes that will cause errors if sent.
Returns
string
Definition at line 45 of file Schedule.php.
Referenced by Ctct\Services\CampaignScheduleService\addSchedule(), and Ctct\Services\CampaignScheduleService\updateSchedule().
     {
         $schedule = clone $this;
         unset($schedule->id);
         return json_encode($schedule);
     }
Field Documentation
Ctct\Components\EmailMarketing\Schedule::$id
Definition at line 19 of file Schedule.php.
Ctct\Components\EmailMarketing\Schedule::$scheduled_date
Definition at line 25 of file Schedule.php.
The documentation for this class was generated from the following file:
Schedule.php