Constant Contact for WordPress: ListsCollection Class Reference
ListsCollection Class Reference
Public Member Functions
__construct ($CTCTRequest)
ListsCollection constructor.
getLists ($page=null, $systemLists=false)
Get an array of ContactList objects.
addList (ContactList $List)
Add a new list to Constant Contact account.
getListMembers (ContactList $List, $page=null)
Get a page of contacts from a given list.
getListDetails ($url)
Get full details for a ContactList.
deleteList ($url)
Delete a ContactList from an account.
updateList (ContactList $List)
Update a ContactList.
Public Member Functions inherited from Collection
__construct (CTCTRequest $CTCTRequest, $collectionUri)
Collection constructor.
Data Fields
$CTCTRequest
$uri
Data Fields inherited from Collection
$CTCTRequest
$uri
Detailed Description
Definition at line 41 of file Collections.php.
Constructor & Destructor Documentation
ListsCollection::__construct ($CTCTRequest)
ListsCollection constructor.
Parameters
CTCTRequest $CTCTRequest
Definition at line 49 of file Collections.php.
References $CTCTRequest.
{
         parent::__construct($CTCTRequest, '/ws/customers/'.$CTCTRequest->username.'/lists');
     }
Member Function Documentation
ListsCollection::addList (ContactList $List)
Add a new list to Constant Contact account.
Parameters
ContactList $List - List object created by
Returns
ContactList - newly created ContactList object
Definition at line 80 of file Collections.php.
References ContactList\createStruct(), ContactList\createXml(), and CTCTRequest\makeRequest().
{
         $listXml = $List->createXml();
         $response = $this->CTCTRequest->makeRequest($this->uri, 'POST', $listXml);
         $parsedResponse = simplexml_load_string($response['xml']);
         return new ContactList(ContactList::createStruct($parsedResponse));
     }
ListsCollection::deleteList ($url)
Delete a ContactList from an account.
Parameters
string $url - address to a list
Returns
bool - true is successful, else false
Definition at line 120 of file Collections.php.
References CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'DELETE');
         return ($response['info']['http_code'] == 204) ? true : false;
     }
ListsCollection::getListDetails ($url)
Get full details for a ContactList.
Parameters
string $url - address to a list
Returns
ContactList
Definition at line 109 of file Collections.php.
References ContactList\createStruct(), and CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $parsedResponse = simplexml_load_string($response['xml']);
         return new ContactList(ContactList::createStruct($parsedResponse));
     }
ListsCollection::getListMembers (ContactList $List, $page = null)
Get a page of contacts from a given list.
Parameters
string $url - url to request
Returns
array
Definition at line 92 of file Collections.php.
References ContactList\createMemberStruct(), Utility\findNextLink(), and CTCTRequest\makeRequest().
{
         $membersCollection = array('members' => array(), 'nextLink' => null);
         $url = ($page) ? $this->CTCTRequest->baseUri.$page : $this->CTCTRequest->baseUri.$List->link.'/members';
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $parsedResponse = simplexml_load_string($response['xml']);
         foreach($parsedResponse->entry as $entry){
             $membersCollection['members'][] = new Contact(ContactList::createMemberStruct($entry));
         }
         $membersCollection['nextLink'] = Utility::findNextLink($parsedResponse);
         return $membersCollection;
     }
ListsCollection::getLists ($page = null, $systemLists = false)
Get an array of ContactList objects.
Parameters
string $page - optional link to a lists page, default is first page
Returns
array
Definition at line 58 of file Collections.php.
References ContactList\createStruct(), Utility\findNextLink(), and CTCTRequest\makeRequest().
{
         $page = ($page) ? $this->CTCTRequest->baseUri.$page : $this->uri;
         $listsCollection = array('lists' => array(), 'nextLink' => '');
         $ignoreArray = array("Active", "Removed", "Do Not Mail");
         $response = $this->CTCTRequest->makeRequest($page, 'GET');
         $parsedResponse = simplexml_load_string($response['xml']);
         foreach ($parsedResponse->entry as $entry){
             if($systemLists == false && !in_array((string)$entry->content->ContactList->Name, $ignoreArray)){
                 $listsCollection['lists'][] = new ContactList(ContactList::createStruct($entry));
             } elseif($systemLists == true) {
                 $listsCollection['lists'][] = new ContactList(ContactList::createStruct($entry));
             }
         }
         $listsCollection['nextLink'] = Utility::findNextLink($parsedResponse);
         return $listsCollection;
     }
ListsCollection::updateList (ContactList $List)
Update a ContactList.
Parameters
string $url - address to a list
Returns
bool - true is successful, else false
Definition at line 130 of file Collections.php.
References ContactList\createXml(), and CTCTRequest\makeRequest().
{
         $listXml = $List->createXml();
         $response = $this->CTCTRequest->makeRequest($this->CTCTRequest->baseUri.$List->link, 'PUT', $listXml);
         return ($response['info']['http_code'] == 204) ? true : false;
     }
Field Documentation
ListsCollection::$CTCTRequest
Definition at line 42 of file Collections.php.
Referenced by __construct().
ListsCollection::$uri
Definition at line 43 of file Collections.php.
The documentation for this class was generated from the following file:
Collections.php