Constant Contact for WordPress: Ctct\Util\Config Class Reference
Ctct\Util\Config Class Reference
Static Public Member Functions
static get ($index)
Get a configuration property given a specified location, example usage: Config::get('auth.token_endpoint')
Static Private Member Functions
static getValue ($index, $value)
Navigate through a config array looking for a particular index.
Static Private Attributes
static $props
Detailed Description
Definition at line 10 of file Config.php.
Member Function Documentation
static Ctct\Util\Config::get ($index) static
Get a configuration property given a specified location, example usage: Config::get('auth.token_endpoint')
Parameters
$index - location of the property to obtain
Returns
string
Definition at line 123 of file Config.php.
Referenced by Ctct\Components\Activities\AddContacts\__construct(), Ctct\Services\EmailMarketingService\addCampaign(), Ctct\Services\ActivityService\addClearListsActivity(), Ctct\Services\ContactService\addContact(), Ctct\Services\ActivityService\addExportContactsActivity(), Ctct\Services\ListService\addList(), Ctct\Components\EmailMarketing\Campaign\addList(), Ctct\Services\ActivityService\addRemoveContactsFromListsActivity(), Ctct\Services\ActivityService\addRemoveContactsFromListsActivityFromFile(), Ctct\Services\CampaignScheduleService\addSchedule(), Ctct\Services\ActivityService\createAddContactsActivity(), Ctct\Services\ActivityService\createAddContactsActivityFromFile(), Ctct\Services\EmailMarketingService\deleteCampaign(), Ctct\Services\ContactService\deleteContact(), Ctct\Services\ContactService\deleteContactFromList(), Ctct\Services\ContactService\deleteContactFromLists(), Ctct\Services\CampaignScheduleService\deleteSchedule(), Ctct\Auth\CtctOAuth2\getAccessToken(), Ctct\Services\ActivityService\getActivities(), Ctct\Services\ActivityService\getActivity(), Ctct\Auth\CtctOAuth2\getAuthorizationUrl(), Ctct\Services\ContactTrackingService\getBounces(), Ctct\Services\CampaignTrackingService\getBounces(), Ctct\Services\EmailMarketingService\getCampaign(), Ctct\Services\EmailMarketingService\getCampaigns(), Ctct\Services\CampaignTrackingService\getClicks(), Ctct\Services\ContactTrackingService\getClicks(), Ctct\Services\ContactService\getContact(), Ctct\Services\ContactService\getContacts(), Ctct\Services\ListService\getContactsFromList(), Ctct\Services\CampaignTrackingService\getForwards(), Ctct\Services\ContactTrackingService\getForwards(), Ctct\Services\ListService\getList(), Ctct\Services\ListService\getLists(), Ctct\Services\CampaignTrackingService\getOpens(), Ctct\Services\ContactTrackingService\getOpens(), Ctct\Services\CampaignScheduleService\getSchedule(), Ctct\Services\CampaignScheduleService\getSchedules(), Ctct\Services\CampaignTrackingService\getSends(), Ctct\Services\ContactTrackingService\getSends(), Ctct\Services\CampaignTrackingService\getSummary(), Ctct\Services\ContactTrackingService\getSummary(), Ctct\Auth\CtctOAuth2\getTokenInfo(), Ctct\Services\CampaignTrackingService\getUnsubscribes(), Ctct\Services\ContactTrackingService\getUnsubscribes(), Ctct\Services\AccountService\getVerifiedEmailAddresses(), Ctct\Services\CampaignScheduleService\sendTest(), Ctct\Services\EmailMarketingService\updateCampaign(), Ctct\Services\ContactService\updateContact(), Ctct\Services\ListService\updateList(), and Ctct\Services\CampaignScheduleService\updateSchedule().
     {
         $index = explode('.', $index);
         return self::getValue($index, self::$props);
     }
static Ctct\Util\Config::getValue ($index, $value) static private
Navigate through a config array looking for a particular index.
Parameters
array $index The index sequence we are navigating down
array $value The portion of the config array to process
Returns
mixed
Definition at line 135 of file Config.php.
     {
         if (is_array($index) && count($index)) {
             $current_index = array_shift($index);
         }
         if (is_array($index) && count($index) && is_array($value[$current_index]) && count($value[$current_index])) {
             return self::getValue($index, $value[$current_index]);
         } else {
             return $value[$current_index];
         }
     }
Field Documentation
Ctct\Util\Config::$props static private
Definition at line 15 of file Config.php.
The documentation for this class was generated from the following file:
Config.php