Constant Contact for WordPress: CTCTException Class Reference
CTCTException Class Reference
Public Member Functions
__construct ($message, $code=0, Exception $previous=null)
generateError ($msgPrefix=null)
Private Member Functions
logError ($errorText, $file="error.log")
Detailed Description
Definition at line 1434 of file Components.php.
Constructor & Destructor Documentation
CTCTException::__construct ($message, $code = 0, Exception $previous = null)
Definition at line 1435 of file Components.php.
{
         parent::__construct($message, $code);
     }
Member Function Documentation
CTCTException::generateError ($msgPrefix = null)
Definition at line 1439 of file Components.php.
References logError().
Referenced by ConstantContact\__construct(), Utility\findUrl(), CampaignsCollection\getCampaignsByStatus(), CTCTRequest\makeRequest(), ContactsCollection\searchContactsByLastUpdate(), LibraryCollection\uploadImage(), and CCObject\validate().
{
         $this->logError($this->message);
         echo $msgPrefix.' '.$this->getMessage().'<br />';
     }
CTCTException::logError ($errorText, $file = "error.log") private
Definition at line 1444 of file Components.php.
Referenced by generateError().
{
         date_default_timezone_set('America/New_York');
         $message = "Constant Contact Exception -- ".date("F j, Y, g:i:sa")."\n".$errorText."\n";
         $message .= "Stack Trace: ".$this->getTraceAsString()."\n";
         error_log($message."\n", 3, $file);
     }
The documentation for this class was generated from the following file:
Components.php