Constant Contact for WordPress: CCObject Class Reference
CCObject Class Reference
Protected Member Functions
validate (Array $params)
Validate an object to check that all required fields have been supplied array $params - object property names to reference for validation before HTTP requests.
Detailed Description
Definition at line 2 of file Components.php.
Member Function Documentation
CCObject::validate (Array $params) protected
Validate an object to check that all required fields have been supplied array $params - object property names to reference for validation before HTTP requests.
Returns
void
Definition at line 8 of file Components.php.
References CTCTException\generateError().
Referenced by ContactList\createXml(), Contact\createXml(), Campaign\createXml(), Folder\createXml(), Image\createXml(), and Schedule\createXml().
{
         try{
             foreach($params as $field){
                 if(empty($this->$field)){
                     throw new CTCTException("Constant Contact ".get_class($this)." Error: '".$field."' was required but not supplied");
                 }
             }
         } catch (CTCTException $e){
             $e->generateError();
         }
     }
The documentation for this class was generated from the following file:
Components.php