Constant Contact for WordPress: KWSLog Class Reference
KWSLog Class Reference
Katz Web Services, Inc.
Public Member Functions
load ()
getInstance ()
__construct ($name= 'KWS Log')
wp_enqueue_scripts ()
wp_head ()
log_menu ()
Add the admin menu to the Tools menu.
activate_plugin ()
log_deactivate_plugin ()
debug ($message= '')
print_logs ()
Output logs that were generated while the page was being generated.
log_message ($message, $level= 'debug', $recursive=false)
Create a log message.
get_log_messages ($start=0, $limit=50, $recursive=false)
log_page ()
Private Attributes
$logs = array()
Static Private Attributes
static $name = 'KWS'
static $slug = 'kwslog'
static $tablename
static $instance
Detailed Description
Katz Web Services, Inc.
's logger of choice!
Requires WordPress
Easy to drop in to plugins. Pretty sweet.
Definition at line 26 of file kwslog.php.
Constructor & Destructor Documentation
KWSLog::__construct ($name = 'KWS Log')
Register the action for the logger.
Trigger a log item using `do_action('$tablename', $message, $loglevel);`
Definition at line 48 of file kwslog.php.
References $slug.
{
         $slug = sanitize_title( str_replace(array(ABSPATH, 'plugins/', 'wp-content/', 'mu-plugins/', '/lib'), '', __DIR__) );
         self::$slug = $slug;
         self::$tablename = $slug.'_log';
         /**
          * Register the action for the logger.
          *
          * Trigger a log item using `do_action('$tablename', $message, $loglevel);`
          */
         add_action(self::$tablename, array(&$this, "log_message") ,1,2);
         add_action(self::$slug.'_debug', array(&$this, "debug"));
         add_action('admin_menu', array(&$this, 'log_menu'));
         add_action('wp_enqueue_scripts', array(&$this, 'wp_enqueue_scripts'));
         add_action('wp_head', array(&$this, 'wp_head'));
         add_action('shutdown', array(&$this, 'print_logs'), 10000);
     }
Member Function Documentation
KWSLog::activate_plugin ()
Definition at line 111 of file kwslog.php.
References $tablename.
Referenced by get_log_messages(), and log_message().
{
         global $wpdb;
         $tablename = $wpdb->prefix . self::$tablename;
         if($wpdb->get_var("SHOW TABLES LIKE '{$tablename}'") != $tablename ) {
             $sql = "CREATE TABLE IF NOT EXISTS `{$tablename}` (
                     `log_id` int(11) NOT NULL AUTO_INCREMENT,
                     `message` text NOT NULL,
                     `level` varchar(20) NOT NULL,
                     `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                      PRIMARY KEY (`log_id`)
                 );";
             require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
             dbDelta($sql);
         }
     }
KWSLog::debug ($message = '')
Definition at line 140 of file kwslog.php.
References $logs.
Referenced by wp_head().
{
         $bt = debug_backtrace();
         foreach($bt as $call) {
             if($call['function'] === 'do_action' && $call['args'][0] === 'ctct_debug') {
                 $caller = $call;
                 // do_action and title
                 unset($caller['args'][0]);
                 if(is_string($caller['args'][1])) {
                     unset($caller['args'][1]);
                 }
                 break;
             }
             if(isset($call['line']) && $call['function'] === 'debug' && $call['class'] === 'KWSLog') {
                 $caller = $call;
                 if(!empty($message)) {
                     unset($caller['args'][0]);
                 }
                 break;
             }
         }
         if(!empty($message) && is_string($message)) {
             $message = '<h4>'.$message.'</h4>';
             $hidedata = 'display:none;';
         } elseif(!is_string($message)){
             $message = '';
             $hidedata = '';
         }
         $additional_data = '';
         if(!empty($caller['args'])) {
             foreach($caller['args'] as &$arg) {
                 if(is_string($arg)){
                     $arg = htmlentities2($arg);
                 }
             }
             $additional_data = '<div><a href="#" class="kwslog-toggle">View Data</a></div><div class="data" style="'.$hidedata.'"><pre>'.print_r($caller['args'], true).'</pre></div>';
         }
         $debug_message = '<div class="kwslog-debug">'.$message.'<p><code>'.str_replace(ABSPATH, '', $caller['file']).'</code>, line <code>'.$caller['line'].'</code></p>'.$additional_data.'</div>';
         $logs = (array)$this->logs;
         $logs[] = $debug_message;
         $this->logs = $logs;
     }
KWSLog::get_log_messages ($start = 0, $limit = 50, $recursive = false)
Definition at line 228 of file kwslog.php.
References $tablename, and activate_plugin().
Referenced by log_page().
{
         global $wpdb;
         $tablename = self::$tablename;
         $results = $wpdb->get_results($wpdb->prepare("SELECT message, level, date
             FROM  `{$wpdb->prefix}{$tablename}`
             ORDER BY date DESC
             LIMIT %d,%d", $start,$limit));
         if(!empty($wpdb->last_error) && preg_match('/doesn\'t\ exist/ism', $wpdb->last_error) && !$recursive) {
             $this->activate_plugin();
             $this->get_log_messages($start, $limit, true);
         }
         return $results;
     }
KWSLog::getInstance ()
Definition at line 39 of file kwslog.php.
{
         if(empty(self::$instance)){
             self::$instance = new KWSLog();
         }
         return self::$instance;
     }
KWSLog::load ()
Definition at line 34 of file kwslog.php.
                     {
         $KWSLog = new KWSLog();
         self::$instance = $KWSLog;
     }
KWSLog::log_deactivate_plugin ()
Definition at line 136 of file kwslog.php.
{
     }
KWSLog::log_menu ()
Add the admin menu to the Tools menu.
Definition at line 104 of file kwslog.php.
{
         add_management_page(__(self::$name, 'kwslog'), sprintf(__('%s Log', 'kwslog'), self::$name), 'manage_options', __FILE__, array(&$this, 'log_page'));
     }
KWSLog::log_message ($message, $level = 'debug', $recursive = false)
Create a log message.
If the log table doesn't exist (it should be created on activation), create the log table.
Parameters
mixed $message What the log message should include.
string $level Debug level. Default: 'debug'
boolean $recursive Whether or not the message is being called by itself. Only here to prevent infinite loop.
Definition at line 206 of file kwslog.php.
References activate_plugin().
{
         global $wpdb;
         $message = is_string($message) ? $message : print_r($message, true);
         $values = array(
             'message' => $message,
             'level' => $level
         );
         $wpdb->insert($wpdb->prefix.self::$tablename, $values, array('%s','%d'));
         if(!empty($wpdb->last_error) && preg_match('/doesn\'t\ exist/ism', $wpdb->last_error) && !$recursive) {
             $this->activate_plugin();
             $this->log_message($message, $level, true);
         }
     }
KWSLog::log_page ()
Definition at line 250 of file kwslog.php.
References get_log_messages().
     {
         if (!is_super_admin())
             redirect_post();
         $logdata = $this->get_log_messages(0,40);
     ?>
         <div class="wrap">
             <h2><?php _e(sprintf('%s Log', self::$name), 'kwslog'); ?></h2>
              <table class="widefat post">
                 <thead>
                 <tr>
                     <th class="title"><?php _e('Message', 'kwslog')?></th>
                     <th class=""><?php _e('Level', 'kwslog')?></th>
                     <th class="date"><?php _e('Date', 'kwslog')?></th>
                 </tr>
                 </thead>
                     <tbody>
                     <?php foreach ($logdata as $logEntry) {?>
                         <tr>
                             <td><pre><?php echo $logEntry->message ?></pre></td>
                             <td><?php echo $logEntry->level ?></td>
                             <td><?php echo $logEntry->date ?></td>
                         </tr>
                     <?php }?>
                 </tbody>
             </table>
         </div>
     <?php
     }
KWSLog::print_logs ()
Output logs that were generated while the page was being generated.
Definition at line 191 of file kwslog.php.
{
         if(!current_user_can('manage_options') || defined('DOING_AJAX')) { return; }
         if(empty($this->logs)) { return; }
         foreach($this->logs as $log) {
             echo $log;
         }
     }
KWSLog::wp_enqueue_scripts ()
Definition at line 70 of file kwslog.php.
{
         if(current_user_can('manage_options')) {
             wp_enqueue_script('jquery');
         }
     }
KWSLog::wp_head ()
Definition at line 76 of file kwslog.php.
References debug().
{
         if(current_user_can('manage_options')) {
             ?>
             <script>
                 jQuery('.kwslog-toggle').live('click', function(e) {
                     jQuery('.data', jQuery(this).parents('.kwslog-debug')).toggle();
                     return false;
                 });
             </script>
             <style type="text/css">
                 .kwslog-debug {
                     margin:10px 0 20px;
                     padding:10px;
                     border-top: 1px solid #ccc;
                     border-bottom: 1px solid #ccc;
                     background: rgba(240,240,240,.5);
                 }
                 .kwslog-debug pre {
                     overflow-x:auto; whitespace:pre-line
                 }
             </style>
             <?php
         }
     }
Field Documentation
KWSLog::$instance static private
Definition at line 31 of file kwslog.php.
KWSLog::$logs = array() private
Definition at line 32 of file kwslog.php.
Referenced by debug().
KWSLog::$name = 'KWS' static private
Definition at line 28 of file kwslog.php.
KWSLog::$slug = 'kwslog' static private
Definition at line 29 of file kwslog.php.
Referenced by __construct().
KWSLog::$tablename static private
Definition at line 30 of file kwslog.php.
Referenced by activate_plugin(), and get_log_messages().
The documentation for this class was generated from the following file:
kwslog.php