Constant Contact for WordPress: CampaignsCollection Class Reference
CampaignsCollection Class Reference
Public Member Functions
__construct ($CTCTRequest)
CampaingCollection constructor.
getCampaigns ($page=null)
Get a page of Campaigns.
getCampaignDetails ($url)
Get detailed Campaign object.
updateCampaign (Campaign $Campaign)
Update a campaign with it's current properties.
getCampaignsByStatus ($status, $page=null)
Get a page of campaigns by status.
scheduleCampaign (Campaign $Campaign, $time)
Schedule an email for delivery.
getSchedule (Campaign $Campaign)
Get a schedule for an email.
deleteSchedule (Campaign $Campaign)
Delete a schedule from a campaign (prevent from sending)
getCampaignEvents ($url, $eventType)
deleteCampaign ($url)
Delete a Campaign.
addCampaign (Campaign $Campaign)
Add a new Campaign.
Public Member Functions inherited from Collection
__construct (CTCTRequest $CTCTRequest, $collectionUri)
Collection constructor.
Data Fields
$CTCTRequest
$uri
Data Fields inherited from Collection
$CTCTRequest
$uri
Detailed Description
Definition at line 265 of file Collections.php.
Constructor & Destructor Documentation
CampaignsCollection::__construct ($CTCTRequest)
CampaingCollection constructor.
Parameters
CTCTReques $CTCTRequest
Definition at line 273 of file Collections.php.
References $CTCTRequest.
{
         parent::__construct($CTCTRequest, '/ws/customers/'.$CTCTRequest->username.'/campaigns');
     }
Member Function Documentation
CampaignsCollection::addCampaign (Campaign $Campaign)
Add a new Campaign.
Exceptions
CTCTException - If campaign subject/name are not set
Parameters
Campaign $Campaign
Returns
Campaign
Definition at line 410 of file Collections.php.
References Campaign\createStruct(), Campaign\createXml(), and CTCTRequest\makeRequest().
{
         $campaignXml = $Campaign->createXml();
         $response = $this->CTCTRequest->makeRequest($this->uri, 'POST', $campaignXml);
         $parsedResponse = simplexml_load_string($response['xml']);
         return new Campaign(Campaign::createStruct($parsedResponse));
     }
CampaignsCollection::deleteCampaign ($url)
Delete a Campaign.
Parameters
string $url - url to a campaign
Returns
bool - true is successful, else false
Definition at line 399 of file Collections.php.
References CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'DELETE');
         return ($response['info']['http_code'] == 204) ? true : false;
     }
CampaignsCollection::deleteSchedule (Campaign $Campaign)
Delete a schedule from a campaign (prevent from sending)
Parameters
Campaign $Campaign - Campaign to delete schedule for
Returns
bool - true is successful, else false
Definition at line 372 of file Collections.php.
References CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($this->CTCTRequest->baseUri.$Campaign->link.'/schedules/1', 'DELETE');
         if($response['info']['http_code'] == 204){ return true; }
         else{ return false; }
     }
CampaignsCollection::getCampaignDetails ($url)
Get detailed Campaign object.
Parameters
string $url - url of a Campiagn
Returns
Campaign
Definition at line 299 of file Collections.php.
References Campaign\createStruct(), and CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $parsedReturn = simplexml_load_string($response['xml']);
         return new Campaign(Campaign::createStruct($parsedReturn));
     }
CampaignsCollection::getCampaignEvents ($url, $eventType)
Parameters
string url - url to use to access events from
string $eventType - Sends, Forwards, Bounces, OptOuts, Opens
Returns
array - Found CampaignEvents
Definition at line 383 of file Collections.php.
References CampaignEvent\createStruct(), Utility\findNextLink(), and CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $parsedResponse = simplexml_load_string($response['xml']);
         $events = array();
         foreach($parsedResponse->entry as $entry){
             $events['events'][] = new CampaignEvent(CampaignEvent::createStruct($entry, $eventType));
         }
     $events['nextLink'] = Utility::findNextLink($parsedResponse);
         return $events;
     }
CampaignsCollection::getCampaigns ($page = null)
Get a page of Campaigns.
Parameters
string $page - url to page of campaigns, default is first page
Returns
array - array of Campaign objects and a link to the next page if one exists
Definition at line 282 of file Collections.php.
References Campaign\createOverviewStruct(), Utility\findNextLink(), and CTCTRequest\makeRequest().
{
         $page = ($page) ? $this->CTCTRequest->baseUri.$page : $this->uri;
         $campaignsCollection = array('campaigns' => array(), 'nextLink' => '');
         $response = $this->CTCTRequest->makeRequest($page, 'GET');
         $parsedResponse = simplexml_load_string($response['xml']);
         foreach ($parsedResponse->entry as $entry){
             $campaignsCollection['campaigns'][] = new Campaign(Campaign::createOverviewStruct($entry));
         }
         $campaignsCollection['nextLink'] = Utility::findNextLink($parsedResponse);
         return $campaignsCollection;
     }
CampaignsCollection::getCampaignsByStatus ($status, $page = null)
Get a page of campaigns by status.
Parameters
string $status - draft, running, sent, scheduled
Returns
array - array of campaigns a link to the next page if one exists
Definition at line 320 of file Collections.php.
References Campaign\createOverviewStruct(), Utility\findNextLink(), CTCTException\generateError(), and CTCTRequest\makeRequest().
{
         $statusList = array('sent', 'draft', 'running', 'scheduled');
         $status = strtolower($status);
         $campaignsCollection = array('campaigns' => array(), 'nextLink' => '');
         try{
             if(!in_array($status, $statusList)){throw new CTCTException("Campaign status '".$status."' is not a valid option");}
             $url = ($page) ? $this->CTCTRequest->baseUri.$page : $this->uri.'?status='.$status;
             $response = $this->CTCTRequest->makeRequest($url, 'GET');
             $parsedResponse = simplexml_load_string($response['xml']);
             foreach ($parsedResponse->entry as $entry){
                 $campaignsCollection['campaigns'][] = new Campaign(Campaign::createOverviewStruct($entry));
             }
             $campaignsCollection['nextLink'] = Utility::findNextLink($parsedResponse);
         } catch (CTCTException $e) {
             $e->generateError();
         }
         return ($campaignsCollection['campaigns']) ? $campaignsCollection : false;
     }
CampaignsCollection::getSchedule (Campaign $Campaign)
Get a schedule for an email.
Parameters
Campaign $Campaign - Email to obtain schedule for
Returns
bool|Schedule - Returns schedule if found, else false
Definition at line 360 of file Collections.php.
References Schedule\createStruct(), and CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($this->CTCTRequest->baseUri.$Campaign->link.'/schedules', 'GET');
         $parsedResponse = simplexml_load_string($response['xml']);
         if($parsedResponse->entry){return new Schedule(Schedule::createStruct($parsedResponse->entry));}
         else{ return false; }
     }
CampaignsCollection::scheduleCampaign (Campaign $Campaign, $time)
Schedule an email for delivery.
Parameters
Campaign $Campaign - Campaign to be scheduled
string $scheduleTime - Date/Time for the email to be delivered
Returns
bool - true if success, else false
Definition at line 345 of file Collections.php.
References Schedule\createStruct(), Campaign\createXml(), and CTCTRequest\makeRequest().
{
         $Schedule = new Schedule();
         $Schedule->campaign = $Campaign;
         $Schedule->time = $time;
         $schedXml = $Schedule->createXml();
         $response =  $this->CTCTRequest->makeRequest($this->CTCTRequest->baseUri.$Campaign->link.'/schedules', 'POST', $schedXml);
         $parsedResponse = simplexml_load_string($response['xml']);
         return new Schedule(Schedule::createStruct($parsedResponse));
     }
CampaignsCollection::updateCampaign (Campaign $Campaign)
Update a campaign with it's current properties.
Parameters
Campaign $Campaign - Campaign to be updated
Returns
bool - true if success, else false
Definition at line 310 of file Collections.php.
References Campaign\createXml(), and CTCTRequest\makeRequest().
{
         $response =  $this->CTCTRequest->makeRequest($this->CTCTRequest->baseUri.$Campaign->link, 'PUT', $Campaign->createXml());
         return ($response['info']['http_code'] == 204) ? true : false;
     }
Field Documentation
CampaignsCollection::$CTCTRequest
Definition at line 266 of file Collections.php.
Referenced by __construct().
CampaignsCollection::$uri
Definition at line 267 of file Collections.php.
The documentation for this class was generated from the following file:
Collections.php