Constant Contact for WordPress: ContactList Class Reference
ContactList Class Reference
Public Member Functions
__construct ($params=array())
Constructor.
createXml ()
Create XML Representation of the object.
Static Public Member Functions
static createStruct ($parsedReturn)
Create associate array of object from XML.
static createMemberStruct ($parsedResponse)
Data Fields
$contactCount
$displayOnSignup
$id
$link
$name
$optInDefault
$sortOrder
$updated
Additional Inherited Members
Protected Member Functions inherited from CCObject
validate (Array $params)
Validate an object to check that all required fields have been supplied array $params - object property names to reference for validation before HTTP requests.
Detailed Description
Definition at line 23 of file Components.php.
Constructor & Destructor Documentation
ContactList::__construct ($params = array())
Constructor.
Parameters
array $params - associative array of properties/values
Definition at line 37 of file Components.php.
{
         $this->contactCount = (isset($params['contactCount'])) ? $params['contactCount'] : '';
         $this->displayOnSignup = (isset($params['displayOnSignup'])) ? $params['displayOnSignup'] : '';
         $this->id = (isset($params['id'])) ? $params['id'] : 'data:,';
         $this->link = (isset($params['link'])) ? $params['link'] : '';
         $this->name = (isset($params['name'])) ? $params['name'] : '';
         $this->optInDefault = (isset($params['optInDefault'])) ? $params['optInDefault'] : '';
         $this->sortOrder = (isset($params['sortOrder'])) ? $params['sortOrder'] : '99';
         $this->updated = (isset($params['updated'])) ? $params['updated'] : '';
     }
Member Function Documentation
static ContactList::createMemberStruct ($parsedResponse) static
Definition at line 87 of file Components.php.
Referenced by ListsCollection\getListMembers().
{
         $contact['link'] = (string) $parsedResponse->link->Attributes()->href;
         $contact['id'] = (string) $parsedResponse->id;
         $contact['updated'] = (string) $parsedResponse->updated;
         $contact['emailAddress'] = (string) $parsedResponse->content->ContactListMember->EmailAddress;
         $contact['fullName'] = (string) $parsedResponse->content->ContactListMember->Name;
         return $contact;
     }
static ContactList::createStruct ($parsedReturn) static
Create associate array of object from XML.
Parameters
SimpleXMLElement $parsedReturn - parsed XML
Returns
Definition at line 54 of file Components.php.
Referenced by ListsCollection\addList(), ListsCollection\getListDetails(), and ListsCollection\getLists().
{
         $list['link'] = (string) $parsedReturn->link->Attributes()->href;
         $list['id'] = (string) $parsedReturn->id;
         $list['optInDefault'] = (string) $parsedReturn->content->ContactList->OptInDefault;
         $list['name'] = (string) $parsedReturn->content->ContactList->Name;
         $list['displayOnSignup'] = (string) $parsedReturn->content->ContactList->DisplayOnSignup;
         $list['sortOrder'] = (string) $parsedReturn->content->ContactList->SortOrder;
         $list['contactCount'] = (string) $parsedReturn->content->ContactList->ContactCount;
         return $list;
     }
ContactList::createXml ()
Create XML Representation of the object.
Returns
SimpleXMLElement
Definition at line 69 of file Components.php.
References CCObject\validate().
Referenced by ListsCollection\addList(), and ListsCollection\updateList().
{
         $this->validate(array('name', 'id'));
         $xml_string = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><entry xmlns='http://www.w3.org/2005/Atom'></entry>";
         $xml = simplexml_load_string($xml_string);
         $xml->addChild("id", $this->id);
         $xml->addChild("title");
         $xml->addChild("author");
         $xml->addChild("updated", "2008-04-16");
         $contentNode = $xml->addChild("content");
         $contentNode->addAttribute("type", "application/vnd.ctct+xml");
         $listNode = $contentNode->addChild("ContactList");
         $listNode->addAttribute("xmlns", "http://ws.constantcontact.com/ns/1.0/");
         $listNode->addChild("OptInDefault", $this->optInDefault);
         $listNode->addChild("Name", $this->name);
         $listNode->addChild("SortOrder", $this->sortOrder);
         return $xml->asXML();
     }
Field Documentation
ContactList::$contactCount
Definition at line 24 of file Components.php.
ContactList::$displayOnSignup
Definition at line 25 of file Components.php.
ContactList::$id
Definition at line 26 of file Components.php.
ContactList::$link
Definition at line 27 of file Components.php.
ContactList::$name
Definition at line 28 of file Components.php.
ContactList::$optInDefault
Definition at line 29 of file Components.php.
ContactList::$sortOrder
Definition at line 30 of file Components.php.
ContactList::$updated
Definition at line 31 of file Components.php.
The documentation for this class was generated from the following file:
Components.php