Constant Contact for WordPress: Ctct\Components\EmailMarketing\Campaign Class Reference
Ctct\Components\EmailMarketing\Campaign Class Reference
Public Member Functions
addList ($contact_list)
Add a contact list to set of lists associated with this email.
toJson ()
Create json used for a POST/PUT request, also handles removing attributes that will cause errors if sent.
Static Public Member Functions
static create (array $props)
Factory method to create a Campaign object from an array.
static createSummary (array $props)
Factory method to create a Campaign object from an array.
Data Fields
$id
$name
$subject
$status
$from_name
$from_email
$reply_to_email
$template_type
$created_date
$modified_date
$last_run_date
$next_run_date
$is_permission_reminder_enabled
$permission_reminder_text
$is_view_as_webpage_enabled
$view_as_web_page_text
$view_as_web_page_link_text
$greeting_salutations
$greeting_name
$greeting_string
$message_footer
$tracking_summary
$email_content
$email_content_format
$style_sheet
$text_content
$sent_to_contact_lists = array()
$click_through_details = array()
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Components\Component
static getValue (array $array, $item, $default=null)
Get the requested value from an array, or return the default.
Detailed Description
Definition at line 19 of file Campaign.php.
Member Function Documentation
Ctct\Components\EmailMarketing\Campaign::addList ($contact_list)
Add a contact list to set of lists associated with this email.
Parameters
mixed $contact_list - Contact list id, or ContactList object
Definition at line 275 of file Campaign.php.
References Ctct\Util\Config\get().
     {
         if ($contact_list instanceof ContactList) {
             $list = $contact_list;
         } elseif (is_numeric($contact_list)) {
             $list = new ContactList($contact_list);
         } else {
             throw new IllegalArgumentException(sprintf(Config::get('errors.id_or_object'), 'ContactList'));
         }
         $this->sent_to_contact_lists[] = $list;
     }
static Ctct\Components\EmailMarketing\Campaign::create (array $props) static
Factory method to create a Campaign object from an array.
Parameters
array $props - associative array of initial properties to set
Returns
Campaign
Definition at line 196 of file Campaign.php.
References Ctct\Components\EmailMarketing\Campaign\$click_through_details, Ctct\Components\Tracking\TrackingSummary\create(), Ctct\Components\EmailMarketing\MessageFooter\create(), Ctct\Components\EmailMarketing\ClickThroughDetails\create(), and Ctct\Components\Contacts\ContactList\create().
Referenced by Ctct\Services\EmailMarketingService\addCampaign(), Ctct\Services\EmailMarketingService\getCampaign(), and Ctct\Services\EmailMarketingService\updateCampaign().
     {
         $campaign = new Campaign();
         $campaign->id = parent::getValue($props, "id");
         $campaign->name = parent::getValue($props, "name");
         $campaign->subject = parent::getValue($props, "subject");
         $campaign->from_name = parent::getValue($props, "from_name");
         $campaign->from_email = parent::getValue($props, "from_email");
         $campaign->reply_to_email = parent::getValue($props, "reply_to_email");
         $campaign->template_type = parent::getValue($props, "template_type");
         $campaign->created_date = parent::getValue($props, "created_date");
         $campaign->modified_date = parent::getValue($props, "modified_date");
         $campaign->last_run_date = parent::getValue($props, "last_run_date");
         $campaign->next_run_date = parent::getValue($props, "next_run_date");
         $campaign->status = parent::getValue($props, "status");
         $campaign->is_permission_reminder_enabled = parent::getValue($props, "is_permission_reminder_enabled");
         $campaign->permission_reminder_text = parent::getValue($props, "permission_reminder_text");
         $campaign->is_view_as_webpage_enabled = parent::getValue($props, "is_view_as_webpage_enabled");
         $campaign->view_as_web_page_text = parent::getValue($props, "view_as_web_page_text");
         $campaign->view_as_web_page_link_text = parent::getValue($props, "view_as_web_page_link_text");
         $campaign->greeting_salutations = parent::getValue($props, "greeting_salutations");
         $campaign->greeting_name = parent::getValue($props, "greeting_name");
         $campaign->greeting_string = parent::getValue($props, "greeting_string");
         if (array_key_exists("message_footer", $props)) {
             $campaign->message_footer = MessageFooter::create($props['message_footer']);
         }
         if (array_key_exists("tracking_summary", $props)) {
             $campaign->tracking_summary = TrackingSummary::create($props['tracking_summary']);
         }
         $campaign->email_content = parent::getValue($props, "email_content");
         $campaign->email_content_format = parent::getValue($props, "email_content_format");
         $campaign->style_sheet = parent::getValue($props, "style_sheet");
         $campaign->text_content = parent::getValue($props, "text_content");
         if (array_key_exists('sent_to_contact_lists', $props)) {
             foreach ($props['sent_to_contact_lists'] as $sent_to_contact_list) {
                 $campaign->sent_to_contact_lists[] = ContactList::create($sent_to_contact_list);
             }
         }
         if (array_key_exists('click_through_details', $props)) {
             foreach ($props['click_through_details'] as $click_through_details) {
                 $campaign->click_through_details[] = ClickThroughDetails::create($click_through_details);
             }
         }
         return $campaign;
     }
static Ctct\Components\EmailMarketing\Campaign::createSummary (array $props) static
Factory method to create a Campaign object from an array.
Parameters
array $props - associative array of initial properties to set
Returns
Campaign
Definition at line 253 of file Campaign.php.
Referenced by Ctct\Services\EmailMarketingService\getCampaigns().
     {
         $campaign = new Campaign();
         $campaign->id = parent::getValue($props, "id");
         $campaign->name = parent::getValue($props, "name");
         $campaign->status = parent::getValue($props, "status");
         $campaign->modified_date = parent::getValue($props, "modified_date");
         // remove unused fields
         foreach ($campaign as $key => $value) {
             if ($value == null) {
                 unset($campaign->$key);
             }
         }
         return $campaign;
     }
Ctct\Components\EmailMarketing\Campaign::toJson ()
Create json used for a POST/PUT request, also handles removing attributes that will cause errors if sent.
Returns
string
Definition at line 292 of file Campaign.php.
Referenced by Ctct\Services\EmailMarketingService\addCampaign(), and Ctct\Services\EmailMarketingService\updateCampaign().
     {
         $campaign = clone $this;
         unset($campaign->id);
         unset($campaign->created_date);
         unset($campaign->last_run_date);
         unset($campaign->next_run_date);
         unset($campaign->tracking_summary);
         unset($campaign->click_through_details);
         if (is_null($campaign->message_footer)) {
             unset($campaign->message_footer);
         }
         if (empty($campaign->sent_to_contact_lists)) {
             unset($campaign->sent_to_contact_lists);
         } else {
             // remove sent_to_contact_lists fields that cause errors
             foreach ($campaign->sent_to_contact_lists as $list) {
                 unset($list->name);
                 unset($list->contact_count);
                 unset($list->status);
             }
         }
         return json_encode($campaign);
     }
Field Documentation
Ctct\Components\EmailMarketing\Campaign::$click_through_details = array()
Definition at line 189 of file Campaign.php.
Referenced by Ctct\Components\EmailMarketing\Campaign\create().
Ctct\Components\EmailMarketing\Campaign::$created_date
Definition at line 73 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$email_content
Definition at line 158 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$email_content_format
Definition at line 164 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$from_email
Definition at line 55 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$from_name
Definition at line 49 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$greeting_name
Definition at line 134 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$greeting_salutations
Definition at line 128 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$greeting_string
Definition at line 140 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$id
Definition at line 25 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$is_permission_reminder_enabled
Definition at line 97 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$is_view_as_webpage_enabled
Definition at line 110 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$last_run_date
Definition at line 85 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$message_footer
Definition at line 146 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$modified_date
Definition at line 79 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$name
Definition at line 31 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$next_run_date
Definition at line 91 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$permission_reminder_text
Definition at line 103 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$reply_to_email
Definition at line 61 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$sent_to_contact_lists = array()
Definition at line 183 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$status
Definition at line 43 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$style_sheet
Definition at line 170 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$subject
Definition at line 37 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$template_type
Definition at line 67 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$text_content
Definition at line 177 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$tracking_summary
Definition at line 152 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$view_as_web_page_link_text
Definition at line 122 of file Campaign.php.
Ctct\Components\EmailMarketing\Campaign::$view_as_web_page_text
Definition at line 116 of file Campaign.php.
The documentation for this class was generated from the following file:
Campaign.php