Constant Contact for WordPress: ExceptionalData Class Reference
ExceptionalData Class Reference
Public Member Functions
__construct (Exception $exception)
uniqueness_hash ()
to_json ()
fill_keys (&$arr, $keys)
filter_params ($params, $term)
Protected Attributes
$exception
$backtrace = array()
Detailed Description
Definition at line 3 of file data.php.
Constructor & Destructor Documentation
ExceptionalData::__construct (Exception $exception)
Definition at line 8 of file data.php.
References Exceptional\$action, Exceptional\$blacklist, Exceptional\$context, Exceptional\$controller, $exception, fill_keys(), filter_params(), and ExceptionalEnvironment\to_array().
{
         $this->exception = $exception;
         $trace = $this->exception->getTrace();
         foreach ($trace as $t) {
             if (!isset($t["file"])) continue;
             $this->backtrace[] = "$t[file]:$t[line]:in `$t[function]\'";
         }
         // environment data
         $data = ExceptionalEnvironment::to_array();
         // exception data
         $message = $this->exception->getMessage();
         $now = gmdate("c");
         // spoof 404 error
         $error_class = get_class($this->exception);
         if ($error_class == "Http404Error") {
             $error_class = "ActionController::UnknownAction";
         }
         $data["exception"] = array(
             "exception_class" => $error_class,
             "message" => $message,
             "backtrace" => $this->backtrace,
             "occurred_at" => $now
         );
         // context
         $context = Exceptional::$context;
         if (!empty($context)) {
             $data["context"] = $context;
         }
         if (isset($_SERVER["HTTP_HOST"])) {
             // request data
             $session = isset($_SESSION) ? $_SESSION : array();
             // sanitize headers
             $headers = getallheaders();
             if (isset($headers["Cookie"])) {
               $sessionKey = preg_quote(ini_get("session.name"), "/");
               $headers["Cookie"] = preg_replace("/$sessionKey=\S+/", "$sessionKey=[FILTERED]", $headers["Cookie"]);
             }
             $server = $_SERVER;
             $keys = array("HTTPS", "HTTP_HOST", "REQUEST_URI", "REQUEST_METHOD", "REMOTE_ADDR");
             $this->fill_keys($server, $keys);
             $protocol = $server["HTTPS"] && $server["HTTPS"] != "off" ? "https://" : "http://";
             $url = $server["HTTP_HOST"] ? "$protocol$server[HTTP_HOST]$server[REQUEST_URI]" : "";
             $data["request"] = array(
                 "url" => $url,
                 "request_method" => strtolower($server["REQUEST_METHOD"]),
                 "remote_ip" => $server["REMOTE_ADDR"],
                 "headers" => $headers,
                 "session" => $session
             );
             $params = array_merge($_GET, $_POST);
             foreach (Exceptional::$blacklist as $filter) {
                 $params = $this->filter_params($params, $filter);
             }
             if (!empty($params)) {
                 $data["request"]["parameters"] = $params;
             }
         }
         else {
           $data["request"] = array();
         }
         $data["request"]["controller"] = Exceptional::$controller;
         $data["request"]["action"] = Exceptional::$action;
         $this->data = $data;
     }
Member Function Documentation
ExceptionalData::fill_keys (& $arr, $keys)
Definition at line 98 of file data.php.
Referenced by __construct().
{
         foreach ($keys as $key) {
             if (!isset($arr[$key])) {
                 $arr[$key] = false;
             }
         }
     }
ExceptionalData::filter_params ($params, $term)
Definition at line 106 of file data.php.
Referenced by __construct().
{
         foreach ($params as $key => $value) {
             if (preg_match("/$term/i", $key)) {
                 $params[$key] = '[FILTERED]';
             }
             elseif (is_array($value)) {
                 $params[$key] = $this->filter_params($value, $term);
             }
         }
         return $params;
     }
ExceptionalData::to_json ()
Definition at line 94 of file data.php.
{
         return json_encode($this->data);
     }
ExceptionalData::uniqueness_hash ()
Definition at line 90 of file data.php.
{
         return md5(implode("", $this->backtrace));
     }
Field Documentation
ExceptionalData::$backtrace = array() protected
Definition at line 6 of file data.php.
ExceptionalData::$exception protected
Definition at line 5 of file data.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
data.php