Constant Contact for WordPress: CTCTOAuth Class Reference
CTCTOAuth Class Reference
Public Member Functions
__construct ($consumer_key, $consumer_secret, $oauth_callback=NULL)
getRequestToken ()
generateAuthorizeUrl ()
getAccessToken ($oauth_verifier)
httpRequest ($url, $auth_header, $method, $body=NULL)
Data Fields
$base_url = "https://api.constantcontact.com"
$secure_base_url = "https://oauth.constantcontact.com"
$oauth_callback = "oob"
$username
$consumer
$request_token
$access_token
$oauth_verifier
$signature_method
$request_token_path
$access_token_path
$authorize_path
$debug = false
Detailed Description
Definition at line 887 of file Authentication.php.
Constructor & Destructor Documentation
CTCTOAuth::__construct ($consumer_key, $consumer_secret, $oauth_callback = NULL)
Definition at line 902 of file Authentication.php.
References $oauth_callback.
{
     if($oauth_callback) {
       $this->oauth_callback = $oauth_callback;
     }
     $this->consumer = new OAuthConsumer($consumer_key, $consumer_secret, $this->oauth_callback);
     $this->signature_method = new OAuthSignatureMethod_HMAC_SHA1();
     $this->request_token_path = $this->secure_base_url . "/ws/oauth/request_token";
     $this->access_token_path = $this->secure_base_url . "/ws/oauth/access_token";
     $this->authorize_path = $this->secure_base_url . "/ws/oauth/confirm_access";
   }
Member Function Documentation
CTCTOAuth::generateAuthorizeUrl ()
Definition at line 928 of file Authentication.php.
References $consumer, and $request_token.
{
     $consumer = $this->consumer;
     $request_token = $this->request_token;
     return $this->authorize_path . "?oauth_token=" . $request_token->key;
   }
CTCTOAuth::getAccessToken ($oauth_verifier)
Definition at line 934 of file Authentication.php.
References $oauth_verifier, OAuthRequest\from_consumer_and_token(), and httpRequest().
{
     $request = OAuthRequest::from_consumer_and_token($this->consumer, $this->request_token, "GET", $this->access_token_path);
     $request->set_parameter("oauth_verifier", $oauth_verifier);
     $request->sign_request($this->signature_method, $this->consumer, $this->request_token);
     $headers = Array();
     $url = $request->to_url();
     $response = $this->httpRequest($url, $headers, "GET");
     parse_str($response, $response_params);
     if($this->debug) {
       echo $response . "\n";
     }
     // Set username
     $this->access_token = new OAuthConsumer($response_params['oauth_token'], $response_params['oauth_token_secret'], 1);
   }
CTCTOAuth::getRequestToken ()
Definition at line 916 of file Authentication.php.
References $consumer, OAuthRequest\from_consumer_and_token(), and httpRequest().
{
     $consumer = $this->consumer;
     $request = OAuthRequest::from_consumer_and_token($consumer, NULL, "GET", $this->request_token_path);
     $request->set_parameter("oauth_callback", $this->oauth_callback);
     $request->sign_request($this->signature_method, $consumer, NULL);
     $headers = Array();
     $url = $request->to_url();
     $response = $this->httpRequest($url, $headers, "GET");
     parse_str($response, $response_params);
     $this->request_token = new OAuthConsumer($response_params['oauth_token'], $response_params['oauth_token_secret'], 1);
   }
CTCTOAuth::httpRequest ($url, $auth_header, $method, $body = NULL)
Definition at line 949 of file Authentication.php.
Referenced by getAccessToken(), and getRequestToken().
{
     if (!$method) {
       $method = "GET";
     };
     $curl = curl_init();
     curl_setopt($curl, CURLOPT_URL, $url);
     curl_setopt($curl, CURLOPT_HEADER, 0);
     curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
     curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
     if($auth_header){curl_setopt($curl, CURLOPT_HTTPHEADER, array($auth_header));} // Set the headers.
     if ($body) {
       curl_setopt($curl, CURLOPT_POST, 1);
       curl_setopt($curl, CURLOPT_POSTFIELDS, $body);
       curl_setopt($curl, CURLOPT_CUSTOMREQUEST, $method);
       curl_setopt($curl, CURLOPT_HTTPHEADER, array($auth_header, "Content-Type: application/atom+xml"));
     }
     $data = curl_exec($curl);
     if ($this->debug) {
       echo $data . "\n";
     }
     curl_close($curl);
     return $data;
   }
Field Documentation
CTCTOAuth::$access_token
Definition at line 894 of file Authentication.php.
CTCTOAuth::$access_token_path
Definition at line 898 of file Authentication.php.
CTCTOAuth::$authorize_path
Definition at line 899 of file Authentication.php.
CTCTOAuth::$base_url = "https://api.constantcontact.com"
Definition at line 888 of file Authentication.php.
CTCTOAuth::$consumer
Definition at line 892 of file Authentication.php.
Referenced by generateAuthorizeUrl(), and getRequestToken().
CTCTOAuth::$debug = false
Definition at line 900 of file Authentication.php.
CTCTOAuth::$oauth_callback = "oob"
Definition at line 890 of file Authentication.php.
Referenced by __construct().
CTCTOAuth::$oauth_verifier
Definition at line 895 of file Authentication.php.
Referenced by getAccessToken().
CTCTOAuth::$request_token
Definition at line 893 of file Authentication.php.
Referenced by generateAuthorizeUrl().
CTCTOAuth::$request_token_path
Definition at line 897 of file Authentication.php.
CTCTOAuth::$secure_base_url = "https://oauth.constantcontact.com"
Definition at line 889 of file Authentication.php.
CTCTOAuth::$signature_method
Definition at line 896 of file Authentication.php.
CTCTOAuth::$username
Definition at line 891 of file Authentication.php.
The documentation for this class was generated from the following file:
Authentication.php