Constant Contact for WordPress: Net_DNS_Question Class Reference
Net_DNS_Question Class Reference
Public Member Functions
Net_DNS_Question ($qname, $qtype, $qclass)
display ()
string ()
data ($packet, $offset)
Data Fields
$qname = null
$qtype = null
$qclass = null
Detailed Description
Definition at line 31 of file Question.php.
Member Function Documentation
Net_DNS_Question::data ($packet, $offset)
Definition at line 75 of file Question.php.
References Net_DNS\classesbyname(), and Net_DNS\typesbyname().
     {
         $data = $packet->dn_comp($this->qname, $offset);
         $data .= pack('n', Net_DNS::typesbyname(strtoupper($this->qtype)));
         $data .= pack('n', Net_DNS::classesbyname(strtoupper($this->qclass)));
         return $data;
     }
Net_DNS_Question::display ()
Definition at line 61 of file Question.php.
References string().
     {
         echo $this->string() . "\n";
     }
Net_DNS_Question::Net_DNS_Question ($qname, $qtype, $qclass)
Definition at line 40 of file Question.php.
References $qclass, $qname, $qtype, Net_DNS\classesbyname(), and Net_DNS\typesbyname().
     {
         $qtype  = !is_null($qtype)  ? strtoupper($qtype)  : 'ANY';
         $qclass = !is_null($qclass) ? strtoupper($qclass) : 'ANY';
         // Check if the caller has the type and class reversed.
         // We are not that kind for unknown types.... :-)
         if ( ( is_null(Net_DNS::typesbyname($qtype)) ||
                is_null(Net_DNS::classesbyname($qtype)) )
           && !is_null(Net_DNS::classesbyname($qclass))
           && !is_null(Net_DNS::typesbyname($qclass)))
         {
             list($qtype, $qclass) = array($qclass, $qtype);
         }
         $qname = preg_replace(array('/^\.+/', '/\.+$/'), '', $qname);
         $this->qname = $qname;
         $this->qtype = $qtype;
         $this->qclass = $qclass;
     }
Net_DNS_Question::string ()
Definition at line 68 of file Question.php.
References $qtype.
Referenced by display().
     {
         return $this->qname . ".\t" . $this->qclass . "\t" . $this->qtype;
     }
Field Documentation
Net_DNS_Question::$qclass = null
Definition at line 36 of file Question.php.
Referenced by Net_DNS_Question().
Net_DNS_Question::$qname = null
Definition at line 34 of file Question.php.
Referenced by Net_DNS_Question().
Net_DNS_Question::$qtype = null
Definition at line 35 of file Question.php.
Referenced by Net_DNS_Question(), and string().
The documentation for this class was generated from the following file:
Question.php