Constant Contact for WordPress: CTCT_Admin_Table Class Reference
CTCT_Admin_Table Class Reference
Public Member Functions
__construct ($tablename=false)
Constructor.
set_data ($data=FALSE)
Set the data you wish to display.
set_name ($name='')
Sets the name (after sanitising)
get_name ()
Getter.
get_id ()
Getter.
set_id ($id=FALSE)
Sets the id for the table.
render ()
Alias to $this->render()
get_html ()
Builds the table and returns HTML ready to echo to the browser.
do_not_esc_th ($tf=FALSE)
Prevent escaping of the table headings.
do_not_esc_td ($tf=FALSE)
Prevent escaping of the table cells.
Data Fields
$id
$data
$name
$do_not_esc_th
$do_not_esc_td
Private Attributes
$html
Class variables should only be accessed using setters and getters.
Detailed Description
Definition at line 13 of file table.php.
Constructor & Destructor Documentation
CTCT_Admin_Table::__construct ($tablename = false)
Constructor.
Sets up the table
Parameters
string $tablename unique name for the table e.g. 'users-list'
Definition at line 31 of file table.php.
References do_not_esc_th(), set_id(), and set_name().
{
         $this->set_name( $tablename );
         $this->set_id( $tablename );
         $this->do_not_esc_th = FALSE;
     }
Member Function Documentation
CTCT_Admin_Table::do_not_esc_td ($tf = FALSE)
Prevent escaping of the table cells.
These are taken from the array keys or object properties of the data you have entered. You might want to pass HTML in which case you do not want the text escaped.
Parameters
boolean $tf
Returns
object table helper
Definition at line 210 of file table.php.
Referenced by get_html().
{
         $this->do_not_esc_td = (bool) $tf;
         return $this;
     }
CTCT_Admin_Table::do_not_esc_th ($tf = FALSE)
Prevent escaping of the table headings.
These are taken from the array keys or object properties of the data you have entered. You might want to pass HTML in which case you do not want the text escaped.
Parameters
boolean $tf
Returns
object table helper
Definition at line 192 of file table.php.
Referenced by __construct(), and get_html().
{
         $this->do_not_esc_th = (bool) $tf;
         return $this;
     }
CTCT_Admin_Table::get_html ()
Builds the table and returns HTML ready to echo to the browser.
Returns
string The HTML table
Definition at line 122 of file table.php.
References $html, do_not_esc_td(), and do_not_esc_th().
Referenced by render().
{
         if( ! empty( $this->data ) ) {
             $this->html = "<table id=\"".$this->get_id()."\" class=\"tina_mvc_table\">";
             $this->html .= "<thead>";
             foreach( $this->data AS & $row ) {
                 $this->html .= "<tr>";
                 foreach( $row AS $f_name => & $f_value ) {
                     if( $this->do_not_esc_th ) {
                         $this->html .= '<th>'.$f_name.'</th>';
                     }
                     else {
                         $this->html .= '<th>'.$f_name.'</th>';
                     }
                 }
                 $this->html .= "</tr>";
                 break;
             }
             $this->html .= "</thead>";
             reset( $this->data );
             $this->html .= "<tbody>";
             $alt = '';
             foreach( $this->data as &$row ) {
                 if($alt == 'alt') { $alt = '';} else { $alt = 'alt'; }
                 $this->html .= "<tr class='{$alt}'>";
                 foreach( $row AS $f_name => & $f_value ) {
                     if( $this->do_not_esc_td ) {
                         $this->html .= '<td>'.$f_value.'</td>';
                     }
                     else {
                         $this->html .= '<td>'.$f_value.'</td>';
                     }
                 }
                 $this->html .= "</tr>";
             }
             $this->html .= "</tbody>";
             $this->html .= '</table>';
             return $this->html;
         }
         else {
             return '';
         }
     }
CTCT_Admin_Table::get_id ()
Getter.
Returns
string
Definition at line 87 of file table.php.
References $id.
{
         return $this->id;
     }
CTCT_Admin_Table::get_name ()
Getter.
Returns
string
Definition at line 79 of file table.php.
References $name.
{
         return $this->name;
     }
CTCT_Admin_Table::render ()
Alias to $this->render()
Returns
string
See Also
$this->get_html()
Definition at line 113 of file table.php.
References get_html().
{
         return $this->get_html();
     }
CTCT_Admin_Table::set_data ($data = FALSE)
Set the data you wish to display.
Parameters
mixed $data An array or object of data you want to display
Returns
object table helper
Definition at line 46 of file table.php.
References $data.
{
         if( ! is_array( $data ) AND ! is_object( $data ) ) {
             error( '$data must be an array or an object' );
         }
         $this->data = $data;
         return $this;
     }
CTCT_Admin_Table::set_id ($id = FALSE)
Sets the id for the table.
Parameters
string $id he CSS id for the table
Returns
object table helper
Definition at line 97 of file table.php.
References $id.
Referenced by __construct().
{
         if( ! $id ) {
             error('$id parameter is required.');
         }
         $this->id = str_replace( ' ', '' , $id );
         return $this;
     }
CTCT_Admin_Table::set_name ($name = '')
Sets the name (after sanitising)
Parameters
string $name
Returns
object table helper
Definition at line 64 of file table.php.
References $name.
Referenced by __construct().
{
         if( ! $name ) {
             error('$name parameter is required.');
         }
         $this->name = str_replace( ' ', '' , $name );
         return $this;
     }
Field Documentation
CTCT_Admin_Table::$data
Definition at line 17 of file table.php.
Referenced by set_data().
CTCT_Admin_Table::$do_not_esc_td
Definition at line 17 of file table.php.
CTCT_Admin_Table::$do_not_esc_th
Definition at line 17 of file table.php.
CTCT_Admin_Table::$html private
Class variables should only be accessed using setters and getters.
Direct acces is not supported.
Definition at line 17 of file table.php.
Referenced by get_html().
CTCT_Admin_Table::$id
Definition at line 17 of file table.php.
Referenced by get_id(), and set_id().
CTCT_Admin_Table::$name
Definition at line 17 of file table.php.
Referenced by get_name(), and set_name().
The documentation for this class was generated from the following file:
table.php