Constant Contact for WordPress: CTCT_Admin Class Reference
CTCT_Admin Class Reference
Public Member Functions
add_menu ()
addActions ()
pluginStatus ($content= '')
page ()
content ()
Public Member Functions inherited from CTCT_Admin_Page
__construct ()
print_styles ()
print_scripts ()
help_tabs ($tabs)
getPermission ()
add_menu ()
page ()
Data Fields
$key = 'constant-contact-api'
$title = 'Settings'
Data Fields inherited from CTCT_Admin_Page
$key
$title
$permission = 'manage_options'
$cc
$oauth
$errors
$can_edit = false
$can_add = false
$component = ''
Protected Member Functions
add ()
edit ()
view ()
single ()
processForms ()
Protected Member Functions inherited from CTCT_Admin_Page
addIncludes ()
addScripts ()
isAdd ()
isEdit ()
isSingle ()
isView ()
getKey ()
getTitle ()
getNavTitle ()
add ()
edit ()
view ()
single ()
processForms ()
addActions ()
content ()
print_errors ()
Detailed Description
Definition at line 3 of file class.ctct_admin.php.
Member Function Documentation
CTCT_Admin::add () protected
Definition at line 8 of file class.ctct_admin.php.
 {}
CTCT_Admin::add_menu ()
Definition at line 33 of file class.ctct_admin.php.
{
         // create new top-level menu
         add_menu_page(__('Constant Contact API', 'constant-contact-api'), __('Constant Contact', 'constant-contact-api'), 'manage_options', 'constant-contact-api', array(&$this, 'page'), CTCT_FILE_URL.'images/admin/constant-contact-admin-icon.png');
     }
CTCT_Admin::addActions ()
Definition at line 38 of file class.ctct_admin.php.
{
         $CTCT_Settings = new CTCT_Settings();
         add_filter('admin_footer_text', array(&$this, 'pluginStatus'));
     }
CTCT_Admin::content ()
Definition at line 61 of file class.ctct_admin.php.
References CTCT_Settings\do_settings_sections().
{
     ?>
         <form action="options.php" method="post">
         <?php
             settings_fields('ctct_settings');
             CTCT_Settings::do_settings_sections('constant-contact-api');
         ?>
         </form>
     <?php
     }
CTCT_Admin::edit () protected
Definition at line 9 of file class.ctct_admin.php.
 {}
CTCT_Admin::page ()
Definition at line 52 of file class.ctct_admin.php.
                     {
         if(!$this->cc->isConfigured()) {
             echo kws_ob_include(CTCT_DIR_PATH.'views/admin/view.setup.php', $this);
         } else {
             parent::page();
         }
     }
CTCT_Admin::pluginStatus ($content = '')
Definition at line 44 of file class.ctct_admin.php.
References CTCT_Admin_Page\getKey().
{
         global $plugin_page;
         if($plugin_page === $this->getKey()) {
             return kws_ob_include(CTCT_FILE_PATH.'/views/admin/view.plugin-status.php', $CTCT);
         }
         return $content;
     }
CTCT_Admin::processForms () protected
Definition at line 12 of file class.ctct_admin.php.
References CTCT_Settings\flush_transients().
{
         if(isset($_GET['error']) && isset($_GET['error_description'])) {
             $this->errors[] = new WP_Error($_GET['error'], $_GET['error_description']);
         }
         if(isset($_GET['de-authenticate']) && wp_verify_nonce( $_GET['de-authenticate'], 'de-authenticate' )) {
             $this->oauth->deleteToken();
             delete_option('ccStats_ga_token');
             delete_option('ccStats_ga_profile_id');
         }
         if(isset($_GET['delete-settings']) && wp_verify_nonce( $_GET['delete-settings'], 'delete-settings' )) {
             CTCT_Settings::flush_transients();
             $this->oauth->deleteToken();
             delete_option('ccStats_ga_token');
             delete_option('ccStats_ga_profile_id');
             delete_option('cc_form_increment');
             delete_option('cc_form_design');
             delete_option('ctct_configured');
             delete_option('ctct_settings');
         }
     }
CTCT_Admin::single () protected
Definition at line 11 of file class.ctct_admin.php.
 {}
CTCT_Admin::view () protected
Definition at line 10 of file class.ctct_admin.php.
 {}
Field Documentation
CTCT_Admin::$key = 'constant-contact-api'
Definition at line 5 of file class.ctct_admin.php.
CTCT_Admin::$title = 'Settings'
Definition at line 6 of file class.ctct_admin.php.
The documentation for this class was generated from the following file:
class.ctct_admin.php