Constant Contact for WordPress: CampaignScheduleServiceUnitTest Class Reference
CampaignScheduleServiceUnitTest Class Reference
Public Member Functions
setUp ()
testGetSchedules ()
testGetSchedule ()
testAddSchedule ()
testUpdateSchedule ()
testDeleteSchedule ()
testDeleteScheduleFailed ()
testSendTest ()
Private Attributes
$restClient
$campaignScheduleService
Detailed Description
Definition at line 9 of file CampaignScheduleServiceUnitTest.php.
Member Function Documentation
CampaignScheduleServiceUnitTest::setUp ()
Definition at line 15 of file CampaignScheduleServiceUnitTest.php.
     {
         $this->restClient = $this->getMock('Ctct\Util\RestClientInterface');
         $this->campaignScheduleService = new CampaignScheduleService("apikey", $this->restClient);
     }
CampaignScheduleServiceUnitTest::testAddSchedule ()
Definition at line 52 of file CampaignScheduleServiceUnitTest.php.
References JsonLoader\getCampaignScheduleJson().
     {
         $curlResponse = CurlResponse::create(JsonLoader::getCampaignScheduleJson(), array('http_code' => 200));
         $this->restClient->expects($this->once())
             ->method('post')
             ->with()
             ->will($this->returnValue($curlResponse));
         $createdSchedule = $this->campaignScheduleService->addSchedule('access_token', 9100367935463, new Schedule());
         $this->assertInstanceOf('Ctct\Components\EmailMarketing\Schedule', $createdSchedule);
         $this->assertEquals(1, $createdSchedule->id);
         $this->assertEquals("2012-12-16T11:07:43.626Z", $createdSchedule->scheduled_date);
     }
CampaignScheduleServiceUnitTest::testDeleteSchedule ()
Definition at line 85 of file CampaignScheduleServiceUnitTest.php.
     {
         $curlResponse = CurlResponse::create("", array('http_code' => 204), null);
         $this->restClient->expects($this->once())
             ->method('delete')
             ->with()
             ->will($this->returnValue($curlResponse));
         $this->assertTrue($this->campaignScheduleService->deleteSchedule('access_token', "9100367935463", 1));
     }
CampaignScheduleServiceUnitTest::testDeleteScheduleFailed ()
Definition at line 96 of file CampaignScheduleServiceUnitTest.php.
     {
         $curlResponse = CurlResponse::create("", array('http_code' => 400));
         $this->restClient->expects($this->once())
             ->method('delete')
             ->with()
             ->will($this->returnValue($curlResponse));
         $this->assertFalse($this->campaignScheduleService->deleteSchedule('access_token', "9100367935463", 1));
     }
CampaignScheduleServiceUnitTest::testGetSchedule ()
Definition at line 38 of file CampaignScheduleServiceUnitTest.php.
References JsonLoader\getCampaignScheduleJson().
     {
         $curlResponse = CurlResponse::create(JsonLoader::getCampaignScheduleJson(), array('http_code' => 200));
         $this->restClient->expects($this->once())
             ->method('get')
             ->with()
             ->will($this->returnValue($curlResponse));
         $schedule = $this->campaignScheduleService->getSchedule('access_token', 9100367935463, 1);
         $this->assertInstanceOf('Ctct\Components\EmailMarketing\Schedule', $schedule);
         $this->assertEquals(1, $schedule->id);
         $this->assertEquals("2012-12-16T11:07:43.626Z", $schedule->scheduled_date);
     }
CampaignScheduleServiceUnitTest::testGetSchedules ()
Definition at line 21 of file CampaignScheduleServiceUnitTest.php.
References JsonLoader\getCampaignSchedulesJson().
     {
         $curlResponse = CurlResponse::create(JsonLoader::getCampaignSchedulesJson(), array('http_code' => 200));
         $this->restClient->expects($this->once())
             ->method('get')
             ->with()
             ->will($this->returnValue($curlResponse));
         $schedules = $this->campaignScheduleService->getSchedules('access_token', 9100367935463);
         $this->assertInstanceOf('Ctct\Components\EmailMarketing\Schedule', $schedules[0]);
         $this->assertEquals(1, $schedules[0]->id);
         $this->assertEquals("2012-12-16T11:07:43.626Z", $schedules[0]->scheduled_date);
         $this->assertEquals(2, $schedules[1]->id);
         $this->assertEquals("2012-12-17T11:08:00.000Z", $schedules[1]->scheduled_date);
     }
CampaignScheduleServiceUnitTest::testSendTest ()
Definition at line 107 of file CampaignScheduleServiceUnitTest.php.
References JsonLoader\getTestSendJson().
     {
         $curlResponse = CurlResponse::create(JsonLoader::getTestSendJson(), array('http_code' => 201));
         $this->restClient->expects($this->once())
             ->method('post')
             ->with()
             ->will($this->returnValue($curlResponse));
         $testSend = $this->campaignScheduleService->sendTest('access_token', "9100367935463", new TestSend());
         $this->assertInstanceOf('Ctct\Components\EmailMarketing\TestSend', $testSend);
         $this->assertEquals("HTML", $testSend->format);
         $this->assertEquals("oh hai there", $testSend->personal_message);
         $this->assertEquals("test@roving.com", $testSend->email_addresses[0]);
     }
CampaignScheduleServiceUnitTest::testUpdateSchedule ()
Definition at line 66 of file CampaignScheduleServiceUnitTest.php.
References JsonLoader\getCampaignScheduleJson().
     {
         $curlResponse = CurlResponse::create(JsonLoader::getCampaignScheduleJson(), array('http_code' => 200));
         $this->restClient->expects($this->once())
             ->method('put')
             ->with()
             ->will($this->returnValue($curlResponse));
         $updatedSchedule = $this->campaignScheduleService->updateSchedule(
             'access_token',
             "9100367935463",
             new Schedule()
         );
         $this->assertInstanceOf('Ctct\Components\EmailMarketing\Schedule', $updatedSchedule);
         $this->assertEquals(1, $updatedSchedule->id);
         $this->assertEquals("2012-12-16T11:07:43.626Z", $updatedSchedule->scheduled_date);
     }
Field Documentation
CampaignScheduleServiceUnitTest::$campaignScheduleService private
Definition at line 13 of file CampaignScheduleServiceUnitTest.php.
CampaignScheduleServiceUnitTest::$restClient private
Definition at line 12 of file CampaignScheduleServiceUnitTest.php.
The documentation for this class was generated from the following file:
CampaignScheduleServiceUnitTest.php