Constant Contact for WordPress: LibraryCollection Class Reference
LibraryCollection Class Reference
Public Member Functions
__construct ($CTCTRequest)
LibraryCollection constructor.
addFolder (Folder $Folder)
Add a new Folder.
getFolders ($page=null)
Get a page of Folders.
getImagesFromFolder ($url)
Gets a page of images from a folder.
getImageDetails ($url)
Get details for an image.
deleteImage ($url)
Delete image from an account.
deleteImagesFromFolder ($url)
Delete all the images from a folder.
uploadImage ($imageLocation, $folderUrl)
Upload an image to a folder.
Public Member Functions inherited from Collection
__construct (CTCTRequest $CTCTRequest, $collectionUri)
Collection constructor.
Data Fields
$CTCTRequest
$uri
Data Fields inherited from Collection
$CTCTRequest
$uri
Detailed Description
Definition at line 418 of file Collections.php.
Constructor & Destructor Documentation
LibraryCollection::__construct ($CTCTRequest)
LibraryCollection constructor.
Parameters
$CTCTRequest
Definition at line 426 of file Collections.php.
References $CTCTRequest.
{
         parent::__construct($CTCTRequest, '/ws/customers/'.$CTCTRequest->username.'/library');
     }
Member Function Documentation
LibraryCollection::addFolder (Folder $Folder)
Add a new Folder.
Parameters
string $name - Folder name
Returns
Folder
Definition at line 435 of file Collections.php.
References Folder\createStruct(), Folder\createXml(), and CTCTRequest\makeRequest().
{
         $listXml = $Folder->createXml();
         $response = $this->CTCTRequest->makeRequest($this->uri.'/folders', 'POST', $listXml);
         $parsedResponse = simplexml_load_string($response['xml'], null, null, "http://www.w3.org/2005/Atom");
         return new Folder(Folder::createStruct($parsedResponse));
     }
LibraryCollection::deleteImage ($url)
Delete image from an account.
Parameters
string $url - url to an image
Returns
bool - true if successful, else false
Definition at line 491 of file Collections.php.
References CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'DELETE');
         return ($response['info']['http_code'] == 204) ? true : false;
     }
LibraryCollection::deleteImagesFromFolder ($url)
Delete all the images from a folder.
Parameters
string $url - url to a folder
Returns
bool - true if successful, else false
Definition at line 501 of file Collections.php.
References CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'DELETE');
         return ($response['info']['http_code'] == 204) ? true : false;
     }
LibraryCollection::getFolders ($page = null)
Get a page of Folders.
Parameters
string $page - url to a page of folders, default is first page
Returns
array - Folder objects and a link to the next page if one exists
Definition at line 447 of file Collections.php.
References Folder\createStruct(), Utility\findNextLink(), and CTCTRequest\makeRequest().
{
         $page = ($page) ? $this->CTCTRequest->baseUri.$page : $this->uri.'/folders';
         $foldersCollection = array('folders' => array(), 'nextLink' => '');
         $response = $this->CTCTRequest->makeRequest($page, 'GET');
         $parsedResponse = simplexml_load_string($response['xml'], null, null, "http://www.w3.org/2005/Atom");
         foreach ($parsedResponse->entry as $folder){
             $foldersCollection['folders'][] = new Folder(Folder::createStruct($folder));
         }
         $foldersCollection['nextLink'] = Utility::findNextLink($parsedResponse);
         return $foldersCollection;
     }
LibraryCollection::getImageDetails ($url)
Get details for an image.
Parameters
string $url - url to an image
Returns
Image
Definition at line 479 of file Collections.php.
References Image\createStruct(), and CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $parsedResponse = simplexml_load_string($response['xml'], null, null, 'http://www.w3.org/2005/Atom');
         $image = new Image(Image::createStruct($parsedResponse));
         return $image;
     }
LibraryCollection::getImagesFromFolder ($url)
Gets a page of images from a folder.
Parameters
string $url - url to a page of images, default is first page
Returns
array - image objects and a link to the next page if one exists
Definition at line 464 of file Collections.php.
References Image\createStruct(), and CTCTRequest\makeRequest().
{
         $response = $this->CTCTRequest->makeRequest($url, 'GET');
         $imageCollection = array();
         $parsedResponse = simplexml_load_string($response['xml'], null, null, "http://www.w3.org/2005/Atom");
         foreach($parsedResponse->entry as $entry){
             $imageCollection[] = new Image(Image::createStruct($entry));
         }
         return $imageCollection;
     }
LibraryCollection::uploadImage ($imageLocation, $folderUrl)
Upload an image to a folder.
Exceptions
CTCTException - If file cannot me found or md5Hash cannot be created
Parameters
$imageLocation- Location of an image on disk
$folderUrl - url of a folder to upload an image to
Returns
Image
Definition at line 513 of file Collections.php.
References Image\createStruct(), CTCTException\generateError(), and CTCTRequest\makeRequest().
{
         $imageName = substr(strrchr($imageLocation, '\\'), 1);
         if($imageName == false) { $imageName = $imageLocation; }
         $imageFormat = substr(strrchr($imageName, '.'), 1);
         $boundary = "---------------------".substr(md5(rand(0,32000)), 0, 10);
         try{
             $file = file_get_contents($imageLocation);
             $md5Hash = md5_file($imageLocation);
             if(empty($file)){ throw new CTCTException('Unable to get file contents from: '.$imageLocation);}
             if(empty($md5Hash)){ throw new CTCTException('Unable to create md5Hash from: '.$imageLocation);}
         } catch (CTCTException $e){
             $e->generateError('Error uploading image:');
         }
         switch($imageFormat){
             case 'JPG':
                 $imageType = 'image/jpg';
                 break;
             case 'GIF':
                 $imageType = 'image/gif';
                 break;
             case 'PNG':
                 $imageType = 'image/png';
                 break;
             default:
                 $imageType='image/jpeg';
         }
         $xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>
             <atom:entry xmlns:atom=\"http://www.w3.org/2005/Atom\">
                 <atom:content>
                     <Image>
                     <FileName>".$imageName."</FileName>
                     <MD5Hash>".$md5Hash."</MD5Hash>
                     <Description />
                     </Image>
                 </atom:content>
             </atom:entry>";
         $data = '--'.$boundary."\n";
         $data .= "Content-Disposition: form-data; name=\"part1\"\n";
         $data .= "Content-Type: application/atom+xml\n";
         $data .= "Accept: application/atom+xml\n\n".$xml."\n";
         $data .= "--".$boundary."\n";
         $data .= "Content-Disposition: form-data; name=\"part2\"; filename=\"".$imageName."\"\n";
         $data .= "Content-Type: ".$imageType."g\n";
         $data .= "Content-Transfer-Encoding: binary\n\n";
         $data .= $file."\n";
         $data .= "--".$boundary."--\n";
         $response = $this->CTCTRequest->makeRequest($folderUrl.'/images', 'POST', $data, "multipart/form-data; boundary=".$boundary);
         $parsedResponse = simplexml_load_string($response['xml'], null, null, "http://www.w3.org/2005/Atom");
         return new Image(Image::createStruct($parsedResponse));
     }
Field Documentation
LibraryCollection::$CTCTRequest
Definition at line 419 of file Collections.php.
Referenced by __construct().
LibraryCollection::$uri
Definition at line 420 of file Collections.php.
The documentation for this class was generated from the following file:
Collections.php