Constant Contact for WordPress: Net_DNS_Header Class Reference
Net_DNS_Header Class Reference
Public Member Functions
Net_DNS_Header ($data= '')
Initializes the default values for the Header object.
display ()
Displays the properties of the header.
string ()
Returns a formatted string containing the properties of the header.
data ()
Returns the binary data containing the properties of the header.
Data Fields
$id
The packet's request id.
$qr
The QR bit in a DNS packet header.
$opcode
The OPCODE name of this packet.
$aa
The AA (authoritative answer) bit in a DNS packet header.
$tc
The TC (truncated) bit in a DNS packet header.
$rd
The RD (recursion desired) bit in a DNS packet header.
$ra
The RA (recursion available) bit in a DNS packet header.
$rcode
The RCODE name for this packet.
$qdcount
Number of questions contained within the packet.
$ancount
Number of answer RRs contained within the packet.
$nscount
Number of authority RRs within the packet.
$arcount
Number of additional RRs within the packet.
Detailed Description
Definition at line 34 of file Header.php.
Member Function Documentation
Net_DNS_Header::data ()
Returns the binary data containing the properties of the header.
Packs the properties of the Header object into a binary string suitable for using as the Header section of a DNS packet.
Returns
string binary representation of the header object public
Definition at line 253 of file Header.php.
References $opcode, $rcode, $rd, Net_DNS\opcodesbyname(), and Net_DNS\rcodesbyname().
     {
         $opcode = Net_DNS::opcodesbyname($this->opcode);
         $rcode  = Net_DNS::rcodesbyname($this->rcode);
         $byte2 = ($this->qr << 7)
             | ($opcode << 3)
             | ($this->aa << 2)
             | ($this->tc << 1)
             | ($this->rd);
         $byte3 = ($this->ra << 7) | $rcode;
         return pack('nC2n4', $this->id,
                 $byte2,
                 $byte3,
                 $this->qdcount,
                 $this->ancount,
                 $this->nscount,
                 $this->arcount);
     }
Net_DNS_Header::display ()
Displays the properties of the header.
Displays the properties of the header.
public
Definition at line 200 of file Header.php.
References string().
     {
         echo $this->string();
     }
Net_DNS_Header::Net_DNS_Header ($data = '')
Initializes the default values for the Header object.
Builds a header object from either default values, or from a DNS packet passed into the constructor as $data
Parameters
string $data A DNS packet of which the header will be parsed.
Returns
object Net_DNS_Header public
Definition at line 143 of file Header.php.
References Net_DNS_Resolver\nextid(), Net_DNS\opcodesbyval(), and Net_DNS\rcodesbyval().
     {
         if ($data != '') {
             /*
              * The header MUST be at least 12 bytes.
              * Passing the full datagram to this constructor
              * will examine only the header section of the DNS packet
              */
             if (strlen($data) < 12)
                 return false;
             $a = unpack('nid/C2flags/n4counts', $data);
             $this->id      = $a['id'];
             $this->qr      = ($a['flags1'] >> 7) & 0x1;
             $this->opcode  = ($a['flags1'] >> 3) & 0xf;
             $this->aa      = ($a['flags1'] >> 2) & 0x1;
             $this->tc      = ($a['flags1'] >> 1) & 0x1;
             $this->rd      = $a['flags1'] & 0x1;
             $this->ra      = ($a['flags2'] >> 7) & 0x1;
             $this->rcode   = $a['flags2'] & 0xf;
             $this->qdcount = $a['counts1'];
             $this->ancount = $a['counts2'];
             $this->nscount = $a['counts3'];
             $this->arcount = $a['counts4'];
         }
         else {
             $this->id      = Net_DNS_Resolver::nextid();
             $this->qr      = 0;
             $this->opcode  = 0;
             $this->aa      = 0;
             $this->tc      = 0;
             $this->rd      = 1;
             $this->ra      = 0;
             $this->rcode   = 0;
             $this->qdcount = 1;
             $this->ancount = 0;
             $this->nscount = 0;
             $this->arcount = 0;
         }
         if (Net_DNS::opcodesbyval($this->opcode)) {
             $this->opcode = Net_DNS::opcodesbyval($this->opcode);
         }
         if (Net_DNS::rcodesbyval($this->rcode)) {
             $this->rcode = Net_DNS::rcodesbyval($this->rcode);
         }
     }
Net_DNS_Header::string ()
Returns a formatted string containing the properties of the header.
Returns
string a formatted string containing the properties of the header. public
Definition at line 213 of file Header.php.
Referenced by display().
     {
         $retval = ';; id = ' . $this->id . "\n";
         if ($this->opcode == 'UPDATE') {
             $retval .= ';; qr = ' . $this->qr . '    ' .
                 'opcode = ' . $this->opcode . '    '   .
                 'rcode = ' . $this->rcode . "\n";
             $retval .= ';; zocount = ' . $this->qdcount . '  ' .
                 'prcount = ' . $this->ancount . '  '           .
                 'upcount = ' . $this->nscount . '  '           .
                 'adcount = ' . $this->arcount . "\n";
         } else {
             $retval .= ';; qr = ' . $this->qr . '    ' .
                 'opcode = ' . $this->opcode . '    '   .
                 'aa = ' . $this->aa . '    '           .
                 'tc = ' . $this->tc . '    '           .
                 'rd = ' . $this->rd . "\n";
             $retval .= ';; ra = ' . $this->ra . '    ' .
                 'rcode  = ' . $this->rcode . "\n";
             $retval .= ';; qdcount = ' . $this->qdcount . '  ' .
                 'ancount = ' . $this->ancount . '  '    .
                 'nscount = ' . $this->nscount . '  '    .
                 'arcount = ' . $this->arcount . "\n";
         }
         return $retval;
     }
Field Documentation
Net_DNS_Header::$aa
The AA (authoritative answer) bit in a DNS packet header.
The AA bit as described in RFC1035. AA is set to 1 if the answer is authoritative. It has no meaning if QR is set to 0.
Definition at line 62 of file Header.php.
integer Net_DNS_Header::$ancount
Number of answer RRs contained within the packet.
16bit integer representing the number of answer resource records contained in the answer section of the DNS packet.
See Also
Net_DNS_RR class
Definition at line 109 of file Header.php.
integer Net_DNS_Header::$arcount
Number of additional RRs within the packet.
16bit integer representing the number of additional resource records contained in the additional section of the DNS packet.
See Also
Net_DNS_RR class
Definition at line 129 of file Header.php.
Net_DNS_Header::$id
The packet's request id.
The request id of the packet represented as a 16 bit integer.
Definition at line 42 of file Header.php.
integer Net_DNS_Header::$nscount
Number of authority RRs within the packet.
16bit integer representing the number of authority (NS) resource records contained in the authority section of the DNS packet.
See Also
Net_DNS_RR class
Definition at line 119 of file Header.php.
Net_DNS_Header::$opcode
The OPCODE name of this packet.
The string value (name) of the opcode for the DNS packet.
Definition at line 55 of file Header.php.
Referenced by data().
integer Net_DNS_Header::$qdcount
Number of questions contained within the packet.
16bit integer representing the number of questions in the question section of the DNS packet.
See Also
Net_DNS_Question class
Definition at line 99 of file Header.php.
Net_DNS_Header::$qr
The QR bit in a DNS packet header.
The QR bit as described in RFC1035. QR is set to 0 for queries, and 1 for repsones.
Definition at line 49 of file Header.php.
Net_DNS_Header::$ra
The RA (recursion available) bit in a DNS packet header.
This bit is set to 1 by the DNS server if the server is willing to perform recursion.
Definition at line 83 of file Header.php.
Net_DNS_Header::$rcode
The RCODE name for this packet.
The string value (name) of the rcode for the DNS packet.
Definition at line 89 of file Header.php.
Referenced by data().
Net_DNS_Header::$rd
The RD (recursion desired) bit in a DNS packet header.
This bit should be set to 1 in a query if recursion is desired by the DNS server.
Definition at line 76 of file Header.php.
Referenced by data().
Net_DNS_Header::$tc
The TC (truncated) bit in a DNS packet header.
This flag is set to 1 if the response was truncated. This flag has no meaning in a query packet.
Definition at line 69 of file Header.php.
The documentation for this class was generated from the following file:
Header.php