Constant Contact for WordPress: OAuthServer Class Reference
OAuthServer Class Reference
Public Member Functions
__construct ($data_store)
add_signature_method ($signature_method)
fetch_request_token (&$request)
process a request_token request returns the request token on success
fetch_access_token (&$request)
process an access_token request returns the access token on success
verify_request (&$request)
verify an api call, checks all the parameters
Protected Attributes
$timestamp_threshold = 300
$version = '1.0'
$signature_methods = array()
$data_store
Private Member Functions
get_version (&$request)
version 1
get_signature_method (&$request)
figure out the signature with some defaults
get_consumer (&$request)
try to find the consumer for the provided request's consumer key
get_token (&$request, $consumer, $token_type="access")
try to find the token for the provided request's token key
check_signature (&$request, $consumer, $token)
all-in-one function to check the signature on a request should guess the signature method appropriately
check_timestamp ($timestamp)
check that the timestamp is new enough
check_nonce ($consumer, $token, $nonce, $timestamp)
check that the nonce is not repeated
Detailed Description
Definition at line 482 of file Authentication.php.
Constructor & Destructor Documentation
OAuthServer::__construct ($data_store)
Definition at line 489 of file Authentication.php.
References $data_store.
{
     $this->data_store = $data_store;
   }
Member Function Documentation
OAuthServer::add_signature_method ($signature_method)
Definition at line 493 of file Authentication.php.
{
     $this->signature_methods[$signature_method->get_name()] =
       $signature_method;
   }
OAuthServer::check_nonce ($consumer, $token, $nonce, $timestamp) private
check that the nonce is not repeated
Definition at line 673 of file Authentication.php.
Referenced by check_signature().
{
     if( ! $nonce )
       throw new OAuthException(
         'Missing nonce parameter. The parameter is required'
       );
     // verify that the nonce is uniqueish
     $found = $this->data_store->lookup_nonce(
       $consumer,
       $token,
       $nonce,
       $timestamp
     );
     if ($found) {
       throw new OAuthException("Nonce already used: $nonce");
     }
   }
OAuthServer::check_signature (& $request, $consumer, $token) private
all-in-one function to check the signature on a request should guess the signature method appropriately
Definition at line 629 of file Authentication.php.
References check_nonce(), check_timestamp(), and get_signature_method().
Referenced by fetch_access_token(), fetch_request_token(), and verify_request().
{
     // this should probably be in a different method
     $timestamp = @$request->get_parameter('oauth_timestamp');
     $nonce = @$request->get_parameter('oauth_nonce');
     $this->check_timestamp($timestamp);
     $this->check_nonce($consumer, $token, $nonce, $timestamp);
     $signature_method = $this->get_signature_method($request);
     $signature = $request->get_parameter('oauth_signature');
     $valid_sig = $signature_method->check_signature(
       $request,
       $consumer,
       $token,
       $signature
     );
     if (!$valid_sig) {
       throw new OAuthException("Invalid signature");
     }
   }
OAuthServer::check_timestamp ($timestamp) private
check that the timestamp is new enough
Definition at line 655 of file Authentication.php.
Referenced by check_signature().
{
     if( ! $timestamp )
       throw new OAuthException(
         'Missing timestamp parameter. The parameter is required'
       );
     // verify that timestamp is recentish
     $now = time();
     if (abs($now - $timestamp) > $this->timestamp_threshold) {
       throw new OAuthException(
         "Expired timestamp, yours $timestamp, ours $now"
       );
     }
   }
OAuthServer::fetch_access_token (& $request)
process an access_token request returns the access token on success
Definition at line 525 of file Authentication.php.
References check_signature(), get_consumer(), get_token(), and get_version().
{
     $this->get_version($request);
     $consumer = $this->get_consumer($request);
     // requires authorized request token
     $token = $this->get_token($request, $consumer, "request");
     $this->check_signature($request, $consumer, $token);
     // Rev A change
     $verifier = $request->get_parameter('oauth_verifier');
     $new_token = $this->data_store->new_access_token($token, $consumer, $verifier);
     return $new_token;
   }
OAuthServer::fetch_request_token (& $request)
process a request_token request returns the request token on success
Definition at line 504 of file Authentication.php.
References check_signature(), get_consumer(), and get_version().
{
     $this->get_version($request);
     $consumer = $this->get_consumer($request);
     // no token required for the initial token request
     $token = NULL;
     $this->check_signature($request, $consumer, $token);
     // Rev A change
     $callback = $request->get_parameter('oauth_callback');
     $new_token = $this->data_store->new_request_token($consumer, $callback);
     return $new_token;
   }
OAuthServer::get_consumer (& $request) private
try to find the consumer for the provided request's consumer key
Definition at line 597 of file Authentication.php.
Referenced by fetch_access_token(), fetch_request_token(), and verify_request().
{
     $consumer_key = @$request->get_parameter("oauth_consumer_key");
     if (!$consumer_key) {
       throw new OAuthException("Invalid consumer key");
     }
     $consumer = $this->data_store->lookup_consumer($consumer_key);
     if (!$consumer) {
       throw new OAuthException("Invalid consumer");
     }
     return $consumer;
   }
OAuthServer::get_signature_method (& $request) private
figure out the signature with some defaults
Definition at line 573 of file Authentication.php.
Referenced by check_signature().
{
     $signature_method =
         @$request->get_parameter("oauth_signature_method");
     if (!$signature_method) {
       // According to chapter 7 ("Accessing Protected Ressources") the signature-method
       // parameter is required, and we can't just fallback to PLAINTEXT
       throw new OAuthException('No signature method parameter. This parameter is required');
     }
     if (!in_array($signature_method,
                   array_keys($this->signature_methods))) {
       throw new OAuthException(
         "Signature method '$signature_method' not supported " .
         "try one of the following: " .
         implode(", ", array_keys($this->signature_methods))
       );
     }
     return $this->signature_methods[$signature_method];
   }
OAuthServer::get_token (& $request, $consumer, $token_type = "access") private
try to find the token for the provided request's token key
Definition at line 614 of file Authentication.php.
Referenced by fetch_access_token(), and verify_request().
{
     $token_field = @$request->get_parameter('oauth_token');
     $token = $this->data_store->lookup_token(
       $consumer, $token_type, $token_field
     );
     if (!$token) {
       throw new OAuthException("Invalid $token_type token: $token_field");
     }
     return $token;
   }
OAuthServer::get_version (& $request) private
version 1
Definition at line 557 of file Authentication.php.
References $version.
Referenced by fetch_access_token(), fetch_request_token(), and verify_request().
{
     $version = $request->get_parameter("oauth_version");
     if (!$version) {
       // Service Providers MUST assume the protocol version to be 1.0 if this parameter is not present.
       // Chapter 7.0 ("Accessing Protected Ressources")
       $version = '1.0';
     }
     if ($version !== $this->version) {
       throw new OAuthException("OAuth version '$version' not supported");
     }
     return $version;
   }
OAuthServer::verify_request (& $request)
verify an api call, checks all the parameters
Definition at line 545 of file Authentication.php.
References check_signature(), get_consumer(), get_token(), and get_version().
{
     $this->get_version($request);
     $consumer = $this->get_consumer($request);
     $token = $this->get_token($request, $consumer, "access");
     $this->check_signature($request, $consumer, $token);
     return array($consumer, $token);
   }
Field Documentation
OAuthServer::$data_store protected
Definition at line 487 of file Authentication.php.
Referenced by __construct().
OAuthServer::$signature_methods = array() protected
Definition at line 485 of file Authentication.php.
OAuthServer::$timestamp_threshold = 300 protected
Definition at line 483 of file Authentication.php.
OAuthServer::$version = '1.0' protected
Definition at line 484 of file Authentication.php.
Referenced by get_version().
The documentation for this class was generated from the following file:
Authentication.php