Constant Contact for WordPress: Ctct\Services\AccountService Class Reference
Ctct\Services\AccountService Class Reference
Public Member Functions
getVerifiedEmailAddresses ($accessToken, Array $params)
Get all verified email addresses associated with an account.
Public Member Functions inherited from Ctct\Services\BaseService
__construct ($apiKey, $restClient=null)
Constructor with the option to to supply an alternative rest client to be used.
buildUrl ($url, $queryParams=null)
Build a url from the base url and query parameters array.
getRestClient ()
Get the rest client being used by the service.
setRestClient (RestClientInterface $restClient)
Additional Inherited Members
Static Protected Member Functions inherited from Ctct\Services\BaseService
static getHeaders ($accessToken)
Helper function to return required headers for making an http request with constant contact.
Protected Attributes inherited from Ctct\Services\BaseService
$restClient
$apiKey
Detailed Description
Definition at line 14 of file AccountService.php.
Member Function Documentation
Ctct\Services\AccountService::getVerifiedEmailAddresses ($accessToken, Array $params)
Get all verified email addresses associated with an account.
Parameters
string $accessToken - Constant Contact OAuth2 Access Token
array $params - array of query parameters/values to append to the request
Returns
array of VerifiedEmailAddress
Definition at line 22 of file AccountService.php.
References Ctct\Services\BaseService\buildUrl(), Ctct\Components\Account\VerifiedEmailAddress\create(), and Ctct\Util\Config\get().
     {
         $baseUrl = Config::get('endpoints.base_url')
             . sprintf(Config::get('endpoints.account_verified_addresses'));
         $url = $this->buildUrl($baseUrl, $params);
         $response = parent::getRestClient()->get($url, parent::getHeaders($accessToken));
         $verifiedAddresses = array();
         foreach (json_decode($response->body, true) as $verifiedAddress) {
             $verifiedAddresses[] = VerifiedEmailAddress::create($verifiedAddress);
         }
         return $verifiedAddresses;
     }
The documentation for this class was generated from the following file:
AccountService.php