Constant Contact for WordPress: CTCTRequest Class Reference
CTCTRequest Class Reference
Public Member Functions
__construct ($authType, $apiKey, $username, $authParam)
makeRequest ($url, $method, $body='', $contentType="application/atom+xml")
Data Fields
$baseUri = 'https://api.constantcontact.com'
$username
$apiKey
$authType
$requestLogin
$consumerSecret
$consumer
$accessToken
$signatureMethod
$access_token
Private Member Functions
oAuth_construct ($apiKey, $consumerSecret)
oAuth2_construct ($apiKey, $consumerSecret)
basic_construct ($apiKey, $username, $password)
Detailed Description
Definition at line 1026 of file Authentication.php.
Constructor & Destructor Documentation
CTCTRequest::__construct ($authType, $apiKey, $username, $authParam)
Definition at line 1054 of file Authentication.php.
References $apiKey, $authType, $username, and basic_construct().
{
         $this->apiKey = $apiKey;
         $this->username = $username;
         if($authType == 'basic'){
             $this->authType = 'basic';
             $this->basic_construct($apiKey, $username, $authParam);
         } elseif($authType == 'oauth') {
             $this->authType = 'oauth';
             $this->oauth_construct($apiKey, $authParam);
         } elseif($authType == 'oauth2') {
             $this->authType = 'oauth2';
             $this->oauth2_construct($apiKey, $authParam);
         }
     }
Member Function Documentation
CTCTRequest::basic_construct ($apiKey, $username, $password) private
Definition at line 1086 of file Authentication.php.
References $apiKey, and $username.
Referenced by __construct().
{
         $this->requestLogin = $apiKey.'%'.$username.':'.$password;
         $this->authType = 'basic';
     }
CTCTRequest::makeRequest ($url, $method, $body = '', $contentType = "application/atom+xml")
Definition at line 1091 of file Authentication.php.
References $accessToken, OAuthRequest\from_consumer_and_token(), and CTCTException\generateError().
Referenced by CampaignsCollection\addCampaign(), ContactsCollection\addContact(), LibraryCollection\addFolder(), ListsCollection\addList(), ActivitiesCollection\bulkAddContacts(), CampaignsCollection\deleteCampaign(), ContactsCollection\deleteContact(), LibraryCollection\deleteImage(), LibraryCollection\deleteImagesFromFolder(), ListsCollection\deleteList(), CampaignsCollection\deleteSchedule(), SettingsCollection\getAddresses(), CampaignsCollection\getCampaignDetails(), CampaignsCollection\getCampaignEvents(), CampaignsCollection\getCampaigns(), CampaignsCollection\getCampaignsByStatus(), ContactsCollection\getContactDetails(), ContactsCollection\getContactEvents(), ContactsCollection\getContacts(), EventsCollection\getEventDetails(), EventsCollection\getEvents(), LibraryCollection\getFolders(), LibraryCollection\getImageDetails(), LibraryCollection\getImagesFromFolder(), ListsCollection\getListDetails(), ListsCollection\getListMembers(), ListsCollection\getLists(), EventsCollection\getRegistrantDetails(), EventsCollection\getRegistrants(), CampaignsCollection\getSchedule(), CampaignsCollection\scheduleCampaign(), ContactsCollection\searchContactsByEmail(), CampaignsCollection\updateCampaign(), ContactsCollection\updateContact(), ListsCollection\updateList(), and LibraryCollection\uploadImage().
{
         if($this->authType == 'oauth'){
             $Datastore = new CTCTDataStore();
             $accessInfo = $Datastore->lookupUser($this->username);
             $accessToken = new OAuthToken((string)$accessInfo['key'], (string)$accessInfo['secret']);
             $this->accessToken = $accessToken;
             $request = OAuthRequest::from_consumer_and_token($this->consumer, $accessToken, $method, $url);
             $request->sign_request($this->signatureMethod, $this->consumer, $accessToken);
             $request->get_normalized_http_method();
             $url = $request;
         }
         $curl = curl_init();
         if ($this->authType == 'basic'){
            curl_setopt($curl, CURLOPT_USERPWD, $this->requestLogin);
            curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
         } else if($this->authType == 'oAuth2') {
             //curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
         }
         curl_setopt($curl, CURLOPT_URL, $url);
         //curl_setopt($curl, CURLOPT_FAILONERROR, 0);
         curl_setopt($curl, CURLOPT_HEADER, 0);
         curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
         curl_setopt($curl, CURLOPT_USERAGENT, "Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)");
         curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
         if($this->authType == 'oauth2')
         {
             curl_setopt($curl, CURLOPT_HTTPHEADER, array("Authorization: Bearer " . $this->access_token, "Content-Type: ".$contentType, "Content-Length: ". strlen($body), "Accept: application/atom+xml"));
         }
         else {
         curl_setopt($curl, CURLOPT_HTTPHEADER, array("Content-Type: ".$contentType, "Content-Length: ". strlen($body), "Accept: application/atom+xml"));
         }
         curl_setopt($curl, CURLOPT_CUSTOMREQUEST, $method);
         if ($body) {curl_setopt($curl, CURLOPT_POSTFIELDS, $body);}
         try{
             $return['xml'] = curl_exec($curl);
             $return['info'] = curl_getinfo($curl);
             $return['error'] = curl_error($curl);
             curl_close($curl);
             if(!in_array($return['info']['http_code'], array('201', '200', '204'))){
                 throw new CTCTException('Constant Contact HTTP Request Exception: '.$return['xml']);
             } else {
                 $return = $return;
             }
         } catch(CTCTException $e) {
             $e->generateError();
         }
         return $return;
     }
CTCTRequest::oAuth2_construct ($apiKey, $consumerSecret) private
Definition at line 1080 of file Authentication.php.
References $consumerSecret.
{
         $this->authType = 'oauth2';
         $this->access_token = $consumerSecret;
     }
CTCTRequest::oAuth_construct ($apiKey, $consumerSecret) private
Definition at line 1074 of file Authentication.php.
References $apiKey, and $consumerSecret.
{
         $this->authType = 'oauth';
         $this->consumer = new OAuthConsumer($apiKey, $consumerSecret);
         $this->signatureMethod = new OAuthSignatureMethod_HMAC_SHA1();
     }
Field Documentation
CTCTRequest::$access_token
Definition at line 1044 of file Authentication.php.
CTCTRequest::$accessToken
Definition at line 1040 of file Authentication.php.
Referenced by makeRequest().
CTCTRequest::$apiKey
Definition at line 1031 of file Authentication.php.
Referenced by __construct(), basic_construct(), and oAuth_construct().
CTCTRequest::$authType
Definition at line 1032 of file Authentication.php.
Referenced by __construct().
CTCTRequest::$baseUri = 'https://api.constantcontact.com'
Definition at line 1027 of file Authentication.php.
CTCTRequest::$consumer
Definition at line 1039 of file Authentication.php.
CTCTRequest::$consumerSecret
Definition at line 1038 of file Authentication.php.
Referenced by oAuth2_construct(), and oAuth_construct().
CTCTRequest::$requestLogin
Definition at line 1035 of file Authentication.php.
CTCTRequest::$signatureMethod
Definition at line 1041 of file Authentication.php.
CTCTRequest::$username
Definition at line 1030 of file Authentication.php.
Referenced by __construct(), and basic_construct().
The documentation for this class was generated from the following file:
Authentication.php