
<h2>Spam Settings</h2>

<h3>WangGuard</h3>
WangGuard is a great free spam registration blocker. This plugin integrates with WangGuard. Don't have WangGuard installed? <a class="thickbox" title="Install WangGuard" href="<?php echo admin_url('plugin-install.php?tab=plugin-information&plugin=wangguard&TB_iframe=true&width=640&height=808'); ?>">Install WangGuard</a>.

<h4>Notes on using WangGuard</h4>
If you're using WangGuard, you're going to want to configure the settings in the <a href="<?php echo admin_url( 'admin.php?page=wangguard_conf#wangguard-conf-settings'); ?>">WangGuard settings page</a>. Make sure you understand settings, because they can affect the results.

<div class="divider"></div>

<h3>Akismet</h3>
Akismet is a plugin which identifies and blocks comment and trackback spam on blogs with integration to various blogging systems. It comes installed by default on WordPress, but if you don't have it,  <a class="thickbox" title="Install WangGuard" href="<?php echo admin_url('plugin-install.php?tab=plugin-information&plugin=akismet&TB_iframe=true&width=640&height=808'); ?>">Install Akismet</a>.